### ISSUE TITLE
Add floating scratch layer

### ISSUE THREAD

**Issue by hedning** [paperwm/PaperWM#1]
Make a floating scratch layer:

- When visible should be always on top
- Windows should be shown on all workspaces by default.

#22 is blocking here, since we can't remove windows from the tiling properly.

**Comment by hedning** [comment]
- [MetaWindow.stick](https://developer.gnome.org/meta/stable/MetaWindow.html#meta-window-stick) to set a window on all workspaces.

- `MetaWindow.is_on_all_workspaces()` to check the state

**Comment by hedning** [comment]
After bfa8528d517ebb6b1719ea9655c49b1cc39f9358  and 4a31e49381f7f213540ee40c9e8dd63a150831d5 we have an ad-hoc scratch layer by setting `Always show on visible workspace` (or `meta_window.stick()` in code).

Minimize does almost exactly what we want when hiding the scratch layer, including pushing the windows to the back of the mru.

So now we mostly need a keybinding and a button in the _top bar_ to toggle windows in the scratch layer between `visible` and `minimize`. `<Super>esc` might be a good binding.

We should consider whether to use _always on top_ or not. It might be annoying though.

**Comment by olejorgenb** [comment]
Navigate left/right (`<Super>,/.`) does not work when a "sticky" window have focus.

A sensible behavior (from matrix.org discussion with hedning) might be to make the sticky window transparent and move the tiling as usual, but don't focus on completion (just update `Space.selectedWindow`). When the sticky window is closed/hidden focus should change to the selected window.
