### ISSUE TITLE
Make a click overlay for stacked windows with application icon

### ISSUE THREAD

**Issue by hedning** [paperwm/PaperWM#10]
When a window is scaled and  put on the left or right stack we want clicks on the window to only activate it.

A possible solution is creating a transparent clutter actor above the window, we could add an icon to the actor too, which would be a nice enhancement.

**Comment by hedning** [comment]
Mockup of icon:
![image](https://user-images.githubusercontent.com/71978/30540290-079c0f20-9c66-11e7-9174-ea3f128b1456.png)

**Comment by olejorgenb** [comment]
How to find out how to get the window icon

From altTab.js:

        let tracker = Shell.WindowTracker.get_default();
        this.app = tracker.get_window_app(window);

**Comment by olejorgenb** [comment]
A annoying complication is that mutter's x11 backend need to be told which areas should redirect mouse input to clutter and these areas steal all input regardless of "z stacking". (see comments in stackoverlay.js / notes.org)

This makes it more complex to create a robust solution.

Cases like below for instance (overlay in red): 

![image](https://user-images.githubusercontent.com/72201/31770469-541b4d68-b4d8-11e7-97b3-1f074905cbc9.png)

Clicking on 'r' in overlay wont have any effect using the x11 backend. Must either calculate exact portion of the top stack that actually is visible (not that hard of course) or accept that the visible portion in the bottom right is interactable (not that bad either).

Note that we might want to do something for unstacked but partially visible windows in the future also. The problems that makes it desirable to have the stack overlay apply in large to these windows too. Ie. the "ground suddenly moves below" when clicking in the window. Warping the pointer might work well in those cases.

![image](https://user-images.githubusercontent.com/72201/31770859-064c27f4-b4da-11e7-9e7f-000fd02b19e7.png)
