### ISSUE TITLE
Wrap around workspace switching.

### ISSUE THREAD

**Issue by goodwillcoding** [paperwm/PaperWM#100]
Currently Super+PgUp and Super+PgDn (which do not seem to be documented). Setting that aside, it would be nice to wrap around workspace switching.

**Comment by hedning** [comment]
That could work. For now you can achieve something similar with Super+Escape (when navigating) which takes you back to the starting workspace.

**Comment by goodwillcoding** [comment]
@hedning There is not a Super+Escape in the lastest checkout. There is a Super+Shift+Escape but that do not wrap around unfortunately

**Comment by goodwillcoding** [comment]
@hedning oh I see what you mean now.

**Comment by goodwillcoding** [comment]
@hedning also my appologies on on "undocumented pageUp/pageDown" ... did not realize the little arrows in keybind were expandable (fantastic ide btw, Gnome should copy)

**Comment by goodwillcoding** [comment]
@hedning I created a PR, #101  switching the default workspace behaviour to wraparound. If you want it to be an configurable setting let me know.
