### ISSUE TITLE
Respect configured margins in minimumMargin

### ISSUE THREAD

**Issue by dtolnay** [paperwm/PaperWM#102]
Currently tiling.js has a value called minimumMargin which is fixed at 15px. I haven't looked at all the places this is used, but where I noticed it is that toggleMaximizeHorizontally leaves a gap of minimumMargin on the left and right of the window. I have my horizontal_margin configured to 0, so having those gaps on either side of a supposedly horizontally maximized window looks out of place; I would prefer the window to be horizontally maximized all the way.

I've made a modification locally to set minimumMargin = 0 and that works for me. Maybe the better fix would be to treat `min(prefs.horizontal_margin, 15)` as the minimum margin?

**Comment by hedning** [comment]
> min(prefs.horizontal_margin, 15)

Yep, that makes sense. Using `horizontal_margin` for «maximized» windows didn't work well for larger margins so that's why it's there, but no reason why it shouldn't be capped by `horizontal_margin`.

**Comment by dtolnay** [comment]
Thanks for the quick fix!

I just came across this extension today after trying various other tiling extension for gnome-shell and almost giving up hope, and so far I have found it jaw-droppingly good. I am coming from awesomeWM so the approach will require getting used to, but so far everything makes sense and feels well implemented. Nice work.

**Comment by hedning** [comment]
Cheers :)

It's unorthodox, but we think it's a pretty good compromise between the floating and tiling approach, giving you the no fuss and predictable experience of tiled windows, while still having the «infinite» space of floating.
