### ISSUE TITLE
Fill screen when top bar is hidden

### ISSUE THREAD

**Issue by dtolnay** [paperwm/PaperWM#103]
I am trying out this extension to hide the gnome-shell top bar: https://extensions.gnome.org/extension/545/hide-top-bar/. When combined with PaperWM, the tiling leaves a topbar-sized gap at the top of the screen, rather than filling all the way to the top of the screen. I can manually drag the top edge of a window to resize into this gap, but (as I would expect) it jumps back down when I release the drag.

In case it is relevant, I have their two Intellihide features "Only hide when a window takes the space" and "Only when the active window takes the space" both set to false, which means the top bar should be hidden always.

Would it be possible for PaperWM to tell when there is no top bar and place windows accordingly? If not, would it be possible for PaperWM to provide "hide top bar" functionality itself?

**Comment by olejorgenb** [comment]
gnome-shell has a "workarea" concept: which subrectangle of the monitor that's available for regular windows.

Our code does not respect the "y" part of the workarea atm. 

Fixing the main layout code get's us 90% there. You can test the resulting behavior in the https://github.com/paperwm/PaperWM/compare/respect-workarea-y branch.

**Comment by dtolnay** [comment]
Perfect, that seems to work! Thanks.

**Comment by dtolnay** [comment]
One glitch with that branch: the top bar re-appears after switching workspaces with <kbd>Super</kbd><kbd>Page_Down</kbd> / <kbd>Super</kbd><kbd>Page_Up</kbd>. I need to mouse over the top bar and mouse off of it for it to hide again. I can't tell whether this would need to be fixed in PaperWM or the Hide Top Bar extension, although switching workspaces through Activities does not exhibit the bad behavior.

**Comment by olejorgenb** [comment]
Yes, as always the details are the trickiest :)

We sometimes hide the topbar ourself which complicates the bookkeeping. (mostly related to handling of fullscreen windows)

Another issue is that the workspace names become obscured by the windows in the workspace switcher.

As a hack you can add a early return in `show` and `hide` in `topbar.js` file. That should remove most of our topbar meddling :)

**Note-to-self:** 

Workarea doesn't seem to update until modals are released? Using workarea to determine `animateDown` for fullscreen windows and navigating away from the fullscreen window shows the topbar as expected, but workarea.y is stuck at 0 until navigation ends..

As an alternative to the workarea we could simply calculate the panelBox height as:

```
Math.round(panelBox.get_transformed_size()[1]) * panelBox.visible
```

**Comment by hedning** [comment]
Integrating with the hide topbar extension gets rather hacky (we have to check the position of the panel to see if it's been moved away, which only works due to the fact that the extension happens to move the panel), so I cooked up a prototype which integrates with paperwm https://github.com/paperwm/PaperWM/commits/zen-mode

- [x] easily toggle the top bar using the workspace menu
- [x] always show the top bar when using the workspace carousel 

Needs: 

- [ ] global default preference
- [ ] update the preference gui
- [ ] show the top bar when activating the hot corner (nice to have at least)

The top bar is currently turned off by default for testing, but we'll default to showing the top bar.

**Comment by hedning** [comment]
There's now support for this by setting
```
dconf write /org/gnome/shell/extensions/paperwm/default-show-top-bar false
```

Note we opted out of adding ad-hoc fixes to integrate with the hide top bar extension.
