### ISSUE TITLE
Prefer bringing in windows from left side rather than leaving empty space

### ISSUE THREAD

**Issue by dtolnay** [paperwm/PaperWM#104]
Suppose I have a workspace (big box) containing three windows (little boxes):

```
             +------------------------+
             |                        |
+------------|--+ +-------+ +-------+ |
|            |  | |       | |       | |
|            |  | |       | |       | |
|            |  | |       | |       | |
|            |  | |       | |       | |
+------------|--+ +-------+ +-------+ |
             +------------------------+
```

Currently if I close the rightmost window, I end up with:

```
             +------------------------+
             |                        |
+------------|--+ +-------+           |
|            |  | |       |           |
|            |  | |       |           |
|            |  | |       |           |
|            |  | |       |           |
+------------|--+ +-------+           |
             +------------------------+
```

I would prefer when closing windows to see as much of my remaining windows as possible. In this case:

```
             +------------------------+
             |                        |
          +--|------------+ +-------+ |
          |  |            | |       | |
          |  |            | |       | |
          |  |            | |       | |
          |  |            | |       | |
          +--|------------+ +-------+ |
             +------------------------+
```

**Comment by dtolnay** [comment]
This seems to work as I would expect already when all the remaining windows are able to fit in view at the same time; in that case when I close the rightmost window the remaining windows get centered horizontally. The case that needs work seems to be when the remaining windows wouldn't all fit together, such as in my box drawings.

**Comment by hedning** [comment]
Yeah, that's one of the annoying edge cases which we've put off fixing. At some point we forced alignment with the monitor edges, but that meant manual placement, eg. centering the last window,  became fragile and often got reset. So we need better separation between manual and automatic layouts.

A quick fix if manual placement/centering aren't that important:
```diff
modified   tiling.js
@@ -2031,10 +2031,10 @@ function ensuredX(meta_window, space) {
     let max = min + workArea.width;
     if (meta_window.fullscreen) {
         x = 0;
-    } else if (index == 0 && x <= min) {
+    } else if (index == 0) {
         // Always align the first window to the display's left edge
         x = min;
-    } else if (index == space.length-1 && x + frame.width >= max) {
+    } else if (index == space.length-1) {
         // Always align the first window to the display's right edge
         x = max - frame.width;
     } else if (frame.width > workArea.width*0.9 - 2*(prefs.horizontal_margin + prefs.window_gap)) {
```

**Comment by hedning** [comment]
Added a better fix on 34dbda5ddc79f0a3216b88e922cfb2ec9f6a3c4e

My only concern is having manually placed the last window, eg. centered. On a wide display there might be a a lot of empty space to the right and creating a new window will then move the centered window which is probably not what the user wants.

**Comment by dtolnay** [comment]
Would it work to remember in each workspace which window has been manually placed by the user, if any? This would be the most recent window in which the user invoked the center keybinding or used the mouse to drag the window to a particular horizontal position. Then when performing layout, if layout can be done without repositioning the manually placed window, do it that way; otherwise reset to no manually positioned window.

**Comment by hedning** [comment]
Yeah, we might just need to do the bookeeping.

**Comment by hedning** [comment]
OK, doing  «auto» layout only when the entire workarea was already covered by tiled windows before the layout should work pretty well I think: https://github.com/paperwm/PaperWM/commits/maximize-space-on-remove-add

**Comment by inkhey** [comment]
As i see the issue, one other solution may be making the view "toric"( not sure that clear in english).
What i mean, is that we can imagine an infinite scroll mecanism:

```
            +---------------------------------------------+
            |                                             |
            |                                             |
+-----------------------+ +------------+ +---------+      |
|           |           | |            | |         |      |
|           |           | |            | |         |      |
|           |           | |            | |         |      |
|      1    |           | |      2     | |    3    |      |
|           |           | |            | |         |      |
|           |           | |            | |         |      |
|           |           | |            | |         |      |
|           |           | |            | |         |      |
+-----------------------+ +------------+ +---------+      |
            |                                             |
            +---------------------------------------------+


```
will become by choosing 3:
```
            +---------------------------------------------+
            |                                             |
        +------------+ +----------+ +------------------------+
        |   |        | |          | |                     |  |
        |   |        | |          | |                     |  |
        |   |        | |          | |                     |  |
        |   |        | |          | |                     |  |
        |   |  2     | |     3    | |          1          |  |
        |   |        | |          | |                     |  |
        |   |        | |          | |                     |  |
        |   |        | |          | |                     |  |
        |   |        | |          | |                     |  |
        +------------+ +----------+ +------------------------+
            |                                             |
            +---------------------------------------------+

```

That's probably a more complex mechanism as there is some edge case to handle (we should show only one time a windows, etc…). But this may be effective.

**Comment by olejorgenb** [comment]
Yes, that's an interesting idea. As you mention there's some issues. Eg. when one window ends up visible on both sides of the screen:


                +---------------------------------------------+
                |                                             |
                |                                             |
    +-------------------------+ +------------+ +---------+    |
    |           |             | |            | |         |    |
    |           |             | |            | |         |    |
    |           |             | |            | |         |    |
    |      1    |             | |      2     | |    3    |    |
    |           |             | |            | |         |    |
    |           |             | |            | |         |    |
    |           |             | |            | |         |    |
    |           |             | |            | |         |    |
    +-------------------------+ +------------+ +---------+    |
                |                                             |
                +---------------------------------------------+

Closing 3 would make 1 visible on both sides: (forgive the imperfect drawing)

                +---------------------------------------------+
                |                                             |
            +------------+ +----------+ +------------------------+
            |   |        | |          | |                     |  |
            |   |        | |          | |                     |  |
            |   |        | |          | |                     |  |
            |   |        | |          | |                     |  |
            |   |  1     | |     2    | |          1          |  |
            |   |        | |          | |                     |  |
            |   |        | |          | |                     |  |
            |   |        | |          | |                     |  |
            |   |        | |          | |                     |  |
            +------------+ +----------+ +------------------------+
                |                                             |
                +---------------------------------------------+

This is technically problematic since it's not possible to split the input region of a window like that in X11. (splitting the window texture is not a problem)

Even if we solved the above, I suspect it might end up being confusing. Marking the "seam"/"start" clearly would help ofc.
