### ISSUE TITLE
Is it planned to make paperWM more mouse friendly ?

### ISSUE THREAD

**Issue by inkhey** [paperwm/PaperWM#113]
Hi, PaperWM look like an interesting idea :smiley: . I was searching for a way to have some king of intelligent tiling (with resizing) on gnome-shell and i end up here (more than current half tiling, as i want to have more than 2 windows on one screen). That's was not really what i expected but that's really interesting.

What interesting me is solution about using both tiling (for nice windows placement) and mouse (because finding good keybinding between applications is complex and i'm currently using 2 different keyboard layout).

PaperWM is really nice, i like it but as far as i go, i didn't see a way to move easily windows order, i see mostly keyboard shortcut but not some much mouse interaction. Is there also a way to allow to switch windows using mouse wheel (by placing the mouse a some place or with a key)  ?

**Comment by hedning** [comment]
Yeah, reordering windows using the mouse is on the agenda, but we haven't done anything about yet.

> allow to switch windows using mouse wheel

We support 3-finger swiping with a touchpads and ideally we would support `super+mouse-wheel` to scroll through the tiling, but it's unfortunately not supported by gnome-shell: https://gitlab.gnome.org/GNOME/mutter/issues/207

Having some sort of gui widget that listens to scrolling is possible (eg. you can scroll through workspaces on the workspace name button in the top bar), though not sure where it would fit nicely.

**Comment by olejorgenb** [comment]
PS: I'm sure you know, but all keyboard shortcuts are configurable using either the extension settings (GUI) or dconf-editor[1]. I know it's a pain to reassign a ton of shortcuts though :)

[1] so it is possible to create a script that switches between sets of bindings.

**Comment by olejorgenb** [comment]
Quick prototype of "scroll the topbar to switch windows": 

Scrolling while the mouse pointer is over the topbar selects the next/prev window and brings up a minimap (enters a navigation mode).

While the minimap is open:

- Clicking the topbar close the minimap and focus the selected window
- Pressing <kbd>Return</kbd> close the minimap and focus the selected window
- Pressing <kbd>Esc</kbd> close the minimap and go back to the focused window
- Clicking a non-selected window in the minimap scrolls to that window
- Clicking the selected window in the minimap close the minimap and focus the window (or dobbelclicking a unselected window)
- Cicking a unfocused window (ie. in the actual tiling) focus that window and close the minimap
- Scrolling over the minimap selects the next/previous minimap

Not sure how well it works in practice though. (With minimal adjustments a shortcut could open the minimap so the mouse wouldn't have to be moved)

Note:
- Messes with other elements in the topbar that responds to scroll (eg. the volume icon)
- Clicking the focused window in the tiling is buggy. (press <kbd>Esc</kbd> or <kbd>Return</kdb> to get rid of the minimap)

Replace your ´~/.config/paperwm/user.js´ with the following:

```javascript
var Extension = imports.misc.extensionUtils.extensions['paperwm@hedning:matrix.org']
var Navigator = Extension.imports.navigator;
var Utils = Extension.imports.utils;
var Tiling = Extension.imports.tiling;
var Minimap = Extension.imports.minimap;
var Main = imports.ui.main;
var Clutter = imports.gi.Clutter;

var signals; 

function showMouseMinimap() {

    let space = Tiling.spaces.selectedSpace;
    let minimap = new Minimap.Minimap(space, space.monitor);
    let signals = new Utils.Signals()

    Main.layoutManager.trackChrome(minimap.actor);
    Navigator.navigating = true;
    space.startAnimate();
    minimap.actor.reactive = true;
    minimap.show();

    signals.connect(Main.layoutManager.panelBox.first_child, "button-press-event", () => {
        Main.activateWindow(space.selectedWindow);
        destroy();
    });

    signals.connect(global.display, "notify::focus-window", () => {
        destroy();
    })

    function destroy() {
        Navigator.navigating = false;
        minimap.destroy();
        signals.destroy();
        space.moveDone();
    }

    for (let clone of minimap.container.get_children()) {
        clone.reactive = true;
        clone.connect("button-press-event", () => {
            if (clone.meta_window == space.selectedWindow) {
                if (space.selectedWindow === global.display.focus_window)
                    destroy();
                else
                    Main.activateWindow(clone.meta_window);
            } else {
                Tiling.ensureViewport(clone.meta_window);
            }
        })
    }

    minimap.actor.connect("scroll-event", (actor, event) => {
        let dir = event.get_scroll_direction();
        if (dir === Clutter.ScrollDirection.UP) {
            space.switchLinear(1)
        } else if (dir === Clutter.ScrollDirection.DOWN) {
            space.switchLinear(-1)

        }
    });

    minimap.actor.connect("key-press-event", (actor, event) => {
        let keysym = event.get_key_symbol();
        if (keysym === Clutter.Escape) {
            destroy();
            Tiling.ensureViewport(global.display.focus_window);
        } else if (keysym === Clutter.Return) {
            if (space.selectedWindow === global.display.focus_window)
                destroy();
            else
                Main.activateWindow(space.selectedWindow);
        }
    });

    Main.pushModal(minimap.actor);
}

function init() {
    signals = new Utils.Signals();   
}

function enable() {
    signals.connect(
        Main.layoutManager.panelBox.first_child,
        "scroll-event",
        (actor, event) => {
            if (!Navigator.navigating) {
                showMouseMinimap();
            }
            let dir = event.get_scroll_direction();
            if (dir === Clutter.ScrollDirection.UP) {
                Tiling.spaces.selectedSpace.switchLinear(-1)
            } else if (dir === Clutter.ScrollDirection.DOWN) {
                Tiling.spaces.selectedSpace.switchLinear(1)

            }
        }
    );
}

function disable() {
    signals.destroy();
}
```

**Comment by olejorgenb** [comment]
A cumbersome way to *move* a window using the mouse is to use the scratch layer: Right click the window-titlebar and click "Scratch". Then navigate to another window and insert the scratch window again. It will be inserted to the right of the window selected in the tiling.

Press <kbd>Super+T</kbd> (and hold <kbd>Super</kbd>, navigating the tiling using the mose and let go of <kbd>Super</kbd> also works. (one less shortcut)

**Comment by samesdat** [comment]
Thank you @olejorgenb for the "quick prototype" which works like a charm! Sometimes (when holding the coffee mug in one hand) it's easier to change the active window one-handed by mouse.
Maybe it would be possible to bind the function to the top right hot corner? And why not add the function as "experimental" to the config GUI?

**Comment by olejorgenb** [comment]
Thanks, glad it has come to use :)

> And why not add the function as "experimental" to the config GUI?

I'd rather wait until we have a more complete variant - hopefully not too long :)

> Maybe it would be possible to bind the function to the top right hot corner?

Yes, that's blends well with scroll-left-hot-corner to change workspace also.

For coffe-mug window changes I usually just use the edgeoverlays (ie. move the mouse to the very left/right edge and click) Maybe that's an natural place to activate a (mouse-enabled) minimap also. Right click to open the minimap. Making the edges scrollable might cause to many mistakes though (user intended to scroll the window content but ended up changing focus)

**Comment by samesdat** [comment]
I didn't notice edge overlays before. I tried it out but it works fine only to the right side of the monitor because to the right there is the dash-to-dock, so I have to place the cursor very carefully on the right edge of the dock for invoking egde overlays.

**Comment by hedning** [comment]
Yeah, this won't work great with a left/right aligned dash as they both want to control the edge of the monitor. We went with ceding the space to the dash since it occupies the edge. Personally I put the dash on the bottom and enable autohide.

**Comment by danielyzli** [comment]
This one works great except for when there are no windows and a blank minimap appears to freeze the mouse. Is there an easy fix for that? Thanks!

**Comment by olejorgenb** [comment]
Pressing `Esc` should get rid of the empty minimap at least.

I think returning early if `Tiling.spaces.selectedSpace.selectedWindow == null` in the scroll-event handler should prevent the minimap from appearing when there's no windows but I haven't tested it.

**Comment by hedning** [comment]
We've pushed drag and drop support to develop, here's a short snippet: https://github.com/paperwm/PaperWM/pull/225#issuecomment-575905165
