### ISSUE TITLE
Faster ways to close, maximize and drag active windows from the panel (Fitts law, consistency)

### ISSUE THREAD

**Issue by ripefig** [paperwm/PaperWM#118]
Window management is going to get a lot less consistent with mandatory CSD for all toolkits in Gnome wayland. Behavior is predictable for GTK headerbars, but all bets are off with CSDs from other toolkits (buttin position, drag space, maximization etc. etc.).

Meanwhile the Gnome panel is essentially wasted space, it's sort of a free-for-all system tray area minus the the predictability and customization of traditional system trays.

Given that, I'd suggest considering the following behaviors:
1. Window management buttons positioned at some edge next to an active window indicator. This can be achieved in one of two ways: a) separate small panel on the bottom of the screen containing the title and a few buttons b) integrated into the top panel, like Unity but differently positioned so they don't interfere with hot corner. 

2. Press hotkey then click anywhere in the window to maximize or close it - equivalent of alt+drag.

3. Top panel acts as a large title bar for the active window. (See Latte dock on KDE). When you drag from the top panel, the active window is dragged regardless of geometry. When you right-click or double-click - depending on the config - an empty space in the top panel, the window gets maximized.

**Comment by jtaala** [comment]
Granted this issue is old, and I'm not sure if the current CSD implementation/constraints (in Wayland or otherwise) have had an impact enough to require implementing these suggestions.

Let me know if any current use cases where these suggestions would needed.  Otherwise planning on closing this issue in a month or so.

**Comment by Lythenas** [comment]
I don't see this as an issue ATM. You can navigate to the window with keybindings and then use keybindings to close, maximize or move it. Also you can just press Super and then drag from anywhere in the window to move it.

**Comment by jtaala** [comment]
Closing as stipulated in previous comments (have received no further feedback in more than a month).
