### ISSUE TITLE
Space-saving with pseudo-globalmenu.

### ISSUE THREAD

**Issue by ripefig** [paperwm/PaperWM#119]
Sorry if out of scope, but this is is the biggest deficiency of Gnome IMO.

Right now there is no way to save space or optimize menubars in Gnome, like there is with KDE and unity. Furthermore, the fact that some apps have menubars and titlebars while others have headerbars makes for a hugely inconsistent desktop. In a tiling environment, the extra space occupied by menubars is a big problem.

I would suggest using a HUD popup as a replacement for menubars, like the global menu, but without the problems caused by global menus. (For example global menus are incompatible with sloppy focus, hard to use to large screens, can't be constructed for Gnome apps, and are cumbersome for the same reason that regular menubars are). Furthermore, a global menu extension is technically fraught on Gnome shell, since it gets rendered at the same time as the window - which chokes the shell.

Anyway: 

Ideally the HUD screen would be accessible via the top panel and a hotkey. It would provide an overview for the functionality of each application, much like Gnome overview does for the entire desktop. Here's a mockup I made for how the HUD could be used as drop-in replacement for the menu bar in the Qalculate app. All the menu items are exported as clickable buttons to searchable and scrollable HUD (similar to a Ribbon interface with Ribbons stacked on top of each other). I feel this would be nice complement to the scrollable design of PaperWM.
Such a HUD could work for headerbar apps thanks to Plotinus and the current efforts over at vala panel.

![image](https://user-images.githubusercontent.com/45201036/59563576-8e3c4080-9044-11e9-9d7e-e8e1e0e7b5a6.png)

**Comment by olejorgenb** [comment]
That's an interesting idea, but as you say - quite out of scope for this project :)

In general the WM has very little power to change how applications work (and this is even more true for gnome-shell extensions)

[Plotinus](https://github.com/p-e-w/plotinus) is a really cool project and shows that certain incisions is possible to do quite generally on gtk-applications.

I'm not familiar with vala-panel and couldn't figure it out by a glance. Is it an project that tries to extract the menus of gtk-applicatons?

- Such application-alterning projects require a more complicated installation than an extension.
- Implementing such features as an extension would limit the userbase. (lots of people run gtk apps in other environments)
- In most cases I think only minor window manager integration would be needed. (the menu could be a window that the WM handles in a special way for instance)

I'll close this as out of scope atm. ;)

**Comment by ripefig** [comment]
The appmenu-gtk project is part of Vala panel project. They are trying to find a solution for menu-less GTK apps and GTK4. Their ultimate goal to to keep the Unity dream (having a consistent interface for all applications) alive.

It's obviously out of scope, but it would help streamline PaperWM (and Gnome) a great deal.
