### ISSUE TITLE
GNOME and PaperWM backgrounds are different

### ISSUE THREAD

**Issue by andreasomaini** [paperwm/PaperWM#122]
# The Issue

After setting a background through PaperWM settings, if it is different than the one in GNOME settings: the one in the standard view and the one in the overview (hitting META) are different.

## Standard view

![Schermata da 2019-06-21 20-08-00](https://user-images.githubusercontent.com/49907041/59942806-f33ad080-9460-11e9-87a2-8fec99e92932.png)

## Overview

![Schermata da 2019-06-21 20-08-14](https://user-images.githubusercontent.com/49907041/59942812-f8981b00-9460-11e9-8a27-3058396e59f3.png)

You can see in the workspaces tab the different background which is the one provided in GNOME settings.

## Solution

Maybe we can set as GNOME background the PaperWM one?

**Comment by hedning** [comment]
Yeah, the default background option should probably just be a switch which tells paperwm to use the background that gnome uses.

**Comment by bjeanes** [comment]
Yeah I am not a fan of the coloured workspaces. I already have BG image configured and I'd like to see it. Maybe another signal of the active space could be good or even just the ability to configure the workspace color to "transparent"?

**Comment by hedning** [comment]
A transparent background doesn't really work with the workspace carousel (`super-above_tab`), having the same background on all spaces also looks a bit weird there, but we do have an option for that in the preference gui (`Default Background`).

As noted it might be better to make this a switch which looks up the gnome background, though that will again make the workspace carousel look even weirder (a bunch of the same images on top of the same image).

We should make better default color palette though #127.

**Comment by bjeanes** [comment]
What if the colour was just a thin overlay over the BG image to differentiate them? Or a border?

**Comment by hedning** [comment]
A border makes sense to me, that could in principle fix #83 too and make the scroll cutoff look better in the workspace carousel. I guess some light transparency could work too, but adding color to an unknown image and making it look consistently OK is pretty hard.

Now I'm obviously a fan of the plain color backgrounds :) In particular they make different workspaces identifiable at a glance (eg. my paperwm project workspace is dark green), and there's nothing random peaking out through the gaps between windows. But yeah, I'm open to make the standard wallpaper work a bit better as it seems a lot of people like that and a border might actually iron out some other visual issues too :)

**Comment by hedning** [comment]
OK, made a border/frame prototype https://github.com/paperwm/PaperWM/commits/workspace-frame:

With common background:
![image](https://user-images.githubusercontent.com/71978/60112175-a2342080-976f-11e9-9360-e6725eb2047e.png)

With plain colors:
![image](https://user-images.githubusercontent.com/71978/60113719-add51680-9772-11e9-8a8b-19343d79dab9.png)
