### ISSUE TITLE
Trouble to switch window between monitors

### ISSUE THREAD

**Issue by egegunes** [paperwm/PaperWM#135]
I couldn't figure out how to switch windows or workspaces between monitors. Workspace and window change bindings for Gnome does not work. Can it be accomplished by a custom keybinding?

**Comment by hedning** [comment]
The built in `super-shift-arrows` should work to move windows between monitors (though note that mouse warping isn't supported in wayland making it a bit awkward). If the monitors are scaled differently it might not work however as the resulting resize might push the window back to the original monitor (we simply listen on the event that tells us when windows enters a monitor). Dragging windows with the mouse also works.

There's currently no simple action to move/rotate workspaces between monitors, we should really get that done. It is however possible by pushing the workspace down to the stack (`super-above_tab`) and retrieving it on the other monitor (also with `super-above_tab`).

**Comment by hedning** [comment]
We added a keybinding example which cycles through monitors. Add this to the `init` function in `user.js`:
```
   Extension.imports.examples.keybindings.cycleMonitor();
```
That should make `super+d` cycle through monitors.

**Comment by egegunes** [comment]
I tried the keybinding but it selects the other monitor only momentarily.

**Comment by hedning** [comment]
Right, I'm guessing the mouse pointer is stuck on the other monitor? The pointer will then easily trigger a motion event on the old monitor and bring focus back. On x11 we're able to warp the pointer to the correct monitor, but gnome on wayland doesn't support that yet unfortunately.

So, yeah, x11 is by far better when using multiple monitors a lot. Now we should probably add some lower threshold to the pointer motion making it less likely to trigger it without intent.

**Comment by hedning** [comment]
Made a PR which should fix the example keybind on wayland (it will also try to reject random pointer movement).

**Comment by egegunes** [comment]
I checked out motion-workspace-threshold branch and tried. Super+D works now!

**Comment by hedning** [comment]
Cool, I'll push to master pretty soon.

**Comment by egegunes** [comment]
master works fine but switching focus to a fullscreen window with Super+D causes #134

**Comment by hedning** [comment]
Should be fixed #182, though there's still some funky top bar behavior. Really need to rewrite most of that logic I think :/
