### ISSUE TITLE
Super+esc serving double duty results in scratch layer confusion

### ISSUE THREAD

**Issue by kamalmarhubi** [paperwm/PaperWM#136]
The following sequence results in unexpectedly moving back to the initial window:

1. hold super
2. press right a few times to go to another window
3. continue holding super and hit escape to toggle scratch layer

The escape cancels the movement, requiring a second press to get the scratch layer. I also lose my attempted motion in the tiling layer.

I keep expecting the escape press to bring the scratch layer above my current location.

A moving picture is worth a thousand words:
![animation](https://user-images.githubusercontent.com/50936/60275400-df132b00-98c7-11e9-9a15-fe0f2df989d2.gif)

**Comment by olejorgenb** [comment]
Yes, that's absolutely a quirk of the current bindings. I don't think we can/want to change the cancel binding as ESC usually mean cancel and it's also used elsewhere in chrome (eg. to cancel alt-tab)

As a quick-fix you can reconfigure the scratch layer bindings yourself (through the extension settings GUI)

Nice animation btw :) Which program did you use?

**Comment by kamalmarhubi** [comment]
> I don't think we can/want to change the cancel binding as ESC usually mean cancel and it's also used elsewhere in gnome (eg. to cancel alt-tab)

Definitely agree about that one. Do you think the default scratch layer binding might change instead?

> Nice video btw :) Which program did you use?

Hah, nothing fancy:
- `Ctrl+Alt+r` in gnome to record
- [screenkey] for overlay
- [figlet] for terminal contents
- ffmpeg for webm -> gif ([following these instructions][ffmpeg])

[screenkey]: https://www.thregr.org/~wavexx/software/screenkey/
[figlet]: http://www.figlet.org/
[ffmpeg]: http://www.ubuntubuzz.com/2017/08/convert-mp4-webm-video-to-gif-using-ffmpeg.html

**Comment by hedning** [comment]
> Do you think the default scratch layer binding might change instead?

Yeah, open to that, `super+s` (which we started with) is unfortunately already used to toggle the overview by gnome-shell. `super+caps_lock` could be nice, but I don't think it's easy to prevent it from toggling caps. `super-space` is taken by the switch keyboard layout menu.

Suggestions for a good binding is welcome :)

> ffmpeg for webm -> gif (following these instructions)

Nice, last time I tried to convert from webm to gif I ended up with a horrible artifiacts, but this looks good.

**Comment by kamalmarhubi** [comment]
> Suggestions for a good binding is welcome :)

The first thing that came to mind was `super+enter`. But that's used by new window. I don't know what restrictions exist on bindings... are multi-modifier-only bindings possible, eg `super+ctrl`, `super+alt`, or `super+shift`?

**Comment by Pajn** [comment]
I was about to suggest `super+home` as that is next to page up/down and thus where I otherwise change workspace, but noticed that those are taken. Insert and delete are left though, maybe not super obvious but it's nice to have them grouped close together.
