### ISSUE TITLE
super+shift-arrows doesn't work for X11 on secondary monitors

### ISSUE THREAD

**Issue by hedning** [paperwm/PaperWM#140]
For some reason a second `window-entered-monitor` event is triggered on the original monitor causing the window to be moved straight back.

We probably need to add our own actions to fix this.

**Comment by Pajn** [comment]
I have two custom keybinding for this, maybe they might be a base for implementing the functionality in the extension itself https://github.com/paperwm/PaperWM/issues/165#issuecomment-522308865
