### ISSUE TITLE
Virtualbox Windows 10 VM window causes gnome shell crash when paperwm is active

### ISSUE THREAD

**Issue by danielyzli** [paperwm/PaperWM#144]
Virtualbox: 5.2.18 with guest additions; Pop! OS 18.10; gnome shell 3.30.2

When window's display manager (dwm?) starts up in the virtual machine, a tiled virtualbox (that is not full height) attempts to stretch itself vertically, goes blank, then crashes gnome shell and sends me back to the login screen.

**Comment by hedning** [comment]
Probably need some logs to figure this one out. Run `journalctl --pager-end $(which gnome-shell)` and search for `JS ERROR` or `gnome-shell.*segfault` to find stuff that looks relevant.

**Comment by danielyzli** [comment]
Unfortunately I wasn't able to recreate the issue today. I'll keep you posted if it arises again.

**Comment by olejorgenb** [comment]
My hunch is that it's related to virtualbox resizing itself. We do a relayout in response to a resize so if the application is stubborn a resize dance can happen. Mutter/gnome-shell is not always a fan :)

(Unfortunately it's not easy/possible to know if the resize originated from the user or not)

**Comment by jtaala** [comment]
Given the issue couldn't be recreated (from what's recorded in this issue), and the age of this issue and version of PaperWM at the time - I'm going assume this issue is no longer valid.

Planning to close this issue in a month or so.

**Comment by olejorgenb** [comment]
Latest VirtualBox also misbehave in the scratch layer for me, but turning off "Auto-resize guest display" and manually setting the size using the "View -> VirtualScreen *" menu works well. (for some reason the "Adjust windows size" function does not work)

![Image](https://github.com/user-attachments/assets/943d3f93-ce76-4abc-929e-bc60f0d6c4ac)

![Image](https://github.com/user-attachments/assets/04a45e30-3528-4d3c-9a0e-fe90162f7e08)

**Comment by develop7** [comment]
@olejorgenb whoa, thank you for the workaround!
