### ISSUE TITLE
Clicking on stack view makes papervm stop taking user inputs when using desktop icons

### ISSUE THREAD

**Issue by Kolloom** [paperwm/PaperWM#145]
Seems #110 is related

![paper_vm_bug](https://user-images.githubusercontent.com/13244794/60689162-13668880-9e80-11e9-926b-11f7fca69cdd.gif)

Other shell functions are not affected ( calendar on top of screen, hot corners, side bar ) 
Everything papervm touches does not take any mouse or keyboard inputs
Has to log out the session every time this happens

-----
gnome shell 3.32.1
ubuntu 19.04
single monitor setup 
repo ver ae8e910

```
Jul 04 17:09:30 fed-desk gnome-shell[15023]: JS WARNING: [resource:///org/gnome/shell/ui/workspacesView.js 527]: reference to undefined property "_workspacesViews"
Jul 04 17:09:30 fed-desk gnome-shell[15023]: JS ERROR: Exception in callback for signal: cancel: TypeError: this._workspacesViews is undefined
                                             _endTouchGesture@resource:///org/gnome/shell/ui/workspacesView.js:527:25
                                             _emit@resource:///org/gnome/gjs/modules/signals.js:128:27
                                             set enabled@resource:///org/gnome/shell/ui/windowManager.js:478:13
                                             WorkspacesDisplay<@resource:///org/gnome/shell/ui/workspacesView.js:482:9
                                             ViewSelector<@resource:///org/gnome/shell/ui/viewSelector.js:167:35
                                             ControlsManager<@resource:///org/gnome/shell/ui/overviewControls.js:405:29
                                             init@resource:///org/gnome/shell/ui/overview.js:234:26
                                             _initializeUI@resource:///org/gnome/shell/ui/main.js:187:5
                                             start@resource:///org/gnome/shell/ui/main.js:127:5
                                             @<main>:1:31

```

**Comment by hedning** [comment]
Hmm, I'm unable to reproduce, clicking on a workspace in the stack is supposed to activate it, which works as expected here. My hunch is some sort of interaction between paperwm and the desktop extension you're using. Looks like something is at least capturing the click before we can get to it.

The error looks unrelated and seems to emanate from code run on startup.

**Comment by hedning** [comment]
Yeah, I'm able to reproduce with the desktop icon extension. Scrolling on the workspace/activities button in the top bar gets you out of it as a quick fix.

Now, the desktop icon extension puts icons above paperwm's chrome. Working around this is paperwm would probably take far too much work, so I'd say your best bet is disabling the desktop icon extension unfortunately.

**Comment by Kolloom** [comment]
> Scrolling on the workspace/activities button in the top bar gets you out of it as a quick fix.
The windows remain unresponsive to mouse and keyboard inputs. 

The desktop icon in gnome tweak is disabled though. Not sure if this is a different package or what. I did upgrade from 18.10

I don't have a problem with not using desktop icon, but as this is the default behavior on ubuntu, it might be helpful to put that in a faq somewhere

**Comment by hedning** [comment]
Makes sense to add that to the readme if you find a way to disable it. It looks like there miht be an option  `/org/gnome/nautilus/desktop` in dconf-editor.

**Comment by Kolloom** [comment]
Ah I got it. 

gnome tweak has no effect on desktop icon extension whatsoever. 

Disabling it from the web interface does nothing either. 
Had to uninstalled it 
https://extensions.gnome.org/local/

Mouse works correctly now in stack view

**Comment by Pajn** [comment]
Instead of uninstalling, choosing Gnome instead of Ubuntu at login should work. Notice though that Gnome defaults to Wayland and Ubuntu to X, so make sure you get the one you want.

**Comment by Kolloom** [comment]
@Pajn There is only two options `ubuntu` and `ubuntu-wayland`

After rebooting, the extension came back. 

Looks like the extension is enforced via https://help.gnome.org/admin/system-admin-guide/stable/extensions-lockdown.html.en key

However disabling that seems to have no effect either. An older version of the extension will be installed regardless upon login in. 

uninstalling `gnome-shell-extension-desktop-icon` will get rid of `ubuntu-desktop` and `ubuntu-desktop-minimal` so I am not sure if disabling this extension is even possible.

**Comment by olejorgenb** [comment]
Installing `gnome-session` (`sudo apt install gnome-session`) will give you a vanilla gnome option in ubuntu (more recent versions at least)

**Comment by Kolloom** [comment]
@olejorgenb that did it. I was wondering why

**Comment by Kolloom** [comment]
there is two options under org.gome.nautilus.desktop `home-icon-visible` and `network-icon-visible` neither affects the shell extension.
