### ISSUE TITLE
Bottom margin

### ISSUE THREAD

**Issue by Danmou** [paperwm/PaperWM#146]
Currently it seems the vertical margin setting only applies to the top margin and gaps between vertically stacked windows, whereas the bottom edge of the window is always flush with the bottom of the screen. It would make more sense if the margin was applied on the top and bottom, or if there was a separate setting for the bottom margin.

**Comment by olejorgenb** [comment]
Yes, this is on the TODO list :)

Semirelated: At work I have a very large monitor and actually run with a patch allowing (singel-column) windows to not be vertically maximized. In the long run we might incorporate a variant of that too.
