### ISSUE TITLE
Super+tab doesn't work for 'switch to previous workspace'

### ISSUE THREAD

**Issue by Danmou** [paperwm/PaperWM#149]
I want to use `super+tab` to switch to the previous workspace, instead of `super+above_tab`. I managed to set the keybinding and disable all other keybindings that used the same combo (I had to use gsettings to set the keybinding because the GUI wasn't picking it up). Now it works for switching to the previous workspace, but if I press tab again to cycle through the workspaces, it cancels and goes back to the original workspace.

**Comment by hedning** [comment]
Right, copied this special case from gnome-shell's switcherpopup code:
https://github.com/paperwm/PaperWM/blob/f93357155f44fdf89b4c47723e9a61ce1d99f866/navigator.js#L110

Can't come up with a good reason to keep it, so should just remove it.

> I had to use gsettings to set the keybinding because the GUI wasn't picking it up

Yeah, IIRC the gtk widget that's used to record the keybinding simply refuses to pick up `super+tab`.

**Comment by olejorgenb** [comment]
This [commit](https://gitlab.gnome.org/GNOME/gnome-shell/commit/4a7082bb0f3ec8f8cc4a200aa974aa20de379f8f) introduced the behavior in gnome-shell. I don't think the applies to us. If we were to support binding super-esc to navigation cancelable naviagation we'd rather allow explicitly rebinding the cancel action.

**Comment by olejorgenb** [comment]
Note to future user finding this issue: Use dconf-editor to bind actions to keys the GUI doesn't allow.

Starting it like this makes it aware of the schema creating a much better experience.

```
GSETTINGS_SCHEMA_DIR=$HOME/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/schemas dconf-editor /org/gnome/shell/extensions/paperwm/
```
