### ISSUE TITLE
Disable background active window indicator highlight

### ISSUE THREAD

**Issue by danielyzli** [paperwm/PaperWM#154]
The background highlight colour isn't pleasant for any transparent elements. I'm using the glassy-gnome extension and I used to have a translucent terminal window, both of which have weird colour changes when active because of the background highlight bleeding through. Could you show me how to disable it?

Would it be out of question to put some of the glassy-gnome transparency effects into paperwm? It could play well with the zen mode in #21 and remove the need for the big window highlight. Another possible tweak would be to have the option to un-decorate the non-scratch windows (i.e. hide non-gtk app title bars) because those title bars aren't of much use.

Another issue is that the background highlight sometimes hangs for me, for instance if you open a window then hit `Super + D` you have a highlight that stays on your desktop.

Thanks devs in advance!

**Comment by hedning** [comment]
This should hide the highlight. Not sure if it makes sense to create a preference for this though, as there isn't anything else which properly indicates the pseudo-focus when navigating (eg. when using `super+arrows`). 
```diff
modified   tiling.js
@@ -178,6 +178,7 @@ class Space extends Array {
         let selection = new St.Widget({name: 'selection',
                                        style_class: 'tile-preview'});
         this.selection = selection;
+        this.selection.hide();
 
         clip.space = this;
         cloneContainer.space = this;
```

> Would it be out of question to put some of the glassy-gnome transparency effects into paperwm?

Not out of question, but not it's not something I'm personally interested in (I've never taken to transparent windows etc.).

> Another issue is that the background highlight sometimes hangs for me, for instance if you open a window then hit Super + D you have a highlight that stays on your desktop.

Using the `cycleMonitor` keybind? I'm not able to reproduce that at least. What commit are you on? We recently fixed some issues with dynamic workspaces and multiple monitors (eg. 570abadc9b713b1f184da0c974b5e3864fcafc45).

**Comment by YoungElPaso** [comment]
@danielyzli 
Personally, I just edited the stylesheet so it was something a bit more muted with rounded corners (to better fit my Gnome shell styles).  It was pretty easy.  Maybe just documenting that or providing a user.css file would make sense. Must say, this is a pretty incredible project tho.

**Comment by hedning** [comment]
There's now rounded corners in develop :) (8px which I believe is the same used for adwaita corners).

**Comment by Hoffmano** [comment]
> @danielyzli Personally, I just edited the stylesheet so it was something a bit more muted with rounded corners (to better fit my Gnome shell styles). It was pretty easy. Maybe just documenting that or providing a user.css file would make sense. Must say, this is a pretty incredible project tho.

What is this file location?
Found => `~/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/stylesheet.css`

```
.paperwm-selection {
    /* matches border radius of default gnome windows */
    border-radius: 12px;
```

**Comment by Lythenas** [comment]
You can edit that one but it will get overwritten when you update the extension.

You can add your own styles to `~/.config/paperwm/user.css`.
