### ISSUE TITLE
Dialogs from scratch layer window open below window

### ISSUE THREAD

**Issue by kamalmarhubi** [paperwm/PaperWM#161]
Observed in Firefox when downloading files, but more easily reproduces by just hitting `<C-o>` to open a file.

Steps:
1. put firefox window in scratch layer
2. hit `<C-o>`

Expected: file dialog is visible.

Actual: File dialog is not visible, Firefox browser window is dimmed and does not have focus; instead the hidden dialog does.

The only way I've found to bring the dialog to the front is to switch workspace a couple times. You can hit escape to close the dialog and get focus back to the visible Firefox window.

**Comment by olejorgenb** [comment]
Can not reproduce here. Can you post some details of your system:

- X11 or Wayland
- gnome-shell version
- paperwm commit
- other extensions active (or - have you tried with only paperwm active?)
- firefox version (have you experienced it with other programs? (gedit for instance))

Check the output from `journalctl --pager-end $(which gnome-shell)` for suspicious output. (esp. ERROR) 

Have it only recently started happening? We fixed a bug a couple of days ago that might be related.

**Comment by hedning** [comment]
Yeah, this only happens on wayland.

Pretty sure it's an upstream bug with «always on top» windows in wayland as I'm able to reproduce it without paperwm.

IIRC this started to happen in 3.32.

**Comment by hedning** [comment]
Did a quick test to see if we could fix it ourselves by making the menu «always on top», but it doesn't work unfortunately.

**Comment by hedning** [comment]
Hmm, nevermind, I misread dialog as menu. I'm unable to reproduce with firefox running in wayland mode at least.

**Comment by olejorgenb** [comment]
Some changes that miiight affect this bug has been checked in. (https://github.com/paperwm/PaperWM/commit/611680e06be5ef4f1e9aa1da85de6b83ee5fba31)

**Comment by kamalmarhubi** [comment]
I still see this with context menus, now under Wayland with GNOME 3.34. Don't recall if 3.32 had the issue, but it's somewhat annoying. Happy to provide other environment issue. In the meantime, a screenshot:
![Screenshot from 2019-11-26 18-39-59](https://user-images.githubusercontent.com/50936/69681465-2de20e00-107c-11ea-99cc-e52e147c4a27.png)

**Comment by hedning** [comment]
Yeah, that's unfortunately an upstream bug with «Always on top» windows in wayland: https://gitlab.gnome.org/GNOME/mutter/issues/587

**Comment by kamalmarhubi** [comment]
Ah ok, closing this and linking to upstream issue in top message in case anyone else gets here.
