### ISSUE TITLE
Dash to panel intellihide weird bounce when second window is opened in paperwm

### ISSUE THREAD

**Issue by danielyzli** [paperwm/PaperWM#166]
Paperwm: latest version
Gnome-shell: 3.30.2
Dash to panel: v21
OS: Pop OS 18.10

Steps to reproduce:
Dash to panel intellihide configuration:
- Hide from focused windows
- Allow panel to be shown in fullscreen mode
- Require pressure to reveal panel
- Do not only hide secondary panels
Make sure paperwm is enabled (bug does not occur when paperwm is not enabled)
Open any window, then open a second window

Expected behaviour:
New window opens and since it doesn't obstruct the panel, dash to panel stays as is

Actual behaviour:
As the new window opens, dash to panel quickly hides then un-hides

![Peek 2019-08-22 09-12](https://user-images.githubusercontent.com/47434276/63531312-17487b80-c4bd-11e9-84ae-3bd54d55a7f7.gif)

**Comment by jtaala** [comment]
This doesn't occur in recent versions of PaperWM.  Dash-to-panel currently works well with PaperWM (tip: in PaperWM settings you can turn off the `Window position bar` at the top).
