### ISSUE TITLE
Window positions increadibly messed up under Gnome 3.34

### ISSUE THREAD

**Issue by Pajn** [paperwm/PaperWM#168]
I don't know how to explain the behaviour but:
- Sometimes windows are placed correctly
- Sometimes windows are placed just a little bit off, aprox. 20px to the left and 40 px to the top (so it's below the top bar and just a bit outside the monitor).
- Sometimes windows are placed nearly completely outside the monitor
- Sometimes windows are placed on the wrong screen (though I could only get this once)
- Sometimes one of the windows are placed behind the others outside of the normal row combined withe the other windows being a little bit of as described above

Most times when clicking on the top bar of a messed up window, it slides to the correct position.

**Comment by hedning** [comment]
Ah, haven't tested 3.34 yet, will do and check what needs fixing :)

**Comment by hedning** [comment]
Ok, that was fortunately easier than it sounded (pushed a fix to your PR).

Seems like they've added this rather weird hack, making any `object.actor` access return `object` (for clutter actors), this happened to break our usage of `clone.actor` where `clone !== clone.actor`:

https://gitlab.gnome.org/GNOME/gnome-shell/blob/master/js/ui/environment.js#L232

**Comment by Pajn** [comment]
It seems to work great, thank you!
I will try to get some time to fix the comment in the PR so that it can be merged.

**Comment by hedning** [comment]
Should be fixed by #167
