### ISSUE TITLE
Keybinding does not trigger without a window focused

### ISSUE THREAD

**Issue by mogenson** [paperwm/PaperWM#169]
Hello, I'm trying to implement some convenience shortcuts via the user.js init() function. This one should open a new terminal window in the same directory if Gnome terminal is focused. Otherwise it should create a new terminal. This works as expected when a Gnome terminal or other window is focused. But I can't get the keybinding to trigger when no window is focused. For example, when starting with a blank desktop or switching to an empty workspace.

```
    Keybindings = Extension.imports.keybindings;
    // note: Open New Window shortcut has been remapped to Super + N
    Keybindings.bindkey("<Super>Return", "open-terminal", (metaWindow) => {
        if (metaWindow.get_gtk_application_id() == "org.gnome.Terminal") {
            // open new terminal window in same directory
            var app = App.Tracker.get_window_app(metaWindow);
            App.newGnomeTerminal(metaWindow, app);
        } else {
            // create a new terminal in default directory
            imports.misc.util.spawn(['gnome-terminal']);
        }
    });
```

By the way, is there a way to spawn a new application by gtk id, or tell the gnome terminal server to create a new terminal instead of spawning a command line process?

**Comment by olejorgenb** [comment]
The accelerator grab API added a mandatory flag argument in 3.3x. Seem I used the `PER_WINDOW` flag. I don't it was intentionally so I'll change it to `ALL` which should fix the problem. (The flag should probably be exposed to the keybinding API though)

> By the way, is there a way to spawn a new application by gtk id, or tell the gnome terminal server to create a new terminal instead of spawning a command line process?

See https://github.com/paperwm/PaperWM/blob/master/app.js#L8 for the second part.

**Comment by mogenson** [comment]
Fixed, thanks!

As a note to future me: don't forget to check if metaWindow is null.     
  

> See https://github.com/paperwm/PaperWM/blob/master/app.js#L8 for the second part.

I mean how to launch a new application if no window is focused and metaWindow and app are null?

**Comment by olejorgenb** [comment]
Ups. This is one way:

```
let gtAppInfo = imports.gi.Gio.DesktopAppInfo.new("org.gnome.Terminal.desktop")
gtAppInfo.launch_action("new-window", null)
```

https://developer.gnome.org/gio/stable/gio-Desktop-file-based-GAppInfo.html
