### ISSUE TITLE
Keep workspaces in same order

### ISSUE THREAD

**Issue by jlacson** [paperwm/PaperWM#171]
Could it be possible to keep the workspaces in the same numerical order when toggling between them instead of in order of recently used? It seems that PaperWM takes over the Win+PageUp and Win+PageDown shortcuts that move up and down workspaces.

I also didn't see any toggle that would suggest that this is a possibility, if this is already a feature apologies in advance.

**Comment by hedning** [comment]
Yeah, ideally `Super+PageDown/Up` would move sequentially while `Super+Above_tab` moves in most recently used order (https://github.com/paperwm/PaperWM/pull/115).

For a quick fix you can go remove the `super+pagedown/up` bindings, that will automatically enable the native bindings (though we kill the animation, which is what's missing in #115). Removing bindings is done by clicking on the binding and pressing backspace.

![image](https://user-images.githubusercontent.com/71978/65220891-0c810680-dabc-11e9-8ed4-806d4405162d.png)
