### ISSUE TITLE
add keyboard shortcuts to switch/move between displays

### ISSUE THREAD

**Issue by tycho01** [paperwm/PaperWM#172]
Currently, the readme lists a number of keyboard shortcuts, though none related to displays.
As a result, moving windows between my monitors is one of the only things I'm using the mouse for with PaperWM.
Would it be possible to add a shortcut for this?

**Comment by olejorgenb** [comment]
The builtin `super+shift-arrows` shortcuts should work on wayland.

Moving a window from one monitor to another: #140, #135

Switch focus between monitors: https://github.com/paperwm/PaperWM/issues/135#issuecomment-507061302

**Comment by hedning** [comment]
@Pajn made more complete bindings: https://github.com/paperwm/PaperWM/issues/165#issuecomment-522308865

We should probably just adopt those tbh.

**Comment by tycho01** [comment]
seems to work :), hope it'll make it into the readme but let's close this in favor of the existing thread!
