### ISSUE TITLE
Super-Left/Right Preview (Disable minimap?)

### ISSUE THREAD

**Issue by rawkode** [paperwm/PaperWM#173]
Is it possible to hide the preview when using the Left/Right window shortcuts?

**Comment by olejorgenb** [comment]
Not atm.

Why do you want to disable the previews (aka. minimap)? I recommend giving it some time to get used to. I rarely get distracted by the minimap's presence and it's often useful when moving a larger distance.

Would a configurable delay work? (there's a 200ms hardcoded delay atm.)

If you really can't stand it you can apply this patch: :D

```diff
diff --git a/keybindings.js b/keybindings.js
index 2d43d00..1514523 100644
--- a/keybindings.js
+++ b/keybindings.js
@@ -95,8 +95,8 @@ function init() {
     registerMinimapAction("switch-first", Tiling.activateFirstWindow);
     registerMinimapAction("switch-last", Tiling.activateLastWindow);
 
-    registerMinimapAction("switch-right", (mw, space) => space.switchRight());
-    registerMinimapAction("switch-left", (mw, space) => space.switchLeft());
+    registerNavigatorAction("switch-right", (mw, space) => space.switchRight());
+    registerNavigatorAction("switch-left", (mw, space) => space.switchLeft());
     registerMinimapAction("switch-up", (mw, space) => space.switchUp());
     registerMinimapAction("switch-down", (mw, space) => space.switchDown());
```

(you might want to do the same for "switch-first/last/up/down" too)

**Comment by flukejones** [comment]
I second this. I've found I try to look past the minimap to see what I've selected as teh minimap isn't that readable at a glance. Maybe it's the theme (Adwaita).

**Comment by hedning** [comment]
Right, we should be able to do a toggle, it's basically just checking a preference here
https://github.com/paperwm/PaperWM/blob/e629cde2ccb15ca012d28a2d365fd86ab00b5661/navigator.js#L155

(Doing `Navigator.Navigator.prototype._showMinimap = () = {}` in user.js should also do the trick).

Now, one idea is deferring the minimap until we actually scroll the viewport. This way navigating visible windows, which doesn't really benefit from the minimap, is clean, while we get the benefit when doing potentially larger navigations.

**Comment by kurka** [comment]
> Would a configurable delay work? (there's a 200ms hardcoded delay atm.)

Increasing/configuring the delay would be a great solution, in my opinion. Is this currently possible?

**Comment by hedning** [comment]
> Is this currently possible?

Not at the moment.

**Comment by jtaala** [comment]
I can understand this preference.

Mini-map size is now user-configurable (#454) - we could allow it settable to 0% and make that hide the mini-map?  I think that would satisfy this request.

**Comment by terlar** [comment]
I'm one of those people who would prefer not having the mini-map. Related issue #325

**Comment by jtaala** [comment]
> I'm one of those people who would prefer not having the mini-map. Related issue #325

Thanks @terlar, I'll work on a quick PR for this and get you to test it when it's done.

Cheers.
