### ISSUE TITLE
gnome-shell restart creates "window ready" notifications for every window

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/PaperWM#18]
Introduced roughly between dd5d7621229c33c6e27c8a4a3165428f99dc675a and 9c3931f429a368cf339f7e8d8fb2a24ecff6eae9

**Comment by olejorgenb** [comment]
It doesn't happen every time. Attempts at bisecting came up short. Maybe the bug always been there, but we didn't restart that often before packaging the extension?

**Comment by hedning** [comment]
Might be caused by 'window-removed' focusing the window to the left. When eg. closing `emacs` I get these popups, probably for the windows left of the closing emacs windows.

**Comment by olejorgenb** [comment]
I still get them after commenting out (in remove_handler)

        // space[Math.max(0, removed_i - 1)].activate(global.get_current_time());

and restarting twice.

But gnome-shell might do some focus-another-window-after-remove by itself?

**Comment by olejorgenb** [comment]
Fixed as a side effect of some other changes?  (at commit ca35cf2595f2b36b2147b6f5e8fe3e15d5b322e3)
