### ISSUE TITLE
Consider using schemas

### ISSUE THREAD

**Issue by atagulalan** [paperwm/PaperWM#180]
Instead of pushing key:value pair, please consider using schemas.
With this, we can use **gsettings** easily to change any settings.

**Comment by hedning** [comment]
Not entirely sure I follow. We're are using schemas: https://github.com/paperwm/PaperWM/blob/master/schemas/org.gnome.shell.extensions.org-scrollwm.gschema.xml

In the code we're using a convenient wrapper, `Settings.prefs`, where are updated when the schema values change.

**Comment by olejorgenb** [comment]
Note that extension schemas is not automatically picked up by the generic tools: https://github.com/paperwm/PaperWM#using-dconf-editor-to-modify-settings

I guess a similar trick can be used to make `gsettings` aware of the schema.

**Comment by hedning** [comment]
I'll close this as I then :)
