### ISSUE TITLE
Emacs GUI / gnome-terminal difficult to resize

### ISSUE THREAD

**Issue by danielyzli** [paperwm/PaperWM#187]
Using resize bindings (```Super + R``` and ```Super + Shift + R```) don't really affect emacs GUI window. Also, emacs GUI window bottom edge doesn't line up with the bottom of all other windows.

**Comment by danielyzli** [comment]
Just tested ```gnome-terminal```, it also doesn't respond well to ```Super + R```. Perhaps the emacs GUI inherits the issue from ```gnome-terminal```

**Comment by hedning** [comment]
Yeah, apps that don't do pixel resizing have some sharp edges. We simply don't have access to the necessary information from javascript unfortunately: https://github.com/paperwm/PaperWM/issues/106

For emacs you want to set this `(setq frame-resize-pixelwise t)` to make it well behaved. I'd recommend tilix as a alternative to gnome-terminal (it also handles zoom in a sane manner).

**Comment by olejorgenb** [comment]
The *cycle* actions (eg. `Super + R`) allow for some slack when determining the next size, but if the resize increment is larger than this slack they might get stuck. 

We could check the size after resize and issue a new slightly larger/smaller resize if the window didn't respond :thinking: 

@hedning resize is synchronous for Xwayland windows?

**Comment by hedning** [comment]
> @hedning resize is synchronous for Xwayland windows?

Yeah, Xwayland windows operate as if they're on X11 IIRC.

**Comment by danielyzli** [comment]
Thanks! The fix worked! Can close now :smile: 
Just wanted to say (a trick I figured out for fellow tilix users), you can get a clean ```Open Tilix Here``` and no ```Open Terminal Here``` duplicate in Nautilus file manager context menus by ```apt install nautilus-python && apt remove nautilus-extension-gnome-terminal```
