### ISSUE TITLE
Error on enabling paperwm: "Error ocurred in keybindigs @enable: action is undefined"

### ISSUE THREAD

**Issue by kamalmarhubi** [paperwm/PaperWM#190]
I just updated to the latest head for the first time since 02131fb (2019-06-17) and encountered this error in a notification on enabling the extension:

```
Error ocurred in keybindigs @enable:

action is undefined
```
and the extension was not enabled.

I removed my config and it persisted. I bisected and found this commit added in #182 to be the first exhibiting this issue: 3af9d23d767d1f8c7bdb06fdb89abd1c063ce305.

As a workaround, I'm running with its parent commit 80c3792ad8a5f87646a8bd9ff84fddcdfe06b8b2. I don't have time to look into the issue, but hopefully this is useful!

**Comment by olejorgenb** [comment]
We'll look into that. If/when you have time it would be useful if you click on the notification. gedit should open with a stacktrace which will be helpful.

**Comment by hedning** [comment]
A quick way to debug without ruining your own session:
```bash
dbus-run-session gnome-shell --nested --wayland
```

**Comment by hedning** [comment]
Pushed a branch which should hopefully work and give some useful output: https://github.com/paperwm/PaperWM/tree/debug-keybindings

**Comment by hedning** [comment]
Narrowed this down to schemas and code being out of sync. The new bindings gets picked up from the schema without a full reload, but the code assumed a full reload had taken place. 

Note, disabling and enabling an extension in gnome-shell won't actually get it to load new code, you'll have to restart gnome-shell for that to happen unfortunately.
