### ISSUE TITLE
When a non-focused window is closed, focus is changed to its left neighbour

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/PaperWM#20]
Open a terminal and type `sleep 3 && exit` to test.

When we get notified about closed windows in `window-removed` a new window have already received focus, so it's whether the closed window was focused or not is not directly available.

Haven't tested it, but from the mutter code it didn't look like the `unmanage` signal ran early enough either.

**Comment by hedning** [comment]
We should probably only switch to the left/right when the left/right is on top of the mru.

**Comment by olejorgenb** [comment]
Mutters default behavior seems to do a decent job when closing focused windows?

Ref: meta_workspace_focus_default_window ending in focus_ancestor_or_top_window if focus_mode_click.

So the behavior might depend on the stacking level of the tiling, but we probably want to keep that anyway.

**Comment by hedning** [comment]
`alt-tab` will raise all members of the group you select, so that can cause problems.
