### ISSUE TITLE
Option to disable swipe gestures

### ISSUE THREAD

**Issue by mtaung** [paperwm/PaperWM#201]
Hi, love the work here. I have custom gestures running (for xorg) which no longer work due to paperwm taking precedence. I couldn't find any information for this in issues here, so I'd like to politely request if you might consider implementing an option to disable these, or point to where I can edit these out.

**Comment by mtaung** [comment]
Update: I may have made a fool of myself because I managed to find a workaround for my current implementation using comfortable-swipe. I do think it might be useful to have this feature, but I don't know how many others might be affected since there are a few different ways people set up gestures on gnome

**Comment by hedning** [comment]
Cheers :)

Now, gnome shell doesn't support touchpad gestures on X11, so I don't think we're able to to steal swipes at all there. If you saw smooth scrolling while doing a 3-finger swipe you were probably on wayland (assuming no distro have some sort of patch enabling this on X11). What kind of setup where you using for X11 gestures?

I can make a toggle though, that's pretty much as straightforward as it can be. The relevant entry points are here https://github.com/paperwm/PaperWM/blob/b58050f7f5915634fe67faeec1dfa113f6df7d1c/gestures.js#L55 and here https://github.com/paperwm/PaperWM/blob/b58050f7f5915634fe67faeec1dfa113f6df7d1c/gestures.js#L303

**Comment by mtaung** [comment]
Thanks for the swift response. 

I realised I had been mapping key input combinations to swipes, which were the source of conflict on my end. Sorry for the daft mistake there. 

Good to see the ease of implementation for this option though!

**Comment by jtaala** [comment]
Closing as original issue resolved.
