### ISSUE TITLE
Can't enable extension: debugging help?

### ISSUE THREAD

**Issue by kamalmarhubi** [paperwm/PaperWM#204]
I have PaperWM installed in two user accounts on my machine. It works in one, but has stopped working in the other. The only recent changes are upgrading from Fedora 30 to 31 (Silverblue), which means a change from GNOME 3.32 to 3.34.

Since I'm using Silverblue, it's trivial to rollback to Fedora 30, but that hasn't helped.

Things I've tried:
- deleting the extension and reinstalling it, including logging out / logging in before reinstall
- looking at Looking Glass, which shows the extension as present but disabled, and reports no errors
- attempting to enable under GNOME 3.32 with `gnome-shell-extension-tool`
- looking at log output in journald for `/usr/bin/gnome-shell`

I _can_ get the preferences for PaperWM via `gnome-extensions prefs paperwm@hedning:matrix.org`, so it's present and works at least to some degree.

I've found no easy way to get log output. The most detail I've found is
```
$ gnome-extensions show paperwm@hedning:matrix.org
paperwm@hedning:matrix.org
  Name: PaperWM
  Description: Tiling window manager with a twist
  Path: /home/kamal/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org
  URL: https://github.com/paperwm/PaperWM
  State: INITIALIZED
```

(In the account where it works, this shows `ENABLED`.)

I'd appreciate any help debugging this, as I've almost forgotten how to use a computer without PaperWM at this point!

**Comment by hedning** [comment]
Hmm, if a search of  `#paperwm` from the journal doesn't turn up anything I'd guess gnome-shell have force disabled it for some reason. You can check like this:
```bash
gsettings get org.gnome.shell disabled-extensions
```
I hit that for some reason a few times when upgrading to 3.34, and confusingly tweaks would show the extension as enabled.

Resetting should hopefully work:
```bash
gsettings set org.gnome.shell disabled-extensions '[]'

**Comment by hedning** [comment]
Another possibility is this:
```bash
gsettings get org.gnome.shell disable-user-extensions
```
Though I'm fairly certain that will show up in tweak tool (the toggle in the upper right corner will be off, and extensions will be greyed out).

**Comment by kamalmarhubi** [comment]
```
$ gsettings get org.gnome.shell disabled-extensions
@as []
$ gsettings get org.gnome.shell disable-user-extensions
true
```
Looks like we have a culprit! Fixed with
```
$ gsettings set org.gnome.shell disable-user-extensions false
```

Do you know if this gets set automatically in some situations? I don't even have tweak tool installed.

**Comment by hedning** [comment]
> Do you know if this gets set automatically in some situations?

Not entirely sure, I believe it might be set if gnome-shell crashes, but not consistently. I'd guess it was  triggered by the upgrade to 3.34, IIRC there's been a few similar issues upstream.
