### ISSUE TITLE
Release to extensions.gnome.org?

### ISSUE THREAD

**Issue by danmou** [paperwm/PaperWM#205]
Is there any reason PaperWM is not on [extensions.gnome.org](extensions.gnome.org) yet? And would it be possible to start using tagged releases, preferably with changelogs etc? I use PaperWM every day but I'm always hesitant to pull the latest changes because I never know what's new and there's always a chance something's gonna be broken.

**Comment by hedning** [comment]
> Is there any reason PaperWM is not on extensions.gnome.org yet?

We'll probably have to change a few things
(https://wiki.gnome.org/Projects/GnomeShell/Extensions/Review), in particular
things are set up for
[gnome-shell-mode](https://github.com/paperwm/gnome-shell-mode/) use which
implies a few oddities. I've kinda just assumed it would be a lot of work, though looking at linked review help, it doesn't look that bad.

> And would it be possible to start using tagged releases, preferably with changelogs etc?

Yeah, we really should start doing that.

**Comment by olejorgenb** [comment]
> And would it be possible to start using tagged releases, preferably with changelogs etc?

https://github.com/paperwm/PaperWM/releases

**Comment by jtaala** [comment]
Closing as done!  https://extensions.gnome.org/extension/6099/paperwm/
