### ISSUE TITLE
Scroll windows with mouse wheel

### ISSUE THREAD

**Issue by gavr123456789** [paperwm/PaperWM#206]
How about a new feature of scrolling Windows(the same which I assume is now happening when scrolling with three fingers on the touchpad on Wayland) but when scrolling with the mouse wheel in the top bar?  
I think it will greatly improve the usability of PaperWM when using only mouse.

**Comment by hedning** [comment]
Yeah, it could be nice. @olejorgenb made a prototype here https://github.com/paperwm/PaperWM/issues/113

The main issue is how it interacts with other elements that reacts to scroll in the topbar, eg. the workspace/activities button and the volume icon.

I've also been playing with showing all windows to the left/right, when interacting with the monitor edges.

**Comment by flukejones** [comment]
Was about to make a new issue for something similar.

My personal preference (which might suit someone) is:
1. Using topbar to scroll workspace only (with this [extension](https://extensions.gnome.org/extension/943/workspace-scroll/))
2. And hold meta down to scroll windows left/right with mouse scroll wheel.

It would be great to have point 1 integrated. And point 2 might be a good compromise?

Another idea perhaps could be using "pressure" edge activation; the user mouses over to an edge and after using pressure movement (as in how the standard overview hotcorner works) triggers scrolling in that direction proportional to mouse movement. And it deactivates when they mouse away from it.

The pressure thing would be a requirement due to window scrollbars.

**Comment by hedning** [comment]
> Using topbar to scroll workspace only

We support scrolling on the workspace name to change workspace.

> And hold meta down to scroll windows left/right with mouse scroll wheel.

Yeah, we'd like to do this, but it's unfortunately not supported by gnome-shell/mutter: https://gitlab.gnome.org/GNOME/mutter/issues/207

**Comment by hedning** [comment]
Some sort of pressure thing could work (the reactive edge could for instance react to scroll-events).

**Comment by flukejones** [comment]
> > Using topbar to scroll workspace only
> 
> We support scrolling on the workspace name to change workspace.

Yeah I see that. Unfortunately it requires mousing *alllll* the way over there, and on an ultrawide (where this extension really shines) that can be tiring.

> > And hold meta down to scroll windows left/right with mouse scroll wheel.
> 
> Yeah, we'd like to do this, but it's unfortunately not supported by gnome-shell/mutter: https://gitlab.gnome.org/GNOME/mutter/issues/207

Bugger, that's unfortunate

**Comment by hedning** [comment]
> Yeah I see that. Unfortunately it requires mousing alllll the way over there, and on an ultrawide (where this extension really shines) that can be tiring.

Right, I can see that's a use-case. Will keep it in mind :)

**Comment by YoungElPaso** [comment]
Man, the mouse would be awesome. Shame about that binding modifier issue! This extension is incredible btw, replaced my using i3. Very well done.

**Comment by gavr123456789** [comment]
Any news?

**Comment by christopher-l** [comment]
I found a way to enable scrolling through windows with super + scroll wheel with my `user.js`: https://github.com/christopher-l/dotfiles/blob/329fa77a1f37069696951c122e9eb3722a39de48/config/paperwm/user.js#L37-L91

**Comment by jtaala** [comment]
> I found a way to enable scrolling through windows with super + scroll wheel with my `user.js`: https://github.com/christopher-l/dotfiles/blob/329fa77a1f37069696951c122e9eb3722a39de48/config/paperwm/user.js#L37-L91

Very cool!  I've recently added workspace swapping on monitors (#588).  I like the keybinds for just moving a workspace (and having the previously selected workspace on that monitor.

I might add official support for "moving" workspaces.

I'd also accept a PR for adding scrolling windows with mouse wheel (maybe as a toggleable option).

Nice work!

**Comment by v7rzlhb3xg** [comment]
Any solution to this for GNOME 45+ now that user.js is deprecated?

**Comment by jtaala** [comment]
> Any solution to this for GNOME 45+ now that user.js is deprecated?

Hey @v7rzlhb3xg - so, `user.js` simply injected in code in PaperWM - functionally no different from modifying the source code directly (which is what you'd do in 45+).  E.g. install via source, and then modify source code with something similar to what's done in `user.js`.  If you progress this def feel free to submit a PR with any changes.

If you don't want to touch code, you could also use something like [input-remapper](https://github.com/sezanzeb/input-remapper) to remap some keybinding (including with mouse/touchpad scroll) to `super`+`left` etc. (e.g. holding some key combo down to scroll windows).  I do something similar with a mouse (hold down side mouse button and scroll-well swipe through windows).

**Comment by jtaala** [comment]
Closed as implemented by #883.

**Comment by diegocortassa** [comment]
> I found a way to enable scrolling through windows with super + scroll wheel with my `user.js`: https://github.com/christopher-l/dotfiles/blob/329fa77a1f37069696951c122e9eb3722a39de48/config/paperwm/user.js#L37-L91

sorry to resurrect this old Issue but I'd really like to use super + scroll wheel as an alternative to super + arrows left/right to move trough my windows train but it seems like this  code doesn't work anymore for me on gnome 46.
Is there anyway to make it work?

**Comment by LDAP** [comment]
> > I found a way to enable scrolling through windows with super + scroll wheel with my `user.js`: https://github.com/christopher-l/dotfiles/blob/329fa77a1f37069696951c122e9eb3722a39de48/config/paperwm/user.js#L37-L91
> 
> sorry to resurrect this old Issue but I'd really like to use super + scroll wheel as an alternative to super + arrows left/right to move trough my windows train but it seems like this code doesn't work anymore for me on gnome 46. Is there anyway to make it work?

I made a patch here https://github.com/LDAP/PaperWM/commit/d6e5e137879129f5d663254a12e83a73e85fb9b4.

@Thesola10 I'd like to have something like this in PaperWM, tough I am not that familiar with the GNOME stuff, a little help for the settings toggle would be greatly appreciated.

I also inverted all the scroll directions here: https://github.com/LDAP/PaperWM/commit/d1e46b4058f170a903714b9bc063cdd67f98fc4d3 as I found this much more intuitive. Is there a chance that a toggle for that will be added?
