### ISSUE TITLE
[Feature Request] Remove window indicator highlight from maximized windows

### ISSUE THREAD

**Issue by necopinus** [paperwm/PaperWM#208]
The current window indicator highlight is still present (at least on the left) for maximized windows; this is particularly noticeable when using a transparent dock (with, for example, the dash-to-dock extension).

The indicator doesn't really serve a purpose for transparent windows (and already appears to have been removed from the top of the window)... Any chance that it could just be removed entirely in this case?

**Comment by necopinus** [comment]
Here's an example (look at the right-side of the dock): https://drive.google.com/file/d/140l-qZue5ZnkmVUaCfGST6hKvGTyCo0t/view

**Comment by hedning** [comment]
Yep, that makes sense, basically the same rational as removing it from the top, I just didn't think of the use-case of transparent docks tbh.

**Comment by hedning** [comment]
This is fixed in 7841e7368b40047d310adce1094a9c66bc91dc79, so should be fixed 34.1
