### ISSUE TITLE
GNOME 3.35.2 Compatibility

### ISSUE THREAD

**Issue by Plailect** [paperwm/PaperWM#212]
The extension fails to launch on GNOME 3.35.2 with error:

`Error occurred in tiling @enable: space.clip.raise_top is not a function`

**Comment by hedning** [comment]
Right, looks like they removed some stuff (`raise_top` and `reparent` at
least) that's been deprecated a long time. Throwing this in your user.js
(topelevel) should probably work.

``` javascript
Clutter.Actor.prototype.raise_top = function raise_top() {
    this.get_parent().set_child_above_sibling(this, null);
}
Clutter.Actor.prototype.reparent = function reparent(newParent) {
    const parent = this.get_parent();
    parent.remove_child(this);
    newParent.add_child(this);
}
```

**Comment by hedning** [comment]
OK, got a build of 3.35.2 running, this works:
```js
    Clutter.Actor.prototype.raise_top = function raise_top() {
        const parent = this.get_parent();
        if (!parent)
            return;
        parent.set_child_above_sibling(this, null);
    }
    Clutter.Actor.prototype.reparent = function reparent(newParent) {
        const parent = this.get_parent();
        if (parent) {
            parent.remove_child(this);
        }
        newParent.add_child(this);
    }
``

**Comment by hedning** [comment]
Pushed a [`gnome-shell-3.36`](https://github.com/paperwm/PaperWM/commit/325317e9a125ef8e7ae4ee2e8c7bc1b9527df8f0) branch. There's some wonkyness going on with the buttons in the workspace menu (they're really huge), but it should hopefully otherwise work.

**Comment by hedning** [comment]
#254 have been merged, forgot to close this.
