### ISSUE TITLE
How to configure window border width and color?

### ISSUE THREAD

**Issue by zhenyw** [paperwm/PaperWM#213]
Looks I can't find a way to change border pixel width or color. How I can do that?
And it may be better we can provide config option in setting to change that.

thanks

**Comment by hedning** [comment]
Ah, right, the border width can be controlled by changing the `window-gap` preference. The border is hard coded at half the window gap.

There's currently no preference for the color/style, but @olejorgenb has some code lying around for that.

We should probably change the tooltip as this question has popped up a few times, so it's obviously not very clear. I'm guessing you want a larger border? We might want to increase the default value (I run with a 20px gap at least).

**Comment by olejorgenb** [comment]
If you add the following to `~/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/stylesheet.css` and restart gnome shell the highlight/border should change: (tweak as necessary :))

```css
.tile-preview {
    border-color: black;
    background-color: rgba(10, 10, 10, 0.5);
}
```

(Ignore the other style definition in the file)

**Comment by hedning** [comment]
Just thought I'd mention the paperwm selection now has it's own style class `paperwm-selection`, so it's now best to use `.paperwm-selection { ... }` for styling.

**Comment by jtaala** [comment]
Hey @smichel17 - this one too! should prob be closed, given the ability to override `paperwm-selection` style with preferred border, size, colour, etc. with `user.css` from #414.

**Comment by joeyh** [comment]
>  The border is hard coded at half the window gap.

I want zero top window border, because I've moved the gnome bar to the bottom, and this lets me use fitt's law effectively with eg switching tabs in firefox. So I had to set the window gap to 0 to accomplish that, which is not ideal visually to tell where one window ends and another begins..

**Comment by jtaala** [comment]
Closing this as answered.

@joeyh - if you still want what you mentioned definitely submit a feature request and/or have a go at this and submit a PR.
