### ISSUE TITLE
Gnome shell crashing with JS WARNING

### ISSUE THREAD

**Issue by joe-pritchard** [paperwm/PaperWM#218]
Nothing in particular causes this, it seems to just happen every now and again, even when I'm not doing anything (for example, it happened while I was writing the first draft of this issue, killing Chrome. I don't think I even moved my mouse...).

Each time, here are the errors from syslog:

`JS WARNING: [/home/joe/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/scratch.js 144]: reference to undefined property Symbol()`

Followed immediately by:

`JS WARNING: [/home/joe/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js 332]: reference to undefined property "_targetWidth"`

Then gnome shell restarts. Same behaviour on both develop and master branches I think. I'm disabling the extension for now because this is quite frequent, but from what I've seen so far I love it!

**Comment by hedning** [comment]
Hmm, yeah that's no fun :( I'm guessing you've pulled in 49fe4a39f71077c09703bac3a0da3f7c0f10cab8, which fixed a crash when using multiple monitors (eg. after unlock or dimming).

So the warnings you mention are perfectly normal and shouldn't cause any problems.

Some potentially useful information:
- distro and gnome-shell version
- does it happen on wayland or X11
- what monitor setup are you using
- crashes will often result in a stack trace, so searching for `Stack trace for context` in the syslog might reveal something useful.

**Comment by joe-pritchard** [comment]
Distro: Ubuntu 19.10
Gnome Shell Version: 3.34.1
X11 or Wayland: X11
Monitors: Laptop as main with external monitor via HDMI, but pretty sure the crash occurs with no monitor attached too.

Will run again for a bit to try and get a stack trace :)

**Comment by hedning** [comment]
You can probably do something like `journalctl --boot | grep 'Stack trace for context' (if it happened within a boot at least.

**Comment by joe-pritchard** [comment]
Got one! Sorry if there's stuff irrelevant stuff in there I just copied it straight out of the log. This happened when moving a window from my external monitor to the laptop screen: Dump attached.

Thanks, Joe
[logdump.txt](https://github.com/paperwm/PaperWM/files/4035367/logdump.txt)

**Comment by hedning** [comment]
Hmm, so that seems to come from the [desktop-icons](https://gitlab.gnome.org/World/ShellExtensions/desktop-icons/) extension (We don't seem to make any `St.Bin`s at all actually). I'm guessing there's some sort of bad interaction between desktop-icons and paperwm.

In general we don't recommend running desktop-icons together with paperwm, though it's unfortunately not entirely straight forward to disable it on ubuntu: https://github.com/paperwm/PaperWM#note-for-ubuntu-users.

Weirdly you're getting something that looks like this: https://gitlab.gnome.org/World/ShellExtensions/desktop-icons/issues/17, but it seems like that should've been fixed long ago.

It might be worth trying an upgrade, though again, it's probably best to get desktop-icons disabled, as it simply doesn't play nice with paperwm :(

**Comment by joe-pritchard** [comment]
Thanks, will disable desktop-icons and confirm :)

**Comment by joe-pritchard** [comment]
Alright I think that's it. Been running with no crashes for a while now. I *did* have desktop-icons disabled, but I guess I still had an icon on my desktop :man_shrugging: I re-enabled desktop-icons in tweaks, deleted the icon, and then disabled desktop-icons again. All good!

**Comment by hedning** [comment]
Good to hear. If you've found a reliable way to turn off desktop-icons (which persists through logins) in the ubuntu flavored gnome we'd be grateful if you could share, as that seems like recurring issue :)

**Comment by joe-pritchard** [comment]
I don't know I just disabled it in Tweaks and it seems to work fine, sorry I couldn't be more helpful!

**Comment by step21** [comment]
> Good to hear. If you've found a reliable way to turn off desktop-icons (which persists through logins) in the ubuntu flavored gnome we'd be grateful if you could share, as that seems like recurring issue :)

What might be relevant - at least in my ubuntu-gnome, there are two ways to have desktop icons. So maybe disabling the extension is not enough, but ordinary desktop icons in control center have to be disabled too...
