### ISSUE TITLE
Exiting fullscreen video from browser causes top bar to overlap with top of maximized window

### ISSUE THREAD

**Issue by redplanks** [paperwm/PaperWM#220]
Coming out of fullscreen video on a browser (tested on Firefox and Chromium) causes the top bar of GNOME to overlap with the top of the browser's window, which lasts until the top bar is interacted with or clicked on. The browser's window has to be maximized; when not maximized, coming out of fullscreen video behaves correctly.

**Comment by hedning** [comment]
Looks like the culprit is the top bar animation we add. I'm guessing the `workarea` calculation is smart and knows that the top bar is scaled, telling the maximized window it has the whole screen.

It might be best to just remove the animation tbh.

**Comment by redplanks** [comment]
Apprently, this only happens with Dash to Dock where the dock is on the bottom. When I tried using the default Ubuntu GNOME 3 dock on the side, it behaves correctly.

**Comment by hedning** [comment]
Hmm, I'm guessing having the dock on the side actually «fixes» it. I was able to reproduce without dash-to-dock active.

**Comment by hedning** [comment]
Had to fix the integration with the hide top bar preferenc, so took longer than expected.
