### ISSUE TITLE
Some default gnome short cuts not restored on paperwm disable

### ISSUE THREAD

**Issue by goodwillcoding** [paperwm/PaperWM#223]
In setup where "Move the active window to the right (or left) monitor are shared with move-to-monitor-right/move-to-monitor-right. When paperwm is disabled those default shortcuts are not reset to the default. It takes a gnome shell restart to regain them.

@hedning I am happy to do PR with fix if you point me in the fix direction.

**Comment by hedning** [comment]
Cheers, had inadvertently bound these to the workspace switcher :/

Didn't test, but should work :)
