### ISSUE TITLE
Dual monitor setup: popup-dowload windows from one workspace on one monitor appear on second

### ISSUE THREAD

**Issue by danieltomasz** [paperwm/PaperWM#226]

**Comment by danieltomasz** [comment]
paperWM 34.2 on Gnome 3.28 on Ubuntu 18.04;
Sometimes when popup-download window will appear in another workspace on 2nd screen,
Accessing it is only possible when the parent browser window is moved to the workspace where it  appears

**Comment by hedning** [comment]
OK, floating windows should now be forced onto the correct monitor when they spawn. That should hopefully fix it :)

**Comment by hedning** [comment]
I'm fairly certain this should be fixed now. If you still experience trouble, please reopen.

**Comment by dazu89** [comment]
I am experiencing this exact issue on

Distribution: Fedora Linux 42 (Workstation Edition)
GNOME Shell: 48.4
Display server: Wayland
PaperWM version: 48.0.3
Enabled extensions:
- iso-clock@tweekism.fairchild.au
- paperwm@paperwm.github.com
- dash-to-panel@jderose9.github.com

with LibreOffice main window and save dialog.
