### ISSUE TITLE
Support for collapsible gaps

### ISSUE THREAD

**Issue by emilazy** [paperwm/PaperWM#228]
Thanks for the extension!

It would be nice to be able to set gaps to not apply to the edge of the screen, so that maximized windows could take up all the available screen real estate, or at least to be able to control the horizontal and vertical gaps separately; I'm currently running a fork with the vertical gaps patched out because I dislike wasting the vertical screen real estate on a laptop.

**Comment by hedning** [comment]
Setting `horizontal-margin` to zero should give you the full width when using `Super+F`. You'll still be left with a gap on the top. If you really dislike that you can use the native maximize window, which will take up the whole workarea.

**Comment by emilazy** [comment]
That works for fully maximized windows, but still leaves all non-maximized windows wasting valuable screen space :( is there a reason that there's a fixed amount of vertical margin based on the gap even when it's explicitly set to 0?

**Comment by hedning** [comment]
Right, I follow now. So the main reason is that this looks somewhat weird tbh:
![image](https://user-images.githubusercontent.com/71978/72667044-f8bcc100-3a17-11ea-9b3e-977d2b3deeff.png)

My feeling is that the best default is having the top margin equal to the height of the protruding highlight, which means the top margin should follow the window gap by default.

Looking again at how the top margin works I see it's pretty useless in it's current state, it only has an effect when it's larger than the highlight, which I'm guessing no one wants :laughing:

So it probably makes sense to to have a top margin toggle, which defaults to false. Turning it on should then make paperwm respect the top margin correctly. We haven't implemented the logic to limit the height of the highlight so it will avoid protruding into the top bar though, so we'll see when it gets done, open to a PR though :p

**Comment by hedning** [comment]
> control the horizontal and vertical gaps separately

Right, this would be simpler to implement. If we could have a lock window gap width/height toggle, that could work too :+1: Sounds like you have some code that could work with that?

**Comment by emilazy** [comment]
The patch I have locally just eliminates vertical gap handling; it doesn't take any precautions to avoid overflowing into the top bar if you have an actual gap, since I wouldn't be able to see it anyway; I patched out the forced-transparent top bar because it was distracting and the workspace names kept overlapping unreadably. (I don't try to be so picky about software, I swear! ^^; )

If you'd be interested in a patch adding some configuration twiddles for things along those lines and/or potentially the no-gaps-on-screen-eges solution, I can try and work something up; I'd probably personally sooner just tweak the selection styling than try to make the selection carefully bounded, but if you'd rather see that than a config option that might cause the borders to spill into the top bar then I can give it a go, or maybe just send a separate vertical gaps patch (I don't have enough vertical room to use vertical tiling much anyway).

**Comment by jtaala** [comment]
Closing this as looks no longer valid given PaperWM gap settings in preferences.
