### ISSUE TITLE
Regression: new windows (eg. gnome-terminal) opens in the background 

### ISSUE THREAD

**Issue by hedning** [paperwm/PaperWM#23]
Probably due to db5f36a1d50e57ef930a49a168d616f9091b71bd

**Comment by olejorgenb** [comment]
Seems to be triggered by the existence of a gnome-terminal that is sticky, always-on-top and minimized...

Turning always on top off when hiding the scratch layer might be a workaround.

New firefox windows also had problems though?

**Comment by hedning** [comment]
Right, seems like keepassx also prevented new gnome-terminals from getting proper focus. And riot prevented new firefox windows.
