### ISSUE TITLE
Primary Workspace Inaccessible to Secondary Display After Adding New Display

### ISSUE THREAD

**Issue by trst** [paperwm/PaperWM#232]
I'm noticing some strange workspace behaviour when using multiple monitors.

The primary workspace is not accessible to an external display after plugging it into my ThinkPad. When I boot with the display already connected, the primary workspace is accessible to both displays in the workspace picker (assuming one of the displays is not currently using workspace 1).

Workspace 1 is available to my laptop monitor but when adding an external monitor, I can cycle through all the other workspaces, in my case 2-4, but am unable to view workspace 1 on the external monitor.

Is there any other debugging info I can provide that would be helpful?

Thank you for your efforts on PaperWM. I truly appreciate the project and all your hard work :smile:

**Comment by hedning** [comment]
> Workspace 1 is available to my laptop monitor but when adding an external monitor, I can cycle through all the other workspaces, in my case 2-4, but am unable to view workspace 1 on the external monitor.

Workspaces on other monitors isn't be accessible from `super+above_tab`. While `Super+PageUp/Down` will only show you workspaces that are empty or on the current monitor (ie. the monitor the workspace was last used).

Filtering out workspaces like this on `super+pageup/down` might not be ideal, I mostly use `super+above_tab` to change workspaces so input is welcome. Though it's worth noting that changing monitors will cause the workspace to be resized, so it's not all that smooth.

An ad-hoc way to move a workspace to another monitor is hiding it with eg. `super+above_tab`, go to the desired monitor, change to the workspace with `super+workspace`. But that's admittedly a bit wonky :laughing: 

We also ship an example keybinding for moving spaces between montiors. To use it add this to your `user.js` init function (requires a restart, or live evaluation through [gnome-shell-mode](https://github.com/paperwm/gnome-shell-mode/). `super+alt-arrow_keys` will then swap the current worspace with the one on the right/left/up/down.
```javascript
    Examples.keybindings.moveSpaceToMonitor();
```

**Comment by trst** [comment]
Thanks for the response.

I have tried but been unable to make the `super+above_tab` and `super+workspace` combo work for me  :woman_shrugging:

Modifying the `user.js` did the trick. Though I do see why it's not included by default. Repainting is a look, but beyond cosmetics its perfect. I wonder if just presenting the users with the wallpaper and fading in the windows from transparent once they've been recalculated and drawn wouldn't suffice... I'm not sure that would fit user expectations given how quickly the switch happens, but it's a thought :laughing:

**Comment by hedning** [comment]
> `super+workspace`

Opps, that should've been just `super+above_tab` again, the idea is making the workspace hidden, and then changing to it with `super+above_tab` on the desired monitor.

> I wonder if just presenting the users with the wallpaper and fading in the windows from transparent once they've been recalculated and drawn wouldn't suffice

Yeah, that could be a solution. I can't quite remember the problems with the current example, just that it wasn't quite production ready :p

**Comment by trst** [comment]
Okie dokie. Thanks for all your help :smiley_cat:
