### ISSUE TITLE
Setting for removing active window border

### ISSUE THREAD

**Issue by mhamrah** [paperwm/PaperWM#235]
When using PaperWM there is a small border around the active window. I'd like to remove it. I thought this was getting set with util.js as a hard coded 2px, but removing that code or setting to 0px isn't helping. I also can't find a css setting to hide this.

Any help appreciated.

Thank you,

Mike

**Comment by hedning** [comment]
See https://github.com/paperwm/PaperWM/issues/213. The border scales linearly with the window gap, so setting that to 0 should work. It's also possible to style it as noted in the linked issue.

**Comment by mhamrah** [comment]
Thanks the tile-preview worked css override worked.
