### ISSUE TITLE
Super+O sometimes doesn't work (conflicts with rotate-video-lock-static)

### ISSUE THREAD

**Issue by hedning** [paperwm/PaperWM#237]
gnome-settings-daemon already use `super+o`, and we make no attempt to override gsd shortcuts. So we'll need to find a way to do an override, or change the shortcut to something else.

Edit for searchability: the action in question is expel from column

**Comment by olejorgenb** [comment]
To disable the video-lock-static binding: 
```shell
dconf write /org/gnome/settings-daemon/plugins/media-keys/rotate-video-lock-static "@as []"
```

**Comment by skf-funzt** [comment]
> To disable the video-lock-static binding:
> 
> ```shell
> dconf write /org/gnome/settings-daemon/plugins/media-keys/rotate-video-lock-static "@as []"
> ```

I want to add to restart the Gnome Shell afterwards

```
Alt + F2 -> r -> Enter
```

Thanks, @olejorgenb for saving me from dropping PaperWM on onboarding/first steps trying this extension.

**Comment by jtaala** [comment]
An option to avoid this in the future is to add the `/org/gnome/settings-daemon/plugins/media-keys` schema to be checked by PaperWM for conflicts (we manage other schema's for conflicts).  PaperWM will then disable this one automatically when active (if there's a conflict with a PaperWM keybind that is) and then restore when PaperWM is disabled. 

I'll put this on my list of things to implement.

**Comment by jtaala** [comment]
Hey @skf-funzt,

Are you on gnome 45 (or on a previous version of gnome)?

If you're on gnome 45, are you able to test this PR branch?  It will automatically disable media-key conflicts if there is a PaperWM conflict, and then restore that original keybind when PaperWM is disabled.

If you're on gnome 44 let me know and I'll create a branch for you to test.

```
git clone https://github.com/paperwm/PaperWM.git
cd PaperWM
git checkout fix-237-mediakey-conflicts
./install.sh
```

And then logout/login.

For testing, feel free to reset the original setting of `rotate-video-lock-static` with something like

```
dconf reset /org/gnome/settings-daemon/plugins/media-keys/rotate-video-lock-static
```

**Comment by jtaala** [comment]
P.S. if you set a media-keys keybind during runtime (that conflicts with a PaperWM key) - then PaperWM will notify you that that specific keybdind is being overriden.

**Comment by jtaala** [comment]
Oops - forgot to add actually installing PaperWM in the directions above.  Should be:

```
git clone https://github.com/paperwm/PaperWM.git
cd PaperWM
git checkout fix-237-mediakey-conflicts
./install.sh
```

And then logout/login.

**Comment by skf-funzt** [comment]
@jtaala 
Sorry for the delay, I can confirm that this works. 
But I haven't seen any notification about that a keybinding has been overriden.

**Comment by jtaala** [comment]
ah, no you won't see it's overridden normally - but if you open up keyboard shortcuts and try to reset the `rotate-video-lock-static` shortcut then PaperWM will inform you that it won't reset it as it's being overriden.

**Comment by skf-funzt** [comment]
Understood, thanks.
