### ISSUE TITLE
[Feature Request] Desktop zoom function

### ISSUE THREAD

**Issue by fgheng** [paperwm/PaperWM#238]
would you like to add desktop zoom feature?

**Comment by olejorgenb** [comment]
Gnome-shell has a built in magnifier: https://help.gnome.org/users/gnome-help/stable/a11y-mag.html.en / https://unix.stackexchange.com/questions/33243/does-gnome-3-support-desktop-zoom#192896

I think there's a couple extensions offering alternatives also.

That being said: On wayland three finger swipe (up/down) enumerates the workspace stack (in paperwm). Swiping up at the top of the stack zooms in to indicate there's noting above. It could be nice to center the zoom on the pointer to double as a quick-zoom:

![Screencast from 08  feb  2020 kl  08 56 +0100](https://user-images.githubusercontent.com/72201/74081747-b43ea700-4a52-11ea-97bd-106d347fd980.gif)

**Comment by olejorgenb** [comment]
I tried to actually use the built-in magnifier and it's unfortunately quite [broken](https://gitlab.gnome.org/GNOME/gnome-shell/issues/2188) in gnome-shell 3.34

**Comment by jtagcat** [comment]
If you need to temporarily quickly zoom and are on laptop, you can zoom with three fingers (but it's quite hard).

**Comment by fgheng** [comment]
using three fingers makes it into windows preview

**Comment by fgheng** [comment]
> Gnome-shell has a built in magnifier: https://help.gnome.org/users/gnome-help/stable/a11y-mag.html.en / https://unix.stackexchange.com/questions/33243/does-gnome-3-support-desktop-zoom#192896
> 
> I think there's a couple extensions offering alternatives also.
> 
> Edit: seem
> 
> That being said: On wayland three finger swipe (up/down) enumerates the workspace stack (in paperwm). Swiping up when at the top of the stack zooms in to indicate there's noting above. It could be nice to center the zoom on the pointer to double as a quick-zoom:
> 
> ![Screencast from 08 feb 2020 kl 08 56 +0100](https://user-images.githubusercontent.com/72201/74081747-b43ea700-4a52-11ea-97bd-106d347fd980.gif)
thank u, i found it
