### ISSUE TITLE
How to get top bar back

### ISSUE THREAD

**Issue by AckslD** [paperwm/PaperWM#239]
I clicked to remove the top bar on one of the workspaces, how can I get it back?

Thanks for the great work :)

**Comment by olejorgenb** [comment]
Activate the overview and right click the workspace name (use a hotkey - or change to another workspace first, then changing the workspace inside the overview before right clicking on the name)

The top-bar toggle is unfortunately not in the prefs GUI yet.

**Comment by AckslD** [comment]
Thanks @olejorgenb! I couldn't find this setting but I pulled again and I can now set this :)

**Comment by jtagcat** [comment]
First time I hid a top bar I was confused as well, maybe add something about it in the docs?

**Comment by hedning** [comment]
Yeah, been a recurring issue, I've simply removed the toggle from the workspace menu. It's now only in the preferences,  meaning turning it off and on uses the same workflow.
