### ISSUE TITLE
Hook into the ctrl-enter behavior in overview to create a global new window action

### ISSUE THREAD

**Issue by hedning** [paperwm/PaperWM#24]
It's possible to ask well behaved applications (probably due to their `.desktop` file) to create new window. That might make it viable to have a global `<Super>N` binding for new windows (depending on how badly behaving applications behave).

**Comment by olejorgenb** [comment]
Relevant documentation: https://developer.gnome.org/shell/3.24/shell-shell-app.html#shell-app-open-new-window

**Comment by olejorgenb** [comment]
Closed by 56708fee15b5155a48eb11b734f261a2f42840e0
