### ISSUE TITLE
Multi-Monitor: When in overview, other displays magically dissapear.

### ISSUE THREAD

**Issue by jtagcat** [paperwm/PaperWM#241]
Not in overview: (2 windows on both monitors)
![image](https://user-images.githubusercontent.com/38327267/74091958-ca318380-4ab5-11ea-8f38-b8cef0accf36.png)
In overview:
![image](https://user-images.githubusercontent.com/38327267/74091969-f51bd780-4ab5-11ea-8c54-1ec959dc9c5e.png)

**Comment by olejorgenb** [comment]
My immediate guess is that the left terminal window is a scratch window. Minimizing a window moves it to the [scratch layer](https://github.com/paperwm/PaperWM#scratch-layer)

That said - paperwm isn't perfectly integrated with the overview yet.

**Comment by olejorgenb** [comment]
Sorry, I misread :)

Only the active workspace is shown in the overview - each monitor has its own workspace. This is how the overview works out of the box when combined with our implementation of per-monitor workspaces.

**Comment by Pajn** [comment]
What's a bit strange thou is that windows from the active workspace appears on other monitors in the overview if they are scrolled outside of the monitor that workspace is on.

Preferably all windows on the active workspace should appear on the monitor for the active workspace also in overview. A nice extra bonus would be that all monitors display their respective workspace while in overview.

**Comment by hedning** [comment]
Ok, took a look and it seems fairly doable. While gnome shell assumes a workspace spans all monitors, it does create an actor for each monitor workspace combination, making it reasonable to plug in a workspace per monitor model :)

**Comment by jtaala** [comment]
Fixed in #588.
