### ISSUE TITLE
Adding additional keybindings

### ISSUE THREAD

**Issue by trst** [paperwm/PaperWM#243]
Hola!

I was inspired by the "DWM-ish" keybindings you've listed in the wiki and I fashioned my own (though they're reasonably similar... the curse of open-source fragmentation rears its head again!). I've pushed mine to their own [repository](https://github.com/trst/PaperWM-Vim-ish-Keybindings).

Not sure if you're into adding it to the Wiki, if not no biggie :smile: I would have opened up a pull request, but I forgot that Github handles wiki's separately.

**Comment by olejorgenb** [comment]
Feel free to add them to the wiki :)

**Comment by olejorgenb** [comment]
Just noticed that the wiki was read only for regular users. The wiki should be writable for any github user now.

**Comment by olejorgenb** [comment]
https://github.com/paperwm/PaperWM/wiki/Alternative-keybindings#other

**Comment by trst** [comment]
Ah shucks! Thanks for putting up the link, I appreciate that.
