### ISSUE TITLE
Top bar not showing at all

### ISSUE THREAD

**Issue by darkfrog26** [paperwm/PaperWM#244]
I've seen other issues mentioning that the top bar switches monitors, but I have two monitors and the top bar is not appearing on either of them.  Ideally, I'd prefer a setting that allows me to set it to appear on one monitor.

I'm running the latest version of OpenSUSE Tumbleweed and GNOME 3 (3.34.3) with Wayland

**Comment by hedning** [comment]
Does it appear in the overview? In that case right click on the worspace name (top left corner) and turn off `hide top bar`.

We'd like to have an option to keep the top bar on the primary monitor, though there's a few things which needs fixing, so we'll see when it gets done.

**Comment by darkfrog26** [comment]
Thanks, that did the trick.
