### ISSUE TITLE
Better Resizing Control

### ISSUE THREAD

**Issue by darkfrog26** [paperwm/PaperWM#246]
Right now, resizing has three presets, but it can be very useful to have more fine-grained control over the adjustment. Similar to i3's "resize mode" it would be useful to be able to toggle resize mode and just use the arrow keys to adjust.

**Comment by olejorgenb** [comment]
Gnome has this built in :) (Alt-F8) https://help.gnome.org/users/gnome-help/stable/shell-windows-states.html.en

We also have "experimental" actions to adjust the width in `examples/keybindings`. See the top comment there. The function `adjustWidth` set's up inc/dec bindings bound to `super +` and `super -` with 50px increments by default.

**Comment by darkfrog26** [comment]
Ah, I never noticed that before! I appreciate it.
