### ISSUE TITLE
Window sometimes not showing when not focused

### ISSUE THREAD

**Issue by jtagcat** [paperwm/PaperWM#248]
![image](https://user-images.githubusercontent.com/38327267/74580001-66b4c380-4f97-11ea-9b9d-1dcaa83a574f.png)
I can see and manipulate the window (but not click things in it). While switching windows or changing the size of it, I can see it while the animation lasts, then it goes to being like shown on the image.

I tried resizing the window with mouse and then this happened on releasing. Normally resizing with mouse works.

I have had this issue before randomly, not even doing anything.

Closing and reopening the window works fine, but sometimes I have apps what don't recover from just simply reopening.

**Comment by hedning** [comment]
Right, I'm unable to reproduce. But from what you're describing it looks like the actual window is stuck on opacity `0` (see 88eacec974389d69875a265f783b833a0dbe3f3b for why we set the opacity). If resizing the broken window doesn't trigger a layout then that's surely the case at least. 

4ccf271593f23a7a8fd33abaf676f77f853040a0 should in principle make sure the window opacity is always reset correctly.

**Comment by jtagcat** [comment]
Right, I'm switching to develop and see if I come across this again.

**Comment by hedning** [comment]
OK, I think I've seen this happen a few times on X11 gnome-shell 3.34 (ubuntu 19.04). I'll see if I'll get a chance to investigate.

**Comment by jtagcat** [comment]
My situation differs, Wayland, 3.36.3, Fedora 32.

**Comment by jtaala** [comment]
Please let me know if you're still seeing this on a recent version of PaperWM.

**Comment by jtagcat** [comment]
No longer using PaperWM.
