### ISSUE TITLE
When top bar is only on main display, indicate somehow, what monitor is selected.

### ISSUE THREAD

**Issue by jtagcat** [paperwm/PaperWM#249]
Continuing #242 
When the top bar is only on main display, it's difficult to find what display you are activated on.

Maybe option for a 1px line at the bottom of the screen?

**Comment by hedning** [comment]
Yep, this is one of things which is nice with having the top bar move :p 

So we should at least dim the highlight on the inactive monitor (like we do when a scratch window is focused). We could also make the edges flash when switching monitors making switches noticeable. If a good «select monitor animation» solves the problem I'd prefer that tbh.

**Comment by jtagcat** [comment]
for horizontal monitors, have 2px say green line on top and bottom of active screen animate slide over to the next one, for switching vertically, have 2px line at the right and left edge of the screen slide up/down to the next display
the 2px should be a percentage of the display (to account for 4k and stuff) (looks like a scrollbar)

you don't really want to dim the inactive ones, because monitors are for viewing stuff, I personally dislike dimming very much, if you want you can dim for 3-5s from the last monitor move and then brighten up again

**Comment by hedning** [comment]
> I personally dislike dimming very much

Yeah, me too :) I meant dimming the blue active window highlight.

**Comment by johnmee** [comment]
I wouldn't be keen on any of those ideas as they take up screen space (even 1px), or involves colors (theming), or dimming (not focused but still reading it).  

Worst case, could we hack the 'workspace' label and change the text to indicate focus/not?

Better, can we put anything in the top bar?   I'm thinking a sequence of small monitor icons, corresponding to how many are detected, with the one that is in focus empasized, whilst the rest are de-emphasized.  Once you know its there, if you get confused where the focus is, a quick glance will tell you.

**Comment by jtagcat** [comment]
> I wouldn't be keen on any of those ideas as they take up screen space (even 1px), or involves colors (theming), or dimming (not focused but still reading it).
> 
> Worst case, could we hack the 'workspace' label and change the text to indicate focus/not?
> 
> Better, can we put anything in the top bar? I'm thinking a sequence of small monitor icons, corresponding to how many are detected, with the one that is in focus empasized, whilst the rest are de-emphasized. Once you know its there, if you get confused where the focus is, a quick glance will tell you.

The pixels wouldn't be taking up space, they would be animations (and then go away after a second).

**Comment by smichel17** [comment]
@jtagcat Does https://github.com/paperwm/PaperWM/pull/464 fix this for you?

**Comment by jtagcat** [comment]
> @jtagcat Does #464 fix this for you?

I've switched to KDE 1.5-2 years ago, and later to Sway. Gnome was and has been just too much junk. I now have more beefy machines (8x performance, in just apps running), so I might revisit the setup/project some day.

I'm glad you're still improving PaperWM, thank you!
