### ISSUE TITLE
Mozilla's about windows

### ISSUE THREAD

**Issue by jtagcat** [paperwm/PaperWM#251]
![image](https://user-images.githubusercontent.com/38327267/74581319-0416f400-4fa6-11ea-9345-1175291dfc77.png)
They are supposed to be smaller. (where the colour ends on the Firefox one).

**Comment by hedning** [comment]
Not much we can do about this. The windows are marked as normal windows and not as modals, they're also resizable so from our perspective there's not much to separate them from windows that should be tiled and resized.
