### ISSUE TITLE
Top margin not respected fully

### ISSUE THREAD

**Issue by Hergeirs** [paperwm/PaperWM#256]
When I set top padding to 0 there's still some padding on top. I'd love it if there'd be no padding. :)

I really appreciate the work you have put into it. So nice for a keyboard based workflow. :+1: 

![image](https://user-images.githubusercontent.com/20126436/75720873-8d813280-5cd7-11ea-940a-a0a5c4242b96.png)

**Comment by olejorgenb** [comment]
See this thread: https://github.com/paperwm/PaperWM/issues/228#issuecomment-575913854

**Comment by Hergeirs** [comment]
Oh. So a workaround for me was to set the "gap between windows" to 0 as well. This behaviour should probably be changed or explained somehow. But I see your discussing this in #228 as well :)
