### ISSUE TITLE
Add better keybindings for mouse usage (one hand on keyboard)

### ISSUE THREAD

**Issue by hedning** [paperwm/PaperWM#257]
When using a mouse the default navigation keybindings  (`super+,/.`) are difficult to use, as `,/.` is not on the same side on the keyboard as `super`.

This becomes very noticeably when using the clutter-dnd branch which allows navigation while dragging windows.

The dvorak keyboard layout have  `,/.` positioned at `w/e` which is close to ideal for one handed use. `super+w/e` aren't used for anything else (by paperwm or gnome shell) so we should add these to the default keybindings.

**Comment by jtagcat** [comment]
I would look in to Saka key for inspiration.

**Comment by DanielJoyce** [comment]
Super-WASD? Does anything use those? :)

**Comment by hedning** [comment]
Yeah, `Super-A` opens the applications view and `Super-S` opens the overview.

**Comment by jtagcat** [comment]
vimkeys?

**Comment by hedning** [comment]
We'll probably not do vim keys by default (nothing against vim, I'm a vim user myself), but we've thought about having some simple toggles so it's easy to get different keybinding styles.

**Comment by rawkode** [comment]
I just tried mapping super-h and super-l to window left/right - didn't work.

Super-L locked my screen, whoops. Super-H moves to scratch (and I can't get it to register during set either)

**Comment by hedning** [comment]
Right, since the shortcut is already taken the accelerator widget never receives the combo. You should be able to add it via eg. dconf-editor though (and paperwm will do the necessary work to «steal» the action, with some caveats).

**Comment by jtaala** [comment]
Closing as PaperWM now has a (fairly) mature keybinding implementation (via PaperWM settings) that allows users to modify keybindings to suit their needs.
