### ISSUE TITLE
Fully override maximize

### ISSUE THREAD

**Issue by hedning** [paperwm/PaperWM#26]
Ideally we want to fully customize the `maximize` action so eg. titlebar buttons will work correctly, and the window will correctly report itself as `maximized`.

**Comment by olejorgenb** [comment]
These commits improve maximize integration significantly. Maximize-horizontally and maximize remains separate concepts.

 e87080e7956245d9928c3d3483d3a33a23b53b5e
ba0c82f27346d8428a9c156269261983a3d8f9a1
c3e5d5f8dda5f1c5f59db063210284a33b6b3860
7841e7368b40047d310adce1094a9c66bc91dc79
