### ISSUE TITLE
What is the best way to change the default keybindings?

### ISSUE THREAD

**Issue by hackeryarn** [paperwm/PaperWM#260]
I've been able to create my own custom keybindings in `.config/papwerwm/user.js`, but I am wondering what's the best way to change a default keybinding.

 For example, I want to change the commands to move windows to the left and right to work with `super` `shift` instead of `super` `ctrl`.

I would be happy to document this too to make overall configuration easier for others.

**Comment by olejorgenb** [comment]
There's a gui for changing keybinding in the extension preferences. (right click the workspace menu (top right) and click on "workspace preferences", or open the prefs from gnome-tweak-tool)

Alternatively you can use dconf-editor:
```
GSETTINGS_SCHEMA_DIR=$HOME/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/schemas dconf-editor /org/gnome/shell/extensions/paperwm/keybindings
```

**Comment by hackeryarn** [comment]
Thank you so much for the help @olejorgenb
