### ISSUE TITLE
super+r could default to half-width

### ISSUE THREAD

**Issue by pomdtr** [paperwm/PaperWM#262]
I have the impression that as users, we often need to split our screen by half, but much less frequently in 3/4 + 1/4.

In PaperWM, to place two window side by side, I need to :

1. Focus the first window
2. 2* `super+r`
3. `super+.`
4. 2* `super+r`
5. `super+,`

Which seems quite laborious for a basic feature. Default to half-width would improve this.

**Comment by hedning** [comment]
Yeah, there's some improvements possible here.

`<Super>R` is currently state-less, it simply picks the first step that's wider than the current width. There's some work in progress which makes `<super>r` remember things as long as `super` is down #193. So we can for instance try to preserve the original window position, or make half width the first step.

Now, you can change the step widths in dconf: 
```
dconf write /org/gnome/shell/extensions/paperwm/cycle-width-steps "[0.5]"
```

@olejorgenb also have code in the making which can do some basic auto-layout (eg. distributing the available width among the visible windows). We should probably get that into examples/keybindings.js at least.

**Comment by olejorgenb** [comment]
See https://github.com/paperwm/PaperWM/issues/303#issuecomment-636313932 for new actions that will fit two windows in various ratios

**Comment by jtaala** [comment]
I also note that with #463 winprops can be set for windows by `wm_class`, `title` etc.

We could also support wildcards in window winprops?  e.g. you could then set a winprop for all windows to set preferred with on create to 50% (or otherwise).
