### ISSUE TITLE
Feature request:more rows per workspace

### ISSUE THREAD

**Issue by enzogurgel** [paperwm/PaperWM#265]
Would be possible to implement something like partial  Workspace Matrix grid layout?

[https://extensions.gnome.org/extension/1485/workspace-matrix/](url)

Basically the feature would allow users to **change rows per workspace** ,but not columns, so  the user would be able to better display his/hers tasks per workspace.

- Usage example: user reads a lot of documents or a lot of windows are open,like browser or terminal.

- What is possible now: user can stack windows horizontally and vertically,however it appears bugged in super+<arrow keys> when windows are stacked vertically,also horizontal scrolling can be a bit messy due to **different apps per row in workspace.**

- What would could do after implementation: user is going to be able to isolate workspaces in n fixed rows so documents share a single row,browser windows  share the next row and so on.

**Comment by hedning** [comment]
Hmm, so having several horizontal scroll strips per workspace, of which you can only view one at a time (at least with a single monitor)? We've thought about having some sort of workspace grouping, though not sure if it's worth the extra complexity.

> however it appears bugged in `super+,/.`

I'm guessing you're referring to how `switch-next` and `switch-previous` goes through all the windows in a column linearly? `super+left/right` (`switch-left`/`switch-right`) always takes you to the next column, but that's only possible by also having actions for up/down `super+up/down` (`switch-up`/`switch-down`). You can always bind `super+,/.` to the `switch-left/right` actions to get the other behavior.
