### ISSUE TITLE
Deskop Icons visible while switching windows

### ISSUE THREAD

**Issue by Philipp0205** [paperwm/PaperWM#266]
First of all thank you for making this awesome extension! 

While switching windows desktop icons are visible above the windows. I am using Ubuntu 19.10. 
The problem is visible in the following video. (look at the top left corner)

![Peek 2020-03-12 13-20](https://user-images.githubusercontent.com/36603238/76521164-8fc85700-6464-11ea-9ab8-0448b3b8d24d.gif)

![Peek 2020-03-12 13-28](https://user-images.githubusercontent.com/36603238/76521621-77a50780-6465-11ea-961a-95be8bfefb62.gif)

**Comment by hedning** [comment]
Cheers :)

This is known issue, and we've landed on simply not supporting desktop-icons for the moment.

Disabling desktop-icons in tweak-tools should probably work in 19.10, so that's your best bet.

**Comment by Philipp0205** [comment]
Thank you for the answer! I will just disable it, who needs desktop icons any-ways ;)

Best Regards
Philipp
