### ISSUE TITLE
GNOME 3.35.91 Compatibility 

### ISSUE THREAD

**Issue by faebser** [paperwm/PaperWM#267]
I found #212 and used the branch mentioned in the issue. Sadly I still get a bunch of errors when enabling:

`
Error occurred in tiling @enable:
space.clip.raise_top is not a function
`

**Comment by olejorgenb** [comment]
Master (and develop) should now be compatible with 3.36 (and 3.35.x) :)

**Comment by olejorgenb** [comment]
Closing this. Let us know if the master and/or develop branch don't work out :)

**Comment by faebser** [comment]
yes, it works. thanks
