### ISSUE TITLE
switch-monitor-[left,right,down,up)] default bindings (usually) don't work on empty workspaces

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/PaperWM#269]
This is due to the actions we override (move-to-monitor-*) is registered as PER_WINDOW.

If we "lose" the initial keybinding "fight" we have to override the action which won, but there's no way(?) to override the keybinding flags :/

Fixable by either rebinding to some other combination or rebinding/unbinding the move-to-monitor-* actions (`dconf-editor /org/gnome/desktop/wm/keybindings/move-to-monitor-down`)

**Comment by jtaala** [comment]
Appears to be an old bug report.  On recent versions of PaperWM switching between monitors works correctly (whether workspaces are empty or not).

Will close this in a few weeks.
