### ISSUE TITLE
develop fails to start on GNOME Shell 3.28  (master works)

### ISSUE THREAD

**Issue by wleoncio** [paperwm/PaperWM#271]
Whenever I try enabling the extension, I get the following error message:

```
-En PaperWM
Error occured in tiling @enable:

invalid property id

@/home/waldir/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/navigator.js:28:5
@/home/waldir/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/topbar.js:23:5
@/home/waldir/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/scratch.js:11:5
@/home/waldir/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:28:5
safeCall@/home/waldir/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:58:13
run@/home/waldir/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:44:14
enable@/home/waldir/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:109:9
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:135:9
onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:289:9
onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:286:5
```

Currently on Ubuntu LTS (18.04). I tried following the instructions on README, but I found it a bit confusing after running `./install.sh`.

**Comment by olejorgenb** [comment]
Master or develop branch? Most development has happened using at least gnome-shell 3.34 lately so it's not impossible a 3.28 bug has been left in in.

**Comment by wleoncio** [comment]
develop. I followed the default README instructions, and double-checked with `git branch`.

**Comment by olejorgenb** [comment]
I don't have time to look into it before tonight/tomorrow, but it would be helpful if you tried the master branch: `git checkout master` (no need to run the install script again, but you need to restart gnome-shell (Super-F2 r if you're on X)

**Comment by wleoncio** [comment]
Master branch works, thanks!

BTW, I believe the shortcut to restart the shell is <kbd>Alt</kbd>+<kbd>F2</kbd>.

**Comment by olejorgenb** [comment]
Hopefully that was it. We no longer have easy access to a 3.28 environment so it's not actually tested :see_no_evil:
