### ISSUE TITLE
unplugged external monitor, now it crashes every time I try and start it

### ISSUE THREAD

**Issue by DanielJoyce** [paperwm/PaperWM#273]
-En PaperWM
Error occured in tiling @enable:

oldSpace.monitor is null

Space@/home/danieljoyce/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:176:17
addSpace@/home/danieljoyce/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2012:21
Spaces@/home/danieljoyce/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:1271:13
enable@/home/danieljoyce/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2206:14
safeCall@/home/danieljoyce/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:59:37
run@/home/danieljoyce/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:44:14
enable@/home/danieljoyce/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:109:9
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:132:13
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:403:13
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:400:9

**Comment by DanielJoyce** [comment]
Changing line 175 of tiling.js to this

``` javascript
        if (oldSpace && oldSpace.monitor) {
```
fixes the issue.

**Comment by DanielJoyce** [comment]
Thanks!

**Comment by hedning** [comment]
Hey, thanks for figured out the fix.

I'm guessing you encountered an edge case where for some reason a space was created with a null monitor, which I'm a bit uncertain how could happen. Though we've had a report which indicated that primaryMonitor can be null in some cases (https://github.com/paperwm/PaperWM/issues/110), so might be related.

**Comment by DanielJoyce** [comment]
I had set my external monitor as primary in my display settings so when I attach it, and have the external and laptop open, all the primary controls appear on the external monitor.
