### ISSUE TITLE
Why do terminal windows move workspace when I move

### ISSUE THREAD

**Issue by adschem** [paperwm/PaperWM#274]
As title suggests

If i have a terminal window open and i change workspace with either super + pgup/down and or super + above tab I always take the terminal windows with me and they do not stay in the workspace they are in. help?

**Comment by olejorgenb** [comment]
I suspect the terminal window is in the scratch layer (ie. floating). (Right click on the window title and see if "scratch" is checked)

The scratch layer is shared between workspaces by design.

Can you post a screenshot when the terminal is open?

**Comment by jtaala** [comment]
Given no response and not much info, will close this in a month or so.
