### ISSUE TITLE
Usage of object.actor is deprecated on Gnome Shell 3.36.0

### ISSUE THREAD

**Issue by mogenson** [paperwm/PaperWM#276]
Hey, I noticed some messages spawning from Paper WM in journalctl:

```
Usage of object.actor is deprecated for MessageTray
Usage of object.actor is deprecated for PanelCorner
Usage of object.actor is deprecated for WorkspaceMenu
```

This is on Gnome Shell 3.36.0, Arch Linux, Wayland.

**Comment by hedning** [comment]
Yeah, gnome-shell 3.34 (IIRC) added warnings when accessing  `.actor` on objects that are themselves actors. Unfortunately to support earlier gnome-shell versions we need to do this sometimes.

I've eliminated most of the spam by taking reference on startup and using that instead, but there's some still remaining when navigating workspaces from a fullscreen workspace I think.

Won't be fixed entirely until we drop support for <= 3.34.
