### ISSUE TITLE
Move workspace between monitors?

### ISSUE THREAD

**Issue by crispinb** [paperwm/PaperWM#280]
I think this isn't possible now, but I've only been using PaperWM for a day so apologies if I've missed something.

I'd like to be able to move a whole workspace to a different monitor. This would be great for working on a laptop and switching between internal-screen-only and internal-plus-external workflows. When plugging a monitor in, just push one of the workspaces to it (rather than dealing individually with a bunch of windows).

The next best thing would be to be able to move all windows from one workspace to another.

[Aside: I was thrilled to discover PaperWM. Combining the ergonomics of a tiling WM with my distro's underwriting of the gnome ecosystem is just what I've wanted, and you've made a great job of it from what I've seen so far. Thanks!]

**Comment by hedning** [comment]
Yeah, we haven't made a default binding for that yet, but there's a rough implementation in `examples/keybindings.js`

You can turn it on by adding `Examples.keybindings.moveSpaceToMonitor()` in the init function in `~/.config/paperwm/user.js`. That will make `<Super><Alt>up/down/right/left` move spaces between monitors.

**Comment by crispinb** [comment]
Thanks. That works nicely.

**Comment by planetA** [comment]
If I add this line (moveSpaceToMonitor), when I login I get the following error message:

```
Error occurred in user @init

function Gtk.accelerator_parse_with_keycode: At least 2 arguments required, but only 1 passed
```

```
gnome-shell --version
GNOME Shell 44.2
```

PaperWM version is 44.0

**Comment by jtaala** [comment]
> If I add this line (moveSpaceToMonitor), when I login I get the following error message:
> 
> ```
> Error occurred in user @init
> 
> function Gtk.accelerator_parse_with_keycode: At least 2 arguments required, but only 1 passed
> ```
> 
> ```
> gnome-shell --version
> GNOME Shell 44.2
> ```
> 
> PaperWM version is 44.0

I'm not sure if the experimental stuff works on recent versions given considerable changes here.  However #588 might help here, along with workspace stack switching (see comment for video): https://github.com/paperwm/PaperWM/issues/571#issuecomment-1671623560

**Comment by jtaala** [comment]
> If I add this line (moveSpaceToMonitor), when I login I get the following error message:

Let me know what you think of the swapping workspace behaviour just added in latest PaperWM.

I'd be happy to add official support for moveSpaceToMonitor if swapping isn't quite the right behaviour to quickly move workspaces around.

Also see https://github.com/paperwm/PaperWM/issues/206#issuecomment-1698998753
