### ISSUE TITLE
Switching directly to spaces

### ISSUE THREAD

**Issue by bsundsrud** [paperwm/PaperWM#282]
Is there a way to switch directly to a numbered workspace?  I've been trying to add a keybinding to jump to a workspace index (Using `Tiling.spaces.switchWorkspace()`) but I'm running into javascript errors no matter which way I try, which is leading me to believe I'm trying to go about this the wrong way.

**Comment by olejorgenb** [comment]
The regular gnome-shell keybindings for switching workspaces (by number) should work. Use settings -> keyboard shortcuts or `dconf-editor /org/gnome/desktop/wm/keybindings/switch-to-workspace-1`

**Comment by bsundsrud** [comment]
`dconf-editor` was the trick; I wanted to bind more than 1-4 exposed via the UI.  Thanks!

**Comment by mawkler** [comment]
> The regular gnome-shell keybindings for switching workspaces (by number) should work

This is true, but it looks really buggy on multiple monitors
