### ISSUE TITLE
Where can I set the resize definitions?

### ISSUE THREAD

**Issue by whnr** [paperwm/PaperWM#285]
Hello! I tried to find it in the code and would hope I can set them but I had no luck.

Where are the breakpoints for horizontal (and vertical) sizing steps defined? The seem to be 100% 66% 50% and 33%.

Can I set my own somewhere? In code today and in a setting in the future?

--Flo

**Comment by olejorgenb** [comment]
Yes, this we have undocumented options for this: 

Dconf keys: `/org/gnome/shell/extensions/paperwm/cycle-height-steps` and `/org/gnome/shell/extensions/paperwm/cycle-width-steps`

Launch dconf-editor like this `GSETTINGS_SCHEMA_DIR=$HOME/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/schemas dconf-editor /org/gnome/shell/extensions/paperwm` to get "schema-aware-editing"

**Comment by olejorgenb** [comment]
Ref:  #129
