### ISSUE TITLE
«Workspace preference» button is broken in GS >= 3.36.1

### ISSUE THREAD

**Issue by hedning** [paperwm/PaperWM#287]
`gnome-shell-extenssion-prefs` no longer takes an uuid argument, instead we need to use `gnome-extensions prefs`, or a method that should be available in GS 3.36.2.

Unfortunately the preference app is now launched through dbus. Meaning we can't control the environment of the process correctly which then breaks the method we used to launch the preference gui with the correct workspace selected.

**Comment by jtaala** [comment]
I'm not sure what this bug refers too - but seems to be a prior way of opening workspace settings?  In any case, does not appear to be relevant to recent versions of PaperWM.

Will close in a few weeks.
