### ISSUE TITLE
Workspace disappeared (but exists in settings)

### ISSUE THREAD

**Issue by crispinb** [paperwm/PaperWM#288]
One of my workspaces disappeared, possibly after an xorg crash (not caused by PaperWM). By 'disappeared' I mean I can't find it cycling through with `Super >`, `Super PgDown` etc.

However it's still in workspace settings -> per workspace. It's a minor irritant because I had named it and want that name back. In any case, presumably this shouldn't happen?

**Comment by hedning** [comment]
Right, I've seen that happen a few times, but haven't found a solid cause/fix. 

Now there's buttons in the workspace menu (right click on the workspace name) which cycles through which preference/name a workspace should have, so you can get it back that way.

**Comment by crispinb** [comment]
Thanks, that helps. I hadn't noticed the buttons in the workspace context menu.

**Comment by jtaala** [comment]
Hey @crispinb - let me know if this still happens for you.  Will re-open if it does.
