### ISSUE TITLE
Gnome Screenshots multimonitor broken

### ISSUE THREAD

**Issue by jtagcat** [paperwm/PaperWM#290]
This is my current monitor setup. All are FHD.
![image](https://user-images.githubusercontent.com/38327267/79625656-f141ac80-8119-11ea-8e7f-511465ad963c.png)
I made a screenshot of an area on monitor 3, I got a screenshot of the same absolute area (location and size) on monitor 1.

**Comment by hedning** [comment]
Yeah, I've seen bugs upstream about this, eg.: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2567. So not a bug in paperwm.
