### ISSUE TITLE
Vertical trackpad swipes don't allow workspace selection

### ISSUE THREAD

**Issue by crispinb** [paperwm/PaperWM#291]
Swiping up & down (with 3 fingers) does scroll through the workspaces, but from there I can't select any workspace other than the one I started the scroll from. It stays in scrolling mode unless I either (a) intervene with the keyboard (eg. using Super-`) or (b) scroll back to the workspace I was in  when initiating the scroll.

**Comment by hedning** [comment]
Sounds like a problem with desktop-icons: https://github.com/paperwm/PaperWM/issues/145

**Comment by crispinb** [comment]
Yep - works as expected with the generic gnome-session.
