### ISSUE TITLE
Disable window gaps

### ISSUE THREAD

**Issue by azmeuk** [paperwm/PaperWM#295]
Hello. First thank you for this amazing extension!
I am not sure this bugtracker is the right place for asking questions, but as I did not found any documentation on the topic, maybe it worth a discussion :)

Is it possible to remove window gaps, so every pixel in my screen is used?

Thank you for your help

**Comment by hedning** [comment]
Yeah, that's configurable in the paperwm preferences (opened through «Extensions» or «Tweaks»). Or just run this:
```
dconf write /org/gnome/shell/extensions/paperwm/window-gap "0"
```

**Comment by azmeuk** [comment]
Exactly what I needed. Thank you.
