### ISSUE TITLE
Windows don't receive input events after monitor switch with scratch layer.

### ISSUE THREAD

**Issue by Strauman** [paperwm/PaperWM#298]
## Description
After monitor switch, in combination with scratch layer, windows stop receiving input.
## Reproduction steps:
- Using two monitors. Referring to as Monitor 1 and Monitor 2.
1. Add at least two tiling windows to Monitor 1 and make one of the windows floating.
1. Disable scratch screen on Monitor 1, and use the mouse to activate Monitor 2.
1. Open at least one tiled window on Monitor 2.
1. Use the mouse to activate a tiled window on Monitor 1, and enable activate the scratch layer and focus/activate the floating window.
1. Use the mouse to now select a tiled window on Monitor 1, and no windows are no able to be selected.

It "snaps out of it" by Activating the window to the left or right (with <kbd>super</kbd><kbd>Left</kbd> or <kbd>super</kbd><kbd>Right</kbd> by default)

## Technical info
- Gnome shell 3.28.4
- On git commit 42a69e6c8b748723fcf06e0c4219b8fc2a40fc04 (Develop branch)
- Ubuntu 18.04.4 LTS

Perhaps related to #297 as it addresses multi-monitor scratch layer problem. Possibly related also related to a similar problem in #110, but in that it occurs with only one monitor https://github.com/paperwm/PaperWM/issues/110#issuecomment-489356359.

**Comment by hedning** [comment]
Right, we probably need to check if the scratch window is actually on current monitor:
```diff
modified   stackoverlay.js
@@ -138,7 +138,8 @@ class ClickOverlay {
 
         // But don't change focus if a stuck window is active
         if (display.focus_window &&
-            display.focus_window.is_on_all_workspaces())
+            display.focus_window.is_on_all_workspaces() &&
+            display.focus_window.get_monitor() == this.monitor.index)
             select = display.focus_window;
 
         if (select) {
```

**Comment by hedning** [comment]
Though, a bit weird, I'd would've thought `workspace.activate_with_focus(...)` would actually activate the correct workspace even though the focus is on all workspaces...

**Comment by jtaala** [comment]
Just cleaning up some older issues.  I can't reproduce this issue, and given it's age will close unless this is still an issue on recent versions of PaperWM (e.g. on Gnome 44, 45, 46 etc.).
