### ISSUE TITLE
Always Center

### ISSUE THREAD

**Issue by rawkode** [paperwm/PaperWM#299]
The more I use PaperWM, the more I play around with certain applications behind slightly different widths.

It would be really beneficial if there was an option to always center on the active window

**Comment by rawkode** [comment]
#150 might be close enough to this

CC @olejorgenb

**Comment by hedning** [comment]
You can get something like this by turning up the horizontal margin (eg. to 1/2 the screen). It won't center the first and last window though, and the preference gui still has a bug which limits you to max 100px so you'll have to use eg. dconf-editor to set it higher.

Auto centering would absolutely be nice, especially on wide screens.

I guess there's a few options here:
- add a «mode» that can be toggled
- let windows inherit centering, ie. if the previous window was centered, center the new one. That might be workable as a default.


For a quick local fix this should work in user.js (and similarly for `Space.switchLeft/Right`):
```js
    let orgSwitch = Tiling.Space.prototype.switchLinear;
    Tiling.Space.prototype.switchLinear = function (dir) {
        orgSwitch.call(this, dir);
        Tiling.centerWindowHorizontally(this.selectedWindow);
    }
```

**Comment by winteriscariot** [comment]
The main issue related to this that I run into, is if I have windows spread out to the right, I can scroll horizontally (works great!) but since there's no snappy, it's entirely possible for me to stop scrolling with half of one window hanging off-screen to the right or left. 

If we could get horizontal viewports to snap based on window geometry (ie, snap to columns), that would be very handy.

**Comment by todiadiyatmo** [comment]
@hedning 

how to properly paste the code in user.js ? inside enable function or outside ?

**Comment by olejorgenb** [comment]
The fix hedning suggested should go in the `init` function. (otherwise a new override layer would be added each time the screen was unlocked)

**Comment by jtaala** [comment]
#482 does this.  Well, it adds a persistent sticky centering mode (can set it at a workspace level).  Just collecting feedback for this atm - after that (if no showstoppers) I'll merge it in.
