### ISSUE TITLE
Patreon / GitHub Sponsors

### ISSUE THREAD

**Issue by rawkode** [paperwm/PaperWM#300]
Hi @hedning,

I just want to say thank you for your continued effort on this project.

I'd like to encourage you to sign up for GitHub Sponsors or another such tool so that I can give a little back.

Thanks :heart:

**Comment by hedning** [comment]
Cheers :) It's fun to see people find our approach enjoyable. 

I've been meaning to sign up, so thanks for the nudge :heart:
