### ISSUE TITLE
automatically activates on startup

### ISSUE THREAD

**Issue by rommeljohn** [paperwm/PaperWM#302]
PaperWM extension is always active on startup even if it was deactivated before shutting down.
OS: Debian 10 buster
Kernel: x86_64 Linux 4.19.0-8-amd64
Shell: bash 5.0.3
DE: GNOME 
WM: GNOME Shell

**Comment by olejorgenb** [comment]
That's strange and an upstream bug almost by definition. I'd use the big guns and remove the `$HOME/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org` directory/symlink.

**Comment by rommeljohn** [comment]
deleted $HOME/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org
logout / login
paperwm is not active but also no longer in the extensions list
reinstalled using install.sh
paperwm installed successfully and activated
deactivated paperwm
logged out / logged in
paperwm is once again active upon logging in.

**Comment by olejorgenb** [comment]
gnome-shell version? 

They have changed how to enable extensions programmatically around a bit.

You could try to install manually (simply copy the paperwm folder to `$HOME/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/`. A restart is usually required for gnome to find the extension)

**Comment by jtaala** [comment]
Noting this issue is older, is this still happening for anyone?  I haven't been able to reproduce this (and haven't seen this happen).

**Comment by jtaala** [comment]
Closing as no responses confirming this is still impacting anyone after a month.
