### ISSUE TITLE
Make workspaces swappable

### ISSUE THREAD

**Issue by zklaus** [paperwm/PaperWM#310]
Right now, you cannot switch to a workspace that is active on another monitor.
It would be nice to be able to do that, resulting in the swapping of the two workspaces.

**Comment by hedning** [comment]
See https://github.com/paperwm/PaperWM/issues/280 on how to use the experimental keybindings for moving workspaces between monitors.

**Comment by zklaus** [comment]
Thanks @hedning! It works well.

**Comment by jtaala** [comment]
Looks like part implemented in #280 but not enabled by default(?).

Anyone want to have a look at testing these advanced shortcuts and potentially turning some of them on (with default keybindings)?

**Comment by jtaala** [comment]
Official support (with keybinds) added in #588.
