### ISSUE TITLE
Add a setting for the default window size(s)

### ISSUE THREAD

**Issue by 1over137** [paperwm/PaperWM#316]
This scrollable tilling scheme seems to work really well with my super-ultrawide monitor. However, I feel that the smallest default width (seems to be about 30~40% of the screen width) is a bit too large, and I don't find anything in the settings to change it. It would be great if I can choose the sizes given by ctrl-r.

**Comment by hedning** [comment]
You can change the step widths like this (using screen width ratios):
```
dconf write /org/gnome/shell/extensions/paperwm/cycle-width-steps "[0.1, 0.3, 0.5]"
```
You can also specify static widths, but the ratios and exacts can't be mixed at the moment:
```
dconf write /org/gnome/shell/extensions/paperwm/cycle-width-steps "[300, 500, 700]"
```

There's also `<Super>+/-` which increases/decreases the window width 10% (IIRC).

**Comment by shaoyu6174** [comment]
Thanks, this works well. Is this documented anywhere?

**Comment by hedning** [comment]
Nope, doesn't look like it :p

Might be good as an example in https://github.com/paperwm/PaperWM/#using-dconf-editor-to-modify-settings (or the wiki, which is pretty bare bones at the moment).
