### ISSUE TITLE
Small offset on workspace name

### ISSUE THREAD

**Issue by Natchuz** [paperwm/PaperWM#318]
This small visual bug appears all workspaces except on the first you see after launching Gnome. It's also visible when cycling, that mentioned workspaces have their names a little bit moved. However I was not able to take example screenshot, since it's impossible capturing when holding super key. This bug happens currently on Fedora 32, Gnome 3.36.3. I also noticed this bug, before I moved to Fedora, on Ubuntu 19.10 (I don't remember which Gnome version it was).
After quick extension re-enable, bug dissapears.

![Screenshot from 2020-06-29 19-25-37](https://user-images.githubusercontent.com/30700722/86036561-609f1b00-ba3e-11ea-946c-3d68c3b085c0.png)

**Comment by hedning** [comment]
Right, I've noticed this when launching nested gnome-shell, on secondary monitors.

Are you seeing this with only a single monitor and are you seeing it on wayland or x11?

**Comment by Natchuz** [comment]
Normally I use one monitor, so I plugged second cable and it still happens on both outputs, no matter if it's x11 or wayland.

**Comment by christopher-l** [comment]
For me, this happens when new workspaces are added dynamically ("Dynamic Workspaces" activated).

**Comment by jtaala** [comment]
Hey all, this shouldn't happen on recent supported versions of PaperWM (e.g. on `develop`, `release`, or on PaperWM installed via https://extensions.gnome.org/extension/6099/paperwm/).

Let me know if anyone is still seeing this, otherwise will close this issue in a few weeks or so.

**Comment by christopher-l** [comment]
Looks good to me now.

**Comment by jtaala** [comment]
> Looks good to me now.

Thanks @christopher-l.
