### ISSUE TITLE
Is it possible to hide the edges of off-screen windows?

### ISSUE THREAD

**Issue by exp2ipi** [paperwm/PaperWM#319]
I like to keep two windows side by side, but in PaperWM the edge of the window off-screen in the linear layout, to the left (or sometimes to the right) usually shows (see screenshot). Is it possible to size windows in a way that would hide it?

Furthermore, is it possible to minimize the gaps between windows (ideally I would like two windows in a 50/50 split, with minimal gaps, and no fringes of windows visible on the edges).

![image](https://user-images.githubusercontent.com/338250/86098868-91497980-ba6b-11ea-9c7b-51e98e2791a9.png)

**Comment by hedning** [comment]
You can configure the window gap and horizontal margin in the preference GUI. the GUI can be launched from gnome-tweaks, the extension app or via right clicking the workspace label (upper left corner).

**Comment by exp2ipi** [comment]
This does the trick and seems to result in a more stable behavior! I was getting weird unexpected window switching when I think I would accidentally mouseover the horizontal margin.
