### ISSUE TITLE
path name with colon causes problems with gsettings and GSETTINGS_SCHEMA_DIR

### ISSUE THREAD

**Issue by wbolster** [paperwm/PaperWM#322]
this extension uses a `:` (colon) character in its directory name in `~/.local/gnome-shell/extensions`, namely `paperwm@hedning:matrix.org`, which causes problems when using `GSETTINGS_SCHEMA_DIR=...` and the `gsettings` command line tool. the `:` is interpreted as a path separator.

this means `gsettings` cannot be used to configure this extension, as suggested in the readme.

since this is only the extension (out of quite a few on my system) using a non-standard character, i suggest to adhere to the established practices and conventions for gnome extensions, and use an identifier and directory name that do not cause problems.

**Comment by hedning** [comment]
Right, that's a good point, the directory won't work in at least `XDG_DATA_DIR` which is colon separated. Now I'm fairly certain `GSETTINGS_SCHEMA_DIR` isn't colon separated, it's only meant to be used by a single directory, as the suggested dconf-editor hack in the readme works.

As an aside you can set things without a schema too (at least with `dconf`).

Will have a think about changing the id, and how a smooth upgrade can be handled.

**Comment by wbolster** [comment]
glib changed, and it only works with older versions

**Comment by hedning** [comment]
Right, never noticed as I've only really used dconf-editor together with `GSETTINGS_SCHEMA_DIR`, and looking at the code it does some manual handling were it treats it as a single directory. So that's actually a bug in dconf-editor :p

**Comment by wbolster** [comment]
this popped up again in https://github.com/paperwm/PaperWM/issues/376#issuecomment-815561175

the best would be to just ‘get with the program’ :wink: and use the same naming conventions as pretty much all other gnome extensions. without a colon, that is.

**Comment by hedning** [comment]
Yeah will just have to bite bullet here, propably do it for the 40 release

**Comment by jtaala** [comment]
To avoid future (potential) issues with this - yeah, I think we should change the id/name to `paperwm@hedning.matrix.org`?

Will create a PR for this.

**Comment by jtaala** [comment]
Closing as uuid has been changed to safer `paperwm@paperwm.github.com`.
