### ISSUE TITLE
Question: Disable minimap for switching between windows

### ISSUE THREAD

**Issue by terlar** [paperwm/PaperWM#325]
Is there a way to disable minimap for switching windows, I see the option `opensMinimap`, but does that mean I have to override all those keybindings and trying to figure out what the default values are? 

Or if it is not possible with a lot of effort is it possible to configure extend the delay until it shows up?

**Comment by hedning** [comment]
`opensMinimap` is keybind/action specific. There's not a global preference at the moment, others have asked about it before and I've been meaning to implement it, but haven't gotten to it yet.

It should be a really straightforward fix though:

- Just add a new option ([like this](https://github.com/paperwm/PaperWM/blob/clutter-dnd/schemas/org.gnome.shell.extensions.org-scrollwm.gschema.xml#L354-L357))
- Compile the schemas (eg. `make` or just `glib-compile-schemas schemas/`)
- Add the new option to the internal prefs tracking ([like this](https://github.com/paperwm/PaperWM/blob/clutter-dnd/settings.js#L34-L37)).
- And check against it [here](https://github.com/paperwm/PaperWM/blob/clutter-dnd/navigator.js#L160-L162).

Ideally it should be added to the preference gui too ([something like this](https://github.com/paperwm/PaperWM/blob/clutter-dnd/prefs.js#L138-L144)).

**Comment by terlar** [comment]
This is a duplicate of #173
