### ISSUE TITLE
Automatically move a certain window class/app/etc. to scratch

### ISSUE THREAD

**Issue by taciturasa** [paperwm/PaperWM#326]
When using PaperWM, it is somewhat disappointing that it is difficult to use ULauncher with the setup. As it is seen as a window, PaperWM grabs it into the tiling stack. It would be helpful if there was a way to set a specific WMCLASS or application name to always put in the scratch layer on launch, no matter what.

**Comment by hedning** [comment]
We have functionality for this, though it's only available by using the `user.js` file.

Here's some examples:
https://github.com/paperwm/PaperWM/blob/ac54a572db0963628d442955093ad643a951c842/settings.js#L92-L103

«Winprops» should be defined inside your init function in user.js.

**Comment by taciturasa** [comment]
Much help. Thanks!

**Comment by erwin** [comment]
This discussion is about using `user.js`, but note that was disabled...

So you now do it via the PaperWm Configuration "Winprops" tab.

See: https://github.com/paperwm/PaperWM/issues/466#issuecomment-1399223112

**Comment by Thesola10** [comment]
@erwin user.js no longer works since GNOME 40. Input yoir winprops in PaperWM preferences.
