### ISSUE TITLE
Visual artifacts when opening windows with mutter 3.36.4

### ISSUE THREAD

**Issue by shibotto** [paperwm/PaperWM#328]
3.36.3 (good)
![3-36-3](https://user-images.githubusercontent.com/3816409/87222996-33753580-c379-11ea-8608-b41215feedf1.gif)

3.36.4 (bad, notice the blue rectangles)
![3-36-4](https://user-images.githubusercontent.com/3816409/87223001-41c35180-c379-11ea-8a6b-653a45a8bd2d.gif)

I bisected the mutter commit that introduced this down to https://gitlab.gnome.org/GNOME/mutter/-/commit/44a3358125317dbe2151cf0ac70ec2c382236881.

I can only reproduce this using PaperWM, vanilla GNOME doesn't seem to be affected.

**Comment by hedning** [comment]
Right, I suspected there might be some breakage when looking at the release notes.

Thanks for taking the time bisecting the problem. Will take a look.

**Comment by shibotto** [comment]
Still a problem (even worse maybe) with GNOME 43 + Xorg and develop branch  :(

https://user-images.githubusercontent.com/3816409/196010349-fd28dfbe-6a7f-4ac7-be54-73cfb6599462.mp4

**Comment by jtaala** [comment]
Thanks @shibotto, your comment re still happening on Gnome 43 caught my attention  (I'm also on Gnome 43).   

I didn't really notice it (but then again I prefer speeding up `animation-time` to 0.15).  Changing `animation-time` to 0.99 you can see the `selected` actor being drawn with the rectangles you refer to  for some of the windows.

Will have a look and see about cleaning up / improving the animation/tween used.

**Comment by jtaala** [comment]
Hey @shibotto, sorry it took a while (was working on a few different things).

Anyways, checkout #501 - it should look much better (also I put up some before/after vids in that PR).
