### ISSUE TITLE
rofi inaccessible if launched without open windows (on Wayland)

### ISSUE THREAD

**Issue by terlar** [paperwm/PaperWM#329]
I have the following content of the user.js file:
```
var Meta = imports.gi.Meta;
var Clutter = imports.gi.Clutter;
var St = imports.gi.St;
var Tweener = imports.ui.tweener;
var Main = imports.ui.main;
var Shell = imports.gi.Shell;

// Extension local imports
var Extension, Me, Tiling, Utils, App, Keybindings, Examples;

function init() {
    // Runs _only_ once on startup

    // Initialize extension imports here to make gnome-shell-reload work
    Extension = imports.misc.extensionUtils.getCurrentExtension();
    Me = Extension.imports.user;
    Tiling = Extension.imports.tiling;
    Utils = Extension.imports.utils;
    Keybindings = Extension.imports.keybindings;
    Examples = Extension.imports.examples;
    App = Extension.imports.app;
    Settings = Extension.imports.settings;

    Settings.defwinprop({
        wm_class: "Rofi",
        focus: true
    });
}

function enable() {
    // Runs on extension reloads, eg. when unlocking the session
}

function disable() {
    // Runs on extension reloads eg. when locking the session (`<super>L).
}
```

If opening rofi before opening any other windows all keyboard input will be locked and rofi will only respond to mouse operations. If I run Alt+F2 (which luckily still works), I can launch any Application and rofi will start work again.

<details>
  <summary>Original</summary>
I have the following content of the user.js file:
```
var Meta = imports.gi.Meta;
var Clutter = imports.gi.Clutter;
var St = imports.gi.St;
var Tweener = imports.ui.tweener;
var Main = imports.ui.main;
var Shell = imports.gi.Shell;

// Extension local imports
var Extension, Me, Tiling, Utils, App, Keybindings, Examples;

function init() {
    // Runs _only_ once on startup

    // Initialize extension imports here to make gnome-shell-reload work
    Extension = imports.misc.extensionUtils.getCurrentExtension();
    Me = Extension.imports.user;
    Tiling = Extension.imports.tiling;
    Utils = Extension.imports.utils;
    Keybindings = Extension.imports.keybindings;
    Examples = Extension.imports.examples;
    App = Extension.imports.app;
    Settings = Extension.imports.settings;

    Settings.defwinprop({
        wm_class: "Rofi",
        focus: true
    });

    Settings.defwinprop({
        wm_class: "Spotify",
        scratch_layer: true
    });
}

function enable() {
    // Runs on extension reloads, eg. when unlocking the session
}

function disable() {
    // Runs on extension reloads eg. when locking the session (`<super>L).
}
```

Neither of the window properties seem to take effect, Spotify is still acting like a normal window, not being attached to the scratch layer, and what I guess the Rofi properties would fix is that still without any windows open rofi will lock all interactions (not being focused, but still hogging the keys).

Any thoughts why this is? I have tried with the Tiling.defwinprop as well, but I saw in the definition that the one that should actually be used is the Settings.defwinprop. Neither of them work though.
</details>

**Comment by hedning** [comment]
Spotify suffers from an issue where its WM_CLASS is sometimes set too slow. So that probably what you're seeing (in my experience the spotify winprop mostly works, but can fail sometimes). This might be fixed by looking up the app id instead (which the winprops currently doesn't support, but really should ([relevant code here](https://github.com/paperwm/PaperWM/blob/develop/settings.js#L290-L310)).

Not sure what's up with rofi, I've used a scratch winprop successfully in the past, but that doesn't seem to work now. I'd suspect there's some wayland issue here.

**Comment by olejorgenb** [comment]
Which gnome-shell version are you running? Both Rofi (without any winprops) and spotify (with the same winprop as yours) works in 3.36 here (X11).

Note that you have to restart gnome-shell for the changes to take effect.

Checking `journalctl --boot 0 $(which)` for errors/weirdness might help.

**Comment by terlar** [comment]
I am using:
GNOME Shell 3.36.4

However, I use Wayland, so I think that is the crux.

Thank you, I have never seen any winprop stuff work, but I will try with a few other Applications to see. I guess I just happen to use the two unlucky ones.

Good tip with the journal, I see this:
```
Jul 19 18:50:00 beetle .gnome-shell-wr[2636]: JS WARNING: [/run/current-system/sw/share/gnome-shell/extensions/paperwm@hedning:matrix.org/scratch.js 144]: reference to undefined property Symbol()
Jul 19 18:50:00 beetle .gnome-shell-wr[2636]: JS WARNING: [/run/current-system/sw/share/gnome-shell/extensions/paperwm@hedning:matrix.org/settings.js 316]: reference to undefined property 0
Jul 19 18:50:00 beetle .gnome-shell-wr[2636]: JS WARNING: [/run/current-system/sw/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js 323]: reference to undefined property "_targetWidth"
```

@hedning Does that mean you also have this behavior for rofi, before opening any applications/windows if I run rofi, it won't take input and most keybindings will be dead, luckily Alt+F2 still works so I could kill rofi with that. If I open any window, and then run rofi it works.

**Comment by hedning** [comment]
Yeah, rofi won't take input here (gnome shell 3.36.4 Wayland) with or without winprops.

While not as fully featured as rofi, [`switcher](https://github.com/daniellandau/switcher) works fairly well as a launcher/window picker.

**Comment by terlar** [comment]
Yeah, I was using that up until now, but I missed being able to enter arbitrary shell-commands, as I can do with rofi run. Before I was using switcher and then some things didn't have a desktop file and didn't appear, so then I had to fallback to Alt+F2.

Also running Rofi 1.5.4

Thank you, perhaps I should rename this ticket to just be regarding rofi. I will try out to see if I can get some winprops stuff working and in that case this title would be invalid.

**Comment by terlar** [comment]
I tried it with Slack and it worked. So just unlycky to try with Spotify and rofi then.

**Comment by terlar** [comment]
I'm happy to announce that with the latest version of rofi and gnome-shell this is solved!

I'm running:
```
$ rofi -version
Version: 1.6.1
$ gnome-shell --version
GNOME Shell 3.38.2
```

and now I can both launch it without any windows and while running the new pgtk version of Emacs that didn't work before.

**Comment by terlar** [comment]
Hmm, funny enough after a reboot or so it is not working again (still on the same versions). I wonder what made it work, I was surprised by it wokring and tried it in the various places, however this time around it is back to old behavior...
