### ISSUE TITLE
app-switcher and window-switcher always force current-workspace-only

### ISSUE THREAD

**Issue by mhamrah** [paperwm/PaperWM#330]
I prefer the gnome app and window switcher to have current-workspace-only set to false. This works with PaperWM disabled, but when enabled, super+tab only shows windows in the current workspace, making jumping to windows in other workspaces difficult. Is there a way to either:

1) Super+Tab across all workspaces with PaperWM enabled?
2) List/jump-to any open window in any workspace?

Thank you,

Mike

**Comment by hedning** [comment]
Right, the way alt-tab previews windows didn't make that much sense with the workspace animation we had at the time.

Did a quick test now and it makes sense with the new default workspace animations.

We should probably respect the `window-switcher/current-workspace-only` preference.

**Comment by ankostis** [comment]
(thank you for your efforts)
Should there be a separate new issue for respecting `window-switcher/current-workspace-only` preference?

**Comment by Lythenas** [comment]
Since this issue is quite old, I would say create a new one. And maybe reference this.
