### ISSUE TITLE
Super-O (expel from column) not working

### ISSUE THREAD

**Issue by rosskarchner** [paperwm/PaperWM#337]
Hello! For some reason, Super-I works for me, but Super-O does nothing. I'm on a pretty fresh Gnome setup (deleted .conf/dconf and rebooted before installing PaperWM)

I would appreciate any tips about where to start troubleshooting.

**Comment by hedning** [comment]
Yeah, this is a known bug: #237. You can either change the paperwm binding to something else, or remove the conflicting binding as described [here](https://github.com/paperwm/PaperWM/issues/237#issuecomment-636315224)

We should probably use another binding as the default as we can't reliably steal it (IIRC).
