### ISSUE TITLE
Feature request: make entire window highlighting visible when changing to window

### ISSUE THREAD

**Issue by GeneralPoxter** [paperwm/PaperWM#338]
When switching to a window to the left, for example, paperwm doesn't make the left margin visible, which means the window highlighting on the left edge gets cut off:
![image](https://user-images.githubusercontent.com/20214615/93222495-03615e80-f73d-11ea-9d6e-69cd2ba9a7a9.png)
I was wondering whether the window could be shifted slightly to the right automatically (and vice versa when moving to a window on the right) so that all window edge highlighting is visible.

**Comment by jtaala** [comment]
This was by design earlier in PaperWM (see #364) but was superceded (i.e. changed) in #488.  Now PaperWM will show margins regardless if it's a tiling edge.
