### ISSUE TITLE
Hide scratch windows in overview

### ISSUE THREAD

**Issue by Pacman99** [paperwm/PaperWM#340]
Is it possible to hide scratch windows in the GNOME activities overview? It feels weird to have the windows follow me through every workspace, and they take up a lot of space in the overview. I don't see the point of them being there, when you can just bring the entire scratch layer to the front at any time to see what windows are in it.

Thank you so much for this extension, its really amazing and I've gotten such a great setup now on GNOME.

**Comment by hedning** [comment]
Cheers.

In principle this should be fairly straightforward (we have a toggle to do the opposite, see 719d01e1f9372d8c3cc8666af8d694c197ecb1ab), though gnome-shell 3.38 introduced fairly large changes to the overview code so that might require some additional change.

**Comment by Pacman99** [comment]
Cool thanks for showing me that! I figured out how to add the feature locally. Just created a pr to possibly make it available for others. I set it up so hopefully it won't be too hard to account for 3.38 changes in the future.
