### ISSUE TITLE
Modals move windows to the current workspace.

### ISSUE THREAD

**Issue by jtagcat** [paperwm/PaperWM#342]
When the user is not on the workspace that the window is on, and a new attached promt appears, for example:
 - Firefox basic authentication (example: https://authenticationtest.com/HTTPAuth/ )
 - Pamac (example: select changes, click apply, in a moment a confirmation one appears)

The modals steal focus, what I do not want to happen under any circumstances (I want 'the window is ready'). If a window was on workspace 1:
 - and I'm on workspace 2, it changes to an active window on ws 2.
 - and I'm on ws 1, it changes to the active window.

**Comment by hedning** [comment]
Yeah, modals from somewhere else than the active window shouldn't really get focus, that would be ideal. 

Now, we don't do anything with the modal focus, so this could be a default gnome behaviour. We do raise the modal to the top, which could affect focus, but I'd guess we'd have to do some work to block focus to certain windows. This isn't entirely straightforward as there's no `before-focus` signal, but it could be possible to make some rules and redirect focus back to the last window.

https://github.com/paperwm/PaperWM/blob/develop/tiling.js#L2416-L2425

**Comment by jtaala** [comment]
Note this is gnome behaviour (hence labelled as `upstream`) - happens with or without PaperWM in my tests.

**Comment by jtaala** [comment]
On latest `develop` with Gnome 44 I can no longer reproduce this.  Are other seeing this?

Planning on closing this in a month or so (assuming no responses).
