### ISSUE TITLE
No property background

### ISSUE THREAD

**Issue by tomkdale** [paperwm/PaperWM#343]
Updated from Ubuntu 20.04 to 20.10 and extension immediately broke. Gnome version 3.38.1. I tried a few different branches, develop & gnome-3.38 reinstalling with default settings everytime. Let me know what logs I can grab

Getting errors:
-En PaperWM
Error occured in tiling @enable:

No property background on MetaBackgroundActor

createBackground@/home/tdale/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:1048:27
setMonitor@/home/tdale/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:1082:18
Space@/home/tdale/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:182:14
addSpace@/home/tdale/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2012:21
Spaces@/home/tdale/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:1271:18
enable@/home/tdale/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2206:14
safeCall@/home/tdale/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:59:52
run@/home/tdale/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:44:14
enable@/home/tdale/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:109:12
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:168:32
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:496:35
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:496:14
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:533:46
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:195:29
EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:307:38
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:327:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34

and also:

-En PaperWM
Error occured in kludges @init:

obj is undefined

registerOverridePrototype@/home/tdale/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/kludges.js:286:5
...

**Comment by dblincoe** [comment]
I was having similar issues with this right after the update. I came back a couple hours later. Maybe timing could be an issue in this

**Comment by tomkdale** [comment]
Right, strange. I just checked back on that machine and Paperwm is up and running fine again. Thanks!
