### ISSUE TITLE
Overview brings back top bar when it is supposed to be hidden

### ISSUE THREAD

**Issue by jsravn** [paperwm/PaperWM#345]
I have "hide top bar" enabled for a workspace. If I press Super to bring the overview, then go back to the workspace, the top bar comes back. In addition the focused window border extends up into the top bar. I'd expect the top bar to be rehidden after coming out of the overview.

**Comment by hedning** [comment]
Cheers, had left a mistake on a rename/refactor.

**Comment by jsravn** [comment]
It works perfectly, thanks for the quick fix. Loving paperwm!
