### ISSUE TITLE
"Workspace x" text still shows even when top bar is hidden

### ISSUE THREAD

**Issue by jsravn** [paperwm/PaperWM#348]
I'm hiding the top bar in all workspaces. However the text "Workspace 1", etc., is still displayed when not covered by a window. Is that normal, or should it disappear as well? I'd prefer if it could be removed as well when the top bar is hidden.

**Comment by hedning** [comment]
It's sorta intended, but works pretty poorly as it will mostly be partly hidden by windows. It should probably be hidden as you say.

It should be fairly easy to check if the `this.showTopBar` here:
https://github.com/paperwm/PaperWM/blob/40a750918845f3c708dd1b51a40f2d29c48808c2/tiling.js#L1018-L1034

`Space.updateName` will then have to be run after `Space.updateShowTopBar` too.

**Comment by jsravn** [comment]
It would be great if it was hidden. :+1:

**Comment by jsravn** [comment]
As a workaround I've just labeled the workspace ` `.

**Comment by tadfisher** [comment]
Here's a diff that just removes the top bar space: https://github.com/tadfisher/PaperWM/commit/d53746025f45b3a3847bae3d29c32f75c394ef0d

I'm curious why the workarea height needs adjusting; it seems to work fine with this commit with the standard top panel, and as a bonus there isn't extra top space when using Dash-to-Panel on the bottom or sides.

**Comment by hedning** [comment]
Hehe, yeah, would've been good with some comments htere :p It's there to make workspaces on other monitors behave when top-bar-follow-focus (ie. when the top bar isn't on the monitor).

Also IIRC an older gnome-shell version reported different workarea depending presence of fullscreen windows which meant it wasn't entirely reliable, but I believe that's no longer the case.

@tadfisher It probably makes sense do what you suggest when the top bar doesn't follow focus at least (which should probably become the default tbh).

**Comment by jtaala** [comment]
I note this is an old issue and many things have changed.

This should be fixed now (relatedly you can also explicitly disable/not-show the workspace indicator with
```
dconf write /org/gnome/shell/extensions/paperwm/show-workspace-indicator false
```

Planning on closing this issue in a few weeks.
