### ISSUE TITLE
Tweener JS module error after update to ubuntu 20.10

### ISSUE THREAD

**Issue by ruanformigoni** [paperwm/PaperWM#349]
Hi! After the ubuntu 20.10 update, I've been receiving the error message below, each time the plugin is enabled.

<details>
<summary>Log</summary>
-En PaperWM
Error occured in user @enable:

No JS module 'tweener' found in search path

@/home/ruan/.config/paperwm/user.js:6:15
safeCall@/home/ruan/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:58:22
run@/home/ruan/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:49:17
enable@/home/ruan/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:109:12
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:168:32
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:496:35
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:496:14
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:533:46
enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:195:29
EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:307:38
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:327:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34
</details>

**Comment by terlar** [comment]
The tweener JS module is gone now:
https://github.com/paperwm/PaperWM/issues/341

**Comment by ruanformigoni** [comment]
@terlar Thanks!
