### ISSUE TITLE
Bug: Launching and closing activities using the Super key causes the mouse to stop working

### ISSUE THREAD

**Issue by umnikos** [paperwm/PaperWM#354]
OS: Debian GNU/Linux 10 (buster) x86_64
Resolution: 1366x768
DE: GNOME 3.30.2
WM: GNOME Shell
PaperWM version: 38.0

Steps to reproduce:
1. Open 2 windows in a workspace and make them maximum width (Super+F)
2. Focus on the first window
3. Lock the computer (with Super+L)
4. Unlock the computer
5. Press the Super key twice. That will open and close the activities menu
6. Use the mouse to switch to the second window by left clicking
7. You can still move the mouse but left and right click do nothing. The keyboard still works so the system hasn't frozen.
8. Press the Super key once more to fix. That opens and closes the activities menu quickly. Executing a PaperWM keyboard shortcut also works.

The lock+unlock of the computer is only necessary if you've recently switched workspaces.

For anyone else experiencing the problem often, Super+PgDn and then Super+PgUp once after logging in prevents it from happening until you lock and unlock your computer.

**Comment by umnikos** [comment]
Edit: The two windows need to be at maximum width (Super+F).

For anyone experiencing the problem often, Super+PgDn and then Super+PgUp once after logging in prevents it from happening until you lock and unlock your computer.

**Comment by umnikos** [comment]
This bug still persists. Has anyone looked into it?

**Comment by jtaala** [comment]
Hey @umnikos - having a look at this.  I can't reproduce this on the latest PaperWM `develop` branch (note I'm on Gnome 43.4).

You mentioned locking/unlocking the screen, so #477 may have resolved this (see info on FIX2) - basically, #477 fixes a bug where on lock/unlock PaperWM can go through many fast enable/disable cycles (which can cause a bunch of weird behaviour).

Let me know if you still use PaperWM and if this is still an issue.

Planning on closing this (as I can't reproduce) in a month or so, unless others can reproduce or confirm if it's still an issue.

**Comment by umnikos** [comment]
I think it has indeed fixed itself as I also cannot reproduce it. I'll close the issue
