### ISSUE TITLE
[Feature request] Touch gestures for scrolling through workspace?

### ISSUE THREAD

**Issue by Thesola10** [paperwm/PaperWM#363]
First off, awesome extension, I use it everyday and have grown addicted to its workflow! I'm using a convertible laptop, and was wondering if it was possible to add a way to scroll through windows in a workspace with touch events?

The way I'd envision it would be to handle scrolling on the topbar, or along the top and bottom edges of the screen (I use Dash to Panel).

I'm not well-versed enough in GJS to really help, sorry

**Comment by hedning** [comment]
Yes, this is possible, and I'd be happy to take PR and help people out with the code, but it won't be something I'll prioritize spending time on myself (there's a quite a lot of other stuff that needs fixing/merging etc.).

Some pointers to the code.

[gesture.js](https://github.com/paperwm/PaperWM/blob/develop/gestures.js) is the current implementation of touchpad scrolling. There's a bit ad-hoc code there to make things look right and such. But it might be straightforward to mostly copy the functionality and hook it up to the touch action api. An example of how the touch api is used can be found for instance in gnome-shell's [EdgeDragAction](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/edgeDragAction.js).

To get something up and running fast I think adapting the `update` and `done` functions in `gesture.js` to `vfunc_gesture_progress` and `vfunc_gesture_end` might work (you'll also need to put some start conditions in `vfunc_gesture_prepare`).

(Worth noting while I have a laptop with a touchscreen, it's currently out of service so testing out a PR might be a troublesome for me).

**Comment by Thesola10** [comment]
I did it!! over at [my fork](https://github.com/Thesola10/PaperWM)

**Comment by Thesola10** [comment]
uh, closed by #643
