### ISSUE TITLE
"Use default GNOME Shell background" setting doesn't work with GNOME 3.38 default wallpaper

### ISSUE THREAD

**Issue by ngkz** [paperwm/PaperWM#365]
When the wallpaper is GNOME 3.38 default one, "Use default GNOME Shell background" setting does not affect. PaperWM shows a flat color instead of the wallpaper.
It shows the wallpaper correctly when I select non-default wallpaper.
I'm using latest PaperWM, latest Arch Linux, and GNOME 3.38.3.

**Comment by johnfraney** [comment]
I've noticed this, too, and for me it only affects "live" backgrounds that change depending on the time of day, like this one:

![Screenshot from 2021-01-17 18-47-26](https://user-images.githubusercontent.com/1728528/104858311-8285bf80-58f4-11eb-8082-c50277bebf38.png)

For static images it works well.

**Comment by hedning** [comment]
Ah, that makes sense, we haven't implemented support for animated backgrounds.

**Comment by steelcowboy** [comment]
Same behavior on Ubuntu 20.10, GNOME 3.38.1. Going into the Activities Overview shows my background (the default Groovy Gorilla), but it disappears when I go to a workspace.

Can also confirm that I see this on my work computer, Fedora 33

**Comment by johnmee** [comment]
Wierd.  I use "variety" to change the background daily.  All was fine.  It worked and this was not an issue for me.  Not sure what I did, or why I was so lucky, but it stopped working just in the past week.  The live wallpaper shows in the Overview mode, but not on the workspace.

I may have done a git pull from the develop branch.  Tried switching back to gnome-42 branch and much gnome-shell resetting, and playing around in paperwm/gnome/variety preferences but no finding my way back (yet).

**Comment by johnmee** [comment]
I may have worked this one out...

Ubuntu, sets their own background which interferes?  Turn that off.

`gsettings set com.canonical.unity.desktop.background draw-background false`

**Comment by jtaala** [comment]
Live/animated wallpaper support has been added for Gnome 42-45 with #637 (which is now merged into `release` and `gnome-44` branches.

Closing this ticket now.

Note: support hasn't be backported for previous version of gnome shell (e.g. < 42, including gnome 3 etc.).  If anyone uses these version of gnome, and is interested in porting support for animated/live wallpappers, let me know.
