### ISSUE TITLE
Cancelling super+tab with ESC sometimes leaves all windows "dim"

### ISSUE THREAD

**Issue by kamalmarhubi** [paperwm/PaperWM#366]
I don't have a clear repro for this. But I've seen it happen with just these two steps:
- super+tab a few times
- ESC

It happens maybe every other week or so.

All windows will be dimmed out as if they are not the window selected by super+tab. There's no way to get them to go back to normal; in particular these don't help:
- no amount of super+tab or anything
- disabling paperwm and re-enabling

The only fix I have is to log out and log back in, which is not ideal.

The attached clip is not a repro, but just to illustrate the "dimming" I mean.

https://user-images.githubusercontent.com/50936/106002484-31f22d00-607f-11eb-8e89-8faa668d6a64.mp4

This is my current version info, though this has been happening for many months across many versions:
```
$ cd ~/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/
$ git describe --tags
38.1-5-g4f5b931
$ git show --no-patch HEAD
commit 4f5b9319ed7d3619ae6164784c6fd565a0fc473a
Author: mrspikeroot <61438667+mrspikeroot@users.noreply.github.com>
Date:   Wed Dec 23 19:06:27 2020 -0500

    Add "StackUnstack" action in Examples. (#358)
    
    If the focused window is not stacked, it stacks it at the bottom of an adjacent column
    If the focused window is stacked, it moves it out into its own column.
    
    Co-authored-by: Michael Root <michael.root@rjginc.com>
```

**Comment by hedning** [comment]
Not sure if this actually fixes the issue, but c0a1cee601ca1fe0136a3861133fc0b16f4cad24 should make the code a bit more robust and hopefully makes sure the dimming goes away.

**Comment by kamalmarhubi** [comment]
Meant to say thanks and that I think this may have fixed it! Since it's pretty non-deterministic, I'll follow up in another month or so to close the issue :-)

**Comment by jtaala** [comment]
Closing based on last comment (more than two years ago) suggesting this was fixed.
