### ISSUE TITLE
[Feature Request] Allow Drag & Drop to work with Chrome

### ISSUE THREAD

**Issue by jwest75674** [paperwm/PaperWM#369]
Thanks for the awesome window manager!

One issue that took me too long to want to admit, was accidentally drag & dropping chrome windows, only to not have a method to get out of DnD(?) mode, until recently reading through the changelogs/release notes.

I believe that the issue stems from the fact that Chrome chooses to hide the system title bars and borders.

I am unsure if there is a solution, but allowing floating chrome windows to pop back into the tiling would make for a really great user experience with Chrome. As well, showing the system titlebars looks pretty gaudy in chrome, but for other users, that is a workaround.

Perhaps there is a simply settings mod that can be applied somewhere to workaround this?

**Comment by hedning** [comment]
Cheers: )There's `Ctrl+Super+click`, but it might not work on the whole window on X11. `Ctrl+Super+Escape` will tile most floating windows. And `Super+middle_click` will also give you the gnome titlebar menu where you can toggle «scratch» mode.

We can't really work around how an application reacts/handles clicking on a client side titlebar unfortunately.

**Comment by jwest75674** [comment]
Quite some time has passed and I wanted to add a few more notes. 

Firstly, glad to see PaperWM development is back on track, great work folks.


I've been using the right-click titlebar --> "Scratch" context menu item with relatively good success since I opened this ticket.
I've recently been looking more closely at my everyday behaviours, and I realize that there is only one time when I need to use that solution, which appears to be a combined issue:

When I am trying to go from one tab to another in browsers, or when an application I am using has an application titlebar underneath the standard system titlebar, I am sometimes miss-clicking the system titlebar, instead of the menu/tab I am aiming for.

While, this is human error at it's finest, the resulting functionality seems like it may be a bug, or at least is very strange.

When I am clicking and dragging a titlebar, the window becomes stuck to my mouse, even upon release of the mouse-click.
If I then move the mouse+stuck-window to a new screen, the window sometimes becomes a scratch window, no longer playing by  PaperWM rules. 

If I want to release the window back to it's proper, previous state, I need to click the very top bar (not sure what this one is called, with the date+time and wifi settings, etc.)

This whole window stuck to mouse, even when releasing mouse-click functionality seems very strange to me, and upon looking at my behaviour more, it's clear I've just been living with it, instead of letting you folks know!

1) I wonder if it is possible to add a PaperWM preferences/settings option to disable the whole "drag a title bar to move a window" functionality that is standard?
2) Otherwise, having windows release upon mouse-left-click-up, would be in line with expected behaviour
3) Similarly, a setting so scratch window functionality can simply be disabled altogether would solve the other moving part of this odd behavior

**Comment by jtaala** [comment]
Hey @jwest75674, if you're still using PaperWM, can you let me know if you're still seeing the "stuck to mouse" issue in a recent version of PaperWM (e.g. latest `release` or `develop` branch or an install via https://extensions.gnome.org/extension/6099/paperwm/.

**Comment by jwest75674** [comment]
Not seeing the `stuck to mouse` issue anymore, at this point.

Still can't drag chrome windows without them switching to Scratch, but I assume that's just a chrome thing(?)

**Comment by jtaala** [comment]
> Still can't drag chrome windows without them switching to Scratch, but I assume that's just a chrome thing(?)

Does alt-dragging work? (hold `alt` down and click-drag anywhere in the window to move the window around).

**Comment by jtaala** [comment]
https://unix.stackexchange.com/questions/589662/in-gnome-how-to-move-and-resize-window-using-one-hotkey-like-xfce-alt-or-elem

**Comment by jtaala** [comment]
Or did you mean dragging tabs from one window to another?

**Comment by jtaala** [comment]
I think I'm not understanding the issue here.  I can drag/drop chrome windows fine - when dragging by titlebar, if you drag over an tiling insert area (e.g. between windows etc.) then dropping will re-tile the chrome window (like any other window).

Otherwise, you can use the keyboard shortcut to toggle the chrome window (like any other window) between scratch/tiling (default keybind for `Attach/detach the active window into the scratch layer` is `Ctrl + Super + Escape`.

Is that what you're referring to here?  Or am I misinterpreting the issue you're describing above?

**Comment by jtaala** [comment]
Closing as no response for more than a month (and I can't reproduce this with chrome).
