### ISSUE TITLE
Stopped working after upgrade to 3.38.3

### ISSUE THREAD

**Issue by tflori** [paperwm/PaperWM#370]
Since the update to gnome shell 3.38.3 I get the following error:

```
PaperWM
Error occured in paperwm startup:

metaWindow.clone is undefined

makeScratch@/home/iras/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/scratch.js:68:9
addAll/<@/home/iras/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:1210:25
addAll@/home/iras/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:1207:17
init@/home/iras/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:201:14
init/<@/home/iras/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:1340:37
init@/home/iras/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:1340:14
initWorkspaces@/home/iras/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2235:20
```

PaperWM is a git clone and up to date. I'm running X11 on Manjaro with gnome 3.38.4 and gnome-shell 3.38.3

btw.: can someone explain why gnome-shell is still 3.38.3 and gnome itself is 3.38.4?

**Comment by hedning** [comment]
That's no good :/ I'm not on 3.38.3 yet, but will try to get the time to get a build running and fixing the problem.

**Comment by tflori** [comment]
it is somewhat strange.. I get this error also in gnome-shell 3.38.2 after it crashed. It seems to rebuild the windows and the original clone gets removed or something. I've now downgraded also gnome-desktop to 3.38.2 - hopefully that helps.

I always thought that gnome-desktop and gnome-shell are updated together and the versions have to match.. I also don't know what is providing what: is gnome-desktop providing the engine and gnome-shell is just the basic UI?

**Comment by liquidev** [comment]
@tflori Just throwing an idea here, but gnome-desktop might be your distribution's meta-package for installing all the relevant GNOME packages.

**Comment by tflori** [comment]
Might be but why is the info then showing the version of the meta package?

But in 3.38.2 when it crashes the extension is still working.

**Comment by jtaala** [comment]
Is this still an issue for users on gnome 3.38?

Just asking since this issue is quite old and we have some users still on gnome-3.38 (using the `gnome-3.38` branch successfully).

Let me know if users are still seeing this.  Planning on closing this issue in a month or so unless it's still affecting people.

**Comment by jtaala** [comment]
Closing as no responses (which were resquested)  more than a month a go.
