### ISSUE TITLE
[Feature request] Option to disable "Natural Scrolling" for touchpad gestures

### ISSUE THREAD

**Issue by wraithm** [paperwm/PaperWM#371]
Right now when I three-finger scroll in Wayland, moving my hand to the right makes the windows move to the right as if dragging the proverbial paper. As in, scrolling moves the content, not the view. In Gnome's mouse/trackpad settings, this is referred to as "Natural Scrolling". One can disable "Natural Scrolling" such that two-finger scrolling results in moving the view, not the content.

With respect to PaperWM, I would like to be able to scroll in the opposite direction, where scrolling moves the view, not the content. As in, unnatural scrolling: When my hand moves to the right, I'd like the windows to move to the left. Ideally, this would be true for both horizontal and vertical scrolling.

I don't know, but that's what's intuitive for me. :shrug: I imagine that there are several others who feel the same intuition. Like using an inverted joystick.

I'd be happy to take a crack at adding this feature! I took a look at gestures.js, and it basically looked like I could just use a simple negation on a bool for the direction. Basically, it'd be a 1-2 line change in gestures.js, but the unknown for me would be threading through the boolean toggle to the extension settings menu. I might just need some assistance on messing with the settings.ui menu. I'm not terribly familiar with how that all works.

Thoughts?

**Comment by hedning** [comment]
Does it not work to turn off touchpad natural scrolling in gnome settings?

If not, I'd consider that a bug, and happily merge a PR that makes paperwm respect the «global» touchpad setting. Having a toggle just for PaperWM gestures however doesn't make much sense to me.

**Comment by wraithm** [comment]
Great idea!

It does not respect the global touchpad setting. When looking at the code, it doesn't seem to query the global setting.

As I said, I'd be happy to add this and test it out. If you have an example of querying the global Gnome settings, that'd give me a great head start.

**Comment by wraithm** [comment]
Though, I could imagine that there's a group of people who like natural scrolling for PaperWM and then unnatural scrolling for their browser and such. Maybe it's best to create a setting that defaults to the Gnome Natural Scroll setting, and then it can be overridden? Just a thought.

**Comment by wraithm** [comment]
Makes sense. I'll give it a shot. I'll see what I come up with. Thanks!
