### ISSUE TITLE
Custom keyboard shortcuts defined in GNOME Settings don't seem to be working

### ISSUE THREAD

**Issue by liquidev** [paperwm/PaperWM#374]
I defined a keyboard shortcut `<Super><Return>` for opening a Terminal window, but it doesn't seem to be functioning.

![image](https://user-images.githubusercontent.com/16415678/110340689-d164f100-8029-11eb-9ca1-d881e37074c5.png)

Is this due to PaperWM overriding default GNOME shortcuts? If so, how can I define a shortcut for opening an arbitrary command?

**Comment by olejorgenb** [comment]
Yes, `Super+Return` is bound to open a new window of the active application in PaperWM. You can unbind this paperwm action in the extension preference GUI. You might have to restart gnome to free the binding.

**Comment by liquidev** [comment]
Ah, I didn't notice it when looking through the keybinding list. Thanks!
