### ISSUE TITLE
paperwm alternatives for mac osx?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [paperwm/PaperWM#379]
I love using PaperWM on Gnome on my private machine, but for work I am presently running OSX.
This makes me wonder: what OSX-compatible window manager would be best for someone who likes PaperWM?
I realize this isn't so much an 'issue' for the current repository, but figured this might be the best place to find answers...

**Comment by rayjanoka** [comment]
https://github.com/ianyh/Amethyst is what I used to use

**Comment by polyjitter** [comment]
From what I know, PaperWM is the only currently functional and still developed scrolling tiling wm. There are many tiling WMs for macOS and Windows alike, but they do not have scrolling functionality. It is certainly a space in much need of expansion.

**Comment by magthe** [comment]
I was hoping to find at least one implementation of a scrolling+tiling WM for Wayland, but everyone is literally stuck in a frame :disappointed:

**Comment by olejorgenb** [comment]
> I was hoping to find at least one implementation of a scrolling+tiling WM for Wayland, but everyone is literally stuck in a frame 😞

There's Cardbord WM :) Not sure how stable/complete yet. https://tudorr.ro/blog/technical/2021/01/26/the-wayland-experience/

**Comment by mogenson** [comment]
I made this for MacOS: https://github.com/mogenson/PaperWM.spoon
