### ISSUE TITLE
[Improvement] Send mouse cursor to window that get focus

### ISSUE THREAD

**Issue by bilboquet** [paperwm/PaperWM#381]
Hello

First of all a really big thanks for this very useful piece of code, I love PaperWM.

Now some comments about this issue.
I'm using PaperWM with sloppy focus, as other have already said, it sometimes leads to some weird behavior (it's often the case with sloppy focus, it's not specific to PaperWM).
My guess it that any weird behavior I face with sloppy focus and PaperWM, due to the tilling nature of PaperWM, can be simply solved by sending the mouse cursor to the window receiving the focus.

I wish I could propose a patch, but I don't really know were to start (I've never dig into gnome extension).
Could you point me out where to look? (or tell me if I'm wrong on my guess).

Regards,

**Comment by jgoerzen** [comment]
I also am experiencing issues with non-click-to-focus.  Basically whenever I use Super-, or Super-. to change focus in PaperWM, focus reverts to wherever the mouse pointer is.  This solution (moving the mouse to that window) is acceptable, but it wouldn't have to be; simply letting that window keep focus (if possible) would also work.

**Comment by bilboquet** [comment]
Sorry I've open nearly the same here: #436
Latest one gives a solution, closing this one
