### ISSUE TITLE
[Feature request] Handle bottom panel

### ISSUE THREAD

**Issue by Thesola10** [paperwm/PaperWM#382]
I want to use Dash to Panel with PaperWM, and so far it works just fine (well, it would if GNOME 40 hadn't broken everything :p) with one caveat: PaperWM still assumes that the panel is on top, and forces a good amount of wasted space above the windows to leave room for a nonexistent panel.

Would it be possible to detect the panel edge and update margins to fit, or at least allow the user to punch in negative values for the top margin?

**Comment by jtaala** [comment]
Recent versions of PaperWM now work well in dash-to-panel (including if a panel is at the bottom).  Tip: if using dash-to-panel you likely will want to turn off the `Window position bar` in PaperWM settings general tab.

If you use bottom position, on opening a new window (first time after changing to bottom setting) PaperWM should readjust and remove the gap at the top.

Closing this but let me know if there's still issues here.
