### ISSUE TITLE
Overlapping Workspace name on hot corner

### ISSUE THREAD

**Issue by nsrCodes** [paperwm/PaperWM#384]
Recently updated gnome and other drivers on POP_OS. I noticed about a day later that on the top right-hand corner the name of the workspace was appearing twice and overlapping in a weird way

![Screenshot from 2021-05-19 13-37-25](https://user-images.githubusercontent.com/57226514/118778629-eb337780-b8a7-11eb-9980-f3bca6fd02ba.png)
![Screenshot from 2021-05-19 13-37-02](https://user-images.githubusercontent.com/57226514/118778635-ebcc0e00-b8a7-11eb-9d34-d889ca298a14.png)

But one of them disappears when I press the super key
![Screenshot from 2021-05-19 13-41-07](https://user-images.githubusercontent.com/57226514/118778615-e8388700-b8a7-11eb-9c20-dc188bb07b3a.png)

**Comment by jtaala** [comment]
Hey all, I realise this is a older one but am wondering if this is an issue for others?

I haven't seen this in a good while and recently went through the topbar.js code (when working on #482).

Let me know if anyone is still impacted by this, otherwise will close this issue in a month or so.

**Comment by jtaala** [comment]
Closing as no responses (which were resquested)  more than a month a go.
