### ISSUE TITLE
The Prior Work reference in README.MD links to a gambling site...

### ISSUE THREAD

**Issue by mrsean2k** [paperwm/PaperWM#386]
... but the Wikipedia entry still seems wholsome enough

https://en.m.wikipedia.org/wiki/Multi-touch#10/GUI

**Comment by gcoda** [comment]
vimeo video still up
https://vimeo.com/6712657

**Comment by hedning** [comment]
Should be fixed with https://github.com/paperwm/PaperWM/pull/383
