### ISSUE TITLE
Default Gnome snapping outline appears

### ISSUE THREAD

**Issue by njanne19** [paperwm/PaperWM#390]
Hi all, 

New to PaperWM, so I apologize if any formatting is incorrect. I have the tool installed, and when the windows are snapped correctly to PaperWM, Gnome still displays the window "snapping outline" is the best way I can describe it. I am looking to disable this so I can use PaperWM exclusively, although this is more of an aesthetic issue. Screenshot provided. (White outline around window)

![Screenshot from 2021-08-31 15-20-06](https://user-images.githubusercontent.com/24515342/131563091-3cec9868-c05a-446e-8bd9-cacbdbb62ef3.png)

**Comment by samesdat** [comment]
I think this is intended - the outline shows your active window. I think you can disable this in settings (if they are working again). I can't try it because I uninstalled paperWM after it broke with the update to GNOME 40 and didn't work for weeks/month ...

**Comment by jtaala** [comment]
Yes, this sounds like the selected window indicator / highlight.

You can style this as wanted by overriding with preferred `css`, e.g. add a `user.css` file to `~/.config/paperwm` folder with the following contents:

```css
.paperwm-selection {
    background-color: transparent;
    border-color: transparent;
}
```
or add your own preferred color/style.

**Comment by jtaala** [comment]
Let me know if that's not what you meant, otherwise will close this issue in a month or so.

**Comment by jtaala** [comment]
Closing as no responses (which were resquested)  more than a month a go.
