### ISSUE TITLE
Window spontaneously moves across monitors

### ISSUE THREAD

**Issue by jvns** [paperwm/PaperWM#391]
Here's a behaviour I've been observing with multiple monitors:

1. I open a new window (let's say `evince`) on Monitor 1 as a tiling window
2. I switch back to my browser
3. I switch back to the new `evince`window
4. The `evince` window suddenly moves (as a floating window) to Monitor 2

This behaviour seems to be a bit nondeterministic -- sometimes I need to move back and forth from the new window before it happens.

Also, I think I can stop it from happening if I drag the new window back to Monitor 1 and click "maximize" (the "maximize" icon in the corner, not the PaperWM full screen). 

I searched for a related issue but didn't find one, happy to be redirected :)

**Comment by jtaala** [comment]
Hey @jvns,

I note this issue is very old and likely no longer valid?  I can't currently reproduce this.

Feel free to drop a comment of it's still an issue.

**Comment by jvns** [comment]
Fine by me to close, I'm not using paperwm right now so I can't reproduce either.

**Comment by smichel17** [comment]
Might be a duplicate of #469 as well? Or maybe this was only for a single window?
