### ISSUE TITLE
Command to open as/change to scratch buffer

### ISSUE THREAD

**Issue by Sabicool** [paperwm/PaperWM#395]
I have a keybinding set to open a new Emacs window with org-capture. It runs this command `sh /home/usr/.emacs.d/bin/org-capture` which directs it to a shell script. Is there any commands to make this org capture buffer appear as a scratch buffer instead of to the right of the currently active window?

I am aware that you can make certain window classes open as a scratch buffer, but I don't wan't Emacs to always open as a scratch buffer. I would like to know if there is anything I can do in shell script to make it so that the window is set to a scratch buffer.

I hope that makes sense.

**Comment by gavr123456789** [comment]
What GNOME version u using?

**Comment by Sabicool** [comment]
I am using gnome version 3.36.8 on Ubuntu 20.04.3 LTS

**Comment by jtaala** [comment]
Hmm, noting that with winprops (see #463 for this being integrated into PaperWM settings ui) - if we can isolate on a window `wm_class` or window `title` we can have them added to the scratch layer on window create.

If this is still an issue for you, is there a way to set the window `title` of your window that's created?  If so, could then a winprop for it to auto add it to the scratch layer.

**Comment by jtaala** [comment]
Closing as no response.
