### ISSUE TITLE
Install fails on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by mtgcyoi** [paperwm/PaperWM#398]
Trying to install on OpenSUSE Tumbleweed fails:

`gareth@cube-server ~/PaperWM (master)> ./install.sh
ln: failed to create symbolic link '/home/gareth/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org': File exists

PaperWM runs best with some Gnome Shell settings changed:
 workspaces-only-on-primary off: Required for working multi-monitor support
 edge-tiling off: Natively tiled windows doesn't work in PaperWM
 attach-modal-dialogs off: Attached modal dialogs can cause visual glitching

Use recommended settings (generates a backup) [Y/n]: y
restore-gnome-shell-settings-2022-01-21.sh exists

Enable the extension [Y/n]? y
Trying to load and enable extension:
something went wrong:
(false, '')
Success`

**Comment by paradajz** [comment]
just do `rm /home/gareth/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org` and try again

**Comment by LovesTha** [comment]
I'm not terribly surprised that trying again gets the same result.

How do I get more information about what is going wrong?

**Comment by LovesTha** [comment]
(ooops, I'm the OP, I just logged in to an account I rarely use, this is my normal account)

**Comment by LovesTha** [comment]
No hints on steps to debug why the installer is failing?

**Comment by gwenzek** [comment]
the installation also fails for me on Fedora. I don't even have an error message. The script just return with a failed exit code. Is this only supported on Ubuntu ? Why isn't it available on https://extensions.gnome.org/ ?

**Comment by MerlinR** [comment]
Same issue on Debian 11.
```
Trying to load and enable extension:
something went wrong:
(false, '')
Success
```

**Comment by jamestwebber** [comment]
I'm getting the same result (`(false, '')`) but I just updated to Ubuntu 22.04 and I'm installing with the `gnome-42` branch (gnome version 42.4).

**Comment by mitchweaver** [comment]
Seeing this same issue on Fedora 36, reproducible on a clean install

**Comment by azmeuk** [comment]
I can confirm this on Archlinux with GNOME 42.

**Comment by aliaksandrsen** [comment]
I can confirm this on DEBIAN bookworm with GNOME 43.

**Comment by savy-91** [comment]
I was able to install it today on Tumbleweed following these instructions https://github.com/paperwm/PaperWM/issues/425#issuecomment-1401509135

**Comment by jtaala** [comment]
Original issue resolve and I note that #472 improves the misunderstanding re failing to auto-enable.
