### ISSUE TITLE
How to force a clean restart when paperWM freezes

### ISSUE THREAD

**Issue by rambalachandran** [paperwm/PaperWM#399]
I have been using PaperWM on Ubuntu 20.04 in HP Envy and it has been great for most part. However, occasionally it does freeze and I'm not sure how to kill the process or force restart it. At the moment, I go to login page and restart the computer. I tried to search for the process to kill, but trying
`ps aux | grep paper`
did not turn anything and trying to search for `gnome` returns multiple process.

_What is the clean way to restart or kill paperWM (preferably through TTYs) without having to restar?._

**Comment by johnmee** [comment]
Restart gnome with an "Alt-F2" then "r".  Your mileage will depend on whether things are not too messed up to get the run command dialog (alt-f2).

**Comment by smichel17** [comment]
Gnome shell extensions work by monkey patching gnome-shell (modifying the running code); there's no extensions api or anything like that; the patching is done by the extension itself. When you disable an extension, that's *also* done by the extension itself (extensions are supposed to save the previous state of anything they change and set it back when they're disabled).

This makes it difficult to cleanly disable an extension, especially when you have multiple extensions touching the same code. If an extension is bugged to the point where it can't disable itself, the only clean way to disable it is to restart gnome-shell. The Alt-F2 prompt is probably the easiest way (if you're on X); you can also log out and in. If it's well and truly frozen, you may need to kill `gnome-shell` through a TTY. A web search might find other ways to restart gnome-shell.
