### ISSUE TITLE
Handling of transients belonging to managed windows (on focus)

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/PaperWM#40]
Transient windows are filtered out in `add_handler` since it's almost always desirable to let them float. 

A consequence is that nothing is `ensure_viewport`'ed when such transient windows gain focus. The transient window **is** brought into the viewport by gnome-shell itself, but the parent window does not follow.

A simple way to test this is to open a transient window, go to another window and focus the transient using alt-tab.

This works ok and might even be useful sometimes (if the parent is a huge window and you want to see something else when working in the transient) but it felt a bit confusing at first.

One reasonable policy is that the transients should always positioned relative to the parent (possibly with an option to detach). Note that atm. it's not possible to move the transient - dragging the titlebar moves the both the parent and transient.

Another issue is that transients are not animated during left/right navigation (eg. when navigating to the parent the transient makes a huge jump on animation end)

![image](https://user-images.githubusercontent.com/72201/34908446-fba581fc-f88f-11e7-8efe-bc833d7715fb.png)

**Comment by hedning** [comment]
The above commits fixes the main issues here, opting to keep transient windows anchored to the monitor.
