### ISSUE TITLE
Not taking Effect in Ubuntu

### ISSUE THREAD

**Issue by yhoungdev** [paperwm/PaperWM#400]
no effect in ubuntu running on X11

**Comment by johnmee** [comment]
It does work. Just a matter of persistence :-/  

I'm on ubuntu 21.10 impish, with gnome 40.4.0, and paperwm from git... oh, been a while, in writing this discovering that I'm on a branch called "next-release"; I must have done that last I dug into this, maybe 12 months ago!?

**Comment by jtaala** [comment]
Closing this as it's likely old information.  Please let us know if this is still an issue and we can reopne.
