### ISSUE TITLE
Cannot drag Firefox tabs between *workspaces* (between windows on the same workspace it works fine)

### ISSUE THREAD

**Issue by alexpdp7** [paperwm/PaperWM#401]
Hi,

I'm on `develop` 7331b44807f94d8a2d6adac6e75b0e32b2ad8caf , and I cannot drag Firefox tabs between windows in different workspaces (i.e. from one display to another).

I can drag tabs from Firefox within the same display.

I'm on RHEL 8.5, Gnome 3.32.2.

Cheers,

Álex

p.s.: I also have some cosmetic issues which are just small papercuts. I can report them in separate issues if there's interest- happy to debug, etc. (when unlocking my screen, I have tons of PaperWM notification errors, after suspending my workspaces "switch" displays, some small bugs). However I realize that I'm running an ancient Gnome version and it's probably not worth fixing them- I'm just reporting this one because it *does* affect my workflow, although I can live with it and stick with PaperWM because otherwise it's AWESOME.

**Comment by johnmee** [comment]
Firefox seems to do some funky things with the window framing.  Personally I have trouble when it gets onto the scratch layer and there seems to be no way to get it off the scratch layer-using the mouse. Keyboard shortcuts are your friend...
The keyboard shortcut GUI+CTL+ESC does the trick to toggle the window on and off the scratch layer.

The keyboard shortcut you seek, to shift it to another workspace, is probably GUI+SHIFT+arrowkey.

**Comment by alexpdp7** [comment]
Yeah, after using this consistently for a good while, it seems that most issues seem to be Firefox-specific. I have the same recurrent issues you have with Firefox windows doing odd things- I have some issues using the scratch shortcuts, but the "window menu" (alt+space) seems to work pretty well for unborking things.

I use win+shift+[ctrl]+arrows to move between displays and carry windows around. However, normally I end up "moving" tabs by copying and pasting URLs. That's a decent workaround, but I dunno- maybe this issue can remain open- or at least maybe add some "known issues" to the main README? Something like:

> Firefox seems to misbehave under PaperWM. The following issues are known:
>
> * Tabs cannot be dragged between Firefox windows on different displays
> * Firefox windows can move spontaneously into the scratch layer. Use the window menu (<kbd>Alt</kbd><kbd>Space</kbd>) or <kbd>Super</kbd><kbd>Ctrl</kbd><kbd>Escape</kbd> to fix.

**Comment by jtaala** [comment]
Closing as this is fixed in #574.
