### ISSUE TITLE
this.get(...) is undefined

### ISSUE THREAD

**Issue by dimaqq** [paperwm/PaperWM#406]
```
-En PaperWM
Error occured in paperwm startup:

this.get(...) is undefined

monitorsChanged@/home/<user>/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:1360:14
init@/home/<user>/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:1337:14
initWorkspaces@/home/<user>/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:2235:20
```

![Screenshot from 2022-05-26 16-21-46](https://user-images.githubusercontent.com/662249/170439114-255b21ef-4acf-451b-a66b-245315ae0ca3.png)

**Comment by jtaala** [comment]
Can't reproduce this @dimaqq.  If this is still an issue please let us know gnome version and other details etc. and we can reopen.

**Comment by dimaqq** [comment]
no worries, given how old ago I opened it, I'm sure it's long gone.
