### ISSUE TITLE
Request for Maintainership

### ISSUE THREAD

**Issue by smichel17** [paperwm/PaperWM#407]
@hedning Will you please make me an admin of this repository, and ideally also an owner of @paperwm?

So far, the goal of the [fork](https://github.com/paperwm-community/PaperWM) has been to merge [GNOME 40+ support](https://github.com/paperwm/PaperWM/pull/396) back upstream. To that end, it has stayed a "soft" fork, meaning "bugfixes only and minimal refactoring". However, this raises the barrier to contributions and prevents collaboration on feature development, slowing momentum.

It's been roughly a year since there was any development activity here. I hope you are doing well, and are simply busy with other commitments or no longer interested in actively maintaining PaperWM ([I can relate](https://github.com/LibreShift/red-moon/issues/281)). Regardless of the reason, I think it's been long enough that the hope of getting merged back upstream is not worth the cost.

It would be ideal if development could move back to this repository instead of commencing with a hard fork. There are already many links to this repo, and open issues / history. That's why I am asking for maintainership.

I also understand that you may not want to turn control of the repo over to some random person. That's why ***I*** am asking for maintainership; I think I have enough of a track record with FLOSS projects to establish my responsibility: I am a maintainer of [Red Moon](https://github.com/LibreShift/red-moon/graphs/contributors) and [StreetComplete](https://github.com/orgs/streetcomplete/people), and cofounder of [Snowdrift.coop](https://gitlab.com/groups/snowdrift/-/group_members).

Unfortunately, I am currently too busy to commit to maintaining the PaperWM code myself. Instead, I would facilitate adding other maintainers. I would grant them commit access, but not admin rights\*, so I could act as a failsafe if someone tried to gain control of the repo or push malware. I _could_ also act as an arbiter of which features should be included in PaperWM… only if the other maintainers want.

Thank you,
Stephen

\*If a couple years pass and you're still inactive, then I'll likely also find someone else to grant admin rights, so the same thing doesn't happen again if I disappear. Along those lines, this request still stands even if you show up again shortly— as an insurance policy to decrease the project's [bus factor](https://en.wikipedia.org/wiki/Bus_factor).

/cc @olejorgenb

**Comment by smichel17** [comment]
From experience, I know a detailed response can take a lot of effort.

- A short, bullet-point response is fine. So is just adding me.
- Also helpful: Are likely to resume maintaining PaperWM?
   [ Yes, this month || Probably, this year || Maybe, hopefully some day || Unlikely ]

**Comment by smichel17** [comment]
It's been a month; gnome 42 has introduced more breakage; and we now have a reason besides new features for breaking merge-ability— a better developer experience for the people actually doing the maintenance (https://github.com/PaperWM-community/PaperWM/pull/26). So, we are beginning the hard fork. Planning-in-progress is at https://github.com/PaperWM-community/PaperWM/discussions/27.

The projects re-merging by a simple PR is no longer possible, but @hedning if you return and are interested in collaboration, let's talk; we can probably work something out.

**Comment by Phill030** [comment]
Why don't you just make a fork and work on that one 🤨

**Comment by smichel17** [comment]
There's already a community here that knows about / uses PaperWM. The community is important because that's where potential contributors will come from. With a fork, you lose part of the community-- people who don't realize it exists (perhaps because they didn't read the posts above).

**Comment by galanonym** [comment]
@smichel17, I have managed to contact @olejorgenb and @hedning though him. Looks like they are ready to pass maintainership forward. I have sent you an e-mail with more details.

**Comment by smichel17** [comment]
Thank you! I'm quite busy at $dayjob at the moment (read: my brain is fried), but I'll follow up within a few days.

**Comment by johnmee** [comment]
Can the appropriate branch for gnome 42 be duplicated/committed here now?

**Comment by smichel17** [comment]
Alright, it's been a few more than a few days, but oh well, that's life.

To clear things up: The story of PaperWM's inactive maintainership is nothing new or surprising. They still use PaperWM, on gnome 3.38, but life is busy and it's hard to be motivated to fix frequent breakage. It's a story that is so common in [FLO](https://wiki.snowdrift.coop/about/free-libre-open#flo) software development. When I stopped actively developing Red Moon, it took me several years to accept that it was no longer a priority for me and to [announce that publicly](https://github.com/LibreShift/red-moon/issues/281#issue-771300115). I imagine that we may see @olejorgenb and @hedning around here and there, especially when they upgrade to a newer gnome version, but that the majority of development will be driven by the community.

To that point: I now have the 'maintainer' level of permissions on this repo, so I can merge PRs. As I said in the original post here, and as you can see by how long it's taken me to write this comment, I don't have time to maintain PaperWM myself. That includes code review. So, basically it will work like this: **I will merge PRs where (1) I approve of the feature being added to PaperWM, and (2) Another PaperWM contributor has left a code review with their approval.**

One exception: I will proactively merge a bunch of code for gnome 40+ support which has already been reviewed & merged over in https://github.com/PaperWM-community/PaperWM/. I will talk about my plan for getting that code merged back upstream in #376.

**Comment by smichel17** [comment]
Since I have maintainer permissions, I'll close this now.
