### ISSUE TITLE
Support GNOME 42

### ISSUE THREAD

**Issue by smichel17** [paperwm/PaperWM#409]
Most of the code to do this already exists, but it is scattered around with a messy history and needs to be consolidated so it can be merged back here.

For now, if you are on GNOME 42 and you want to use a working PaperWM, use the `gnome-42` branch of @ccope's fork: https://github.com/ccope/PaperWM/tree/gnome-42

edit: Also, you will almost certainly want to install the **[vertical overview](https://github.com/github.com/RensAlthuis/vertical-overview)** extension alongside PaperWM.

**Comment by labuut** [comment]
Hello! I've tried to use the `gnome-42` branch of @ccope's fork and it works good, but I can't change keybindings. When I tried Paperwm with `Gnome 3.38` it was a special window with keybindings which I could invoke on extension's screen. But on Gnome 42 there isn't this button and I cant adjust hotkeys in default Keyboard-section in system settings. How can I change PaperWM's hotkeys?

**Comment by hedning** [comment]
This should work (assuming the path to the schemas directory is correct):
```shell
export GSETTINGS_SCHEMA_DIR=$HOME/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/schemas 
dconf-editor /org/gnome/shell/extensions/paperwm/
```

**Comment by smichel17** [comment]
@hedning and @olejorgenb: While you're around, there's a bunch of old PRs, which I've marked as drafts: https://github.com/paperwm/PaperWM/pull/188 https://github.com/paperwm/PaperWM/pull/189 https://github.com/paperwm/PaperWM/pull/191 https://github.com/paperwm/PaperWM/pull/193 https://github.com/paperwm/PaperWM/pull/194 https://github.com/paperwm/PaperWM/pull/259

@ccope's `gnome-42` branch also includes formatting the repo with `prettier`. Once it is merged, the old PRs will have a lot of merge conflicts. I can think of 3 options here:

1. Try to merge as many of the old PRs as we can before merging the Prettier formatting.
2. Merge the gnome-42 changes and worry about fixing merge conflicts in the PRs later.
3. Drop the formatting with `prettier`, and fix up the gnome-42 changes so they will apply on top of the non-formatted repo.

I am inclined towards (1) for the smaller PRs and (2) for the larger PRs, which are likely to have merge conflicts in *any* case, but it's really a question of whether you are interested in putting any more effort into the PRs.

**Comment by hedning** [comment]
Hi, thanks for taking an active role :)

I took @ccope branch, removed the the prettier formatting and rebased it on develop here: https://github.com/hedning/PaperWM/tree/gnome-42

It looks up to date with the community edition to me, and works OK (the main annoyance is some weird fading when animating workspaces, haven't figured out where it comes from). If there's nothing missing I'll probably push it here (will probably stay on gnome 42 for a while now that I'm on the Ubuntu 22.04 LTS).

I'd also wait with prettier (especially the 4 -> 2 space thing, that will just cause trouble tbh). Would be nice to get https://github.com/paperwm/PaperWM/pull/259 into gnome-42 it really improves the DnD experience, I'll probably take a crack at it fairly soon, as I'm already missing the functionality. (Never mind, looks like the code is develop, but we don't get any `motion-event`s from the stage when navigation is activated).

**Comment by smichel17** [comment]
There's also a few commits in https://github.com/ccope/PaperWM/pull/5, which got lost on @ccope's `gnome-42` branch somehow.

Besides that, I think everything from the fork has been merged back here (except [these commits](https://github.com/paperwm/PaperWM/compare/develop...PaperWM-community:PaperWM:master), and I am pretty sure they are included on the `gnome-42` branch). So, I think I can go ahead and archive the community repo.

> Hi, thanks for taking an active role :)

You're welcome :). I'm imagining my role as something like "steward of community contributions" — I'm up to help with issue tracking, deciding what to do with PRs, the parts of code review that don't require me to learn GJS (readability & logic bugs)… basically things that separate "I wrote this tool for my own use, do what you want with it" from a FLOSS project with a community.

> I'd also wait with prettier

Sounds good

**Comment by indigoviolet** [comment]
> There's also a few commits in [ccope#5](https://github.com/ccope/PaperWM/pull/5), which got lost on @ccope's `gnome-42` branch somehow.
> 

Just calling out that these fixes added back some Settings tabs (Keybindings, Backgrounds) that have gotten lost in hedning/PaperWM/tree/gnome-42.

**Comment by kmescharikov** [comment]
Hi! I ran install.sh but nothings happen. How can i install this?
`➜  PaperWM-42 git:(gnome-42) ✗ ./install.sh 
ln: failed to create symbolic link '/home/horus/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org': File exists

PaperWM runs best with some Gnome Shell settings changed:
 workspaces-only-on-primary off: Required for working multi-monitor support
 edge-tiling off: Natively tiled windows doesn't work in PaperWM
 attach-modal-dialogs off: Attached modal dialogs can cause visual glitching

Use recommended settings (generates a backup) [Y/n]: Y
restore-gnome-shell-settings-2022-09-22.sh exists

Enable the extension [Y/n]? Y
Trying to load and enable extension:
something went wrong:
(false, '')
Success
`

**Comment by kmescharikov** [comment]
Hi! I ran install.sh and nothing happens. How can i install this?
```sh
➜  PaperWM-42 git:(gnome-42) ✗ ./install.sh

PaperWM runs best with some Gnome Shell settings changed:
 workspaces-only-on-primary off: Required for working multi-monitor support
 edge-tiling off: Natively tiled windows doesn't work in PaperWM
 attach-modal-dialogs off: Attached modal dialogs can cause visual glitching

Use recommended settings (generates a backup) [Y/n]: Y
restore-gnome-shell-settings-2022-09-22.sh exists

Enable the extension [Y/n]? Y
Trying to load and enable extension:
something went wrong:
(false, '')
Success
➜  PaperWM-42 git:(gnome-42) ✗ 
```

**Comment by smichel17** [comment]
This is documented in the README now, so I'll un-pin
