### ISSUE TITLE
Not possible to move transients of mangaged windows.

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/PaperWM#41]
When moving a transient window (of a managed window) both the parent and transient move.

Related: #40

**Comment by olejorgenb** [comment]
Seems to be two different kind of transient. One that can't be moved ("fixed transients"?) independent of the parent and one that can.

In addition, the "fixed transients" can't be moved outside the viewport at all - as opposed to the "regular" transients that behave like normal windows.

Example of a "fixed transient" is the "set language" dialog of gedit (hamburger -> Toos -> Set language)

**Comment by hedning** [comment]
This is controlled with `/org/gnome/mutter/attach-modal-dialogs`, which we include in the recommended settings script. IIRC clones aren't updated properly either when parent window actor is hidden, making it a waste of time tbh.
