### ISSUE TITLE
settings and propety_name undefined on manjaro

### ISSUE THREAD

**Issue by killi1812** [paperwm/PaperWM#410]
## I downloaded version 41.0 from aru and got both errors, and when i downloaded from github i goth just the settings error

Expected type string for argument 'property_name' but got type GObject_Object 

The settings of extension paperwm@hedning:matrix.org had an error:
TypeError: settings is undefined
Stack trace:

syncStringSetting@/usr/share/gnome-shell/extensions/paperwm@hedning:matrix.org/prefs.js:722:5
createFileChooserButton@/usr/share/gnome-shell/extensions/paperwm@hedning:matrix.org/prefs.js:700:22
createWorkspacePage@/usr/share/gnome-shell/extensions/paperwm@hedning:matrix.org/prefs.js:237:49
SettingsWidget@/usr/share/gnome-shell/extensions/paperwm@hedning:matrix.org/prefs.js:199:29
buildPrefsWidget@/usr/share/gnome-shell/extensions/paperwm@hedning:matrix.org/prefs.js:744:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by jtaala** [comment]
Hey @killi1812 - I'm also on Manjaro and am not seeing this.  Is this still an issue for you?

Let me know if you are still seeing this with the [AUR paperwm](https://aur.archlinux.org/packages/gnome-shell-extension-paperwm-git) package or the [AUR paperwm-redux](https://aur.archlinux.org/packages/gnome-shell-extension-paperwm-redux-git) fork package.

**Comment by jtaala** [comment]
Closing now as haven't heard back.  @killi1812, let us know if this is still an issue and we can reopen.
