### ISSUE TITLE
Write patch notes for 38.2 release

### ISSUE THREAD

**Issue by smichel17** [paperwm/PaperWM#416]
I tagged the last commit which supports gnome 38 and earlier: https://github.com/paperwm/PaperWM/releases/tag/38.2

It would be nice to make a release page for it, with a changelog. Here's the commits: https://github.com/paperwm/PaperWM/compare/38.1...38.2, all that's needed is to look at them, figure out what changed, and summarize in human-readable bullet points. Post the text here and I'll create the github release page for it. Thanks!

**Comment by jtaala** [comment]
Done.  See https://github.com/paperwm/PaperWM/releases/tag/38.2
