### ISSUE TITLE
Support GNOME 43

### ISSUE THREAD

**Issue by paradajz** [paperwm/PaperWM#419]
Actually, GNOME 43 and PaperWM work fine once "43" version is added to "shell-version" in `metadata.json`:

```
  "shell-version": ["42", "43"],
```

I haven't noticed any issues for now but will report here if I find some.

**Comment by johnmee** [comment]
@paradajz  From which branch?

**Comment by paradajz** [comment]
develop

**Comment by pixL404** [comment]
can confirm, changing the line inside metadata.json to `"shell-version": ["42", "43"],` and running the install.sh script works flawless on Gnome 43

**Comment by lediur** [comment]
also can confirm that this is a quick workaround to get paperwm working again

~~I did notice an issue that sometimes appears on workspaces with many windows that seems new to Gnome 43. After a while, using keyboard shortcuts to resize window width causes the entire set of windows to scroll horizontally during the resize, not just the windows to the right of the resizing window. This causes the whole monitor full of windows to move, which makes it somewhat disorienting to use.~~

~~I noticed that using the resizing shortcuts when in the "workspace change" view (holding super while moving between workspaces) somehow fixes this issue (at least temporarily).~~

Moved to new issue https://github.com/paperwm/PaperWM/issues/424

**Comment by smichel17** [comment]
> seems new to Gnome 43

I've experienced it on Gnome 42. Could you open a new issue for it?

**Comment by gombosg** [comment]
I think this was resolved by #438. Newly experienced GNOME 43-related bugs can be reported separately.
