### ISSUE TITLE
Moving back into a monitor messes up scaling if topbar follows monitor focus

### ISSUE THREAD

**Issue by alexpdp7** [paperwm/PaperWM#426]
If I move the pointer to a second display, then I come back, all the windows in that screen resize oddly, and part of their title bar ends up behind the Gnome top bar.

If I hit meta+f twice, to toggle full size and go back to the original size, things go back to normal.

**Comment by alexpdp7** [comment]
This is solved by disabling "make topbar follow monitor focus".

**Comment by smichel17** [comment]
I would consider that a workaround, not solved.

**Comment by hansbogert** [comment]
> This is solved by disabling "make topbar follow monitor focus".

just what i need I think, but where can you find this option?

/update

Nvm, this was a setting of PaperWM itself, I thought it was a conflicting gnome-shell setting and therefore couldn't find it.

**Comment by jtaala** [comment]
Closing due to #544.
