### ISSUE TITLE
PaperWM on Wayland has visual errors when using "Rounded Window Corners" extension.

### ISSUE THREAD

**Issue by jonseppanen** [paperwm/PaperWM#431]
This is the extension: https://extensions.gnome.org/extension/5237/rounded-window-corners/

Does not occur in Xorg.

**Comment by smichel17** [comment]
Could you add some more information what what the "visual errors" look like? A screenshot/screen recording would be ideal

**Comment by jonseppanen** [comment]
![Visual Error](https://user-images.githubusercontent.com/10136068/198834518-1c863fde-e944-4c7a-a5ce-1166dc16dc54.png)
These strange outlines appear around all libadwaita apps on wayland, but not xorg. Also on firefox, which does not appear to libadwaita.

**Comment by LinuxSBC** [comment]
I am experiencing the same issues. This is what the problem looks like on Firefox:
![image](https://user-images.githubusercontent.com/18235310/216803879-389edcd2-a834-4ae2-8f2e-6200269fc562.png)
The left and center windows are Firefox, while the right window is something different (Extensions Manager). As you can see, if a Firefox window inhabits the left, right, or bottom edges of the screen, that area is cut off. This is purely visual, so clicks still register and parts of pages are cut off.

Turning off either Rounded Window Corners or PaperWM fixes the issue.

**Comment by jtaala** [comment]
Unfortunately, we don't have the resources to fix all issues resulting from conflicts with other extensions.

I don't use rounded corners extension but we'd happily accept a PR that fixes this from users that use rounded-corners extension.

Planning to close this in a month of so.  If anyone wants to work on this, let me know and we can keep it open.
