### ISSUE TITLE
Alternative layout suggestion for workspace indicator

### ISSUE THREAD

**Issue by jonseppanen** [paperwm/PaperWM#433]
I personally use things like: https://extensions.gnome.org/extension/3968/improved-workspace-indicator/ 
or even: https://extensions.gnome.org/extension/3952/workspace-indicator/
This lets me quickly switch workspaces with a click.
I can use these plugins at the moment with PaperWM, but I have to disable the code block:
`Main.panel.addToStatusArea('WorkspaceMenu', menu, 0, 'left');
    menu.show()`
Inside the topbar.js file, as I then no longer need this.
I guess I'm asking for either a way to disable the PaperWM workspace indicator in case of using another, or improve the paperWM one so it shows all workspaces and has clickable buttons.

**Comment by jtaala** [comment]
Thanks for paitence @jonseppanen, closing this as a duplicate given #387.  

P.S. I'll do up a PR in the next week or so to be able to disable the workspace indicator like we disable  other topbar elements like in later PRs (e.g. #476, #482, #499).
