### ISSUE TITLE
Adding a bottom border crops the window of all apps

### ISSUE THREAD

**Issue by jonseppanen** [paperwm/PaperWM#434]
![Overcropped](https://user-images.githubusercontent.com/10136068/198835374-deef9bf9-1303-4f94-8631-320c0f0bd90f.png)

In the above example, all my windows are cropped instead of size restricted, and I lose the bottom N pixels of each app.

**Comment by jtaala** [comment]
Hey @jonseppanen - bottom border, you mean like adding a bottom margin (like in the PaperWM settings?).

If so, I can't reproduce this.  What's the terminal application you're using in the screenshot?  Let me know and I'll try reproduce.

**Comment by jtaala** [comment]
Haven't seen this and can't reproduce.

Closing as it's been more than 7 months since this was submitted, and more than a month since requesting more information.
