### ISSUE TITLE
[enhancement] Publish PaperWM to extensions.gnome.org

### ISSUE THREAD

**Issue by bilboquet** [paperwm/PaperWM#435]
Hello,

Since I started to use PaperWM, I feel limited when I have to use a computer where it is not installed.
It is probably a lot of work but I think that bringing this wonderful extension to many others would be of great value. 
Hence I suggest it is published to extensions.gnome.org.
It will probably give the project more visibility and hopefully more support.

Many thanks for your work

**Comment by gombosg** [comment]
[Review guidelines](https://gjs.guide/extensions/review-guidelines/review-guidelines.html)
I'll take a look at this. I don't know anything about GJS but good with JS in general so hopefully we could get this through.

**Comment by bilboquet** [comment]
I don't know JS but I can offer some help for tests.

**Comment by jtaala** [comment]
Duplicate of #205.  There may be some issues that go against GJS guidelines (not sure if they would go against https://wiki.gnome.org/Projects/GnomeShell/Extensions/Review).

Mainly things like connecting signals in `init` etc.
