### ISSUE TITLE
[enhancement] Center mouse cursor when switching windows with keyboard

### ISSUE THREAD

**Issue by bilboquet** [paperwm/PaperWM#436]
Hi,

I use the mouse as less as possible. It's even more true since I use PaperWM. It's so true that sometimes I loose the cursor. To prevent this, I would love to have a new option/feature:
   when I switch to another window using the keyboard the mouse cursor is also moved and centered to the window that received the focus.

There is already such a mechanism when one switch from screen to another so I hope it is not much work.

Many thanks (again :) )

**Comment by bilboquet** [comment]
As a follow up, I've found an extension that does exactly this: https://extensions.gnome.org/extension/4642/mouse-follows-focus/

**Comment by jtaala** [comment]
Thanks for the update and solution provided @bilboquet!  Closing this now.
