### ISSUE TITLE
Moving a window to a distant workspace via keybindings takes windows from workspaces in between

### ISSUE THREAD

**Issue by lediur** [paperwm/PaperWM#442]
## Summary

When moving a window to another workspace at least 2 away, the "Move window one workspace up/down" keybindings will take windows from workspaces in between.

For example, if I have workspaces A, B, C, and I want to move a window from A to C, I want to press "Move window one workspace down" twice: one to go from workspace A->B, and one to go from workspace B->C. Since I have the keybinding set to Super+Shift+PageDn, I expect to hold down Super+Shift and then tap PageDn twice to move just that window and no other windows.

## Steps to reproduce

- Create three workspaces
- Open windows in the first two workspaces
- In the first workspace, hold the modifier key part of the "Move window one workspace down" keybinding and tap the "activator" key (not sure terminology here). The navigator should move to the second workspace.
- In the second workspace, continue holding the modifier keys and tap the "activator" key again

## Expected behavior

In the "Move window one workspace up/down" keybinding, pressing and holding modifier keys and tapping the "activator" key the first time should take the focused window from the original workspace and enter the workspace navigation mode.

While the user holds the modifier keys, the move operation is considered in-progress, and PaperWM should not take additional windows when the user presses the "activator" keys to move between workspaces, unless the user explicitly presses the distinct "Take window" keybinding. 

When the user releases the modifier keys, PaperWM should insert the taken windows into the destination workspace.

## Actual behavior

PaperWM will take the window from the first workspace and navigate to workspace B. When the user presses the activator key a second time, PaperWM will also take a window from workspace B and add it to the stack of windows to move. This is not what I intend, since I don't want to modify windows in workspaces I'm paging through.

## Mitigation

I thought this behavior might be unintentional, so I put together a quick fix on my local repo. I'll open a PR and link to it here.

**Comment by lediur** [comment]
There's also some behavior related to this one that's addressed by the same PR:

If you're at a workspace at the top or bottom of your list of workspaces, and you press "Move window one workspace up/down" repeatedly in the direction of the boundary, PaperWM will not navigate to another workspace (since you've hit the boundary) but it will repeatedly take windows from the workspace until it has taken all the available windows. This also feels like a bug to me.

**Comment by hallettj** [comment]
Until this is fixed, there is a workaround that I have been using. Instead of the "Move window one workspace down" command, use the "Take the window" command. I have that bound to Super+T, and my "Switch to workspace below" binding is Super+Page Down so to move a window two workspaces down I do this:

- hold Super, and tap T without releasing Super (if you hold T too long you pick up more than one window)
- press Page Down twice, while still holding Super
- release Super
