### ISSUE TITLE
Focus can't move

### ISSUE THREAD

**Issue by ajfpay** [paperwm/PaperWM#444]
Because at the latest level of manjaro release using Gnome 43, I just removed paperWM 42 after the update was complete. Then I installed paperWM version 43 and paperWM not going normally, this makes me scared. 

![Peek 2022-11-15 12-00](https://user-images.githubusercontent.com/53251872/201857401-660e45d5-4116-4272-8e60-13b6c82eb448.gif)

**Comment by SquidDev** [comment]
Possibly related to https://github.com/paperwm/PaperWM/issues/441 ?

**Comment by ajfpay** [comment]
> Possibly related to #441 ?

yes exactly the same problem

**Comment by VladPetriv** [comment]
Have the same problem:cry:

**Comment by ajfpay** [comment]
> Have the same problemcry

hopefully, someone fixes it soon,
for a while I used forge

**Comment by ajfpay** [comment]
I'm closing because there is a similar issue
