### ISSUE TITLE
Support of the project

### ISSUE THREAD

**Issue by faebser** [paperwm/PaperWM#447]
Hi,

I realised that paperwm became an integral part of my workflow. Is there a way to support this project in a financial sense?

thank you

**Comment by sebastianheuer** [comment]
Sorry for opening a new issue (which I now closed again), I should have taken a little more time to find a related issue :grimacing: 

I have been using and following the project for quite some time now and I wanted to express my gratitude and respect for how all the recent contributors managed to save this unique extension from fading into the void (it sure was a challenge!).

Seeing how active and responsive especially you, @jtaala are, is quite impressive and you are setting a high standard for open source work - which brings me to the suggestion of enabling sponsoring either the project, or you individually.

I do not know how large the user base of PaperWM currently is, but I would be happy to at least contribute in that way to its future. If more happy users think alike, it could at least compensate for some of the time spent on the project.

**Comment by scottames** [comment]
> Sorry for opening a new issue (which I now closed again), I should have taken a little more time to find a related issue grimacing
> 
> I have been using and following the project for quite some time now and I wanted to express my gratitude and respect for how all the recent contributors managed to save this unique extension from fading into the void (it sure was a challenge!).
> 
> Seeing how active and responsive especially you, @jtaala are, is quite impressive and you are setting a high standard for open source work - which brings me to the suggestion of enabling sponsoring either the project, or you individually.
> 
> I do not know how large the user base of PaperWM currently is, but I would be happy to at least contribute in that way to its future. If more happy users think alike, it could at least compensate for some of the time spent on the project.

Seconded. I'd love to contribute to ensure the continued success of this project. I'm very grateful for all the work recent contributors such as @jtaala have put in.

**Comment by jtaala** [comment]
> Sorry for opening a new issue (which I now closed again), I should have taken a little more time to find a related issue grimacing

No problems @sebastianheuer!

Many thanks all, Just knowing PaperWM is being used and appreciated is good enough reward for me!

I keep at it since I love PaperWM, the open-source community (and the idea behind it), and just hope it makes others' (computing) lives better.  Honestly, for me, doing stuff I love (that also happens to help others) is reward in itself (I blame my parents and my culture for raising me like that! :stuck_out_tongue_winking_eye:).

In any case, I appreciate the gesture! (honestly) - maybe @smichel17 might at some point choose to implement some sponsoring stuff for the project in the future (but I reckon that should be at the project level and only used for things to progress the project - whatever that might look like in the future).

Keep those issues and feedback coming.

Jay.

**Comment by NayamAmarshe** [comment]
This project is honestly amazing and I'm surprised other desktops haven't tried a scrolling WM workflow. It's mind blowing and super efficient, like having multiple monitors without multiple monitors!

**Comment by ForteDexe** [comment]
Love the project, how do I support it.
Surprisingly this project doesnt have much attention on youtube, I just randomly found it while browsing the gnome extension

**Comment by matiasnbella** [comment]
Just here to say I'm so glad to see this project alive! I moved on some time ago because I needed to stay updated with fedora and it was lagging behind between gnome versions but I'm definitely giving it another go now.

**Comment by adityainduraj** [comment]
Just wanted to say that I absolutely adore PaperWM and it makes my life better every day. A million thanks to @jtaala , your work helps me out so much. Thanks a ton!

**Comment by Thesola10** [comment]
Superseded by #723
