### ISSUE TITLE
Unable to install on fedora 37 Gnome 43

### ISSUE THREAD

**Issue by ghost** [paperwm/PaperWM#459]
rying to load and enable extension:
Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell was not provided by any .service files
something went wrong:

Success

**Comment by jtaala** [comment]
Hey @ShabirK21, how are you trying to install it? (via a fedora repo) or by cloning this repo (if you're on Gnome 43 you'll need to be on the `develop` branch) and running the `install.sh` script?

**Comment by ghost** [comment]
> Hey @ShabirK21, how are you trying to install it? (via a fedora repo) or by cloning this repo (if you're on Gnome 43 you'll need to be on the `develop` branch) and running the `install.sh` script?

Hi, I'm doing it by cloning this repo and running the script while in develop branch, also I'm using Gnome 43

**Comment by jtaala** [comment]
Hmm, well, that error is only when trying to enable the extension via script (the install, or symlinking the extension to be picked up by gnome, is done prior).  Can you confirm if the extension actually got installed? (you'll need to restart gnome or login/logout, then check if it was installed by opening up the `extensions` app).

Note, either way it shouldn't have died like that, just want to see if there's a deeper issue and it didn't even install.

P.S. I'm not on, nor familiar with Fedora btw - so might be limited in debugging this one.

**Comment by ghost** [comment]
> Hmm, well, that error is only when trying to enable the extension via script (the install, or symlinking the extension to be picked up by gnome, is done prior). Can you confirm if the extension actually got installed? (you'll need to restart gnome or login/logout, then check if it was installed by opening up the `extensions` app).
> 
> Note, either way it shouldn't have died like that, just want to see if there's a deeper issue and it didn't even install.
> 
> P.S. I'm not on, nor familiar with Fedora btw - so might be limited in debugging this one.

So i tried installing and restarted my device. It seems to have installed and is in available in extensions and works. Although i still got the error. Thanks

**Comment by jtaala** [comment]
>...something went wrong:
> 
> Success

Let that be a lesson to everyone - things can (and will) go wrong in life... and you can still have success! :smiley:

**Comment by jtaala** [comment]
I think this is a semi-known issue with the install script when it can't enable the extension (might even be if/when extensions are disabled)... it should prob be fixed (maybe if it errors out at extension enabling have it return something like `logout/login and enable it yourself... please`).

**Comment by smichel17** [comment]
Yeah. The error is actually that the usual script fails to **activate** the extension automatically not that it fails to install. (Failing to install is pretty unlikely, since the install is just a symlink)

Speaking of, personally I don't like the symlink approach. On my own computer I use a git worktree, so the folder is still version controlled, but also has its own copy of files.

**Comment by jtaala** [comment]
> Speaking of, personally I don't like the symlink approach. On my own computer I use a git worktree, so the folder is still version controlled, but also has its own copy of files.

+1 for talking about git worktrees (caused me to learn more about them!).

Any thoughts on a better approach?  Maybe just copy required files to `.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org`?  On reinstall, remove all files from that target folder and fresh copy?
