### ISSUE TITLE
Primary Monitor's workspace suddenly gets snapped onto Seconary Monitor

### ISSUE THREAD

**Issue by borring** [paperwm/PaperWM#469]
Primary Monitor (right) - Workspace 1
Scondary Monitor (left) - Workspace 2

Sometimes while clicking to activate windows, Workspace 1 will suddenly snap onto my secondary monitor (left). All the windows will show on the left monitor, but both monitors will show `Workspace 1` in their list.

There's no way to correct this after it has happened. It requires logging out of Gnome and logging back in.

**Gnome 43.2**

**Comment by smichel17** [comment]
I've also experienced this (Gnome 42.8, both X11 and Wayland). I did find a workaround that does not require logging out, although it is still extremely annoying:

- Open Extensions and Disable PaperWM
- Move all windows to workspace 1
    - Note: It must be workspace 1, not just "all to the same workspace". The important part is that the other workspaces "disappear" in the overview. So if you're using an extension like "minimum workspaces" you'll need to disable that, too.
- Re-enable PaperWM
- Move your windows back to the proper monitors + workspaces

**Comment by Lythenas** [comment]
I have noticed something similar, but after unplugging and re-plugging my external screen on my laptop.

This would just be a workaround but maybe there should be a way to move a workspace to another screen.

**Comment by smichel17** [comment]
I think the whole concept of how PaperWM should work with multiple monitors needs some thought. As I understand it, the current implementation mostly exists for technical reasons.

As I understand it, the way Xorg works (and maybe wayland too?) is that you have a coordinate grid in which windows are laid out, and monitors show a certain part of that grid. This means if you have two monitors next to each other, and you slide window 1 off the side of monitor 1, there's no way to hide it on monitor 2. When gnome used vertical workspaces, you could see this if you stacked two monitors on top of each other and then switched between workspaces with hotkeys— content from one screen would scroll across the other for the animation before they both switched to showing the next workspace.

Each monitor showing a different workspace means you can scroll off the side of one monitor and not appear on the other one, while still allowing the mouse to move between monitors normally.

(I'm not a display server expert, hopefully someone can correct me if I'm wrong).

**Comment by Lythenas** [comment]
That is also my understanding and I think it works more or less the same on Xorg and Wayland. One global coordinate space across all monitors and a workspace crops the virtual coordinate space and shows it on a monitor.

As far as I understand Gnome can only show one workspace on one monitor. So I think there isn't much PaperWM could do differently (e.g. it's not possible to scroll the windows across multiple monitors). But I could be wrong about that. I'm not that deeply familiar with gnome.

**Comment by borring** [comment]
@smichel17 is Do you find it always happens when dealing with a certain application or no? For me, it always happens when I'm dealing with Chrome windows, but I'm always dealing with Chrome windows, so that doesn't mean much... I was wondering if it could have something to do with https://github.com/paperwm/PaperWM/issues/468 since so far it seems like Chrome is partially splitting window focus between 2 monitors somehow.

**Comment by smichel17** [comment]
I don't use Chrome, so it's probably not application-specific. I do often have multiple firefox windows open on different monitors, so your hypothesis seems reasonable. I'll keep an eye out for whether it's always triggered when I have windows of the same application spread across monitors.

**Comment by smichel17** [comment]
I've been watching to try and figure out what circumstances trigger this bug. So far I have three things:

- Moving a window between monitors with keyboard shortcuts
- Moving a window between monitors with the mouse
- Rearranging a window on the same monitor with the mouse
    - It was near the shared edge and I might have dragged it briefly onto the other monitor.

I don't think it's definitively clear enough to say this is triggered by moving windows across the monitor boundary, but it's my best hypothesis so far. Obviously this isn't the only precondition, since it doesn't happen 100% of the time.

**Comment by jtaala** [comment]
> Primary Monitor (right) - Workspace 1 Scondary Monitor (left) - Workspace 2
> 
> Sometimes while clicking to activate windows, Workspace 1 will suddenly snap onto my secondary monitor (left). All the windows will show on the left monitor, but both monitors will show `Workspace 1` in their list.

Hey @borring, yes, I've found this bug and could reproduce reliably (with mutiple monitors, and going into overview, clicking overview workspace 1 on monitor 2, then clicking a window on monitor 2).  It was essentially caused by navigator being out of state and then clicking a window on another monitor - #574 should fix this.
