### ISSUE TITLE
Keep preview visible when switching to an offscreen window with the mouse

### ISSUE THREAD

**Issue by smichel17** [paperwm/PaperWM#470]
A screen recording is probably the easiest way to explain. At 3 seconds in, I click, and the preview disappears. The next window's preview reappears shortly after, when I move my mouse away and back. Ideally, the preview for the next window should appear without needing to move the mouse.

https://user-images.githubusercontent.com/6563664/215345762-aa98bd85-f5d0-45e8-b576-cf2981c0957a.mp4

**Comment by jtaala** [comment]
I like this btw - interestingly, when I was fixing the right-side preview not showing (originally in #458 and part of #454, which got merged) I actually thought to implement keeping the preview open as this PR mentions but didn't pursue it (mostly since I was just trying fix the issue first).
