### ISSUE TITLE
Show an indication of viewport position when there are offscreen windows

### ISSUE THREAD

**Issue by smichel17** [paperwm/PaperWM#471]
The reason for not merging https://github.com/paperwm/PaperWM/pull/364 is that leaving the window border offscreen gives an indication of when you are at the "end" of the row of windows, without having to try and move to the next window in that direction. The goal of this issue is to find some alternative, so we can merge that PR.

An easy solution would be to make the side border of the outermost window a different color (e.g. black). Inelegant but gets the job done.

A more ambitious idea: make a portion of the top bar change color (or opacity?) based on which windows you're currently viewing. For example, if you have 4 full-width windows open, and the 3rd one is visible on screen right now, the top bar could look like this (using obnoxious colors to make it more obvious):

![image](https://user-images.githubusercontent.com/6563664/215351019-87d45450-05ae-4bc2-923c-0d2374b26938.png)

If you had 3 fullscreen windows open, with the center on screen, it would look like this:

![image](https://user-images.githubusercontent.com/6563664/215351210-c4e5f546-2ed8-4c62-a29d-ab422b6bf25d.png)

If two windows, with the left one on screen:

![image](https://user-images.githubusercontent.com/6563664/215351364-9b7660ea-7d38-4bcc-8c7c-2d3213fcbff6.png)

…etc.

I'm not sure if this would be obnoxious or distracting in practice. It wouldn't necessarily need to affect the whole top bar, could be just a small amount along the top or bottom. An alternative would be to use some of the empty space in the top bar (to the left of the clock) to show a smaller-scale version of this, maybe using icons too, something like this (geary, gimp, and part of extensions would be visible in this example):

![image](https://user-images.githubusercontent.com/6563664/215351759-de9f14a2-ec0b-4c32-8f33-435fec842271.png)

**Comment by jtaala** [comment]
Out of these, I like the idea of the topbar border coloured segments - I think that would be a very cool and effective way to tell what window you're on.  I don't think it would be too hard to implement this (could be wrong though - depends on how much css gnome supports) - and we could provide a css classname so users could set/override the coloured segment with a colour/thickness etc. of their choosing (kind of like what was done in #460). 

Also like the border approach (which would also be the simplest to implement)- could even have the right or left border of the right-most or left-most window a different color (kind of like i3wm's border lines indicating where the next window will be placed).

The least liked would be the icon approach - I feel it would just clutter the bar and wouldn't be great for multiple windows of the same app (e.g. multiple browsers) separated by other apps/icons.  I like that paperwm is clean and non-cluttered when it comes to icons on the topbar.

**Comment by jtaala** [comment]
Since the border approach is easiest, could give that one a go first and see how it looks.
