### ISSUE TITLE
Could not enable PaperWM

### ISSUE THREAD

**Issue by JCCPort** [paperwm/PaperWM#474]
Hi, 
I'm trying to install PaperWM on Manjaro running GNOME 43.2 and get the following output when I run `install.sh`. I've heard many happy noises about your software so would like to get it working! :)

```
PaperWM runs best with some Gnome Shell settings changed:
 workspaces-only-on-primary off: Required for working multi-monitor support
 edge-tiling off: Natively tiled windows doesn't work in PaperWM
 attach-modal-dialogs off: Attached modal dialogs can cause visual glitching

Use recommended settings (generates a backup) [Y/n]: y
restore-gnome-shell-settings-2023-02-12.sh exists

Enable the extension [Y/n]? y
Trying to load and enable extension:
Could not enable PaperWM automatically. You may need to enable it manually.
Debug output: (false, '')

```

**Comment by Lythenas** [comment]
See also #425 

This is unfortunately normal. Gnome does not allow enabling an extension from a script anymore.

You have to manually enable PaperWM in the gnome extensions (like all other extensions) and possible restart gnome first. (Not 100% sure about having to restart).
