### ISSUE TITLE
I could use better errors 🙈 

### ISSUE THREAD

**Issue by dimaqq** [paperwm/PaperWM#475]
I've updated PaperWM with `git pull` after more than a year, and the extension fails on startup.

All I see if a little one-line floaty thing from gnome shell.
If I click that I get a more detailed error, which still doesn't quite help me:

```
-En PaperWM
Error occured in tiling @init:

fields are not currently supported

safeCall@/home/<user>/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:60:22
run@/home/<user>/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:46:14
init@/home/<user>/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/extension.js:100:9
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:435:50
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:27
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:601:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:576:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:610:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:641:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:257:22
start@resource:///org/gnome/shell/ui/main.js:146:5
@<main>:1:47
```

Versions:
* paper wm: f590f8b
* gnoem shell: whatever I get with ubuntu 20.04.x

**Comment by dimaqq** [comment]
The error seems to point at `Extension` here:

https://github.com/paperwm/PaperWM/blob/f590f8b30f0c1962e2bc18f1a39355b0a72636cb/extension.js#L57-L62

**Comment by dimaqq** [comment]
Here are the additional `journaltcl` logs:

```
Feb 20 09:24:55 kuro PackageKit[10259]: daemon start
Feb 20 09:24:55 kuro gnome-shell[10215]: #paperwm init: 1676852695688#
Feb 20 09:24:55 kuro dbus-daemon[793]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Feb 20 09:24:55 kuro systemd[1]: Started PackageKit Daemon.
Feb 20 09:24:55 kuro gnome-shell[10215]: #paperwm init tiling
Feb 20 09:24:55 kuro gnome-shell[10215]: #paperwm tiling failed init
Feb 20 09:24:55 kuro gnome-shell[10215]: JS ERROR: SyntaxError: fields are not currently supported
<traceback as above>
```

**Comment by dimaqq** [comment]
This specific error seems to come from `git diff 309f7c7^..309f7c7`
https://github.com/paperwm/PaperWM/commit/309f7c73603f85b82bc031b9d92df71c6abf3369

That change added the class-level "fields" `actor` and `background` although it seems the only reason for these fields is type annotation.

I'm getting a feeling that perhaps I'm using old node.js?

...

And here's my answer: `GNOME Shell 3.36.9` 🙈 

So, in the end, I guess it's all my fault for not reading the readme 🙈 

I'm sure someone else will get hit by this, so what can be done?

Would it be possible to check the gnome shell version early on and refuse to load the extension if the gnome shell is too old?

**Comment by hallettj** [comment]
The `develop` branch of PaperWM requires the latest Gnome release, version 43. It looks like Ubuntu 20.04 ships Gnome version 3.36. Looking at the PaperWM readme I see that the latest compatible tag for that Gnome version is https://github.com/paperwm/PaperWM/releases/tag/38.2

**Comment by Lythenas** [comment]
The metadata.json listst shell versions (https://github.com/paperwm/PaperWM/blob/develop/metadata.json#L7) so I would expect an error when installing. But maybe we circumvent the check because we are not installing it "normally" through the gnome extension UI. Or I guess the check is not performed at all because you git pulled after installing it.

I think a check for this with better error message should not be hard to implement. I will take a look at this.
