### ISSUE TITLE
Update README with useful info

### ISSUE THREAD

**Issue by jtaala** [paperwm/PaperWM#479]
Add things like "vertical overview" extension recommendation and changing dconf settings like `animation-time` etc.

See [this zulip thread](https://paperwm.zulipchat.com/#narrow/stream/174097-new-members/topic/Compatibility.20with.20impatience).

**Comment by smichel17** [comment]
At some point it'll also get long enough that we'll want to split it up. Not sure if we're there yet but when we get there I strongly suggest following https://diataxis.fr/
