### ISSUE TITLE
"Take window", but sticky?

### ISSUE THREAD

**Issue by crispinb** [paperwm/PaperWM#486]
I find window rearrangement between workspaces a bit tricky. The most obvious option is 'Cycle through the most recently used, taking the active window with you' but that picks up other windows along the way, making the results unpredictable.

"Take the window, placing it when finished navigating"  would be great if you didn't have to hold the key combo (`super t` by default) while also trying to navigate.

What might work better for me would be the same 'take window' action, but sticky such that the window stays 'taken' until the navigation operation is complete, at which point 'take' could be cancelled, presumably with `esc`.

Might this be possible? Or are there already better options?

**Comment by Lythenas** [comment]
Huh. I never noticed this behavior... And I think it is very indeed very odd to take all windows you accidentally "navigate over". Just to showcase this with a video:
[Screencast from 2023-03-07 19-31-01.webm](https://user-images.githubusercontent.com/32217236/223517097-2a6bd349-81bb-42c5-8624-9278e25db41f.webm)

> "Take the window, placing it when finished navigating" would be great if you didn't have to hold the key combo (`super t` by default) while also trying to navigate.

For me releasing the `t` and just holding `Super` works. And you need `Super` anyway to navigate.

IMO that is a good enough workaround for now. But the current behavior of `Super + Ctrl + PageUp/Down/Above_Tab` still seems strange to me. Not sure if this was intended.

**Comment by crispinb** [comment]
> For me releasing the t and just holding Super works. And you need Super anyway to navigate.

You're right! Somehow I didn't notice that. Thanks. I agree that's good enough, making this issue just noise, so I'll close it.  Perhaps I should add another one re the `Cycle ..` command picking up extra windows.
