### ISSUE TITLE
Update for Gnome 44

### ISSUE THREAD

**Issue by Lythenas** [paperwm/PaperWM#490]
Gnome 44 is about to release. If I understand https://wiki.gnome.org/FortyFour correctly it will release on March 22nd.

I haven't looked at all into what changed. But since I'm running Arch (btw) I expect to upgrade to Gnome 44 shortly after the release. See also https://gitlab.gnome.org/Teams/Engagement/release-notes/-/issues/43

If possible, we should just add support to the `develop` branch. Would be ideal for me because I still have Gnome 42 (Ubuntu 22.04) on my work laptop.

I'm happy about any comments on how we should proceed with the update/testing. If we are lucky we won't actually have to change anything^^

This issue is mostly meant as a placeholder to track any issues found on Gnome 44 and to provide others information on the status of the support.

## Issues found

- [x] Not tested so far.

**Comment by Lythenas** [comment]
I looked at some other extension and they seem to not needed to change much:

- https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/397
- https://github.com/home-sweet-gnome/dash-to-panel/pull/1833

**Comment by jtaala** [comment]
Hey @Lythenas, yeah, I'm kind of in the same boat (arch based distro - although it's manjaro so might drop in their stable a bit after arch's).  I reckon we just start with enabling it in `metadata.json`  by adding it to `shell-version`.

It will at least run then - and we can start testing and working through any bug reports etc. we get.

**Comment by jtaala** [comment]
Hey @Lythenas - do you want to create a PR just first enabling in `metadata.json`?  Then us and others can at least enable in Gnome 44 and we can start addressing issues via normal bug reports and PRs etc.

**Comment by Lythenas** [comment]
I opened a PR #491, I also added a milestone to organize this a little bit.

**Comment by jtaala** [comment]
Thanks @Lythenas - given Fedora 38 has been released (I think), which ships with Gnome 44, I'm going to start working on Gnome 44 support (will use Fedora 38 as my test distro for this).

**Comment by jtaala** [comment]
See #515 which I believe is now ready, and provides gnome-44 support in PaperWM.
