### ISSUE TITLE
Gnome 44: Window overlaps neighbor on resize

### ISSUE THREAD

**Issue by schopin-pro** [paperwm/PaperWM#494]
Hi,

I'm using PaperWM on the development branch of Ubuntu 23.04, which has gnome-shell 44 rc.

When I cycle through widths to make a window bigger, it overlaps its right neighbor window instead of displacing it.

**Steps to reproduce**

1. Open an app with small default size (e.g. a terminal), twice.
2. Expand the width of the leftmost window
    -> It expands on top of the rightmost window.

**Expected behavior**

I'd expect the rightmost window to be shifted right to account for the new width of the active window.

**Screenshots**
![image](https://user-images.githubusercontent.com/87005181/226311308-16b5e412-0296-4f54-aeaf-bc7e938b3615.png)

**System information:**
```
Distribution: Ubuntu
GNOME Shell 44.rc
PaperWM branch/tag: develop
PaperWM commit: d601f99d87837f925ebc41a5ab961cd13aa0f1c7
Enabled extensions:
- paperwm@hedning:matrix.org
- nightthemeswitcher@romainvigier.fr
- vertical-workspaces@G-dH.github.com
- ubuntu-appindicators@ubuntu.com
```

**Comment by amfern** [comment]
Having the same issue and it seems be fixed in fixes-gnome-44-support, i installed it with the [gnome-shell-extension-paperwm-redux](https://aur.archlinux.org/packages/gnome-shell-extension-paperwm-redux-git)
