### ISSUE TITLE
Remove transparency from the top toolbar

### ISSUE THREAD

**Issue by robintown** [paperwm/PaperWM#496]
**Is your feature request related to a problem? Please describe.**
I have a fairly busy and bright wallpaper, and the low transparency of the top toolbar in PaperWM impedes the readability of the text and symbols displayed on it. I also prefer GNOME's default black toolbar from a purely aesthetic perspective.

**Describe the solution you'd like**
Don't add transparency to system components, as it makes the desktop less accessible.

**Describe alternatives you've considered**
A more pronounced blurring and tinting effect, to at least reduce the business of the background? Still, I don't understand what purpose the transparency serves.

**Additional context**
![Screenshot from 2023-03-20 23-07-30](https://user-images.githubusercontent.com/48614497/226509024-5e278221-c09f-4c2a-8010-cfb6f12bc93a.png)

**Comment by Lythenas** [comment]
Try updating. With #476 there is now also a backdrop in the top bar. You can then also adjust the background with the css class `.paperwm-window-position-bar` if I remember correctly.

**Comment by jtaala** [comment]
Hey @robintown, yes if you're on the latest on `develop`  branch you can set the topbar background to your preferred colour.

Try add this to a `user.css` file (placed in `~/.config/paperwm` folder):

```css
.topbar-transparent {
    background-color: black;
}

.paperwm-window-position-bar-backdrop {
    background-color: black;
}
```

And then logout/login (or reload the css theme as outlined in the [README.md](https://github.com/paperwm/PaperWM#development--user-configuration)).

**Comment by jtaala** [comment]
If you don't like the window position topbar indicator approach, you can disable it but keep that css and it will do what you're after.

P.S. you can disable the "window position bar" feature in paperwm extension settings (set `Enable Window Position Bar` to false) or by running this command from terminal:

```
dconf write /org/gnome/shell/extensions/paperwm/show-window-position-bar false
```

**Comment by jtaala** [comment]
@robintown, from your pic it looks like you're on an old commit/branch? (or you've disabled the `window position bar`).

Note: you'll need to update to the latest (`git checkout develop`, `git pull`) to change this stuff.

**Comment by robintown** [comment]
I have disabled the window position bar, yes. I was more or less aware that there was probably some custom CSS I could apply that would remove the transparency (and thanks for saving me from figuring out the selectors myself), but my request is more specifically that it be opaque by default, since the current behavior is somewhat of an accessibility regression.

**Comment by jtaala** [comment]
Interestingly, I raised this for discussion here: https://github.com/paperwm/PaperWM/pull/476#issuecomment-1462233925

Got no feedback there, hence the transparency stayed (e.g keeping on with status quo).  Transparency was originally implemented a long time ago (see #344) - so we had two options:

1. carry on with what we have now (as it's been for a long time) and provide a way for users to change this to preference (override css);
2. change current behaviour (no transparency by default) and mostly likely have complaints we've changed the current behaviour;

Given no feedback at the time, I chose (1) - which was seen as the safest option (at least for that PR).  We'd happily look at a PR from you for changing that behaviour - but unless more users (and @smichel17) agree it should be changed - it's likely not going happen(?).

**Comment by jtaala** [comment]
@vincentmathis, @Thesola10, @raiguard, you commented on #344 - any thoughts here?  See my last comment (https://github.com/paperwm/PaperWM/issues/496#issuecomment-1478671519).

**Comment by Lythenas** [comment]
The transparency of the topbar was intended to show the (default) color of the workspace (each workspace has a different color assigned that can also be changed in the settings). Since you set a custom wallpaper (presumably also in the settings) this is of course no longer the case. And therefore it doesn't look so nice.

But IMO in this case it is reasonable for the user to also add a couple of lines to the `user.css`. We could of course document this a lot better. Maybe with some examples.

**Comment by Thesola10** [comment]
Adding more lines to `user.css` isn't going to fix the conflict with other extensions that control topbar opacity.

**Comment by jtaala** [comment]
Hey, [Thesola10](https://github.com/Thesola10) had a decent point (I don't know where his comment went - seems he left this chat?).

Anyways, his point was that even with user.css - it can be hard to fix the conflicts with other extensions that might control/change topbar opacity.  `user.css` is good, but even using values for `background-color` like `inherit`, `initial`, or `unset` would basically revert to the default paperwm transparency.

It seems that that's a valid case here - if users want to delegate topbar opacity/colour to other extensions.

I'd be happy to add a simple dconf user setting/flag - something like `dont-change-topbar-opacity` (or something) - a user setting which would stop paperwm from ever touching/changing topbar styles (so it doesn't interfere with other extensions changing them).

One complication would be the window position indicator - which sits behind the topbar (we make topbar completely transparent so we can see it) - but window position bar indicator can be disabled anyway (up to the user).

So, we'd have a pretty configurable approach to topbar opacity/style:
- default thing with transparency to see workspace colours;
- `user.css` to change topbar (and window position indicator) styles to preferred;
- even simpler setting / flag to have paperwm never touch topbar styles (e.g. so other extensions can manage topbar opacity)

Thoughts?

**Comment by Lythenas** [comment]
Seems reasonable to me.

**Comment by jtaala** [comment]
Hey all, added simple user preference flag that will disable PaperWM's ability to change the gnome topbar styling (e.g. make it so that PaperWM doesn't touch topbar at all).  See here:

https://github.com/paperwm/PaperWM#gnome-topbar-opacity--styling
