### ISSUE TITLE
Add the config directory to the search path

### ISSUE THREAD

**Issue by hedning** [paperwm/PaperWM#51]
We add the config directory to the search path `Extension.imports.searchPath.push(configDir)` and run the config through that mechanism. This way we retain the scope making it easy to integrate gnome-shell-mode support.

When installing also install the config directory and a config template containing at the minimum something like this:

```javascript
var Extension;
function init() {
  // Runs _only_ once on startup
  Extension = imports.misc.extensionUtils.getCurrentExtension();
}

function enable() {
  // Runs on extension reloads, eg. when unlocking the session
}

function disable() {
  // Runs on extension reloads eg. when locking the session (`<super>L).
}

```

**Comment by olejorgenb** [comment]
- Handling of `has-installed-config-template` flag when the install step fails should be improved
- Errors should be made more visible to the user

**Comment by olejorgenb** [comment]
Atm. all user files are exposed directly under `Extension.imports`

Would be nice to namespace them, but AFAICS that requires either adding "~/.config" (yuck) to the searchpath or adding another directory level: "~/config/paperwm/user/user.js"
