### ISSUE TITLE
Gnome 44: windows on primary monitor resize to overlap top bar

### ISSUE THREAD

**Issue by jfmcbrayer** [paperwm/PaperWM#519]
**Describe the bug**

I'm running the gnome-44 support branch on Fedora 38. When I have one or more windows open on my primary monitor, then switch to my secondary monitor and back, the windows on the primary monitor resize to full height, appearing under the top bar. The only way I've seen to get them back to normal is to open another window on the primary monitor. Possibly noteworthy: while the secondary monitor is focused, the windows on the primary monitor leave space for the top bar, even though it does not appear.

**To Reproduce**
1. Open one or two windows on the primary monitor.
2. Switch to secondary monitor with mouse or keyboard
3. Switch back to primary monitor with mouse or keyboard (it is not necessary to create a window on the secondary monitor.

**Expected behavior**

**Screenshots**
To be added later, if the description is not clear enough.

**System information:**
```
Distribution: Fedora Linux
GNOME Shell 44.1
Display server: Wayland
PaperWM branch/tag: fixes-gnome-44-support
PaperWM commit: 47a6d9ead03c899a96cf5efe57d7b747a74db262
Enabled extensions:
- appindicatorsupport@rgcjonas.gmail.com
- gnome-extension-brightness@bruno.englert.gitlab.com
- paperwm@hedning:matrix.org
- user-theme@gnome-shell-extensions.gcampax.github.com


```

Edited to add:

Turning off the "Make top bar follow monitor focus" prevents this from happening. With "Enable window position bar" turned on, they may briefly expand to full screen height, but then quickly return to the correct height.

**Comment by jtaala** [comment]
Thanks @jfmcbrayer - will hopefully have time to look at this one once we get the `fixes-gnome-44-support` branch into `develop` (getting closer and hopefully that should be this week).  Definitely pull the latest from that branch if you're on it - have fixed a bunch more gnome-44 issues the last couple of days.

Did you notice this happening on gnome 43? (if you were using PaperWM on 43 that is).

**Comment by amfern** [comment]
~~Having the same issue, and it seems to be fixed in fixes-gnome-44-support, I installed it with the [gnome-shell-extension-paperwm-redux](https://aur.archlinux.org/packages/gnome-shell-extension-paperwm-redux-git)~~

Sorry, I commented on the wrong Issue, i don't have two monitors so i can't test it.

**Comment by jtaala** [comment]
Thanks @amfern, good point @jfmcbrayer, pull the latest from the `fixes-gnome-44-support` branch - the commit you were on is before a bunch of gnome 44 fixes went in (although these might not have addressed this issue specifically, but worth a try).

**Comment by jtaala** [comment]
> Turning off the "Make topbar follow monitor focus" prevents this from happening

Thanks @jfmcbrayer - finally got a chance to look at this.  So, the `Make top bar follow monitor focus` is somewhat broken and, to be honest, is a pain that I don't think should be supported on PaperWM.  AFAIK, it's not supported on Gnome itself (e.g. dynamically changing topbar monitor with mouse focus) and the code implemented in PaperWM to support it is quite hacky.

Question (to all) - is the `Make topbar follow monitor focus` heavily used & loved by anyone?  Can we look at removing/deprecating this functionality?

I can try to fix it, but tbh, it's going be more hacks on hackiness.  Happy to do my best to keep that feature alive, but if not many people use it, then I'm thinking it's not worth the effort to maintain that feature.

Open to others' thoughts here! (and especially if you use the "topbar focus follows mouse" feature and love it... let me know why :smile:).

**Comment by Lythenas** [comment]
I would rather have a topbar on all monitors instead of topbar follow focus. We I think we discussed this before on Zulip and we don't want to support that.

But with topbar on all monitors it would be as easy as hiding all except the current one. Not sure if/how much this would interfere with normal gnome. But there are other topbar extensions that also do things like this. Maybe we should just pick one of those and "officially" support it.

**Comment by jtaala** [comment]
Well, by default, on monitors without the topbar, PaperWM shows the "Window position bar", which also has the workspace name, focus-mode icon etc.

Anyone who uses multi-monitors want to try out one of those extensions to see how it works with PaperWM - this one looks like it might work with 44: https://github.com/realh/multi-monitors-add-on.
