### ISSUE TITLE
`set-recommended-gnome-shell-settings.sh` does not work if it was previously ran on the same day

### ISSUE THREAD

**Issue by Lythenas** [paperwm/PaperWM#520]
**Describe the bug**
`set-recommended-gnome-shell-settings.sh` does not work if it was previously ran on the same day.

**To Reproduce**
1. run `set-recommended-gnome-shell-settings.sh`
2. Manually reset or change the gnome settings
3. run the script again
4. Recommended settings are not applied

**Expected behavior**
The script should always apply the recommended settings..

**System information:**

```
Please include this information in your bug report on GitHub!
Distribution: Arch Linux
GNOME Shell 43.5
Display server: Wayland
PaperWM branch/tag: gather-system-info-update
PaperWM commit: 1ab44cddc3778276039a59b9316c87f8cb3fbcea
Enabled extensions:
- paperwm@hedning:matrix.org
- switcher@landau.fi
- appindicatorsupport@rgcjonas.gmail.com
```

**Additional context**

This is cause by the following lines:
https://github.com/paperwm/PaperWM/blob/1130b663806d6daba1c8355c4b99c287d237e918/set-recommended-gnome-shell-settings.sh#L3-L8

So you only run into this behavior if you run the script multiple times on the same day.

IMO we can just remove this check and add the time to the restore file name.

I can create a PR for this once we decide what to do.

**Comment by tlevani** [comment]
I agree, adding the exact time in the restore file name should be enough to basically solve this issue and make this check unnecessary. I guess the only question is what precision is good enough, seconds or milliseconds?

**Comment by Lythenas** [comment]
Seconds are probably enough but there is also no harm in including milliseconds.

**Comment by tlevani** [comment]
True. Then maybe something like an ISO 8601 format with ms precision and without a timezone could work fine. For example `date +"%Y-%m-%dT%H:%M:%S.%3N"`?

**Comment by jtaala** [comment]
> I agree, adding the exact time in the restore file name should be enough to basically solve this issue and make this check unnecessary. I guess the only question is what precision is good enough, seconds or milliseconds?

Clever!  I didn't even think of that - elegant and easy solution.
