### ISSUE TITLE
Settings option for always floating specific apps

### ISSUE THREAD

**Issue by t3dium** [paperwm/PaperWM#521]
Some apps i wouldn't want to tile and would prefer to have them floating, whilst i could use the keybinding to do this every time, it'd be convenient to have a setting to always un-tile/float specific apps.

**Comment by Lythenas** [comment]
You can do this using winprops to start them on the scratch layer (which is what we call the floating windows). See https://github.com/paperwm/PaperWM#setting-window-specific-properities

**Comment by jtaala** [comment]
Closing this as this is already a feature of PaperWM, and can be set a few ways, including in PaperWM settings.  You can see this done for gnome-terminal in the following video:

https://user-images.githubusercontent.com/30424662/211422647-79e64d56-5dbb-4054-b9a6-32bf3194b636.mp4

**Comment by jtaala** [comment]
You can define rules for apps via it's `wm_class` or by a `title` - you can find these a variety of ways including in looking glass (that outlined in the README.md).
