### ISSUE TITLE
Changing wezterm font size with PaperWM loaded in Gnome 44 causes gnome-shell to crash

### ISSUE THREAD

**Issue by crispinb** [paperwm/PaperWM#522]
NB: I don't know whether this is a wezterm or a PaperWM issue, or some odd interaction between the two. Filing here because it only happens when the PaperWM extension is loaded.

**Describe the bug**
Changing font size repeatedly in a running Wezterm window with the PaperWM extension loaded causes a gnome-shell segfault.

**To Reproduce**
1. Run Gnome + PaperWM extension
2. Open a Wezterm window
3. Press `ctrl+` or `ctrl-` a few times (variable) to increase/decrease the font size

**Expected behavior**
gnome-shell doesn't crash ;)

```
Distribution: Fedora Linux
GNOME Shell 44.1
Display server: Wayland
PaperWM branch/tag: fixes-gnome-44-support
PaperWM commit: 477d546e5a78280cb324379a365225b0f702ad8d
Enabled extensions:
- impatience@gfxmonk.net
- highlight-focus@pimsnel.com
- clipboard-history@alexsaveau.dev
- paperwm@hedning:matrix.org
- vertical-overview@RensAlthuis.github.com
- background-logo@fedorahosted.org
- appindicatorsupport@rgcjonas.gmail.com
```

**Additional context**
- I don't think this happened under gnome 43
- unlike with other terminal apps (eg. Kitty), changing wezterm's font size
  also causes its window to resize. Perhaps relevant?
- given previous problems with wezterm + PaperWM, perhaps wezterm is more trouble
  than it's worth in this environment. But a reproducible crash seems odd so I thought 
  worth reporting.

**Comment by Lythenas** [comment]
Might also be related to #498 

Maybe it would be worth figuring out what makes wezterm so special :D If the whole gnome-shell segfaults it might also be worth reporting directly to gnome-shell. Although I don't know if they are willing to fix it if it only happens with PaperWM.

**Comment by jtaala** [comment]
Hey @crispinb, just installed wezterm on latest `develop`.  I can't seem to reproduce this crash, doing lots of `ctrl+` and `ctrl-` and they're changing the font size (and interestingly the width of the window) but getting no crashes.

Can you confirm you're still seeing this on latest `develop`?

**Comment by crispinb** [comment]
@jtaala - I actually moved to mainly using kitty. I was previously using wezterm because I preferred its font rendering & layout handling & lua scripting, but it wasn't worth the crashes.

Anyway I've just tried it again and .. it appears I've given you a bum steer. Yes, I'm still finding Gnome crashes on font resizing (odd that you're not - perhaps it's version specific?). BUT it also happens without PaperWM loaded. Not sure how I got that wrong;  for some reason without PaperWM I do have to resize more times to get the crash so I guess I just didn't test enough.

Anyway I think this is firmly not your problem. Sorry to waste your time. I'll leave you to close this issue as I'm never sure about the etiquette involved with other people's repos.

**Comment by jtaala** [comment]
All good @crispinb  - was playing around with wezterm as I hadn't used it before and always like trying out new terminals.  Looks alright.

Yeah, not too fussed, re etiquette, can close the issue if you've opened it.  I'll close this one though.

Cheers!

Jay.

**Comment by jtaala** [comment]
For reference, I tried out this version:

![image](https://github.com/paperwm/PaperWM/assets/30424662/5e813f92-e29a-46cf-b930-e71f5e965cac)
