### ISSUE TITLE
open new window to left of focused window

### ISSUE THREAD

**Issue by joeyh** [paperwm/PaperWM#526]
I find that often I want to open a new window to the left of the focused window. Since text goes left to right, the left side of a window like a browser or a terminal often has more useful information in it than the right side does. When the two windows can't fit on the screen together, opening a new window to the right will prevent referring back to the original window as effectively as if the new window were on the left. 

Currently I have to open the window and then move it to the left. That sounds easy, but it's kinda not. Really the process is: Press key that will open the new window. Wait some amount of time for it to appear. Screen shifts right. Multifinger keypress to move it to the left. Screen shifts left. The variable delay and screen movement make this significantly more taxing than if the window could be opened to the left. It's a small papercut, but one that happens repeatedly thruought my day.

**Describe the solution you'd like**

I'd be ok with an option that changes all windows to default to open to the left rather than the right.

Since super-I also pulls from the right, any change would also need to affect it presumably.

**Comment by jtaala** [comment]
I can see the utility in this request.   Technically, it's fairly straightforward to implement.  If we're going to make it a user settable option, we could provide a few options, e.g.:

- open new windows to the right (current behaviour);
- open new windows to the left;
- open new windows at start of windows (position 0);
- open new windows at end of windows (position n);

I played around with the last two and feel some people might like those behaviours (they're at least very consistent?)... actually, think this would be a pain with lots of windows, although we do have keybinds to go to start/end of windows.

Although, I can see some times where I'd like one behaviour over another... it's feasible we could add modes (like window focus modes) - with a similar icon, although I'm weary of crowding the topbar with icons.

The latter is more complexity, so maybe just a setting to set the behaviour for all windows is preferable?

Thoughts?

**Comment by jtaala** [comment]
P.S. if you wanted to try out always opening windows to the left, just comment out (or delete) this line:

https://github.com/paperwm/PaperWM/blob/0592c9263121d4ffc8ce4d932bca57be1bf4dd65/tiling.js#L2919

and then logout/login.

**Comment by Lythenas** [comment]
I think a setting would probably be fine. You can always emulate a "mode" by creating a keybinding with the correct `dconf write` command (although you would not get any indicator in the top bar).

If we add any more indicators I think we should make them as compact as possible. Although at least on my monitor resolution I'm not running out of space any time soon :D

**Comment by joeyh** [comment]
A setting would be fine with me. 

I'm using the index++ removal hack and happy with how it behaves with that change.

**Comment by madx** [comment]
This would be super cool too, I'd definitely be interested in opening at the end of windows too. A setting is fine and keeps the things simple imo

**Comment by jtaala** [comment]
Hey all,

I've now implemented this - could I have others test this please?

Check out the branch for the shell you're on:

### Gnome 45

```
git clone https://github.com/paperwm/PaperWM.git
cd PaperWM
git checkout feature-526-open-new-window-position-gnome45
./install.sh
```
then logout/login and open preferences and choose your preferred option.

### Gnome 44 (or 43, 42)

```
git clone https://github.com/paperwm/PaperWM.git
cd PaperWM
git checkout feature-526-open-new-window-position
./install.sh
```
then logout/login and open preferences and choose your preferred option.

**Comment by jtaala** [comment]
![image](https://github.com/paperwm/PaperWM/assets/30424662/2e6ac703-f5e1-426e-9b58-76ff59be1d16)

**Comment by jtaala** [comment]
Merged into `release` and `gnome-44` branch.
