### ISSUE TITLE
Sponsoring

### ISSUE THREAD

**Issue by sebastianheuer** [paperwm/PaperWM#527]
I have been using and following the project  for quite some time now and I wanted to express my gratitude and respect for how all the recent contributors managed to save this unique extension from fading into the void (it sure was a challenge!). 

Seeing how active and responsive especially you, @jtaala are, is quite impressive and you are setting a high standard for open source work - which brings me to the suggestion of enabling sponsoring either the project, or you individually. 

I do not know how large the user base of PaperWM currently is, but I would be happy to at least contribute in that way to its future. If more happy users think alike, it could at least compensate for some of the time spent on the project.

**Comment by jtaala** [comment]
Many thanks @sebastianheuer!  Just knowing PaperWM is being used and appreciated is good enough reward for me mate!

I keep at it since I love PaperWM and hope it makes others' (computing) lives better.
