### ISSUE TITLE
Window height immediately snaps back to 100% when resizing

### ISSUE THREAD

**Issue by kanni** [paperwm/PaperWM#528]
**Describe the bug**
When changing the height of a window via  shift + super +  - it resizes for a split second but then snaps back to 100% height

**To Reproduce**
- do a fresh install of Fedora 38
- install papwerWM from fixes-gnome-44-support branch
- press shift + super +  -  with an active window

**Expected behavior**
The window resizes to a smaller height

**Screenshots**

**System information:**
```
Distribution: Fedora Linux
GNOME Shell 44.1
Display server: Wayland
PaperWM branch/tag: fixes-gnome-44-support
PaperWM commit: 1ac33b4620c1cecc9578eab50b92fbe2ee109673
Enabled extensions:
- paperwm@hedning:matrix.org
```

**Additional context**
I'm using a monitor with an unusual aspect ratio/resolution: 2560x2880

**Comment by Lythenas** [comment]
I believe this is expected for tiled windows as they are supposed to take up two whole height.

However if you are talking about windows in the scratch layer (i.e. floating windows), then this is a bug.

For what it's worth the keybinding works correctly for floating windows on gnome 43 with the `fixes-gnome-44-support` branch.

**Comment by kanni** [comment]
@Lythenas Thanks for the clarification! I think you are correct.
