### ISSUE TITLE
Keybind fails

### ISSUE THREAD

**Issue by eliorc** [paperwm/PaperWM#536]
**Describe the bug**
Some keybinds fail. For example Super+Right can navigate to the right, Super+Left does nothing. Before uninstalling and installing all over again, also Super+Page Down worked while Super+Page Up didn't. This is accompanied by a weird topbar visualization bug 

**To Reproduce**
1. uninstall by executing `./uninstall`
2. As it still appears in the extension menu, manually delete it from there
3. Reinstall from scratch, without restoring previous settings
4. Open two windows
5. Navigate right (Super+Right)
6. Try to navigate left (Super+Left) - fail

**Expected behavior**
That super + left will work as well

**Screenshots**
Maybe its relevant but the top bar gets "highlighted" relatively to the active window, in this image the left window is in focus
![image](https://github.com/paperwm/PaperWM/assets/17727283/6ea81544-3c34-46d3-98b7-ef7720b84c69)

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

```
Example:
Distribution: Ubuntu
GNOME Shell 42.5
Display server: Wayland
PaperWM branch/tag: gnome-42
PaperWM commit: 9a1611a23c30386f1b6b7ce148470d96f47b730c
Enabled extensions:
- paperwm@hedning:matrix.org
- ubuntu-appindicators@ubuntu.com
- ubuntu-dock@ubuntu.com
```

**Additional context**
None

**Comment by Lythenas** [comment]
This might be the same issue I ran into on gnome 43: #533 

Regarding the topbar: This is a new feature. See https://github.com/paperwm/PaperWM#window-position-bar-colored-bar-segment-in-top-bar

**Comment by eliorc** [comment]
Oh, good to know regarding the topbar 👍🏼

**Comment by jtaala** [comment]
Thanks @eliorc!

Hey all, big thanks to @Lythenas for testing this out and creating some PRs.

I've now implemented a multi-gnome version fix/PR that should fix this once and for all (in all gnome versions) - see #539 for details.

@eliorc  can you please test this PR/branch.  I've testing on Gnome 43 (just bit the bullet and installed a 43 vm) and also Gnome 44.

NOTE: I know it mentions gnome43 in the branch name but this should also work for Gnome 42 just fine.

```
git fetch --all
git checkout fix-regression-gnome43-keybindclash
./install.sh
```

and then logout/login.

Thanks

**Comment by jtaala** [comment]
P.S. hopefully you like the `window position-bar` (I'm hoping since I spent a lot of time on it!) - however, if you don't like it you can turn it off in the paperwm extension settings or via terminal with:

```
dconf write /org/gnome/shell/extensions/paperwm/show-window-position-bar false
```

**Comment by jtaala** [comment]
Hey @eliorc,

This should now be fixed in `gnome-42` branch.  Please do a:

```
git checkout gnome-42
git pull
```
and logout/login to get these fixes.

Thanks!
