### ISSUE TITLE
Guake causes workspace to be scrolled to the left

### ISSUE THREAD

**Issue by xanf** [paperwm/PaperWM#56]
Hi! And thanks for amazing job. I have a weird issue: if I'm using guake window and toggle it with hotkey - after hiding workspace is immediately scrolled to the left-most position

**Comment by xanf** [comment]
Nevermind, it was fixed by applying "scratch" rule to guake, sorry for buzz (forgot to reload gnome-shell to see result)

**Comment by hedning** [comment]
No problem, nice knowing someone else is using it :)

Applying a scratch winprop is indeed the easy fix here.

Found the culprit that was causing the underlying issue though. Focusing a window that weren't part of the scratch layer or tiling would raise the first window in the tiling.

**Comment by xanf** [comment]
Actually I'm coming from awesome WM - moving to wayland due to mix of hi-dpi and normal dpi monitors in my common workflow, and I really love PaperWM tiling approach and that it is js (which is my primary coding language)

**Comment by hedning** [comment]
Good to know it's working okay on wayland (I'm mostly using X, but have tested things out in wayland from time to time), and that multi monitors with different scaling works (which I haven't tested out properly).

We hang out on #paperwm:matrix.org if you have any quick questions etc.
