### ISSUE TITLE
Documentation Request - Key binding cheat sheet

### ISSUE THREAD

**Issue by liljenstolpe** [paperwm/PaperWM#578]
**Is your feature request related to a problem? Please describe.**

Not so much a problem as a request - a quick reference cheat sheet for the default keybindings would be nice for the first few days when adopting PaperWM.

**Describe the solution you'd like**

A simple cut & paste job on the README.md 

**Describe alternatives you've considered**

Not many other alternatives....

**Additional context**

May have already done it.... :)

**Comment by liljenstolpe** [comment]
Watch for the PR....

**Comment by jtaala** [comment]
Hey @liljenstolpe, just in case you haven't seen it - there's some changes needed in your PR (which is still broken).

Cheers,

Jay.

**Comment by liljenstolpe** [comment]
Oops - sorry, missed that - was away for a bit of holiday, and then some business travel.  Will get on that today or tomorrow.

**Comment by jtaala** [comment]
No problems.

Also, I think the 404 shown on the branch's github page (when clicking the link in `README.md`) may a github issue?  I'm not sure - it should work on your fork but seems to not (likely from the typo of the filename).

Also, we've created a few more shortcuts (see latest `release` and useful widths/height backwards cycling keybind).

**Comment by jtaala** [comment]
We've recently simplified the keybind section of README.md.  closing this.
