### ISSUE TITLE
Change default keybiding for "Consume the window to right into active colunm"

### ISSUE THREAD

**Issue by bilboquet** [paperwm/PaperWM#583]
I often accidentally hit "Super+I" which triggers "Consume the window to right into active column". It's not a big deal, I can easily hit "Super+O" to expel the window. Where it's a bit frustrating is that it often changes the consumed window width, even when it's restored.

I would suggested to have a more complicated shortcut for such functions.
I've changed it to "Ctrl+Super+I" (and "Ctrl+Super+O" for consistency).

It's still easy to consume a window when I want but no more accident :)

Many thanks for you great work.

**Comment by jtaala** [comment]
Hey @bilboquet, we wouldn't change a default shortcut, especially one that has been around a quite a while (doing so ~~wouldn't~~ would change it for all users, including those who like it as it currently is).

Users can change it to what they want though.

Cheers.

**Comment by bilboquet** [comment]
ok that's fine :)
