### ISSUE TITLE
Wayland, "blank" window area labeled @!0,0;BDHF

### ISSUE THREAD

**Issue by matrixes** [paperwm/PaperWM#586]
**Describe the bug**
Using the current release of PaperWM in Ubuntu 22.04 together with Wayland, I have this "blank" window area that I can switch to using Super+Left/Right.

**To Reproduce**
1. Install latest PaperWM by cloning and installing from the "release" branch
2. Log in using Wayland and enable PaperWM
3. Notice there's a bland area that you can switch to.

**Expected behavior**
There should probably not be a blank area like this.

**Screenshots**
![2023-08-24_18-08](https://github.com/paperwm/PaperWM/assets/46491408/377f4480-65ad-4234-8337-bebfe00f9621)

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

```
Please include this information in your bug report on GitHub!
Distribution: Ubuntu
GNOME Shell 42.9
Display server: Wayland
PaperWM branch/tag: release
PaperWM commit: 626bc60077d0fd89b5842a8e6da4bd95c9f988fe
Enabled extensions:
- paperwm@paperwm.github.com
- ding@rastersoft.com
- ubuntu-appindicators@ubuntu.com
- ubuntu-dock@ubuntu.com```

**Comment by Lythenas** [comment]
The only situation where I got this before was when I had a desktop icon extension enabled. It is not in the list enabled extensions you posted (although I don't know what "ding@rastersoft.com" is). Can you double check that you don't have a desktop icon extension enabled (in the Extensions app).

I also don't know if that can cause problems, but can you try disabling the dock extension?

**Comment by matrixes** [comment]
@Lythenas You hit the nail on the head regarding the DING (Desktop Icon Extension) being enabled. Disabling that made everything much better. Thanks!
