### ISSUE TITLE
Workspace Swap triggered by Super+Page UP shortcut

### ISSUE THREAD

**Issue by tmayoff** [paperwm/PaperWM#591]
**Describe the bug**
After updating to the latest release, whenever I try switching workspaces up and down, PaperWM instead swaps them between my monitors. Only way to get workspace switching is by disabling the Swap shortcuts completely. 

**To Reproduce**
1. Press Super+Page Up
2. Experience workspace swapping rather than switching up
3. Press Super+Page Down
4. Experience workspace swapping back rather than switching down

**Expected behavior**
Each keybinding should trigger it's own behaviour.

**Screenshots**

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

```
Distribution: Debian GNU/Linux
GNOME Shell 43.6
Display server: Xorg
PaperWM branch/tag: release
PaperWM commit: 839ba2b9e16eee11b7eebcaed6011ff2f2b4ff0f
Enabled extensions:
- ddterm@amezin.github.com
- openweather-extension@jenslody.de
- paperwm@paperwm.github.com
- material-you-theme@asubbiah.com
- gsconnect@andyholmes.github.io
- appindicatorsupport@rgcjonas.gmail.com
- blur-my-shell@aunetx
- AlphabeticalAppGrid@stuarthayhurst
- nightthemeswitcher@romainvigier.fr
- native-window-placement@gnome-shell-extensions.gcampax.github.com
```

**Additional context**

**Comment by inmanturbo** [comment]
Yes this has crippled me.

**Comment by tmayoff** [comment]
For now you can disable the swap shortcuts in the extension settings, that worked for me

**Comment by inmanturbo** [comment]
Thank you

**Comment by jtaala** [comment]
Thanks for reporting!  Looking at it now.

**Comment by jtaala** [comment]
Hey all, I've now temporarily disabled the new `swap` keybinds and pushed the change into release.  It seems `Super+Alt+left/right` do that same as `Super+page_up/page_down`.

**Comment by jtaala** [comment]
Found it - seems the `Move to workspace on the left` and `Move to workspace on the right` stahdard gnome shortcuts are causing the issue.  PaperWM should be overriding those shortcuts, but seems something awry is going on there.  Will have a look tonight.

**Comment by jtaala** [comment]
![image](https://github.com/paperwm/PaperWM/assets/30424662/a4ced041-fa69-4367-94d2-cc38ef20df28)

Confirmed - seems gnome has some alternate keybinds for this action.

**Comment by jtaala** [comment]
Hey all, this took me a day or so to address (actually rewrote the keybind clash implementation to be simpler and more robust).  See #594.

Are you able to test this new branch (which fixes this, and re-enables the `swap` keybinds)?

```
git fetch --all
git checkout improve-keybind-clash-overiding
```
and then logout/login.

Once logged in, please re-enable the swap keybinds (if you previously disabled them).

Thanks!

**Comment by tmayoff** [comment]
Tested and is working

**Comment by jtaala** [comment]
Morning all!

PR #594, which fixes this issue, as well as many other keybinding related issues, has now been merged into `develop`.

Could I request that users here give the current `develop` branch a good test?  This will then make it's way into the next release.

```
git checkout develop
git pull
```

Then logout/login.

Thanks!

**Comment by jtaala** [comment]
Oops that git command was supposed to checkout `develop` branch (fixed comment now).
