### ISSUE TITLE
Scratch windows not showing in overview

### ISSUE THREAD

**Issue by romaia** [paperwm/PaperWM#601]
**Describe the bug**
When I press the "windows" key to display the overview of all windows, the windows I sent to the scratch layer don't show up, even though I have the setting to "always".

Trying to change the setting does not change the behaviour. When set to "never", no windows show up in the overview.

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

```Distribution: Ubuntu
GNOME Shell 42.9
Display server: Xorg
PaperWM branch/tag: v44.9.2
PaperWM commit: 6366778696bc8d05b8f9802942d6ebd5e341f5eb
Enabled extensions:
- paperwm@paperwm.github.com
- sound-output-device-chooser@kgshank.net
- lockkeys@vaina.lt
- bluetooth-quick-connect@bjarosze.gmail.com
- ubuntu-appindicators@ubuntu.com

```

**Comment by jtaala** [comment]
I see it.  Thanks for reporting!

**Comment by jtaala** [comment]
Looking at this now.  Will push up a PR to fix this in the next day or so.

**Comment by jtaala** [comment]
Hey @romaia, fix has now been merged into `develop` branch and will make it into the next `release` (which I'm planning in the next few days).
