### ISSUE TITLE
Setting use-workspace-name to false breaks extension on GNOME 45

### ISSUE THREAD

**Issue by bbhtt** [paperwm/PaperWM#607]
**Describe the bug**

Follow https://github.com/paperwm/PaperWM?tab=readme-ov-file#click-to-expand-and-see-user-configurable-properties

and do `dconf write /org/gnome/shell/extensions/paperwm/use-workspace-name false`

Restart

See

![image](https://github.com/paperwm/PaperWM/assets/62639087/b4ceb1c7-cad3-464a-aa89-88d79b35c027)

**To Reproduce**

See above

**Expected behavior**

It'd replace the "Workspace 1" with the default activities pill on GNOME 45

**Screenshots**

See above

**System information:**

```
Example:
Distribution: Fedora 39 beta
GNOME Shell 45
PaperWM version: 20 from EGO
Enabled extensions:
- paperwm@paperwm.github.com
- https://github.com/popov895/Clipman
- https://micheleg.github.io/dash-to-dock/
```

**Additional context**

NA

**Comment by bbhtt** [comment]
Oh just noticed the fix here https://github.com/paperwm/PaperWM/pull/605/commits/2b26cdfe750a028ae355fa0ade2b4f3b36007403

**Comment by jtaala** [comment]
Aha!  Good timing.  Yes, it's now fixed in `gnome-45` branch (pull the latest) there.

It's also fixed in https://extensions.gnome.org/extension/6099/paperwm/ as well.

**Comment by jtaala** [comment]
Closing this now.  Latest also fixes the FocusMode icon issue not showing.

Thanks!

**Comment by jtaala** [comment]
Oh, also, if you were trying to use the new Gnome Activities instead of the PaperWM workspace element, you can now do a:

```
dconf write /org/gnome/shell/extensions/paperwm/show-workspace-indicator false
```

and it will instead use the new activities pill.

**Comment by bbhtt** [comment]
> Aha! Good timing. Yes, it's now fixed in `gnome-45` branch (pull the latest) there.
> 
> It's also fixed in https://extensions.gnome.org/extension/6099/paperwm/ as well.

Thanks, when I opened the issue EGO didn't have v22 but it has now.
