### ISSUE TITLE
App not respecting last set window size and animation glitch

### ISSUE THREAD

**Issue by adityainduraj** [paperwm/PaperWM#612]
**Describe the bug**
I am using both Firefox and Vivaldi browser. Firefox and other apps work as intended. But some apps like Vivaldi and Brave Browser face this issue. If I set a window size as 1 step less than full, and then close the app, when I reopen it it opens at full size instead of the set size, and has a pretty ugly animation glitch while doing it. I have attached a screen recording of the same.

**To Reproduce**
1. Open Vivaldi/Brave/some other apps
2. Set window size to full using Super + F, then Super + - to go one step less.
3. Close the app. 
4. Reopen to see above issue.

**Expected behavior**
Should function normally, respecting previous app size and no animation glitch

https://github.com/paperwm/PaperWM/assets/85331139/5b3a0ad6-536f-4621-be4d-1f5cc99c2235

**Screenshots**

**System information:**
Couldn't run gather system info command as I installed PaperWM through extensions.gnome.org. 
Distribution: Fedora 38
GNOME Shell  44
Latest PaperWM from extensions.gnome.org
Extensions enabled: 
PaperWM
Dash to Dock

**Comment by jtaala** [comment]
Thanks for reporting.

Unfortunately (aside for the animation issue), this is an application issue (e.g. brave, vivaldi not remembering / restoring their last window size). 

I use brave and have tested with PaperWM disabled and for me, brave never remembers it last size - it always seems to restore to almost a half-screen width.

I also use the a [default window property rule](https://github.com/paperwm/PaperWM#setting-a-default-window-property-rule) so I brave (and other windows) to 50% width by default - even then brave misbehaves on occasion.

In essence, PaperWM doesn't track or save applications last window sizes (and it shouldn't) - it will simply tile a window with with the size it's given (unless users set a `winprop` rule for that application).

**Comment by jtaala** [comment]
Here's my tests without PaperWM enabled to confirm brave itself is not respecting last size/position:

https://github.com/paperwm/PaperWM/assets/30424662/336eb1ef-aae4-42ac-bd03-1ae5b8a6be3b

Can you confirm you're also seeing this?

**Comment by adityainduraj** [comment]
Oh okay, that's good to know. 
Is there a guide on setting the winprops that I could refer to? I have tried to set some but I must be doing something wrong and I was unable to find any online resources to help me with it.

**Comment by jtaala** [comment]
> Oh okay, that's good to know. Is there a guide on setting the winprops that I could refer to? I have tried to set some but I must be doing something wrong and I was unable to find any online resources to help me with it.

https://github.com/paperwm/PaperWM#setting-window-specific-properties

**Comment by jtaala** [comment]
Easiest to just set them in PaperWM preference settings.

**Comment by jtaala** [comment]
Closing this as it's the application that's not respecting it's own previous/saved sizing.

**Comment by jtaala** [comment]
Will defer to #615 for the animation issues.
