### ISSUE TITLE
Animation Glitch on some Gnome apps like terminal, document viewer etc

### ISSUE THREAD

**Issue by adityainduraj** [paperwm/PaperWM#615]
**Describe the bug**
An animation glitch on apps like Terminal, Document Viewer, Extension-Manager, Extensions, Gradience etc.

**To Reproduce**
1. Open any of these apps (not from dock, using search/keybindings)
2. Look towards the bottom side of the window
3. It initially opens at a weird size and then adjusts, giving a very weird animation

**Expected behavior**
Should open normally like Spotify, Firefox and the others.

**Screenshots**

```
Distribution: Fedora 38
GNOME Shell 44.5
PaperWM branch/tag: latest from extension manager
- paperwm@paperwm.github.com
- switcher@landau.fi
```
[Screencast from 2023-10-04 07-13-41.webm](https://github.com/paperwm/PaperWM/assets/85331139/bca157b6-ab65-4f5a-8bc2-7eb88f59b21a)

**Additional context**
Temporarily fixed by using Burn My Windows extension for a different animation effect.

**Comment by jtaala** [comment]
Hey @adityainduraj,

See #616 for an explanation of what you're seeing.  That PR fixes these opening app animation issues.

Are you able to test this out for me?

You can install this PR version by removing the EGO version of PaperWM, and then (from a terminal):
```
git clone https://github.com/paperwm/PaperWM.git
cd PaperWM
git checkout fix-opening-animation-glitches
./install
```

and then logout / login.

Cheers!

**Comment by jtaala** [comment]
Otherwise, will merge this in in the next few days (and it will make it to EGO then).

**Comment by adityainduraj** [comment]
I tested this out and yes, it does clean up the animation a LOT. Thanks!
Also, can I simply uninstall this particular version through extension manager and install the EGO version or do I need to use the terminal?

**Comment by jtaala** [comment]
You should be able to uninstall just from extension manager and then reinstall EGO version.

**Comment by jtaala** [comment]
Thanks for testing - I'll aim to merge this in tonight.

**Comment by adityainduraj** [comment]
Ok, thanks a ton!

**Comment by jtaala** [comment]
P.S. that's a pretty fancy theme you've got going on there...

**Comment by adityainduraj** [comment]
Lmao yes, I've been spending way too much time on r/unicorn...
