### ISSUE TITLE
allow maximize width (super f) to take up less than 100% width

### ISSUE THREAD

**Issue by KiaraGrouwstra** [paperwm/PaperWM#620]
**Is your feature request related to a problem? Please describe.**
i like to know where i am among my windows, but when i maximize their width i can no longer see anything of the surrounding windows

**Describe the solution you'd like**
it would be nice if the user could configure the max width to allow the user some freedom in this regard

**Describe alternatives you've considered**
- settle for not knowing what's around on max width
- super-f-minus

**Additional context**
cf. seemingly opposite request #585

**Comment by jtaala** [comment]
Hey @KiaraGrouwstra, what version of PaperWM are you running?

To see where you are among windows (whether they are max or not) was the purpose for the [Window Position Bar (coloured bar segment in topbar)](https://github.com/paperwm/PaperWM#window-position-bar-colored-bar-segment-in-top-bar).

**Comment by jtaala** [comment]
Although I can see the utility in having this user configurable and this would be straight-forward to implement.  

If you'd like to test this out you can change this line:

https://github.com/paperwm/PaperWM/blob/d695baaa436508379beb562d6f554b3224316422/tiling.js#L3643
to something like (for example, setting to 80% instead of ~100%):

```javascript
let reqWidth = 0.8*workArea.width - Settings.prefs.minimum_margin * 2;
```

and then change line:
https://github.com/paperwm/PaperWM/blob/d695baaa436508379beb562d6f554b3224316422/tiling.js#L3659

to reference it, e.g.:
```javascript
metaWindow.move_resize_frame(true, x, frame.y, reqWidth, frame.height);
```
Let us know if that works and what you think of it.

**Comment by jtaala** [comment]
P.S. if you're on branch `gnome-44` then the line numbers would be slightly different (but you should be able to find these).

**Comment by jtaala** [comment]
Hey @KiaraGrouwstra,

Can you please test this branch out and let me know how it works?

```
git checkout pref-setting-customise-maximise-width
./install.sh
```

and then logout / login.

NOTE: this PR is based on the `gnome-44` branch so will work for shell versions gnome 42-44.

Thanks!

**Comment by KiaraGrouwstra** [comment]
@jtaala that's perfect, thank you! :smiling_face_with_three_hearts:

**Comment by jtaala** [comment]
Hey @KiaraGrouwstra - just updated this branch and will merge in fix.  I noticed that if set to 0.95, then sometimes when you click on a window to the side, it doesn't actually activate it.

Anyways, will now merge this in and do a new release.

**Comment by jtaala** [comment]
Merged.

**Comment by KiaraGrouwstra** [comment]
nice, can't wait to try it out ^^
