### ISSUE TITLE
Dash to dock misbehaves with window at top of column, no issues with other windows.

### ISSUE THREAD

**Issue by adityainduraj** [paperwm/PaperWM#622]
**Describe the bug**
When window is in the top of the column, it misbehaves with dash-to-dock, which refuses to leave. Only happens with the top window, not the bottom window. PFA the video of the bug.

**To Reproduce**
1. Add minimum of 3 windows.
2. Make a column out of 2 of them
3. Focus on bottom window. Should behave normally. Then focus on top window. 
4. Dash to dock refuses to leave.

**Expected behavior**
Dash to dock should disappear after the normal amount of time same with the rest of the windows.

**Screenshots**
[Screencast from 2023-10-08 17-28-43.webm](https://github.com/paperwm/PaperWM/assets/85331139/32474d37-7684-4edc-965f-82081987ccf7)

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

```

Distribution: Fedora 38
GNOME Shell 44.5
Enabled extensions:
- paperwm@paperwm.github.com
- dash to dock
```

**Additional context**

**Comment by adityainduraj** [comment]
[Screencast from 2023-10-08 17-28-43.webm](https://github.com/paperwm/PaperWM/assets/85331139/4a677192-cac9-4d8c-81dd-f9611adc004a)
not sure if the video uploaded right.

**Comment by jtaala** [comment]
Note: this is a dash-to-dock issue (not PaperWM), for dash-to-dock issues please submit them to dash-to-dock.

In any case:

This is designed behaviour in dash-to-dock (intelligent autohide) - when you think about it it's working as designed (e.g. show dock if no overlap with focused window... which is at the top).

Change the autohide settings in dash-to-dock:

dash-to-dock settings --> `Position and size` --> `Intelligent autohide` --> `Dodge windows` section --> choose `All windows` options.

![image](https://github.com/paperwm/PaperWM/assets/30424662/19e4b1f2-4705-4068-ad4d-ad4fafe1709e)
