### ISSUE TITLE
Desktop switching when cursor moves from primary monitor to secondary

### ISSUE THREAD

**Issue by CapSel** [paperwm/PaperWM#630]
**Describe the bug**
When PaperWM is enabled it works OK only on one of monitors. When moving cursor to other monitor an animation of desktop switching is shown. When I try to move window from primary to external monitor window is immediately moved back to primary monitor.

**To Reproduce**
1. Enable PaperWM (or install)
2. Move window to secondary monitor

**Expected behavior**
Switching desktops should not occur. Window should be moved.

**System information:**
```
Distribution: Arch Linux
GNOME Shell 45.0
Display server: Wayland
PaperWM branch/tag: release
PaperWM commit: 517e1a5c2b69a7ef190eddd712f5d6113ee5f4b2
Enabled extensions:
- thinkpad-battery-threshold@marcosdalvarez.org
- appindicatorsupport@rgcjonas.gmail.com
- places-menu@gnome-shell-extensions.gcampax.github.com
- windowsNavigator@gnome-shell-extensions.gcampax.github.com
- user-theme@gnome-shell-extensions.gcampax.github.com
- arch-update@RaphaelRochet
- dash-to-dock@micxgx.gmail.com
- GPaste@gnome-shell-extensions.gnome.org
```
all extensions were installed via extensions.gnome.org

**Comment by jtaala** [comment]
Thanks @CapSel for the report.  Good timing!  I pushed up a fix and submitted it to extensions.gnome.org about 20 mins ago.

Just waiting for it to get approved on ego.

**Comment by CapSel** [comment]
It kind of had to reset internal data after upgrade - disconnecting and then connecting monitor helped - and now it works ok
