### ISSUE TITLE
TypeError: clone is undefined on unlock

### ISSUE THREAD

**Issue by chromakode** [paperwm/PaperWM#636]
**Describe the bug**

PaperWM errors on unlock with:

```
JS ERROR: TypeError: clone is undefined
allocateClone@/home/chromakode/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:2828:22
init/<@/home/chromakode/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:1761:30
init@/home/chromakode/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:1758:14
initWorkspaces@/home/chromakode/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:2937:20
upgradeGnomeMonitors/<@/home/chromakode/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/utils.js:568:13
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
```

This also consistently repros for me if I try to enable the extension again.

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

```
Distribution: Ubuntu
GNOME Shell 44.3
Display server: Wayland
PaperWM branch/tag: gnome-44
PaperWM commit: 70c70dee7de16e7b3219bd03f9ac06e2396c84d1
Enabled extensions:
- ubuntu-appindicators@ubuntu.com
```

**Additional context**
Appears to be similar to https://github.com/paperwm/PaperWM/issues/492

**Comment by chromakode** [comment]
I was able to narrow down a repro by closing windows and re-enabling the extension. This appears to happen when I use `super+shift+f` to fullscreen a Chrome window running an installed progressive web app, like Home Assistant.

I inspected the window a little in the Gnome Looking Glass shell. The window's `is_override_redirect` returns `false` and `windowType` is `0`.

**Comment by jtaala** [comment]
Great report and potentially narrowing down the issue.

I'll try reproduce.

So, does this occur when you fullscreen the app and then lock/unlock?

**Comment by jtaala** [comment]
Hmm - I installed a PWA (app.todoist.com), fullscreened it, and the locked/unlocked.

Any tips on how to reproduce here?

**Comment by jtaala** [comment]
If you are able to reproduce this error @chromakode, could you try reproduce on this branch:

```
git fetch --all
git checkout fix-636-clone-undefined-on-unlock
./install
```

then logout / login and test?

Thanks @chromakode.

**Comment by jtaala** [comment]
Oh, not sure if you're familiar with installing PaperWM from source:

Steps:

1. uninstall extensions.gnome.org version of PaperWM (don't worry you won't lose your paperwm settings etc.);
2. open a terminal and clone the repo and install:

```
git clone https://github.com/paperwm/PaperWM.git
cd PaperWM
git checkout fix-636-clone-undefined-on-unlock
 ./install.sh
```

Then login / logout.

**Comment by chromakode** [comment]
Thank you @jtaala! I'm running out of a git clone so this'll be easy to test. I'll check it tonight after work.

**Comment by jtaala** [comment]
Oh, of course you are - I should have seen it in the bug report.

Many thanks.

**Comment by chromakode** [comment]
Yep, this does the trick! I can no longer repro the crash on this branch. I also verified rolling back and reproed again. Thanks so much for the speedy fix @jtaala!

**Comment by jtaala** [comment]
Thanks @chromakode.  Did you notice any side-effects or anything else?

I'll merge this in shortly.

**Comment by chromakode** [comment]
I haven't noticed any side-effects yet. I'll open a new issue if I spot any. Thanks again! :heart:
