### ISSUE TITLE
Allow regular expressions in window rules

### ISSUE THREAD

**Issue by Thesola10** [paperwm/PaperWM#653]
**Is your feature request related to a problem? Please describe.**
Given that `config/user.js` is no longer working on GNOME 45, and certain apps such as Waydroid have inconsistent window class names, it would be nice to be able to specify regexps as class names for window rules in the settings GUI.

**Describe the solution you'd like**
A way in the Settings window to specify that the window class or title in the rule is a regular expression.

**Describe alternatives you've considered**
Hard-coding Waydroid exclusion rule in PaperWM source code.

**Comment by jtaala** [comment]
Hey @Thesola10 - this is already supported.

See https://github.com/paperwm/PaperWM#setting-window-specific-properties

> The match of wm_class and title are with an OR condition; and in addition to a plain string matching, a constructed [RegExp()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/RegExp) can be used to utilise regex matching. For example, e.g. `/.*terminal.*/i` would match on any value that contains the word "terminal" (case-insensitive).

![image](https://github.com/paperwm/PaperWM/assets/30424662/29adccd2-38a6-40bd-ac44-6c3ba2e5657e)

**Comment by jtaala** [comment]
Note, make sure to pull the latest release (today I fixed an issue where winprop rules weren't being applied consistently), see https://github.com/paperwm/PaperWM/issues/642.
