### ISSUE TITLE
Glitchy and sluggish window opening and closing animation after updating to latest EGO version.

### ISSUE THREAD

**Issue by adityainduraj** [paperwm/PaperWM#657]
**Describe the bug**
The window opening animation has become very sluggish and glitchy after updating to the latest EGO version. The window appears and disappears from the left side of the screen instead of smoothly appearing where the new window is supposed to open, causing at least 2-3s of additional delay while opening windows. Tried to go back to previous version from the Releases page but it said that that version is incompatible with the version of GNOME I have installed. 

**To Reproduce**
1. Install latest version of PaperWM on Gnome 45 from EGO.
2. Try opening new windows. They appear from bottom left of screen and the animation is very glitchy and slow. Not like previous versions.
3. 

**Expected behavior**
Smooth animation where window appears from the designated area for the new window. Screen recordings attached for reference.

**Screenshots**
Current version (GLITCHED ONE)
https://github.com/paperwm/PaperWM/assets/85331139/f8c08d95-3151-4853-b642-9d854ec3caf3

Old smooth version

https://github.com/paperwm/PaperWM/assets/85331139/a27e4952-0d7b-4113-8fb7-629f2c8b7344

Unfortunately the only video I have is this of the older one, and I can't test the older one out as it says it is incompatible with my version of GNOME.

**System information:**

Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

```
Example:
Distribution: Fedora 38
GNOME Shell 44.5
PaperWM branch/tag: latest EGO version
Enabled extensions:
- paperwm@paperwm.github.com
- dash to dock
- burn my windows

```

**Additional context**

**Comment by jtaala** [comment]
Yes, these animation changes were required to fix https://github.com/paperwm/PaperWM/issues/642.  Basically there was an animation race condition (which our custom animation) which broke winprop functionality (or made it very inconsistent).

We're now using just gnome window animation (which often opens it somewhere, e.g. to the left) and then PaperWM moves it into place.

> but it said that that version is incompatible with the version of GNOME I have installed.

Sounds like you pulled a Gnome 45 version on ego (there's two versions there, gnome 42-44 and gnome 45.  If you want to download previous version(s) for Gnome 44, make sure choose the 44 shell (try version 40):

![image](https://github.com/paperwm/PaperWM/assets/30424662/fc9b985e-a92c-4114-b1dd-eb47a344f810)

**Comment by jtaala** [comment]
I'll see if we can improve anything there without breaking the winprop functionality.

**Comment by jtaala** [comment]
> causing at least 2-3s of additional delay while opening windows

No, the actual opening of windows is done in the same `animation_time` regardless of what the animation looks like.  Previously we were "hiding" part of the animation with a workaround/hack (basically setting opacity to 0). 

This isn't really a bug, but rather fixes a bug and removes some workaround code - but it has introduced an animation change which isn't as good as the previous one.

**Comment by jtaala** [comment]
Okay, I think I can restore the previous animation while keeping winprop fix code.  I'll give this a go today.

**Comment by jtaala** [comment]
Have a fix, just testing this.  Will push this today sometime.

**Comment by adityainduraj** [comment]
> Have a fix, just testing this.  Will push this today sometime.

Awesome, thanks a million!

**Comment by adityainduraj** [comment]
@jtaala when will these fixes be pushed to the EGO version? Also, is there a specific version that I need to install?

**Comment by jtaala** [comment]
It's already been submitted to EGO - but hasn't been looked at yet by EGO team (they look at and approve every version).  For gnome-44 you'll be wanting version 48 on EGO.

Alternatively you can install the source release.  Just delete the EGO version (don't worry your settings / config are saved) and then do a:

```
git clone https://github.com/paperwm/PaperWM.git
cd PaperWM
git checkout gnome-44
./install.sh
```

And then logout / login.

Otherwise just wait for the EGO version to become available (usually doesn't take too long).

**Comment by adityainduraj** [comment]
Okay, this worked, the animation is back to perfect again. Thank you so much!

**Comment by jtaala** [comment]
yay!

**Comment by jtaala** [comment]
Yeah, if you want to get back on the EGO version again just delete PaperWM and install from EGO again (but wait until they approve/release version 48).

**Comment by jtaala** [comment]
Just a note that latest versions are now on EGO (so you can install from EGO again if you wanted).
