### ISSUE TITLE
Only steal built-in actions if their binding collide with our actions

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/PaperWM#66]
Write-up based on [discussion](https://matrix.to/#/!xMhYMdDfRQyjlSrmQN:matrix.org/$1529944045159203gPczU:matrix.org) in our chat room.

Atm. we change the meaning of built-in actions whose default binding collide with one of *our* default bindings.

eg.  The default binding of (our) `live-alt-tab` is <kbd>Super+Tab</kbd> which collide with the default binding of (gnome-shell's) `switch-applications`.

Unfortunately gnome-shell/mutter doesn't have a proper system for resolving such conflicts(?). Which action "wins" is somewhat random.

That leaves two options for problematic built-in actions:
1. Change the action's binding
2. Change the action's meaning (ie. which function that is called)

1 is invasive since it persists reboots/uninstallation of our extension. We could make an effort to restore the binding on disable, but disable isn't exactly guaranteed to run (things can crash etc).

2 works well. It's a bit work to restore the default behavior\[1\] for some actions, but the majority can easily be reset to the default behavior. It is robust - removing the extension and rebooting will result in a clean slate. 

BUT it is very annoying for users that have rebound the built-in actions - or rebound our actions.

\[1\] the right thing to do when disabling the extension

As a principle we should not touch built-in actions unless there is a conflict between the *actual* bindings.

gnome-shell/mutter works against us in achieving a fully general solution: not all aspects of the keybinding system is "inspectable":
- It's not possible to list all bindings
- It's not possible to ask for the associated settings object of an action
- It's not possible to ask which key-combos an action is bound to.

But we know where the built-in actions are specified so something like this goes a long way:

```
    function isBound(binding, action, settings) {
        // Can use Gtk.accelerator_parse to deal with different ways of writing the binding string
        return settings.get_strv(action)
            .map(k => k.toLowerCase()).includes(binding.toLowerCase());
    }
    if (isBound('<super>tab', 'live-alt-tab', paperSettings) &&
        isBound('<super>tab', 'switch-applications', settings)) {
        setKeybinding('switch-applications', // <Super>Tab
                      paperActions.byName('live-alt-tab').handler);
    }
```

It's also possible to ask if a key combo is bound at all so we can add a warning notification if any of our actions can not be bound (could happen if another extension use the binding)

If we need to redefine built-in actions we should ideally show a notification/warning the first time the extension runs.

(ping @xanf)

**Comment by hedning** [comment]
@xanf we just finished up a functional, if not beautiful,  preference UI.

I'm now eager to get a working solution for the keybindings, incorporating your well laid out ideas above. Did you get anywhere with an implementation we could build upon? If not I'll just start coding something up.

**Comment by xanf** [comment]
Sorry, I'm out of big coding at least for one week yet, so if you do not want to wait you can start coding something up, hope I will jump in

**Comment by hedning** [comment]
No problem, I'll start getting something up and running then.

**Comment by hedning** [comment]
Prototype (not any warnings or UI yet) in [keyconflicts](https://github.com/paperwm/PaperWM/tree/keyconflicts) branch.

**Comment by hedning** [comment]
I've added basic integration with the preference UI:

![tooltip - 1](https://user-images.githubusercontent.com/71978/42733552-4a8a1002-8833-11e8-95f0-4b2e69b43132.png)

If the keybinding conflicts with one of the builtin bindings it will show a warning icon to the left and the tooltip is set describing the conflict.

The toggle button to the right resets the binding to its default value.

**Comment by hedning** [comment]
Pushed basic support to master a few days ago, with integration in the preference UI. It's now possible to go into the preference UI (or dconf for that matter) and eg. delete the `<super>Home/End` bindings, automatically handing control of these keycombos back to Gnome Shell. No restarts required :)

**Comment by hedning** [comment]
This is also done, the preference UI isn't super pretty, but the basic functionality is there.
