### ISSUE TITLE
Unable to interact with the minimized window once it's restored

### ISSUE THREAD

**Issue by paradajz** [paperwm/PaperWM#666]
**Describe the bug**

Once the window has been minimized and restored by clicking on it in the overview, interaction with it is impossible. The only way to restore the interaction is to switch the window back from scratch mode (in the video below I've hit the keyboard combination to remove the window from scratch layer).

**To Reproduce**
1. Open any application
2. Minimize it
3. Open overview
4. Click on the minimized window
5. Try to interact with the window

Demo:

[Screencast from 2023-11-04 07-52-54.webm](https://github.com/paperwm/PaperWM/assets/2544094/b6512884-fb36-42db-963c-bb3c506f4919)

From 12sec onwards I'm clicking all over the window but nothing is happening until I remove the window from scratch layer via keyboard shortcut.

**System information:**

```
> ./gather-system-info.sh
Please include this information in your bug report on GitHub!
Distribution: openSUSE Tumbleweed
GNOME Shell 45.0
Display server: Xorg
PaperWM branch/tag: develop
PaperWM commit: c9606090ecee5206601279f2a6849c4dde20c6b5
Enabled extensions:
- paperwm@paperwm.github.com
- Vitals@CoreCoding.com
- clipboard-history@alexsaveau.dev
- launch-new-instance@gnome-shell-extensions.gcampax.github.com
```

**Comment by jtaala** [comment]
Hmmm - haven't been able to reproduce as yet.  Tried to do exactly what you're doing:

https://github.com/paperwm/PaperWM/assets/30424662/bfeb3407-af7b-4f97-964e-95fe32496d98

You getting any errors / output from `journalctl -f /usr/bin/gnome-shell` when this happens for you?

**Comment by paradajz** [comment]
No, I don't see anything there, forgot to mention.

**Comment by jtaala** [comment]
ha - might be an issue just on xorg?  Did this just start happening for you?

**Comment by jtaala** [comment]
I'll put some labels up to see if others are seeing this.

**Comment by paradajz** [comment]
To be honest I'm not sure when did it start. I don't minimize windows often so... Let me try it on Wayland.

**Comment by paradajz** [comment]
Yeah, on Wayland it works fine.

**Comment by jtaala** [comment]
Yeah, me too (I don't minimize often and I haven't used xorg for quite a while now).

Ah, okay, yep, I can see it on X11 - looks like hasn't activated window properly (and I had to click/select a different window and back again to get control again).

Will have a looksy into this one.

Thanks for reporting!

**Comment by jtaala** [comment]
Hey @paradajz,

So a bisect identified the commit (a27d316) where this issue was introduced (for X11).

It's actually when coming out of overview (e.g. selecting a scratch window in overview) where the issue occurs.  Interestingly it just occurs in X11.

Anyways, I've implemented a fix, just testing to make sure it doesn't cause any regressions (in X11 or Wayland).

**Comment by jtaala** [comment]
Hey @paradajz,

See PR #668 for fix.

Could you please test this out? (especially in X11)?

```
git checkout fix-666-cant-control-scratch-window-restore-from-minimise-gnome45
./install.sh
```

Then login/logout.

Let me know how it goes!
