### ISSUE TITLE
Make the workspace indicator optional

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/PaperWM#67]
Some users might want to use another extension instead. The interaction with the "hot corner" is also a weird atm.

**Comment by xanf** [comment]
Still need an ability to set workspace params though (background color for example). Probably in settings?

**Comment by hedning** [comment]
I think a good solution here is making the WorkspaceMenu toggle the overview by default, only showing the config menu on right click (I like the idea that clicking on the workspace name takes you to the overview). Pushed a fix for that now.

We could then add a setting which would simply set text to the original `Activities`, which should be pretty easy to maintain compared to disabling our own menu entirely.

**Comment by hedning** [comment]
Done in adcfa414add974355cd04c3608c26aa07c260215
