### ISSUE TITLE
Disable Overview transition animation on window selection

### ISSUE THREAD

**Issue by mepowerleo10** [paperwm/PaperWM#672]
**Is your feature request related to a problem? Please describe.**
Sometimes selecting a window from the overview is much faster than navigating using the keyboard. But each time I select a window from the overview when using PaperWM, the overview translation animation runs which gets disorienting after multiple uses.

**Describe the solution you'd like**
Instead of animating the translation to the window selected from the overview, there can be an option to just fade in the window.

**Describe alternatives you've considered**
- Speeding up the animations for the GNOME shell
- Disabling animations
- Speeding up animations in PaperWM

**Additional context**
https://github.com/paperwm/PaperWM/assets/26873863/9778a130-a13d-4d54-b51b-ad9fb07d22f1

**Comment by jtaala** [comment]
Do you mean the entire overview animation (including gnome overview animation) or just the animation at the end (where PaperWM takes you to the tiled position of the window that was selected)?

Interestingly, if you mean the latter - then that's what used to happen [but this issue](https://github.com/paperwm/PaperWM/issues/347) saw that behaviour as a glitch (or at least more confusing).

**Comment by jtaala** [comment]
> Instead of animating the translation to the window selected from the overview, there can be an option to just fade in the window.

This is kind of interesting - we can't really change the gnome overview exit animation, but fading out / in to show the new window position might look kind of cool (or weird).

If anyone is interested in giving this one a go feel free to submit a PR for this.

**Comment by mepowerleo10** [comment]
I mean the animation at the end. If you have 10 windows on the same workspace, it just gets even more confusing.

> Interestingly, if you mean the latter - then that's what used to happen [but this issue](https://github.com/paperwm/PaperWM/issues/347) saw that behaviour as a glitch (or at least more confusing).

Oh! I missed that issue, but is it possible to have an option to switch this behaviour on/off? Or it interferes with the current implementation?

**Comment by jtaala** [comment]
Well, it's possible - previously it just snapped to the window (see videos from that issue) which was quite disjoint after the gnome overview exit animation zoom in back in... then snapping/jumping to another window (that might be tiled offscreen).

**Comment by jtaala** [comment]
Anyways, making that an option is fairly trivial - but I think the fading might be a pretty cool (less jarring?) option?

**Comment by jtaala** [comment]
@mepowerleo10, what do you reckon?  Better or worse?  This uses a slight fade-in effect (instead of the translation effect) after overview:

https://github.com/paperwm/PaperWM/assets/30424662/d4593740-a22f-493e-bb10-dd982f6c0c16

**Comment by mepowerleo10** [comment]
> Anyways, making that an option is fairly trivial - but I think the fading might be a pretty cool (less jarring?) option?

The fading effect might be a nice touch

**Comment by mepowerleo10** [comment]
> @mepowerleo10, what do you reckon? Better or worse? This uses a slight fade-in effect (instead of the translation effect) after overview:
> 
>  Kooha-2023-11-08-21-07-36.mp4

I think this is much better @jtaala

**Comment by vvvvvvitor** [comment]
> @mepowerleo10, what do you reckon? Better or worse? This uses a slight fade-in effect (instead of the translation effect) after overview:
> 
>  Kooha-2023-11-08-21-07-36.mp4

Much better, but it would be even better if it just used the normal gnome animation like previously.

**Comment by jtaala** [comment]
> Much better, but it would be even better if it just used the normal gnome animation like previously.

Indeed would be great, but gnome overview isn't aware of how we tiled windows and how we move the entire scrolling container - so it animates windows to where it was offscreen... hence we can only control what happens after overview exit animation.

~~If someone wants to give the above a go though (although I think it would require rewriting quite a bit of gnome overview animation/easing code etc.), we would def accept a PR for it.~~

**Comment by jtaala** [comment]
Actually, we might be able to pre-move the cloneContainer (Clutter container that holds our tiled clones) and have it in place before exit animation starts... (maybe).

I'll play around some more with this after we merge in #679.

**Comment by jtaala** [comment]
Hey all,

I've added options to PaperWM settings now to set the Gnome overview (exit) "select window" animation.  See #715.

To test this out:

```
git clone https://github.com/paperwm/PaperWM.git
cd PaperWM
git checkout enhancement-672-overview-exit-transition-animation
./install.sh
```

then logout / login.

**Comment by jtaala** [comment]
> Actually, we might be able to pre-move the cloneContainer (Clutter container that holds our tiled clones) and have it in place before exit animation starts... (maybe).
> 
> I'll play around some more with this after we merge in #679.

Just commenting on this.  So, we do use the default Gnome overview - problem with the overview animation is it return to the original window positions... so we still need a "post" Gnome Overview animation to bring the tiled window into view.

You can see this by disabling PaperWM and moving a window right offscreen (to simulate what PaperWM does) and then going into overview and selecting that window:

https://github.com/paperwm/PaperWM/assets/30424662/82170e63-e224-4cf6-a08f-5572ae5f77e7
