### ISSUE TITLE
howto question: windows not using all the space

### ISSUE THREAD

**Issue by stefangweichinger** [paperwm/PaperWM#673]
I assume it's an FAQ and I am missing something. Forgive me, I am a user in its first hour of using PaperWM ;-)

What do I have to do to have my windows use all the place and not leave a small gap around as shown here:

![image](https://github.com/paperwm/PaperWM/assets/2673904/c3915fd5-925b-4973-9e64-fa150490a6ed)

I can't always do an active "maximize window" after changing windows ... (?)

thanks for any help on this, looking forward to using this innovative software.

**Comment by stefangweichinger** [comment]
Let me add something:

This is Fedora 39 workstation. I just checked if I have any other extensions that might conflict and logged out/in again.

What I also notice: `Alt-Tab` doesn't work currently. So I might have some additional issues ...

**Comment by jtaala** [comment]
Please take time to read the [README](https://github.com/paperwm/PaperWM#readme) (it will save you a lot of time in understanding PaperWM).

Gaps etc. can be changed from PaperWM settings (extension settings):

![image](https://github.com/paperwm/PaperWM/assets/30424662/fe48d60a-9d99-42f8-8ac8-73cc1e6809c6)

**Comment by jtaala** [comment]
Finally, PaperWM uses it's own window switching etc.  Default is `Super`+`Tab`, although you can change this to your liking in PaperWM settings (e.g. this one will change this to `Alt`+`Tab`):

![image](https://github.com/paperwm/PaperWM/assets/30424662/dd8c52fd-45d7-408c-87a0-0a64d1040b80)

**Comment by stefangweichinger** [comment]
Thanks! I have the README already pinned in my browser ... working through it and trying things.

**Comment by jtaala** [comment]
It's also often helpful to open the `extensions` app and click PaperWM settings to see all the options.  Looking through the keybindings will be helpful to see what you can do and then change them to your preference.

**Comment by jtaala** [comment]
> I can't always do an active "maximize window" after changing windows ... (?)

Not sure what you mean here, but see:
https://github.com/paperwm/PaperWM#setting-window-specific-properties

and 

https://github.com/paperwm/PaperWM#setting-a-default-window-property-rule

for setting default window width rules.

**Comment by stefangweichinger** [comment]
@jtaala thank you. fiddled with the gaps, the vertical gap doesn't really change here AFAI see. But I have to be patient and proceed to learn things. Will test on a second machine later, and see if it behaves the same there (laptop vs. desktop system).

**Comment by jtaala** [comment]
I'm not sure what you mean by "vertical gap"?  E.g. setting all gaps to 0 will remove spacing and the border (although that would make it much harder to see current window).

**Comment by jtaala** [comment]
Basically, you can set the gaps at the top / bottom of windows, gaps at the left / right of screen (horizontal margin) and then gaps between windows.

Closing this ticket.

Note these issues are for bug reports, or feature requests etc.  To learn and ask questions of others / learn stuff feel free to join the [zulip chat](https://paperwm.zulipchat.com/).

**Comment by stefangweichinger** [comment]
![image](https://github.com/paperwm/PaperWM/assets/2673904/f1076bb5-22a6-4024-b0cb-07f2bea11ced)

By gap I mean the blue space to the left and above the window.

Is it intended to look like that? On my desktop system I could maybe live with "wasting space", on my laptop I'd prefer to use every pixel available. Maybe I habe to get used to the look ...

Thanks for the help, and the pointer to the chat. Might join in there, yes.

**Comment by jtaala** [comment]
Ah, I see - did you set gaps to 0?  Like this:

![image](https://github.com/paperwm/PaperWM/assets/30424662/e1698622-8ee1-410b-999e-1bebec8295a6)

Windows will then look like this:

![image](https://github.com/paperwm/PaperWM/assets/30424662/b611b884-40b7-42be-b766-93f27fe72fd3)
