### ISSUE TITLE
Shortcut "Move window one workspace up/down" doesn't work

### ISSUE THREAD

**Issue by Ancairon** [paperwm/PaperWM#674]
**Describe the bug**

When I assign a key and focus on a window, upon activation of the shortcut I just switch from the wall view to the up/down workspace, without moving the actual window.

**To Reproduce**
1. Set the shortcut
2. Trigger shortcut

**Expected behavior**

To be able to move the active window to the up/down workspace

**Screenshots**

**System information:**

I have the gnome extension

**Additional context**

Bug is present in both Xorg and Wayland, albeit in wayland I found a lot of things breaking, so I am trying to get this working on Xorg mainly.

**Comment by rodrigogonegit** [comment]
Can confirm it also does not work for me

**Comment by jtaala** [comment]
Thanks for reporting.

Need a bit more information here.  

1. what do you mean by "wall view"?
2. what "shortcut" are you talking about?  is this a shortcut from another extension?

In PaperWM to 

https://github.com/paperwm/PaperWM/assets/30424662/7ce288b9-077c-4f56-a965-6c9a43ae84ce

move windows to another workspace you generally use the `Take the window, dropping it when fininshed navigating` keybind (default `Super`+`T`):

**Comment by paradajz** [comment]
I actually have the same issue. The shortcut for taking the window and moving it to another workspace stopped working fairly recently.

**Comment by paradajz** [comment]
![image](https://github.com/paperwm/PaperWM/assets/2544094/2e7d1a83-ee3f-4556-81c1-83a6cec0470e)

These shortcuts now result in switching between workspaces instead of moving the windows workspace left/right.

**Comment by jtaala** [comment]
Ah - I see!  Apologies, misunderstood the issue.  Thanks for reporting all!

Okay, will look a this one to see where it went wrong.

**Comment by borring** [comment]
I just upgraded to Gnome 45, so I got latest from develop to get the extension working.

This was the result of the bisection:
```
1ccb092f2cb885b1409253c8c6e5db4ae51aec4d is the first bad commit                                         
commit 1ccb092f2cb885b1409253c8c6e5db4ae51aec4d                                                          
Author: Jay Ta'ala <jay@jaytaala.com>                                                                    
Date:   Sat Oct 28 13:15:31 2023 +1100                                                                   
                                                                                                         
    Small improvements.  Main one is option to draw the space on a monitor                               
    without actually setting the space.monitor to it.  I.e. only set the                                 
    monitor to a space if it's actually selected.                                                        
                                                                                                         
 tiling.js | 19 +++++++++++--------                                                                      
 1 file changed, 11 insertions(+), 8 deletions(-) 
 ```

**Comment by jtaala** [comment]
Thanks @borring!  I was just about to do a bisection.  Interestingly, it's working in our gnome-44 branch (just not gnome-45).

**Comment by jtaala** [comment]
Let me confirm.  Yep, I see it.

**Comment by jtaala** [comment]
Ahhh - found it, equality check issue:

https://github.com/paperwm/PaperWM/blob/0e4af8606b9b44edc2b3371a0474492a67e75db0/tiling.js#L2391 (should be looser equality).

**Comment by jtaala** [comment]
I'll push a fix up shortly.

Again, thanks for reporting all (@borring for pinpointing the commit where it happened).

**Comment by jtaala** [comment]
Hey all, can you please test latest `develop`?

```
git checkout develop
git pull
```
logout and then login.

Will be kicking off a release shortly.

**Comment by jtaala** [comment]
Hey all,

Fix has been released and is now in `develop` and `release` branch.

I've also submitted the fixed version to EGO (which after a quick review by their team, will be available for EGO users).

**Comment by borring** [comment]
> I'll push a fix up shortly.
> 
> Again, thanks for reporting all (@borring for pinpointing the commit where it happened).

np. Thanks for the quick fix!
I knew it had to be some sort of javascript shenanigans.
