### ISSUE TITLE
Window from another workspace starts glitching.

### ISSUE THREAD

**Issue by iitzrohan** [paperwm/PaperWM#675]
**Describe the bug**
When there are multiple apps opened on another workspace, if you select any app other than the first and then switch to previous workspace. It starts glitching.

**To Reproduce**
As shown in the video.

**Expected behavior**
It should not be glitched.

**Screenshots**

https://github.com/paperwm/PaperWM/assets/104166410/213e8165-c0fc-4fbd-89e0-32d8fc97c059

**System information:**

```
Distribution: Fedora Linux
GNOME Shell 45.1
Display server: Wayland
PaperWM branch/tag: release
PaperWM commit: 0e4af8606b9b44edc2b3371a0474492a67e75db0
Enabled extensions:
- AlphabeticalAppGrid@stuarthayhurst
- Battery-Health-Charging@maniacx.github.com
- clipman@popov895.ukr.net
- color-picker@tuberry
- hotedge@jonathan.jdoda.ca
- supergfxctl-gex@asus-linux.org
- quake-terminal@diegodario88.github.io
- unsafe-mode-menu@linushdot.local
- miniview@thesecretaryofwar.com
- paperwm@paperwm.github.com
- Vitals@CoreCoding.com
- guillotine@fopdoodle.net
- grand-theft-focus@zalckos.github.com
- appindicatorsupport@rgcjonas.gmail.com
- user-theme@gnome-shell-extensions.gcampax.github.com
- blur-my-shell@aunetx
- smile-extension@mijorus.it

```

**Comment by Lythenas** [comment]
I believe this might be related to #672 Does the glitch also happen if you switch workspaces using the PaperWM keybindings? E.g. `Super+PageUp/Down`

**Comment by iitzrohan** [comment]
@Lythenas  It doesn't happen when changing workspace. Only when toggling them. And yes,even after i move to another workspace with PaperWM keybind, it still happens on pressing windows key(i.e toggling workspace).

**Comment by jtaala** [comment]
This is actually an upstream / gnome issue or behaviour (not PaperWM's). 

E.g.: disable PaperWM (use standard gnome) and move a window on the second workspace offscreen:

https://github.com/paperwm/PaperWM/assets/30424662/bb8a596f-6d61-4e0a-826b-96102979af5a

The above is with PaperWM disabled (just gnome).

Feel free to submit an issue to Gnome - but it's actually standard behaviour in gnome for an offscreen window and multiple workspaces.

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues

**Comment by jtaala** [comment]
Closing this ticket now as upstream issue (would need to be changed in Gnome).
