### ISSUE TITLE
Settings UI

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/PaperWM#68]
Atm, dconf-editor with a [hack to make the extension schema known](https://gist.github.com/olejorgenb/2654a1ee7a91de3af5f9d95ad7c9f00e) and/or gnome-shell-mode works as a poor-mans/expert UI for settings.

Ideally we'd like something more polished of course. Changing keybindings and "composite"\[1\] settings  isn't very pleasant in dconf-editor for instance. 

\[1\] eg. per-workspace settings (#6) - dconf-editor only understands schemas for "preallocated" settings - meaning such settings will either: have bad names (workspace-1, ...) and be limited to some fixed number of objects - or - have good names, no limits, but no schema, meaning no description and no documentation of default values.

**Comment by hedning** [comment]
Started working on this in the  [prefs](https://github.com/paperwm/PaperWM/tree/prefs) branch.

**Comment by olejorgenb** [comment]
Closed by e21433333caa7ed9c1dcf5d8cb77a8bec800f0e2...8c39bb2e212af7d4d7764d80a4adbd2d7a6c11f5
