### ISSUE TITLE
Better touchpad support

### ISSUE THREAD

**Issue by vvvvvvitor** [paperwm/PaperWM#680]
Currently touchpad support is rather lackluster, while there are basic gestures like scrolling with 3 fingers, others are completely missing even though they are pretty important.

Here are some that I noticed while using. (May update.)
- Scrolling while moving a window
- Tiling
- Switching workspaces

**Comment by jtaala** [comment]
Please see the touchpad section on configuring gestures:

https://github.com/paperwm/PaperWM#touchpad-gestures

**Comment by jtaala** [comment]
Hey @vvvvvvitor,

Check that link out.  For workspace switching, we provide 3-finger swipe down (which uses PaperWM's concept of spaces... including nicer workspace previewing).  You can also pull it down part-way and then 3-finger swipe on the part shown workspace to move through the tiling.

Of course you can also disable that and use the default gnome workspace switching gestures (and then switch tiling swiping to 4-fingers) - see https://github.com/paperwm/PaperWM#touchpad-gestures for how to do that.

See video below of using PaperWM's 3-finger swipe down to peek at other workspace windows (or click to select that window):

https://github.com/paperwm/PaperWM/assets/30424662/3aba19f5-9574-4890-b925-9b71196a76fa

**Comment by jtaala** [comment]
I don't know what you mean by these two, can you elaborate?

- Scrolling while moving a window
- Tiling

I.e. what would gestures for above look like? (and what would they do?).

**Comment by jtaala** [comment]
Finally, we're happy with the current gestures and configurability.  However, we'd definitely consider any PR you might provide here!

**Comment by vvvvvvitor** [comment]
> I don't know what you mean by these two, can you elaborate?
> 
> * Scrolling while moving a window
> * Tiling
> 
> I.e. what would gestures for above look like? (and what would they do?).

You can't scroll the workspace while holding a window, sometimes it even bugs making the windows freeform.

[Gravação de tela de 2023-11-11 13-06-32.webm](https://github.com/paperwm/PaperWM/assets/119557151/c28bc016-2a0f-402e-bbd3-2182b2cff387)


As for tiling, it ins't a feature on default GNOME but it would be extremely useful to have the ability to tile the windows with gestures.

[Gravação de tela de 2023-11-11 13-09-57.webm](https://github.com/paperwm/PaperWM/assets/119557151/4bfba207-6935-4667-9cff-3d583fa55cb6)

**Comment by vvvvvvitor** [comment]
> > I don't know what you mean by these two, can you elaborate?
> > 
> > * Scrolling while moving a window
> > * Tiling
> > 
> > I.e. what would gestures for above look like? (and what would they do?).
> 
> You can't scroll the workspace while holding a window, sometimes it even bugs making the windows freeform.
> 
>  Gravacao.de.tela.de.2023-11-11.13-06-32.webm 
> 
> As for tiling, it ins't a feature on default GNOME but it would be extremely useful to have the ability to tile the windows with gestures.
> 
>  Gravacao.de.tela.de.2023-11-11.13-09-57.webm

**Comment by jtaala** [comment]
> You can't scroll the workspace while holding a window, sometimes it even bugs making the windows freeform.

This is specifically what the `Take the window, dropping it when finished navigation` is for (default keybind `Super+T`):

https://github.com/paperwm/PaperWM/assets/30424662/b2067b7b-8a70-4f80-8f83-a0ad6a3a92bd

**Comment by jtaala** [comment]
> sometimes it even bugs making the windows freeform

This is how window dragging works and is designed (it's not a bug).  You can drag a window and tiling prompts appear to slot in windows between other windows (in the tiling stack).  Dropping a  dragged window outside of those prompts will add the window to the scratch layer (floating).

**Comment by jtaala** [comment]
Good news is this is open-source!  You are free to fork PaperWM and change that bahaviour and then submit PRs back for consideration (or just continue using your fork).

**Comment by jtaala** [comment]
> As for tiling, it ins't a feature on default GNOME but it would be extremely useful to have the ability to tile the windows with gestures.

How would that work exactly? Could you describe a gesture and what that gesture would do?  I can't see it - keybinds make more sense to me here.

**Comment by vvvvvvitor** [comment]
> > sometimes it even bugs making the windows freeform
> 
> This is how window dragging works and is designed (it's not a bug). You can drag a window and tiling prompts appear to slot in windows between other windows (in the tiling stack). Dropping a dragged window outside of those prompts will add the window to the scratch layer (floating).

Really? It feels kinda weird, the windows even appear in a workspace they are not in and I couldn't find a way to make them go to normal behaviour again, are you sure that's intentional?

**Comment by jtaala** [comment]
Yes, it's the scratch layer.  See this: https://github.com/paperwm/PaperWM#scratch-layer

**Comment by jtaala** [comment]
Also see this comment https://github.com/paperwm/PaperWM/issues/661#issuecomment-1789628782.

**Comment by jtaala** [comment]
I'd really encourage you to read the [README](https://github.com/paperwm/PaperWM#readme).  It will save you a lot of time in understanding PaperWM concepts and how things are designed to work.

It works (by design) differently to concepts in floating/window based paradigms.

**Comment by jtaala** [comment]
> As for tiling, it ins't a feature on default GNOME but it would be extremely useful to have the ability to tile the windows with gestures.

For this type of tiling, see these keybinds which do these actions:

![image](https://github.com/paperwm/PaperWM/assets/30424662/0d9f4cba-6913-4328-bd82-505b3ade8790)

**Comment by vvvvvvitor** [comment]
> I'd really encourage you to read the [README](https://github.com/paperwm/PaperWM#readme). It will save you a lot of time in understanding PaperWM concepts and how things are designed to work.
> 
> It works (by design) differently to concepts in floating/window based paradigms.

I see, It's just that from a user's perspective it's not really that intuitive it seems, I'll read more about it.

**Comment by jtaala** [comment]
Yes, there's a still a learning curve when using PaperWM! (particularly it's concepts).  But the same could be said for all other tiling window managers (many of us come from other window manager paradigms, like i3wm, awesomewm, Herbstluftwm etc.).

It's definitely not for everyone (although to be fair we didn't develop it for everyone... more for how we wanted it to work).

But it's open-source!  So, anyone can take it and modify / re-develop to how they think it should work.  Definitely feel free to jump into develop, experiment, make changes, and submit PR's with your ideas back to the project.

**Comment by jtaala** [comment]
Having said that - there's a decent argument to have the window just drop back into the tiling layer (instead of the scratch layer)... which would prob help minimize confusion for new players (although  they'd still have to learn about the scratch layer eventually... but at least that learning won't be as forced?).

@Lythenas - what do you reckon about this change?  Granted, there's much better ways to move windows in PaperWM!

**Comment by vvvvvvitor** [comment]
> Having said that - there's a decent argument to have the window just drop back into the tiling layer (instead of the scratch layer)... which would prob help minimize confusion for new players (although they'd still have to learn about the scratch layer eventually... but at least that learning won't be as forced?).
> 
> @Lythenas - what do you reckon about this change? Granted, there's much better ways to move windows in PaperWM!

What if it goes to the scratch layer when dragging up instead?

**Comment by jtaala** [comment]
I think that'll be even more confusing and others will think that's even more of a bug.

**Comment by Lythenas** [comment]
> @Lythenas - what do you reckon about this change? Granted, there's much better ways to move windows in PaperWM!

For anything touch I don't have a particularly strong opinion, since I don't use it. But dropping it back into tiled seems fine.

I think dragging up is not a very good choice because that should put the window at the top of the column (it also shows an indicator if dragged there with the mouse). Maybe wiggling the window would be an option. But that's probably not that easy to implement properly.
