### ISSUE TITLE
Disable topbar transparency

### ISSUE THREAD

**Issue by vvvvvvitor** [paperwm/PaperWM#681]
**Is your feature request related to a problem? Please describe.**
I don't really like how the topbar looks currently, also doesn't look native to the system as transparency effects are almost never used in the system. I also have no idea why it looks like that, I don't see it having any meaningful purpose, wouldn't such functionality be better in a separate extension?

**Describe the solution you'd like**
An toggle or slider to change the topbar's transparency.

**Describe alternatives you've considered**
There are none,

**Comment by jtaala** [comment]
> There are none,

There are.  Please take the time to read the README.md.

https://github.com/paperwm/PaperWM#gnome-topbar-opacity--styling

It's required for the [Window Position bar](https://github.com/paperwm/PaperWM#window-position-bar-colored-bar-segment-in-top-bar) functionality (which shows you where the currently selection window is your tiling stack).

But of course, you can disable and also disable styling of the topbar as mentioned here:
https://github.com/paperwm/PaperWM#window-position-bar-colored-bar-segment-in-top-bar

```
dconf write /org/gnome/shell/extensions/paperwm/disable-topbar-styling true
```
(note you'll need to logout/login after running the above).

You'd also probably want to then disable the window Position Bar indicator (from gnome preferences):

![image](https://github.com/paperwm/PaperWM/assets/30424662/d6e8c66e-f41a-4291-accf-8ada2702e6f2)

**Comment by jtaala** [comment]
Closing as this has already been implemented and outlined clearly in the README.md.
