### ISSUE TITLE
Can't scroll when switching workspaces

### ISSUE THREAD

**Issue by vvvvvvitor** [paperwm/PaperWM#682]
**Describe the bug**
After switching workspaces, I can't scroll anymore.

**To Reproduce**
1. Open the GNOME overview
2. Switch workspace
3. Go back to the previous workspace
4. Can't scroll

**Expected behavior**
For the scrolling to work normally.

**Screenshots**
Couldn't capture any footage as it's really inconsistent.

**System information:**
```
Distribution: Fedora Linux
GNOME Shell 45.1
PaperWM branch/tag: v45.3.3
Enabled extensions:
- paperwm@paperwm.github.com
```

**Comment by jtaala** [comment]
Hey @vvvvvvitor.  

I can't reproduce this and haven't seen this.  Let's put a tag on this to see if anyone else is seeing this also.

**Comment by jtaala** [comment]
Also,

1. is PaperWM the only extension you have enable?
2. are you on X11 or Wayland?

**Comment by jtaala** [comment]
Hey @Lythenas and @Thesola10,

You ever seen this?

**Comment by Lythenas** [comment]
No I don't think I've seen this before.

@vvvvvvitor with "scrolling" do you mean normal mouse scrolling in a window or do you mean navigating the windows?

**Comment by vvvvvvitor** [comment]
> Also,
> 
> 1. is PaperWM the only extension you have enable?
> 2. are you on X11 or Wayland?

Yes and I'm on Wayland.

**Comment by vvvvvvitor** [comment]
I'll

**Comment by vvvvvvitor** [comment]
Accidentally closed this, sorry. I'll try to get a video of it happening, although I've only managed to make it happen 2 times, basically what happens is that instead of scrolling the workspace, it switches the workspace.

**Comment by vvvvvvitor** [comment]
> No I don't think I've seen this before.
> 
> @vvvvvvitor with "scrolling" do you mean normal mouse scrolling in a window or do you mean navigating the windows?

Navigating windows.

**Comment by vvvvvvitor** [comment]
Managed to make it happen! File size ended up being too big so I had to upload it to youtube.
https://youtu.be/_R0Ymp7M4w0

**Comment by jtaala** [comment]
Ah (@Lythenas) - that's why, we're talking about _gnome_ workspace switching! (as opposed to PaperWM space/workspace switching).  I don't use gnome's workspace switching (PaperWM space switching was intended to used instead of gnome workspace switching in PaperWM btw).

However, this should probably be looked at, given in Gnome 45 we do allow the workspace indicator pill (which has touchpad swipe gesture associated that switch workspaces using gnome workspace switching).

**Comment by Lythenas** [comment]
Ah, with the video I understand what you mean by scrolling :D I don't use touch/gestures at all, so don't really have an opinion here.

**Comment by Thesola10** [comment]
I use a vertical workspaces addon, so I'm not really in the right place to repro, but related behavior: once I do GNOME workspace switching (with my vertical ws addon enabled), the three-finger swipe upwards switches workspaces instead of showing the Overview like it did prior to the workspace switch.

**Comment by jtaala** [comment]
> I use a vertical workspaces addon, so I'm not really in the right place to repro, but related behavior: once I do GNOME workspace switching (with my vertical ws addon enabled), the three-finger swipe upwards switches workspaces instead of showing the Overview like it did prior to the workspace switch.

GNOME vertical workspace switching with that addon - does it show vertical switch animation (out of interest)?  or does the normal workspace switching animation for GNOME? (e.g. side to side)?

Does sound like the gnome workspace switching impacts behaviour for both extensions? (vertical workspaces addon and paperwm?).

**Comment by jtaala** [comment]
Another way to reproduce - use 4-finger swipe up (even though it should usually do nothing) and then try 3-finger horizontal swiping! (you can fix it up 3-finger swipe up to do overview and exit that).

Well, at least can repro now so should be able to fix this.

**Comment by jtaala** [comment]
I know what it is... it's the default gnome swipetrackers in `gestures.js` - must be hitting a corner case in our disable code.

**Comment by jtaala** [comment]
Morning all!

I've got an in-development branch that I'm hoping others can test: [fix-682-tiling-gesture-can-break-on-gnome-workspace-switching](https://github.com/paperwm/PaperWM/tree/fix-682-tiling-gesture-can-break-on-gnome-workspace-switching):

I can no longer reproduce the gesture confusion that was occurring here.  Aalthough @Thesola10, not sure if it covers you're use case (with that other extension) but worth a shot.  Also, there's probably still some corner cases here.

```
git clone https://github.com/paperwm/PaperWM.git
cd PaperWM
git checkout fix-682-tiling-gesture-can-break-on-gnome-workspace-switching
./install.sh
```
don't forget to logout / login.

Thanks.
