### ISSUE TITLE
Minimap doesn't show when continuously pressing Super (according to documentation)

### ISSUE THREAD

**Issue by madx** [paperwm/PaperWM#688]
**Describe the bug**
The documentation (README.md) states the following:

> A minimap will be shown when `Super` is continually being pressed, as can be seen in the above screenshot.

However, when I do so, the minimap doesn't show up. It only show up if I actually use a keybind such as the ones for focusing the next/previous windows.

It does stay open after the focus changed if I keep `Super` pressed.
Honestly I'm not sure if this is really a bug or if the documentation is just misleading. It would be a nice feature request if it isn't a bug 😁 (meaning I'll be happy to rewrite this ticket accordingly)

**To Reproduce**
1. Press and hold `Super`.

**Expected behavior**
The minimap shows up.

**Screenshots**
N/A

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

```
Example:
Distribution: Ubuntu
GNOME Shell 45.0-1ubuntu2
PaperWM branch/tag: Installed from EGO.
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Tiling window manager with a twist",
  "name": "PaperWM",
  "settings-schema": "org.gnome.shell.extensions.paperwm",
  "shell-version": [
    "45"
  ],
  "url": "https://github.com/paperwm/PaperWM",
  "uuid": "paperwm@paperwm.github.com",
  "version": 60,
  "version-name": "45.4.0"
}
Enabled extensions:
user-theme@gnome-shell-extensions.gcampax.github.com
gsconnect@andyholmes.github.io
power-profile-switcher@eliapasquali.github.io
one-thing@github.com
mprisLabel@moon-0xff.github.com
top-bar-organizer@julian.gse.jsts.xyz
do-not-disturb-while-screen-sharing-or-recording@marcinjahn.com
quick-settings-tweaks@qwreey
window-state-manager@kishorv06.github.io
paperwm@paperwm.github.com
auto-move-windows@gnome-shell-extensions.gcampax.github.com
```

**Comment by jtaala** [comment]
Ah, no the documentation is incorrect (or misleading) here.  Will update it.

I don't think we would add this as a behaviour for just the super button (since super is used for other shortcuts as well).  But for this type of thing I often use `super` + `down` (tapping the down button) which just shows the minimap without switching to next/prev window.  Well, I do the equivalent of that for my custom keybinds.

I'd look at a PR for this though if you want to give it a go.

**Comment by jtaala** [comment]
Ah, yeah, it's a bit misleading - it should refer to the that happening if users press a switch to window shortcut (and then  hold super down).

**Comment by madx** [comment]
That's what I thought, I'm fine with using `Super` + `down`, didn't think about it! Let's keep things simple and not add another keybinding when there's a simple way to do that. Should I leave this open while you update the docs?

**Comment by jtaala** [comment]
Yes please - I'm working on a fix for something else so will update the doco when can.

Feel free to fork and update the doco too if you feel like giving it a go.  Either way works fine.

Thanks for reporting it here @madx.

**Comment by jtaala** [comment]
Note to self: also remove the zulip reference as we're not really on there very often.

**Comment by madx** [comment]
I can take care of updating the docs!
What's the preferred place to hangout instead of Zulip?

**Comment by jtaala** [comment]
> What's the preferred place to hangout instead of Zulip?

Just github.  We have few contributors (~3 active, including myself).  I don't think zulip is being checked (last time I checked I saw some questions... I usually just tell them to come to github and submit their issue).

**Comment by Lythenas** [comment]
I occasionally check Zulip but I don't have notifications on and often I forget to check it for weeks^^

**Comment by jtaala** [comment]
I'm the same and don't really check zulip.  I also don't even know who the zulip paperwm administrators are? (hence we have no control over it).

@Lythenas are you an admin on zulip?  @smichel17?

Anyways, given this - it might be worth removing the reference to zulip (and also from the GH issue)?  Unless others are happy to keep checking it.

**Comment by Lythenas** [comment]
I'm definitively not an admin.
