### ISSUE TITLE
Open a new instance of an application when it is not on a visible workspace

### ISSUE THREAD

**Issue by distefam** [paperwm/PaperWM#692]
**Is your feature request related to a problem? Please describe.**
Prior to using PaperWM I used a setting in Dash to Dock to "isolate workspaces", which had the convenient effect of launching a new instance of an application when there was no window on any visible workspaces. PaperWM overrides this behavior so that now, when for example I click a link it switches to some recently active workspace and opens that URL in the web browser there.

**Describe the solution you'd like**
The behavior I would like is that clicking that link (or opening an app via an app launcher) would create a new instance/window of an app in the current workspace.

**Describe alternatives you've considered**
It is possible to type ctrl+return in a launcher to open a new instance, but this introduces mental friction, and I haven't found an equivalent when opening links.

**Comment by Lythenas** [comment]
I'm not sure where we would overwrite this to be honest. But it's possible. This might be the related code from dash to dock: https://github.com/micheleg/dash-to-dock/blob/ac7e31749b1755a9d7abf8ff9a4471b2c8fb9f82/docking.js#L1611 note at the end the if to decide if it should activate a window or open a new one.

**Comment by distefam** [comment]
Thank you for the reply. Actually, it led to me finding that this is actually the logic Dash to Dock uses for determining whether to activate a window or open a new one: https://github.com/micheleg/dash-to-dock/blob/master/appIcons.js#L732

After turning the setting off and on again after enabling PaperWM it is fixed when launching an app via the GNOME overview. However, it does not work with apps launched via a keyboard shortcut (configured via GNOME's keyboard shortcut settings). I guess this isn't a PaperWM issue but a GNOME one but do you know how to launch an app via the same mechanism that the GNOME overview does? I've tried `dbus-launch` but that doesn't work.

**Comment by distefam** [comment]
Posted an issue here: https://github.com/micheleg/dash-to-dock/issues/2123. Closing this as it isn't a PaperWM issue.

**Comment by Lythenas** [comment]
I use the "Search Light" extension to launch apps. I think it works the same as the gnome overview. At least I haven't run into any problems.

But not sure how that launcher the apps. I'm guessing there is a command that can launch .desktop fiels (which is what is shown in the gnome overview).

**Comment by Lythenas** [comment]
I found this post: https://askubuntu.com/questions/5172/running-a-desktop-file-in-the-terminal The only command that worked for me was:

```
gio launch /usr/share/applications/firefox.desktop
```

But that does not really help if you need to run other commands or scripts in your keybindings. To be honest I would expect it to open the new window on the current workspace all the time. And as far as I can tell this is also the way it works for me. E.g. the above command works the same as simply executing `firefox`. Note that I haven't tested this in keybindings. I only ran it from the terminal.

**Comment by distefam** [comment]
> I use the "Search Light" extension to launch apps. I think it works the same as the gnome overview. At least I haven't run into any problems.

I never knew [Searchlight](https://extensions.gnome.org/extension/5489/search-light/) existed, thank you for the recommendation. This works for now as it does open apps the same way that the Gnome overview does. 

> gio launch /usr/share/applications/firefox.desktop

Launching via the `.desktop` file doesn't work, unfortunately. It has the same behavior of switching me to a workspace that has a window of the app already open.

Re-opening as this isn't actually a Dash to Dock issue. Not entirely sure it's an issue for here, however, so feel free to re-close the issue.

**Comment by jtaala** [comment]
https://extensions.gnome.org/extension/600/launch-new-instance/ ?

**Comment by jtaala** [comment]
The above extension is supported directly by the gnome team (it's by fmuellner).

Anyways, I remember having this on gnome 43 and preferred it.

This isn't something that really fits in PaperWM, as it's on the launcher side (e.g. we'd need to control other applications - e.g. those clicked on dash or from applications, or opened by custom shortcuts etc.).  The extension above does that (always launches new instance if clicked on dash or from application view).
