### ISSUE TITLE
Window zoom in when scrolling 3 fingers up after workspaces overview

### ISSUE THREAD

**Issue by salahmak** [paperwm/PaperWM#699]
**Describe the bug**
When scrolling through workspaces (three fingers down on touchpad) and then scrolling up to open the current workspace (three fingers up on touchpad), a weird zoom-in animation occurs.

**To Reproduce**
1. Scroll three fingers down on touchpad to open PaperWM's workspace switching overview
2. Scroll three fingers up to end scrolling and focus on workspace

**Expected behavior**
Zoom in stops as soon as the workspace is opened when scrolling 3 fingers up

**Screenshots**
[Screencast from 2023-11-15 18-30-58.webm](https://github.com/paperwm/PaperWM/assets/49586511/b4fba4a3-b84d-43b0-8de6-cc03ee64c230)

**System information:**

```
Distribution: Arch Linux
GNOME Shell 45.1
Display server: Wayland
PaperWM branch/tag: release
PaperWM commit: 2f4cb441e473824e9ca7fd2e319e827d61fd67a9
Enabled extensions:
- gsconnect@andyholmes.github.io
- appindicatorsupport@rgcjonas.gmail.com
- EasyScreenCast@iacopodeenosee.gmail.com
- blur-my-shell@aunetx
- impatience@gfxmonk.net
- caffeine@patapon.info
- paperwm@paperwm.github.com
- lockkeys@vaina.lt
- grand-theft-focus@zalckos.github.com
- drive-menu@gnome-shell-extensions.gcampax.github.com

```

**Comment by jtaala** [comment]
Hey @salahmak, thanks for reporting.

This is not a bug - it's designed as a visual cue to let the user know they are at the top of the MRU (most-recently-used) workspace stack (note 3-finger swipe down orders PaperWM spaces in most-recent-used order - we don't wrap-around in MRU).

You can read more about this here:

https://github.com/paperwm/PaperWM/issues/263#issuecomment-597784774

Historically, 3-finger swipe up only used to do that action (visual indicator zoom) - I changed to overview back in June last year.  See this PR which implemented that:

https://github.com/paperwm/PaperWM/pull/552

P.S. it;s not weird... it's ["curious"](https://github.com/paperwm/PaperWM/issues/263) :smiley:

**Comment by jtaala** [comment]
Yeah, we could just "stop"... but we'd be losing a bit of PaperWM history! (plus, I like the zoom-in... and have played with even providing it as a feature, e.g. "centred zoom").

**Comment by jtaala** [comment]
P.S. feel free to experiment here to see how other approaches feel.

The code in question is here:

https://github.com/paperwm/PaperWM/blob/1e7cab0aa7c7b62112abc62d4c1ddcd598b6eb8f/gestures.js#L507-L513

For example, removing or commenting out those lines disables the zoom visual cue.

**Comment by salahmak** [comment]
oh that's interesting, I actually checked that code and suspected that it's the cause (I didn't try to change it though).

Can you give me quick instructions to test development change on wayland?

Thank you for the answer, so I guess I'll close the issue since it is not a bug :)
