### ISSUE TITLE
Incorrect branch information in readme

### ISSUE THREAD

**Issue by dsm-riact** [paperwm/PaperWM#701]
**Describe the bug**
The readme says to use the branch `gnome-44` with GNOME Shell versions 42-44. However I'm on version 42 and got an error when I used that branch (`keymap.map_virtual_modifiers is not a function`). Switching to the branch `gnome-42` seems to work fine. So I guess either this is a bug in `gnome-44` or the readme is incorrect.

**System information:**
```
Distribution: Ubuntu
GNOME Shell 42.9
Display server: Wayland
PaperWM branch/tag: gnome-42
PaperWM commit: e86f4d1f2c4003222edd025b394406875f097f47
Enabled extensions:
- paperwm@hedning:matrix.org
- ubuntu-appindicators@ubuntu.com
- ubuntu-dock@ubuntu.com
- auto-move-windows@gnome-shell-extensions.gcampax.github.com
- drive-menu@gnome-shell-extensions.gcampax.github.com
```

**Comment by jtaala** [comment]
Thanks for reporting.  `gnome-42` branch is very old.

It's possible compatibility got broken - we don't have very many people to test on Gnome 42. 

I know @Lythenas also uses Gnome 42... @Lythenas has anything broke on your gnome 42 setup?

**Comment by jtaala** [comment]
Just tested on Gnome 43 and appears fine (unfortunately my gnome 42 vm isn't work atm).

**Comment by Lythenas** [comment]
I will try to check this tomorrow, but I haven't noticed it before.

@dsm-riact was there any particular action you took when you got this error? Or is it just on startup?

**Comment by Lythenas** [comment]
At least on startup I don't get an error:

```
Please include this information in your bug report on GitHub!
Distribution: Ubuntu
GNOME Shell 42.9
Display server: Wayland
PaperWM branch/tag: gnome-44
PaperWM commit: 0f81d36dbf9a3d743f93398eb360ee0ee14e082c
Enabled extensions:
- paperwm@paperwm.github.com
- search-light@icedman.github.com
- tophat@fflewddur.github.io
- arch-update@RaphaelRochet
- date-menu-formatter@marcinjakubowski.github.com
- expandable-notifications@kaan.g.inam.org
- lockkeys@vaina.lt
- ubuntu-appindicators@ubuntu.com

```

**Comment by jtaala** [comment]
Thanks @Lythenas,

@dsm-riact, can you please test out disabling all other extensions (only having PaperWM with gnome-44 branch enabled) - logout/login and see if you're still getting that issue?

Sometimes other extensions can change base gnome objects that PaperWM relies (such as `map_virtual_modifiers`).

**Comment by dsm-riact** [comment]
Strange, I can't reproduce the issue any more. It was happening consistently at login before, but now I just switched back to gnome-44 and the problem is no longer happening. Sorry about the confusion, I'll reopen with more info if the problem comes back.
