### ISSUE TITLE
Workspace background images (not just flat colors)

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/PaperWM#71]
Some technical how-to:

####  `Meta.BackgroundActor`:
```javascript
    let imgPath = "/nix/store/2qy36mlqc1m01gi9mr9mss7zl4xk5ik5-gnome-backgrounds-3.28.0/share/backgrounds/gnome/adwaita-day.jpg"
    let imgFile = imports.gi.Gio.File.new_for_path(imgPath)
    let background = new Meta.Background({ meta_screen: global.screen });
    background.set_file(imgFile, imports.gi.GDesktopEnums.BackgroundStyle.SPANNED)
    let bgActor = new Meta.BackgroundActor({ meta_screen: global.screen, monitor: 0, background})

    space.actor.add_actor(bgActor)
    space.actor.set_child_below_sibling(bgActor, space.label)
```

#### `Clutter.Image`:
```javascript
function setBackgroundImage(actor, image_path) {
    const Clutter = imports.gi.Clutter;
    const GdkPixbuf = imports.gi.GdkPixbuf;
    const Cogl = imports.gi.Cogl;

    let image = new Clutter.Image();

    let pixbuf = GdkPixbuf.Pixbuf.new_from_file(image_path);

    image.set_data(pixbuf.get_pixels() ,
                   pixbuf.get_has_alpha() ? Cogl.PixelFormat.RGBA_8888
                   : Cogl.PixelFormat.RGB_888,
                   pixbuf.get_width() ,
                   pixbuf.get_height() ,
                   pixbuf.get_rowstride());
    actor.set_content(image);
    actor.content_repeat = Clutter.ContentRepeat.BOTH
}
```

**Comment by olejorgenb** [comment]
Add noise to the flat colors:

```javascript
let imgPath = "/run/current-system/sw/share/gnome-control-center/pixmaps/noise-texture-light.png"
let noise = new Clutter.Actor()
setBackgroundImage(noise, imgPath)
space.actor.add_actor(noise)
noise.set_size(...space.background.get_size())
noise.content_repeat = Clutter.ContentRepeat.BOTH
```

**Comment by olejorgenb** [comment]
There's also `bgActor.set_vignette(false, 0.5, 0.5)` and `bgActor.set_gradient(false, space.monitor.height, 0.5)` :tada:

**Comment by hedning** [comment]
There's now basic support for background images (49082dbd568092fb58c4eef0af54de367e3546b5). The remaining issue is exposing this through settings.

@xanf if you want to test it out (this integrates a lot better than the walkpaper extension).

To set a background:
```
space.settings.set_string('background', '/path/to/image.png')
```

To reset:
```
space.settings.set_string('background', '')
```

**Comment by naveedpash** [comment]
> There's now basic support for background images ([49082db](https://github.com/paperwm/PaperWM/commit/49082dbd568092fb58c4eef0af54de367e3546b5)). The remaining issue is exposing this through settings.
> 
> @xanf if you want to test it out (this integrates a lot better than the walkpaper extension).
> 
> To set a background:
> 
> ```
> space.settings.set_string('background', '/path/to/image.png')
> ```
> 
> To reset:
> 
> ```
> space.settings.set_string('background', '')
> ```

Where would I have to type this? user.js?

**Comment by olejorgenb** [comment]
It is a persistent "command" so you could just run in in _looking glass_ (`Alt-F2 lg Return`). Press `Super-Ins` first (assigns the current space to the global `space` variable)

Be careful with typos though, gsettings/dconf is picky about the keys (ie. `'background'`) Typing the wrong key could crash gnome-shell.
