### ISSUE TITLE
Mention issues with desktop icons in README

### ISSUE THREAD

**Issue by Lythenas** [paperwm/PaperWM#713]
Update the README to recommend disabling desktop icons extensions and explain what issues they cause.

Originally reported in #712

**Comment by migmanu** [comment]
Hey! I think this PR can be closed, as the Readme states:

> In most cases it should be enough to disable these extensions.
> - [DING (Desktop Icons NG)](https://gitlab.com/rastersoft/desktop-icons-ng) (shipped by default with Ubuntu) or similar extensions that add desktop icons. Creates invisible windows and does not properly show icons. See #784, #266
    
If I'm mistaken and the clarification is required somewhere else, I'll be glad to update the Readme,

**Comment by Lythenas** [comment]
Thanks. I added that in #785 but forgot about this issue.
