### ISSUE TITLE
Opening image in telegram makes the window go outside the screen

### ISSUE THREAD

**Issue by iitzrohan** [paperwm/PaperWM#722]
**Describe the bug**
Same as title

**To Reproduce**
1. Go to Telegram-desktop app.
2. Click on any image.
3. See error

**Expected behavior**
Image should open and shown as normal.

**Screenshots**
![Screenshot from 2023-11-28 14-13-34](https://github.com/paperwm/PaperWM/assets/104166410/c3c68e96-c8c7-4bae-8fdc-1e29b490441e)

**System information:**
```
Distribution: openSUSE MicroOS
GNOME Shell 45.1
Display server: Wayland
PaperWM branch/tag: release
PaperWM commit: 88a79a729acd7eae03833b8f779efb21758a8278
Enabled extensions:
- appindicatorsupport@rgcjonas.gmail.com
- user-theme@gnome-shell-extensions.gcampax.github.com
- AlphabeticalAppGrid@stuarthayhurst
- guillotine@fopdoodle.net
- color-picker@tuberry
- hotedge@jonathan.jdoda.ca
- miniview@thesecretaryofwar.com
- Vitals@CoreCoding.com
- paperwm@paperwm.github.com
- supergfxctl-gex@asus-linux.org
- smile-extension@mijorus.it
- clipman@popov895.ukr.net
- ideapad-controls@azzamalsharafi.gmail.com
```

**Additional context**
None

**Comment by Lythenas** [comment]
Might be related to the other telegram issue: #719 It's possible telegram is doing some strange things in general...

Does it work correctly if telegram is on the scratch layer instead of tiled?

**Comment by Rutherther** [comment]
I think this might be related to #638 as well. Not sure about the relation to #719.

I am actually having the same issue.

> Does it work correctly if telegram is on the scratch layer instead of tiled?

Yes, when telegram is on the scratch layer, it works fine. Another workaround is to unfullscreen the opened image window

**Comment by jtaala** [comment]
This should now be fixed (was a Mutter upstream issue that PaperWM was good at triggering - see #638).

Let us know if your'e still seeing this on `mutter` 45.3+.
