### ISSUE TITLE
Conflict with Ubuntu Tilling Assistant extension

### ISSUE THREAD

**Issue by bilboquet** [paperwm/PaperWM#729]
Hello,

Few days ago I upgraded from Ubuntu 22.04 to Ubuntu 23.10.
Most of the process went fine and even upgrading PaperWM was nothing more than uninstall / reinstall with the extension-manager.
I just had a little difficulty, some shortcuts were conflicting between PaperWM and Ubuntu Tilling Assistant.
Disabling Ubuntu Tilling Assistant manually did the trick.
I do remember that, when I was installing PaperWM manually, some conflicting extensions were disabled.
I suspect this is still the case and so "Ubuntu Tilling Assistant" should be added to this list or maybe this potential issue added to the FAQ.

Thank you

**Comment by jtaala** [comment]
> I do remember that, when I was installing PaperWM manually, some conflicting extensions were disabled.

PaperWM doesn't disable other extensions, but it does disable some gnome settings that don't work well with PaperWM (PaperWM also restores these settings when it's disabled).

Also, disabling other extensions def wouldn't pass EGO (extensions.gnome.org) review process.

> I just had a little difficulty, some shortcuts were conflicting between PaperWM and Ubuntu Tilling Assistant.

Yes, this can happen - PaperWM detects clashes with gnome keybinds, but detecting clashes with other extensions requires a priori knowledge of that extension's schema (path) to detect the clashes - hence it's out of scope to detect these.

We have a section in README.md for recommended extensions.  The most we would do here is add a subsection listing some extensions that don't work well (or would clash with PaperWM).

**Comment by bilboquet** [comment]
Please see #731
I hope it helps

**Comment by jtaala** [comment]
Thanks @bilboquet!

Ah, I wasn't aware it's a default extension (enabled by default?).  If so, then I would agree that it's worth adding it's schema path for keybind conflict detection.

I'll give installing Ubuntu 23.10 a go (in a vm) and find the schema path to add it.

**Comment by bilboquet** [comment]
I think I'm using PaperWM since Ubuntu 20.04 (maybe earlier, but who cares ^^).
Often I delay my system upgrade to be sure that PaperWM is ready (it's not a problem anymore, thanks to you and all other contributors, but it used to be).
So, even if not 100%, I'm pretty sure that `Ubuntu Tilling Assistant` was installed and enabled automatically during the last upgrade.
I hope your test will confirm that point. :)

**Comment by jtaala** [comment]
Hey @bilboquet, thanks for reporting this.  I can confirm that this extension is enabled by default and has keybind clashes with PaperWM.

#732 fixes this (it adds the schema to PaperWM to address conflicts).  Give it a test!

```
git checkout fix-729-paperwm-keybind-clashes-ubuntu-tiling-assistant
./install.sh
```

Then logout/login and you can test enabling tiling assistant.

**Comment by bilboquet** [comment]
Hi @jtaala 
On a freshly installed ubuntu 23.10 (in a vm) I did:
- checkout you branch
- logout/login
- enable PaperWM (it was not enabled by default, not a big deal)
Tilling assistant and PaperWM are both enabled. I tried the shortcut I'm using frequently and everything worked fine :)

So for me the problem is solved. 
Many thanks

PS: I don't know if can approve on your PR, but it looks fine to me
