### ISSUE TITLE
Windows sometimes freeze (receive input but doesn't update visually)

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/PaperWM#73]
Haven't pinpointed the cause, but it can be reproduced by resizing a window starting at the top and decreasing the height. 

Using emacs with `frame-resize-pixelwise` can also trigger the bug when zooming the frame and then using helm (...).

I think I've seen it happen in some unrelated situations too.

It's probably related to forcing the window to be a specific size, although well-behaved windows should settle on a fixpoint..

The window can be "thawed" by resizing the window horizontally. (eg. <kbd>Super r</kbd>)

Only in X11?

**Comment by xanf** [comment]
No, Wayland also sometimes has this effect

**Comment by olejorgenb** [comment]
Hm, still happens here (X11). Also by resizing from the top.

It seem to depend on the application. Firefox handle resizing from the top, but not from the bottom. Gnome-terminal freeze on both top and bottom resize.

**Comment by olejorgenb** [comment]
Seems to be caused by recursive resizes. Ie. calling `move_resize_frame` from within a `size-changed` signal handler.

Defering such calls by wrapping them in `Meta.later_add(Meta.LaterType.RESIZE, ...)` works. (tested on 3.28)

Such recursive calls an happen on non-grab resizes. Eg. when workarea changes force a resize (#108).
