### ISSUE TITLE
Add a keyboard shortcut for "Swipe tilling windows"

### ISSUE THREAD

**Issue by bilboquet** [paperwm/PaperWM#730]
Hello

Most of the time, my main screen is arranged like this:
![image](https://github.com/paperwm/PaperWM/assets/8612342/339d039d-1acc-4e2a-81a2-69f9900f669b)
- A browser on the left (or on the right) to display some documentation/information
- My main application in "the center" (more or less)
- A terminal on one side to monitor logs, etc

Using a touchpad, it's possible to make windows flow from left to right and right to left with 3 fingers (default configuration).
That's the touchpad gestures: Swipe tilling windows (swipe left/right).
That's useful because, without changing my main task (so focus still on the window in the center) I can have more feedback from the left or from the right.
I'm often found myself simulating this behavior with the keyboard only by quickly focussing the window on one side then coming back to the center one.
The default is that it's not always very precise.

So I wish I have keyboard shortcuts that act like the swipe gesture on the touchpad.
It's probably better to leave this kind of shortcut disabled by default.
4 shortcuts would be ideal:
- swipe left smoothly
- swipe right smoothly
- swipe left roughly (same as above but by "jump")
- swipe right roughly

Please let me know what's your thought.

**Comment by jtaala** [comment]
I can see the utility here - could be useful on X11 too (which doesn't support gnome mouse gestures).

**Comment by KETHERCORTEX** [comment]
Is there a way to invoke this functionality by launching a command (in terminal or with GNOME Alt+F2 launcher)?

**Comment by jtaala** [comment]
> Is there a way to invoke this functionality by launching a command (in terminal or with GNOME Alt+F2 launcher)?

Hey @KETHERCORTEX,

No, I don't believe (AFAIK) there's anything like this for gnome extensions - other that simulating touchpad swipes.

This would be nice though, thinking something like `i3-msg`.

**Comment by Lythenas** [comment]
I think I mentioned this in another issue, but we could provide a dbus interface for our "actions". That could be used from outside.

**Comment by jtaala** [comment]
Hey @Lythenas - yes, this is a good idea.  In PaperWM we use a dbus hook to get enriched monitor info.

Can you add an issue? (can reference this issue for example).

Thanks @Lythenas.

**Comment by Lythenas** [comment]
@jtaala I created an issue: #738

**Comment by jtaala** [comment]
Hey @bilboquet,

Please see PR #917.  Are you able to test this please?

```
git fetch --all
git checkout improve-730-swipe-drifting
./install.sh
```

Then logout/login.

Thanks!
