### ISSUE TITLE
WM breaks when set to workspaces on primary display only

### ISSUE THREAD

**Issue by aadityapageni** [paperwm/PaperWM#734]
**To Reproduce**
1. Go to ' set to workspaces on primary display only'
2. have some windows on both monitors
3. overview/super button
4. See error, everything freeze except control center

Distribution: Arch Linux 6.6.4-zen1-1-zen
GNOME Shell 45.2 wayland
Enabled extensions:
- clipboard-indicator@tudmotu.com
- user-theme@gnome-shell-extensions.gcampax.github.com

**Comment by Lythenas** [comment]
I think this is pretty much expected. We need workspaces on all monitors.

The readme also mentions this: https://github.com/paperwm/PaperWM#recommended-gnome-shell-settings although maybe that is worded a bit poorly.

**Comment by jtaala** [comment]
As mentioned in the [README.md](https://github.com/paperwm/PaperWM?tab=readme-ov-file#recommended-gnome-shell-settings) this setting is required for PaperWM to properly function.

> PaperWM manages these settings (disables them) during runtime. It will then restore these settings to their prior values when PaperWM is disabled.
