### ISSUE TITLE
Add ability to generate system information from UI

### ISSUE THREAD

**Issue by Lythenas** [paperwm/PaperWM#745]
**Is your feature request related to a problem? Please describe.**

Users of PaperWM from EGO don't have the `gather-system-info.sh` script.

**Describe the solution you'd like**

Add a button to the settings that generates the same information and maybe copy it to the clipboard.

And update the issue template to mention this for EGO users.

**Describe alternatives you've considered**

Provide that script in the EGO extension (not sure if allowed by EGO) and direct users to execute it from `~/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/gather-system-info.sh`.

**Additional context**

**Comment by jtaala** [comment]
Great enhancement!
