### ISSUE TITLE
Resizing consumed window doesn't resize everything in consumed group

### ISSUE THREAD

**Issue by paradajz** [paperwm/PaperWM#747]
**Describe the bug**

I'm not sure how to phrase the issue so I'll just post the video showing the behaviour.

**To Reproduce**

1. Open a new window
2. Open another window
3. Switch to the first window
4. Consume the second window
5. Attempt to resize one of them

**Expected behavior**
Both (or all, depending on the number of consumed windows) should resize in sync.

**Screenshots**
[Screencast from 2024-01-11 09-36-06.webm](https://github.com/paperwm/PaperWM/assets/2544094/c0bca838-5ab7-4e5a-a38e-c9f389a8ee07)

**System information:**

```
Distribution: openSUSE Tumbleweed
GNOME Shell 45.2
Display server: Xorg
PaperWM branch/tag: develop
PaperWM commit: 84c6dabadd488425236291d4a67382206f1806f6
Enabled extensions:
- paperwm@paperwm.github.com
- Vitals@CoreCoding.com
- clipboard-history@alexsaveau.dev
- switcher@landau.fi
- launch-new-instance@gnome-shell-extensions.gcampax.github.com
```

**Additional context**
I think this started after https://github.com/paperwm/PaperWM/commit/84c6dabadd488425236291d4a67382206f1806f6 was merged.

**Comment by jtaala** [comment]
Thanks @paradajz - git bisect says this commit did it e8f2b104244f83df7bb992e60f138f95b04947cc.

Will have a look at this now.

**Comment by jtaala** [comment]
Found it - will push up a fix soon.
