### ISSUE TITLE
Coverflow Alt Tab extension not working with PaperWM

### ISSUE THREAD

**Issue by ghost** [paperwm/PaperWM#752]
**Describe the bug**
Coverflow Alt Tab extension just stops working and is replaced with a normal alt tab

**To Reproduce**
Just install https://extensions.gnome.org/extension/97/coverflow-alt-tab/
and try to use it with paper wm and without it.

**Question**
Anyway to make the both work?

**Comment by jtaala** [comment]
> Anyway to make the both work?

Sure, just disable PaperWM's conflicting keybinds (in PaperWM extension settings).  E.g. disable anything that's assigned in PaperWM keybinds for `Super`+`Tab` etc.

**Comment by jtaala** [comment]
Although I noticed that cover-flow might be conflicting with three-finger swipe left/right as well (it went a bit weird when enabling cover-flow with PaperWM - so there might be deeper conflicts as well(?).

**Comment by ghost** [comment]
> > Anyway to make the both work?
> 
> Sure, just disable PaperWM's conflicting keybinds (in PaperWM extension settings). E.g. disable anything that's assigned in PaperWM keybinds for `Super`+`Tab` etc.

That was literally the the first thing I tried after i encountered this issue though I did not disable super + tab, now it works perfectly, thanks!

**Comment by astr64** [comment]
It appears to work, but is very broken. Any window that is "cropped" by PaperWM will end up presented on Coverflow in the exact proportions you see it.

**Comment by astr64** [comment]
@jtaala
