### ISSUE TITLE
Add scroll hotspots to window drag-and-drop

### ISSUE THREAD

**Issue by Thesola10** [paperwm/PaperWM#765]
**Is your feature request related to a problem? Please describe.**
This is especially noticeable with touch screens, where there is no alternate way of moving the scroll view while dragging a window. By PaperWM's very nature, repositioning a window across the scroll view is hard without using the keyboard, as window movement is restricted to the spaces currently visible on screen.

**Describe the solution you'd like**
Moving a tiled window close to the edge of the screen should progressively start scrolling the workspace in that direction, like file drag-and-drop operations in Nautilus for instance.

**Comment by jtaala** [comment]
This a good idea.  The mechanism for actually scrolling would also be used by #730.

**Comment by jtaala** [comment]
Closed via #914
