### ISSUE TITLE
Support gnome 3.30

### ISSUE THREAD

**Issue by hedning** [paperwm/PaperWM#77]
3.30 removes `global.screen` and moves the functionality to `global.workspace_manager` and `global.display`.

We'll have to polyfill it (eg. Ubuntu LTS will be stuck on 3.28 for a long time).

**Comment by hedning** [comment]
Hopefully 145a8d3347fbacf67095caf4b54883e823ab3cd0 should do the trick, but I haven't tested it with 3.30 yet.

**Comment by hedning** [comment]
Works in 3.30

**Comment by mogenson** [comment]
Extension appears to work fine under Gnome 3.30.

Watching `journalctl -f | grep paperwm` shows the ocasional warning, but nothing has crashed yet.
```
Sep 18 10:20:28 thinkpad gnome-shell[3305]: JS WARNING: [/home/mike/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/scratch.js 43]: reference to undefined property Symbol()
Sep 18 10:20:28 thinkpad gnome-shell[3305]: JS WARNING: [/home/mike/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js 2016]: reference to undefined property 0
```

Arch Linux, x86_64, Gnome 3.30.0

**Comment by hedning** [comment]
Yeah, those warnings are just because we're accessing some properties unchecked. The one in `scratch.js` just returns a boolean so can't cause any troubles, and what's returned from `find_winprop` is checked before it's used further, so shouldn't cause any problems either.

 As an aside we just fixed a rather nasty performance problem, so hopefully everything should run a lot smoother now :)
