### ISSUE TITLE
Unfocused and deviated maximize-windowed Firefox after exiting full screen 

### ISSUE THREAD

**Issue by woongzeyi** [paperwm/PaperWM#777]
**Describe the bug**
While Firefox is in maximized window mode (i.e. its window title bar double-clicked, not `Super+F` pressed), if you exit from full-screen mode (e.g. watching a YouTube video in full screen, or pressing `F11` on any webpage), the window is unfocused and has its position deviated to the right, leaving a gap on the left side of the window.
This issue does not appear instead if the PaperWM "Toggle Fullscreen" keybinding is used (i.e. `Super+Shift+F`). 

**To Reproduce**
1. Double click on the Firefox window title bar to enter maximized window mode. You will see a title bar on the top of your screen right below the Gnome activities bar unlike in PaperVM "Toggle Fullscreen" mode. 
2. Get on any webpage and press `F11` to enter fullscreen mode. 
3. Press `esc` to exit fullscreen mode. 
4. You shall see the window unfocused and deviated to the right. You are required to click on the window once to refocus onto the Firefox window before proceeding to any mouse action performed on the application. 

**Expected behavior**
The Firefox window isn't unfocused and deviated to the right after exiting fullscreen mode, just like how it is seen in PaperWM "Toggle Fullscreen" mode. 

**Screenshots**
![unfocused and deviated window after exiting fullscreen mode in maximized window mode](https://github.com/paperwm/PaperWM/assets/53040809/ffb3ca62-ad82-413a-913a-6f64764b90ff)

**System information:**

```
Distribution: Fedora Linux
GNOME Shell 45.3
Display server: Wayland
PaperWM branch/tag: release
PaperWM commit: d280bc743d15d869bdbbeb8e410fd3a88e9d17a5
Enabled extensions:
- caffeine@patapon.info
- clipboard-indicator@tudmotu.com
- blur-my-shell@aunetx
- just-perfection-desktop@just-perfection
- dash-to-dock@micxgx.gmail.com
- custom-accent-colors@demiskp
- user-theme@gnome-shell-extensions.gcampax.github.com
- trayIconsReloaded@selfmade.pl
- paperwm@paperwm.github.com
- background-logo@fedorahosted.org
```

**Additional context**
[Demo](https://github.com/paperwm/PaperWM/assets/53040809/e88a9188-bb6a-40b4-8b8c-4a4c47c4eddc)

**Comment by Lythenas** [comment]
~~For what it's worth I can't reproduce this. F11 + F11 (or putting a youtube video in fullscreen and ESC) works as expected and put the window back to where it originally was. When double clicking the title bar twice I noticed that the resulting window is a different size (smaller) but it is still tiled normally and in the center.~~

Sorry I think I misunderstood a bit. After double clicking the topbar and then pressing F11 twice I see the same behavior as you. That behavior is a bit strange.

I guess the root cause it that after double clicking the topbar, the window is not properly tiled anymore. Although it is also not floating and also not on the scratch layer. So I'm not sure what is going on there.

**Comment by jtaala** [comment]
It's most likely the `saveFullscreenFrame` approach - some applications don't properly save/restore to the previous position/size (see this a lot with `brave` browser).

Anyways, PaperWM saves this for restore and takes into account the `horizontal_margin` setting.  I didn't think about the maximised state so it's likely enforcing (moving window frame) to take into account `horizontal_margin` (even though maximised).

E.g. see https://github.com/paperwm/PaperWM/blob/31eb9c78c6e1fd892367fef5f06e9ac3f0a951cd/tiling.js#L3281

Prob just needs a maximised check and don't enforce that if window is maximised.

~~Might also be in the `layout` call - `maximised` state in PaperWM is not that normal (but it is valid so we prob should address it better).~~

Yep, it was what I previously mentioned.  Will push up a fix soon.

Thanks for reporting!

**Comment by jtaala** [comment]
Hey @woongzeyi,

Can you please checkout and test branch [fix-777-maximised-out-of-fullscreen](https://github.com/paperwm/PaperWM/tree/fix-777-maximised-out-of-fullscreen)?

```
git fetch --all
git checkout fix-777-maximised-out-of-fullscreen
./install.sh
```

then logout/login and try firefox again.

Planning to push this fix in next release.
