### ISSUE TITLE
Automatically scroll on hover

### ISSUE THREAD

**Issue by Ioulan** [paperwm/PaperWM#779]
**Is your feature request related to a problem? Please describe.**
Not really, I don't have any problems using the Tiling WM

**Describe the solution you'd like**
When hovering the mouse at the end side of the screen, instead of having a preview and clicking that to go through the next window display, It would be nice for the window manager have an option to automatically scrolls to that next window upon hovering.

**Describe alternatives you've considered**
There's an existing gesture settings for touchpad users though. (swipe tiling windows options)

**Additional context**
![image](https://github.com/paperwm/PaperWM/assets/114978689/4fc05e8e-fd92-4728-8dc3-3f5c0624544e)

**Comment by jtaala** [comment]
Am open to this.  Would you expect it to scroll after a brief delay once the previous shows?

**Comment by Thesola10** [comment]
Hm, that resembles #765 but active all the time

Ideally we could also pick up cursor movement against the edge of the screen (i.e. cursor won't move further right but mouse/trackpad still is) and make it immediately perform a workspace scroll, and the hover approach would be limited to monitor boundaries, as I can imagine forgetting the cursor near screen edge could cause unwanted behavior.

**Comment by Lythenas** [comment]
Just as food for thought as I'm personally not interested in this feature:

In the past I saw some kind of "pressure" system implemented for stuff like this. I.e. you move you mouse to the edge, it shows the preview only, you move it further into the edge it starts to scroll.

But to be honest I'm not sure if that can be implemented in gnome, since you need to know that the mouse was moved further into the edge, without the actual cursor being moved (since it is bounded to the edge).

**Comment by jtaala** [comment]
Hey all, Gnome (actually `Meta`) has a pressure barrier element that is designed for just this.

@Lythenas is right - we did have this previously for this approach, but I removed it (as part of a simplification effort - but that was more the actual implementation at the time wasn't great - not that the concept/approach wasn't good).

I'm happy to look at this as I've been tripped the previews a bit and sometimes they get stuck on, which I've been planning to fix at some point).

**Comment by jdamboeck** [comment]
One of niris best and the biggest missing features in paperwm for me.

**Comment by jdamboeck** [comment]
> Am open to this. Would you expect it to scroll after a brief delay once the previous shows?

Configurable would be the best. I would prefer instant reaction. At least only a very slight delay.

**Comment by jtaala** [comment]
Evening all,

I've now added this option (plus some related options for edge tiling previews), see #848.

Please give this a test and let me know how it feels:

```
git clone https://github.com/paperwm/PaperWM.git
cd PaperWM
git checkout improve-edge-previews2
./install.sh
```
then logout / login.

Thanks!
