### ISSUE TITLE
How to easily scroll through all windows in scratch layer

### ISSUE THREAD

**Issue by dextdc** [paperwm/PaperWM#783]
**Is your feature request related to a problem? Please describe.**
When I send multiple windows to scratch, I'd like to be able to stack them in a i3-like tabbed-stack and scroll through them using Next/Prev workspace shortcuts. 

I do this in i3 by sending an entire stack to the scratch layer. I can cycle through all scratch windows easily by just navigating left/right through the stack. New browser windows created in that stack in i3 continue to remain in that stack, allowing me to create new browser windows in scratch without having to send them to scratch.

My current workaround in PaperVM is to use shortcuts for 'switch to previously active window' and 'switch to previous active window (backwards)' to cycle through the scratch layer windows. It works fairly well but if I overshoot, it mixes the current active window (in non-scratch layer) into the sequence.

**Describe the solution you'd like**
Can we have a new shortcut to cycle through only the windows in the scratch layer. This would be like having a window stack in scratch layer.

**Describe alternatives you've considered**
Detect that if scratch layer is showing, then 'switch to previously active window' and 'switch to previously active window (backwards)' only cycle through the scratch layer windows (eg apply a filter to the list of windows if scratch layer is showing).

Thanks for this extension. I just discovered it and it's making Gnome so much easier to use for my workflow now.

**Comment by jtaala** [comment]
Keybinds for `Switch to next window (scratch)`, `Switch to previous (scratch)` sounds like a good idea and would be very easy to implement.

Interestingly, the hardest part of this would be selecting default specific keybinds for this... any ideas?  Maybe something like `Super+Shift +.` & `Super+Shift+,`?

**Comment by dextdc** [comment]
Thanks for the feedback and taking it into consideration! I think it would help scratch layer navigation alot, too. 

Those defaults  `Super+Shift+.` & `Super+Shift+`, sound like they complement the default `Activate the next or previous window` quite well.

**Comment by dextdc** [comment]
Another data point, I personally am using `Super + [` and `Super + ]` for scrolling through my (scratch) windows (using  `switch to previously active window` and `switch to previous active window (backwards)`). 

For me, that's because my `Super+Shift` is for all moving operations, and so `. ,` are used by me for Moving between workspaces (Super) and Moving windows between workspaces (Super + Shift). Active windows for me are VIM `h` `l` (and shift combo is for moving active window).

**Comment by jtaala** [comment]
Hey @dextdc,

See #789.

This adds keybinds for previous, next windows switching for scratch layer windows (only):

![image](https://github.com/paperwm/PaperWM/assets/30424662/7f5564d6-2ead-4989-ae87-faff134a3fa4)

I haven't set default keybinds for this (users will need to set their own/preferred ones).

**Comment by jtaala** [comment]
I'm still open to adding default keybinds though - what about `alt`+`ctrl`+`tab` and `alt`+`ctrl`+`shift`+`tab`?

**Comment by dextdc** [comment]
This looks really great! Thanks for working on it.

The Alt-variants on Super-Tab seem to fit well into the existing keyboard shortcuts too, as a tab variant on Super-Tab. One drawback I can think of is that it has alot of buttons concentrated on the left hand, which may be had to press in combination to having to also reach for Tab. But other than that, it fits the paradigm well.

The previous one you suggested also fits the paradigm well.

**Comment by jtaala** [comment]
Closing this as now released in v45.11.0.
