### ISSUE TITLE
Active Window Border & Background (change css styles)

### ISSUE THREAD

**Issue by forgottosave** [paperwm/PaperWM#790]
**Is your feature request related to a problem? Please describe.**
I couldn't find a way to disable the bright blue active-window marker. On normal windows this marker results in a nice little blue border, but on semi-transparent windows (like in my terminal, see below) this colors the whole thing blue.

I use Fedora 39.

**Describe the solution you'd like**
It would be nice to have a way to disable, or customize the highlighter-box behind the active window. (or is there already a way? if so i haven't been able to find one)

**Additional context**
![image](https://github.com/paperwm/PaperWM/assets/88790311/8bb821e6-ea62-4802-b223-0813df8f1bf8) 
![image](https://github.com/paperwm/PaperWM/assets/88790311/3e9e4fe1-130a-4d73-920e-6848af515df7)

**Comment by jtaala** [comment]
Hey @forgottosave,

Yes, you can change this.  Many PaperWM element styles can be changed with css.

See this comment: https://github.com/paperwm/PaperWM/issues/683#issuecomment-1806648963

The example there has a border (but not a background) - we should probably make that default (e.g. border but no background).

Shout out if you have troubles with this (note, change the css style then disable/enable PaperWM).

Cheers.

**Comment by forgottosave** [comment]
You guys are awesome. Such a quick reply. 

And I'm sorry I didn't find that setting myself. It works flawlessly, thank you :)
