### ISSUE TITLE
Permit disabling switching to the next/previous windows when clicking on the edge of the monitor.

### ISSUE THREAD

**Issue by grota** [paperwm/PaperWM#793]
I might be clumsy but sometimes I click on the edge of the monitor by mistake and I do not want to switch to the next/previous windows.

I would like to disable that behavior entirely.

For me it would be enough to have the advanced option "Tiling edge preview scale" to disable edge switching when the user puts 0.

An alternative can be a standalone checkbox.

**Comment by jtaala** [comment]
> For me it would be enough to have the advanced option "Tiling edge preview scale" to disable edge switching when the user puts 0.

Hey @grota, this is trivial to implement and I'm happy to add this (it makes sense).  Just requires this change:

replace

https://github.com/paperwm/PaperWM/blob/62976a60808be923a5b686e4d9c408d1c5cf746b/stackoverlay.js#L184

with this:

```
            if (Settings.prefs.edge_preview_scale > 0) {
                Main.activateWindow(this.target);
            }
```

I'll add this to the next update.

**Comment by grota** [comment]
Thank you very much! 😗

**Comment by jtaala** [comment]
Closed as released into latest release branch.
