### ISSUE TITLE
Vertical tiling

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/PaperWM#8]
Lots of design questions that need to be decided, but we do want some form of vertical tiling.

1. Vertical "slurp": Tile the current and the next horizontal neighbor vertically.
2. If it's enough vertical space below the current window when a new window is created it can make sense to tile this window vertically. Maybe conditioning on the wm_class.

Case where it would've been nice if the free vertical space had been automatically used:
![image](https://user-images.githubusercontent.com/72201/30524185-22e3671e-9bef-11e7-86a8-ac326343d85f.png)

**Comment by hedning** [comment]
There's two things that needs to be thought through I think. How to initiate a vertical tile and navigation.

## Navigation

We might want to have two ways to navigate:
1. arrow keys where left/right navigates columns, and up/down navigates rows
2. </> treats the whole tiling as a single list. ie. if the focus is on the top window in a column > would move down the column.

We would then use `super-page-up/down` to navigate the workspace mru stack.

## Creating a vertical tiling

Reducing the vertical size of a window could initiate a slurp. While increasing the vertical size would initiate a burp. Not sure how that would work with more than two windows tiled vertically though.

Integrating `display::grab-op-begin/end` makes mouse resize and moving more flexible. It's for instance possible to reset the size of the window if the resize wasn't large enough to create room for another window.

We could respect the initial height of a window and tile vertically if possible, though it might be better to just make it easy to manually create a vertical tiling and having winprop support.
