### ISSUE TITLE
Swipe tiling windows for touch screen

### ISSUE THREAD

**Issue by thenameisluk** [paperwm/PaperWM#804]
**Is your feature request related to a problem? Please describe.**
i am currently using paperWM on linux table and having and switching between applications that aren't directly next to each requires either hopping windows or opening all windows view and clicking on it
using keyboard shortcuts isn't an option since i don't have external keyboard plugged most of the time

**Describe the solution you'd like**
implementing touchpad "Swipe tiling windows (swipe left/right}" functionality for touch screen would make it way easier

**Describe alternatives you've considered**
if implementing this is not possible
maybe making window position bar interactive could be a solution

**Additional context**
nothing more to add, would probably try to write solution myself (i know js) but i find documentation hard to read and struggle while setting up ide to write any extension at all and doing it without auto completion is not very pleasant experience for me

**Comment by jtaala** [comment]
Hey @LukIsHere,

Just tagging @Thesola10, who also uses a tablet (or at least computer with touchscreen).  I don't have anything with a touchscreen so I won't be much help here.

Jay.

**Comment by Thesola10** [comment]
Have you tried swiping across the panel? That's the top bar with the workspace dots (or the bottom bar on Dash to Panel)

This feature exists since the GNOME 44 version of the extension iirc

**Comment by thenameisluk** [comment]
it does work and fixes my problem
thank u very much
