### ISSUE TITLE
TypeError: extensionModule.default is not a constructor

### ISSUE THREAD

**Issue by rodrigogonegit** [paperwm/PaperWM#809]
**Describe the bug**
Extension does not load, I cannot enable it. TypeError: extensionModule.default is not a constructor

**To Reproduce**
1. Open the Extension Manager app
2. Try to enable PaperWM

**Expected behavior**
I should be able to enable it.

**Screenshots**

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

```
➜  PaperWM git:(release) bash gather-system-info.sh
Please include this information in your bug report on GitHub!
Distribution: Fedora Linux
GNOME Shell 45.5
Display server: Wayland
PaperWM branch/tag: release
PaperWM commit: 80656aedcb0fc72b743479ffc328231a4719f01b
Enabled extensions:
- Vitals@CoreCoding.com
- just-perfection-desktop@just-perfection
- mprisLabel@moon-0xff.github.com
- gsconnect@andyholmes.github.io
- pomodoro@arun.codito.in

```

**Additional context**
Logs

```
Mar 29 12:08:44 rodrigofed gnome-shell[3087]: Extension paperwm@paperwm.github.com: TypeError: extensionModule.default is not a constructor
                                              
                                              Stack trace:
                                                _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:544:17
                                                async*loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:457:33
                                                _onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:300:35
                                                async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:134:41
                                                @resource:///org/gnome/shell/ui/init.js:21:20
                                                
Mar 29 12:08:44 rodrigofed gnome-shell[3087]: Error while compiling schema for extension paperwm@paperwm.github.com: (Child process exited with code 1)
Mar 29 12:08:44 rodrigofed gnome-shell[5217]: /home/rodrigo/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/schemas/org.gnome.shell.extensions.paperwm.gschema.xml:1:1  Erro>
Mar 29 12:08:44 rodrigofed gnome-shell[5216]:  extracting: /home/rodrigo/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/metadata.json
Mar 29 12:08:44 rodrigofed gnome-shell[5216]:   inflating: /home/rodrigo/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js
Mar 29 12:08:44 rodrigofed gnome-shell[5216]:   inflating: /home/rodrigo/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/navigator.js
Mar 29 12:08:44 rodrigofed gnome-shell[5216]:   inflating: /home/rodrigo/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/stylesheet.css
Mar 29 12:08:44 rodrigofed gnome-shell[5216]: Archive:  /tmp/3D1QL2.shell-extension.zip
```

**Comment by jtaala** [comment]
Hey @rodrigogonegit.  Just tested this and installs fine via https://extensions.gnome.org/extension/6099/paperwm/ and from source.

I'm not sure why extension manager is even trying to compile the schema - the schema is already compiled and provided.

Can you try removing from source ( you ran `gather-system-info.sh` so it seems you have source installed):
in the paperm source folder:
```
./uninstall.sh
```

then logout / login.

and try again.  I'll test an install via extension manager too.

**Comment by jtaala** [comment]
Just successfully installed from extension manager.

I'm guessing it's a conflict between having the source version of PaperWM installed and then trying to install via extension manager?  If so, do a

```
rm -rf ~/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com
```
log out / login and then install via extension manager.

**Comment by jtaala** [comment]
> Just successfully installed from extension manager.

https://github.com/paperwm/PaperWM/assets/30424662/c9920738-84ab-43a2-a638-8f0de1ccfa74

Let me know if I'm doing anything different from you.

Jay.

**Comment by jtaala** [comment]
Just checking, is anyone else seeing this?

**Comment by rodrigogonegit** [comment]
Well, that was stupid on my end. Not sure what happened as when I first logged in it stopped working, but that did the trick. Thanks for the quick help and all your work on this extension that is now essential to my workflow :)

**Comment by jtaala** [comment]
No probs @rodrigogonegit.  Glad you got it sorted.
