### ISSUE TITLE
Second monitor doesn't have tiling/Crash

### ISSUE THREAD

**Issue by An-Eagle** [paperwm/PaperWM#816]
**Describe the bug**
When trying to switch a window to my second monitor, using shift+super+ctrl+arrows, it causes a hard crash. The top bar still functions, I can still open quick settings, but everything else just goes black and breaks.
If i do this just after starting gnome starts (I have around 30 seconds), it doesn't crash, but the windows on the second display are floating.

I don't know if this is a missing feature, but I also can't drag a window to another display/workspace, it could be related
**To Reproduce**
1. attempt to move a window using the paperwm keybinds
2. crash, or get a floating window on the second monitor

**Expected behavior**
The window moves to the second monitor, and joins a stack on the second monitor

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.
Distribution: Gentoo
GNOME Shell 45.5
Display server: Wayland
Enabled extensions:
- user-theme@gnome-shell-extensions.gcampax.github.com
- just-perfection-desktop@just-perfection
- paperwm@paperwm.github.com
- launch-new-instance@gnome-shell-extensions.gcampax.github.com

**Additional context**
I only have 1 workspace enabled in gnome settings, I have made sure that I disabled all the settings that weren't recommended in the README.

**Comment by Lythenas** [comment]
>  I only have 1 workspace enabled in gnome settings, I have made sure that I disabled all the settings that weren't recommended in the README.

I think that might be the issue. Although I thoght we automatically set the settings to a usable value when PaperWM is enabled. In PaperWM (unlike what Gnome normally does) each monitor uses it's own workspace.

So can you try to set the number of workspaces to at least two?

**Comment by An-Eagle** [comment]
> > I only have 1 workspace enabled in gnome settings, I have made sure that I disabled all the settings that weren't recommended in the README.
> 
> I think that might be the issue. Although I thoght we automatically set the settings to a usable value when PaperWM is enabled. In PaperWM (unlike what Gnome normally does) each monitor uses it's own workspace.
> 
> So can you try to set the number of workspaces to at least two?

Yes, that allows tiling. Is it normal for it to treat both monitors as 2 completely different workspaces ?

**Comment by jtaala** [comment]
> Yes, that allows tiling. Is it normal for it to treat both monitors as 2 completely different workspaces ?

Yes, in actual fact it's required in PaperWM, it's the _per monitor workspaces_ part of the PaperWM description:

>  PaperWM is a Gnome Shell extension which provides scrollable tiling of windows and per monitor workspaces. It's inspired by paper notebooks and tiling window managers.

It allows separated tiling that PaperWM relies on for multiple monitors.  It's not without it's issues though, (see https://github.com/paperwm/PaperWM/issues/389#issuecomment-1911089672).

> I think that might be the issue. Although I thoght we automatically set the settings to a usable value when PaperWM is enabled. In PaperWM (unlike what Gnome normally does) each monitor uses it's own workspace.

@Lythenas, well, if users use `dynamic` workspaces we ensure that there's at least one workspaces per detected monitor.  However, there's currently no check for `fixed number of workspaces` option so we better prob add one (e.g. change the setting if it's under the required num workspaces).  _Note: the default number of workspaces in Gnome (fixed) is 4._

**Comment by An-Eagle** [comment]
> > Yes, that allows tiling. Is it normal for it to treat both monitors as 2 completely different workspaces ?
> 
> Yes, in actual fact it's required in PaperWM, it's the _per monitor workspaces_ part of the PaperWM description:
> 
> > PaperWM is a Gnome Shell extension which provides scrollable tiling of windows and per monitor workspaces. It's inspired by paper notebooks and tiling window managers.
> 
> It allows separated tiling that PaperWM relies on for multiple monitors. It's not without it's issues though, (see [#389 (comment)](https://github.com/paperwm/PaperWM/issues/389#issuecomment-1911089672)).
> 
> > I think that might be the issue. Although I thoght we automatically set the settings to a usable value when PaperWM is enabled. In PaperWM (unlike what Gnome normally does) each monitor uses it's own workspace.
> 
> @Lythenas, well, if users use `dynamic` workspaces we ensure that there's at least one workspaces per detected monitor. However, there's currently no check for `fixed number of workspaces` option so we better prob add one (e.g. change the setting if it's under the required num workspaces). _Note: the default number of workspaces in Gnome (fixed) is 4._

Makes sense, Thank you

Closing as this is solved
