### ISSUE TITLE
Focus mode resets on screen lock-unlock

### ISSUE THREAD

**Issue by valpackett** [paperwm/PaperWM#819]
**Describe the bug**
Focus mode resets to DEFAULT on screen lock-unlock

**To Reproduce**
1. Change focus mode
2. Lock screen
3. Unlock screen

**Comment by jtaala** [comment]
Ah yes, good pickup.  We'd prob want to save the modes for all spaces and restore them when unlock.

Note: PaperWM only has session mode `user` - Gnome doesn't generally allow extensions to have the `unlock-dialog` session mode which would mean that PaperWM could remain active during window locks.

We'd want to add the current focus mode to the `SaveState` that gets called when we disable the `tiling` module:

https://github.com/paperwm/PaperWM/blob/060c2d6ed0e454116df6129dd1f267e30363a9dd/tiling.js#L3426
