### ISSUE TITLE
Commit f6d45a0 breaks manually moving window to new workspace

### ISSUE THREAD

**Issue by mogenson** [paperwm/PaperWM#82]
Prior to f6d45a0 I could move a window to a specific workspace by opening Gnome's activities overview and dragging a window to a workspace on the right, or by using Gnome's keyboard shortcuts for *Move window to workspace N*. Currently, only PaperWM's method of cycling a window through a carousel of workspaces works.

Tested on Wayland and X11 with Gnome 3.30.1.

**Comment by hedning** [comment]
Ah, missed checking if the window was new or not when fixing the crash issue.

Thanks :)
