### ISSUE TITLE
Activity pill on gnome 45 breaks

### ISSUE THREAD

**Issue by Ancairon** [paperwm/PaperWM#820]
**Describe the bug**

The pill sometimes is a different size, dots disappear etc

**To Reproduce**

use the extension and make some workspaces

**Expected behavior**
For the overview pill to not alter visually than what would happen by default

**Screenshots**
workspace 1
![image](https://github.com/paperwm/PaperWM/assets/70198089/4f2d4701-f1f9-4570-84f1-bca21471350f)
workspace 2
![image](https://github.com/paperwm/PaperWM/assets/70198089/2f1ecece-45f9-416f-b5fd-da09c125fdf1)
workspace 3
![image](https://github.com/paperwm/PaperWM/assets/70198089/e32aa003-e34e-4d3a-9e1d-0bdb353bca03)

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

```
Distribution: Ubuntu
GNOME Shell 45.2
Display server: Wayland
PaperWM branch/tag: release
PaperWM commit: de147afc77d96a9d79fb5eb377d78f369a71c979
Enabled extensions:
- rounded-window-corners@yilozt
- user-theme@gnome-shell-extensions.gcampax.github.com
- panel-corners@aunetx
- nightthemeswitcher@romainvigier.fr
- blur-my-shell@aunetx
- autohide-battery@sitnik.ru
- paperwm@paperwm.github.com
- mediacontrols@cliffniff.github.com
- dash-to-panel@jderose9.github.com
- bottom-overview@fthx
- unite@hardpixel.eu
- battery-indicator-icon@Deminder
- gnome-ui-tune@itstime.tech
- hide-keyboard-layout@sitnik.ru
- caffeine@patapon.info
- swap-finger-gestures-3-4@icedman.github.com
- burn-my-windows@schneegans.github.com
- ubuntu-appindicators@ubuntu.com
```

I use the gnome extension version of this, so the above is just from a clone I got, I am on latest paperwm version afaik

**Comment by jtaala** [comment]
Hey @Ancairon - I can't seem to reproduce this issue.  Let me know if you're doing anything different in the video below:

https://github.com/paperwm/PaperWM/assets/30424662/4b9ebf91-e2f5-4426-8f27-6df95f750b7f

Anyone else seeing this?

P.S. to rule out conflicts with other expensions, can you please disable all other extensions and try to reproduce?  A video or explanation of exact steps to reproduce this would help.

Jay.

**Comment by jtaala** [comment]
~~Also, you're on a very old tag - please update to latest `release` (note release branch is compatible with Gnome 45 & 46).~~

Sorry! I didn't see your comment on being on the latest version (via Gnome extensions).

**Comment by Ancairon** [comment]
I'm going to try disabling all extensions and seeing if it fixes it

**Comment by Ancairon** [comment]
~~Sadly it is Blur my Shell that introduces this bug, installed from extension store too, so I guess we can close this, not your issue guys~~

scratch that it is back

**Comment by Ancairon** [comment]
It could be `Gnome 4x UI Improvements`, I will roll with it for some time off, and then keep an eye to see if it breaks.

**Comment by Ancairon** [comment]
with that extension disabled, it appeared again on external displays connected to laptop 
![image](https://github.com/paperwm/PaperWM/assets/70198089/8acf051c-0fec-415d-b0fb-0225b86a8336)
![image](https://github.com/paperwm/PaperWM/assets/70198089/919977ca-280f-4b94-aafc-c471f82a1a98)

**Comment by jtaala** [comment]
Well, only real way to test this then would be to turn off all extension except PaperWM, log-out/log-in and then see if you can reproduce this.  If you can, keep track of any steps you did so we can try reproduce.

**Comment by jtaala** [comment]
Looking at your pics, it looks theme related - how are you getting the pill background colour changed?  Any extension change the theme/styling/colour of the Gnome pill?

**Comment by Ancairon** [comment]
I change the color with CSS on my custom theme. The pill seemed to be breaking with Dash to Panel.

I am now investigating it more, and will update with any new findings

**Comment by Ancairon** [comment]
@jtaala Disabling dash to panel and 4x ui improvements have fixed this.

**Comment by jtaala** [comment]
Thanks @Ancairon - I had a look and def looks like dash-to-panel was involved.  Perhaps it's a clash between those two extensions.  Closing this ticket now.
Jay.

**Comment by riodevelop** [comment]
Hi, same problem on gnome50:

1st workspace:

<img width="86" height="50" alt="Image" src="https://github.com/user-attachments/assets/87c12e6c-dbee-42d3-98cb-d923024232b1" />

2nd workspace:

<img width="86" height="50" alt="Image" src="https://github.com/user-attachments/assets/0bdc70e7-9579-44b0-aef3-09d404636a96" />

3rd workspace:

<img width="86" height="50" alt="Image" src="https://github.com/user-attachments/assets/aaf50c73-4f5b-492c-91c4-65c3af2f21c6" />
