### ISSUE TITLE
Wallpapers in the overview aren't aligned completly with workspace wallpapers

### ISSUE THREAD

**Issue by DonHugo69** [paperwm/PaperWM#83]
I just discovered this extension and I am very impressed with your idea and work! Thank you!

However, I think that wallpaper images are not scaled. [This](https://i.imgur.com/TTgEvYv.jpg) is the wallpaper I use, it is quite large and I use it on 1366 x 768 display. 
But below is what I get
![bildschirmfoto von 2018-10-19 10-17-00](https://user-images.githubusercontent.com/10484857/47206160-38fe4100-d388-11e8-9dd7-1cb1f84bc2f3.png) 
Would it be possible to adopt the wallpaper scaling from GNOME?

And one idea which came into my mind: 
Right now one can set each workspaces background separately (which is good). Would it be possible to have an option like "Use this wallpaper on all workspaces" in case the user wants to use the same everywhere?

**Comment by hedning** [comment]
Thanks, it's nice to see that other people are using this and finding it useful :)

Looks like the default wallpaper style isn't well suited for pictures (I'm just using colored backgrounds). I took a look at the gnome's defaults and copied those. So pictures should now be zoomed to fit the workspace, while colored backgrounds should get the noise applied as before.

Having a default background should be quite doable. I'll leave the issue open until that's done :)

**Comment by DonHugo69** [comment]
Thanks a lot for the fast response. The wallpaper scaling seems to work.
There is however one small visual inconsistency.
This is the activities overview:
![bildschirmfoto von 2018-10-20 17-11-32](https://user-images.githubusercontent.com/10484857/47257239-b3fc5000-d48b-11e8-8353-907e19e5df85.png)
and this the desktop
![bildschirmfoto von 2018-10-20 17-11-36](https://user-images.githubusercontent.com/10484857/47257245-beb6e500-d48b-11e8-94a0-5e549a037bbd.png)
When one looks closely at the bottom of the desktop picture one can see that the mountain has a small "pedestal". Furthermore, the center of the wallpaper (the tip of the mountain) is moved a bit to the left. This gets much more obvious when one opens and closes the activities overview or switches back and forth between the two screenshots. Is that fixable?

**Comment by hedning** [comment]
Right, that will be a bit more tricky unfortunately. The backgrounds in paperwm are actually somewhat bigger than the display to accommodate the workspace carousel (we want a border around the windows when they're scaled down). This means it doesn't align exactly with the native gnome background which covers the display exactly.

The transition between the regular view and the overview looks somewhat wonky to begin with, eg. if the gnome background is different than the workspace background there's just a sudden switch from one to the other. So a fix would probably be best done when adding somewhat better integration with the overview. The «correct» solution is probably replacing the overview background with the workspace background.

**Comment by DonHugo69** [comment]
Thanks for your response and explanation. It is not too disturbing and mainly visible when one opens the first windows on an empty workspace.

**Comment by olejorgenb** [comment]
Fixed in 86beb27e04045ce38e4a0da7267ef600a2cfdcfc
