### ISSUE TITLE
Windows are not 'grabbed' by PaperWM after hiding them

### ISSUE THREAD

**Issue by bashghost2600** [paperwm/PaperWM#838]
**Describe the bug**
PaperWM doesn't always tile all widnows.

**To Reproduce**
1. Open any window
2. Click Super + H
3. Reopen that hidden window

**Expected behavior**
Windows are not tiled to others, instead they act like in normal, non-tiled mode.

**System information:**
PaperWM 71, Debian 12, Gnome 43.9 (Wayland)

**Comment by jtaala** [comment]
Hey @bashghost2600,

Note: this is not a bug, but by design.  Hidden windows gets restored to the scratch layer:

https://github.com/paperwm/PaperWM?tab=readme-ov-file#scratch-layer

**Comment by jtaala** [comment]
P.S. I'm not saying this is a good design, just that it's always been that way.

@Lythenas - any thoughts here?  I'm open to switching this so window just retiles (maybe if was tiled before hiding?).

**Comment by jtaala** [comment]
Also, @bashghost2600, just to note that if a change was made here it would be in `develop` / `release` branch which is for Gnome 45 / 46.  Gnome 43 (and 44) are EOL now.  This change may be small enough that it would be backportable to 43... but some changes can't be (see https://github.com/paperwm/PaperWM/issues/837#issuecomment-2076650754).

Cheers.

**Comment by bashghost2600** [comment]
> P.S. I'm not saying this is a good design, just that it's always been that way.
> 
> @Lythenas - any thoughts here? I'm open to switching this so window just retiles (maybe if was tiled before hiding?).

Thanks for reply, didn't realize that (sorry for not reading all docs before, just focused on shortcuts part). Yeah, I also think it will be much more intuitive and faster to use (what basically tiling WM is for), cause when you want window to be tiled, you probably want it to be tiled after un-hiding. Thanks so much for fast reaction and already developing this feature!
