### ISSUE TITLE
Select window or workspace above or below

### ISSUE THREAD

**Issue by gustavcedersjo** [paperwm/PaperWM#847]
I have a hard time to remember a lot of different key bindings, so I try to make them few, but useful, and with a regular pattern to more easily remember. For example, I use Super+(direction) to change focus. However, if I want to switch focus to the workspace below, a need a different shortcut for that.

I would really like to reuse the same keybinding for selecting windows and workspaces. That way, I don't have to remember which combination of modifiers I have for switching workspaces. My suggestion is to introduce new keybindings for selecting the window or the workspace above and below, respectively. If selecting upwards, and there is a window above, then that window is selected, otherwise, the workspace above is selected.

I'm on the gnome-44 branch and made a quick implementation there. I can make a pull request if anyone wants to try it.

**Comment by Lythenas** [comment]
By workspace above do you mean you have a monitor above or do you mean switching to another workspace on the current monitor?

Just to mention this: Currently the `Super+Up/Down` would select a window above or below in the current column. Although I never used columns.

**Comment by gustavcedersjo** [comment]
Maybe you could have a similar system for monitors as well, but I was thinking about switching to another workspace. The workspaces are aligned vertically, but monitors are not always set up like that.

**Comment by Lythenas** [comment]
We do have keybindings for switching to a monitor in all directions, including up and down. Although I've never used them. So if you want to switch to the workspace that is shown on the monitor above the current one you can use that keybinding. But that does not sound like what you want.

So you basically want `Super+Down` to act like `Super+PageDown`.

I think that would be ok to add. But probably as a setting or another set of keybindings instead of changing the default.

Unfortunately it is not 100% obvious what the "correct" default behavior should be. E.g. if you have to monitors on top of each other I would expect navigating down to select the other monitor instead of switching workspaces on the current monitor. But it should be fine with a setting or separate keybindings.

**Comment by gustavcedersjo** [comment]
Yes, I want `Super+Down` to act like `Super+PageDown` if there is no window below to switch to. But, of course, as a new command, that I can bind `Super+Down` to.

I think combining "Activate window below/above" and "Switch to workspace above/below" works quite well. Doing something similar in the left/right direction would be trickier, since that would require scrolling through all windows before reaching the end.

**Comment by Lythenas** [comment]
Actually it is probably about the same. Because we do have columns where you can stack windows on top of each other in the workspace. Although I have never used that.

**Comment by gustavcedersjo** [comment]
I usually put two windows above each other in a column, one with an editor and one with a shell  for compiling and stuff. I like that feature very much!

**Comment by jtaala** [comment]
Hey all,

Yes, I can see the utility of that behaviour.  As mentioned we could add new keybinds (and leave it unset by default).

Also, you mentioned you're on Gnome 44, just a heads-up that, that there's many improvements and new features in for PaperWM versions in Gnome 45+, and I'm no longer working on Gnome 44 (which is EOL for Gnome as of 16th March).  In any case, feel free to put up a PR for `gnome-44` (I may use some of those approaches to implement this in `develop`/`release` branches and then backport to `gnome-44` and get you to test it there).

**Comment by gustavcedersjo** [comment]
I changed `Space.switch()` to return `true` if it performs a switch and `false` otherwise, and similarly with `Space.switchUp()` and `Space.switchDown()`. Then I added a function that first tries `Space.switchUp()`/`Space.switchDown()` and falls back to `selectSpaceUp()`/`selectSpaceDown()`. Does it sound like a reasonable solution? I'll come back with a pull request on the `develop` branch.

**Comment by jtaala** [comment]
> I changed `Space.switch()` to return `true` if it performs a switch and `false` otherwise, and similarly with `Space.switchUp()` and `Space.switchDown()`. Then I added a function that first tries `Space.switchUp()`/`Space.switchDown()` and falls back to `selectSpaceUp()`/`selectSpaceDown()`. Does it sound like a reasonable solution? I'll come back with a pull request on the `develop` branch.

Yes, that sounds like a reasonable solution.  With that solution, we could either map that to a new keybind (unassigned by default), or add an option related to this (enable/disable this behaviour).
