### ISSUE TITLE
Cannot enable extension after update

### ISSUE THREAD

**Issue by eliorc** [paperwm/PaperWM#855]
**Describe the bug**
I've installed the PaperWM extension through `extensions.gnome.org` and everything went well.
Then I got prompted to log out and in to get an update. After I clicked the prompt and re-logged, I cannot enable the extension.

I tried to remove the extension and reinstall it, same problem.

Also, through the command line, I tried enabling.

```bash
~ gnome-extensions list
ding@rastersoft.com
tiling-assistant@ubuntu.com
ubuntu-appindicators@ubuntu.com
ubuntu-dock@ubuntu.com
screen-capture-protection@citrix.com
paperwm@paperwm.github.com

 ---

~ gnome-extensions enable paperwm@paperwm.github.com

 ---

~ gnome-extensions info paperwm@paperwm.github.com
paperwm@paperwm.github.com
  Name: PaperWM
  Description: Tiling window manager with a twist
  Path: /home/eliorc/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com
  URL: https://github.com/paperwm/PaperWM
  Version: 46.8.1 (107)
  Enabled: No
  State: INITIALIZED
```

**To Reproduce**
Just click the pop-up on gnome-extension UI and see if it workf for you

**Expected behavior**
To be able to enable the extension

**Screenshots**
Screenshot of the Gnome Extensions UI - cannot enable
![image](https://github.com/paperwm/PaperWM/assets/17727283/bd5de536-0ca5-46eb-9e26-d465bcfd28d0)

**System information:**
Distribution: Ubuntu 24.04 LTS (Noble Numbat)
GNOME Shell: 46.0
Display server: Wayland
PaperWM version: 46.8.1
Enabled extensions:
- tiling-assistant@ubuntu.com
- ubuntu-appindicators@ubuntu.com
- ubuntu-dock@ubuntu.com

**Comment by jtaala** [comment]
hmmm.  Can you try a manual uninstall, login and then try reinstall?  E.g.

```
rm -rf ~/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com
```

Logout, login, and then reinstall via extensions.gnome.org.

**Comment by jtaala** [comment]
Just did a clean install of PaperWM via gnome.extensions.org.  Can't reproduce.

Anyone else seeing this?

**Comment by jtaala** [comment]
Have you recently (or before) installed the source code version?  Sometimes it can get confused and usually requires deleting the source code version installed symlink.

Anyways, let me know how you go.

**Comment by eliorc** [comment]
Now I haven't it's a fresh Ubuntu install, I'm going to try what you mentioned with the manual reinstallation

**Comment by eliorc** [comment]
@jtaala didn't work

**Comment by jtaala** [comment]
hmmm.  Can you paste the output of.

Okay, let's manually remove again:

```
rm -rf ~/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com
```

after that, can you paste the out of:

```
ls ~/.local/share/gnome-shell/extensions/
```

Just need to make sure it's clear.

On a sidenote, it looks like you can't enable any extension from your extension UI screenshot you put up?

**Comment by eliorc** [comment]
> On a sidenote, it looks like you can't enable any extension from your extension UI screenshot you put up?

True that. Seems like something locked the ability to enable extensions. In `/etc/dconf/db/local.d/locks/extensions-mandatory` the value of enabling extensiosn was locked. After I removed it everything works okay. I guess this is not a result of anything related to PaperWM. 

Thanks for the replies anyhow :)

**Comment by jtaala** [comment]
np.  Glad you got it sorted.
