### ISSUE TITLE
Reset settings

### ISSUE THREAD

**Issue by DonHugo69** [paperwm/PaperWM#86]
I am looking for a way to reset PaperWM's settings (e.g. workspace names, wallpapers). So far, deleting the paperwm folder in `.config` did not change anything, the prior settings are still in place. Would this be possible to implement? Or where can one find the necessary files to delete?

**Comment by hedning** [comment]
Settings are stored in dconf, so you'll need use eg. `dconf` or `dconf-editor`.

Eg. launch `dconf` like this from the paperwm source directory: `GSETTINGS_SCHEMA_DIR=$PWD/schemas dconf-editor &. Go to `/org/gnome/shell/extensions`, right click `paperwm` and select «reset recursively».

From the cli something like this should work: `dconf reset -f /org/gnome/shell/extensions/paperwm/`

**Comment by DonHugo69** [comment]
Thanks, `dconf reset -f /org/gnome/shell/extensions/paperwm/` works.
