### ISSUE TITLE
Selected window bordser size (px) 0 (zero) still visible

### ISSUE THREAD

**Issue by skewty** [paperwm/PaperWM#860]
**Describe the bug**
When "Selected window bordser size (px)" is set to : `0` the border is still visible on non legacy (squared bottom corners) in the bottom corners.  Additionally setting for `.paperwm-selection {border-radius: 8px;}` seems to have no effect (bottom borders have 0 radius).

**To Reproduce**
1. Set "Selected window bordser size (px)" to `0`
2. Open a non legacy app such as Gnome Files or Gnome Settings.
3. Notice at the bottom corner the border is visible.

**Expected behavior**
The border cannot be seen.

**Screenshots**

![image](https://github.com/paperwm/PaperWM/assets/9087223/145bebcb-847e-40aa-b693-9b130e42af98)

NOTICE the blue border is still present.

**System information:**
Please provide system information:
Fedora 40 / Gnome 46.

**Comment by jtaala** [comment]
> Additionally setting for `.paperwm-selection {border-radius: 8px;}` seems to have no effect (bottom borders have 0 radius).

How are you setting/applying this?

See this comment for overriding css (including making the colour transparent):

https://github.com/paperwm/PaperWM/issues/683#issuecomment-1806648963

Note, you'll need to disable/enable PaperWM to have styles reapplied (or logout/login).

**Comment by jtaala** [comment]
Scrap that - looks like we're border-radius may not be being applied here.  Will look into it when I get a chance.

Cheers.

**Comment by jtaala** [comment]
ha - looks like Gnome 46 has made changes to the `tile-preview` style (we also apply that class) and it now enforcing border-radius.

**Comment by jtaala** [comment]
In the interim, if you're trying to hide the window selection element (border), add this to your `user.css`:

```
.paperwm-selection {
    border: rgba(0, 0, 0, 0);
    background-color: rgba(0, 0, 0, 0);
}
```
Then disable/enable PaperWM.

**Comment by jtaala** [comment]
@skewty,

I've pushed a PR #861 to completely hide the selection element if border size is 0.

Planning to release this in the next day or so (along with #859).

If you installed via source, feel free to checkout and install [fix-zero-border-size-hide-selection-entirely](https://github.com/paperwm/PaperWM/tree/fix-zero-border-size-hide-selection-entirely) branch.
