### ISSUE TITLE
add links to reimplementations

### ISSUE THREAD

**Issue by spwhitton** [paperwm/PaperWM#864]
Hi,

I have reimplemented PaperWM for Sway/i3wm.

It would be great if you would consider linking to my project at the end of your README.  When I first discovered PaperWM I really wanted to try it, but didn't want to switch to GNOME.  There are probably others like me.

https://spwhitton.name/tech/code/papersway/

**Comment by jtaala** [comment]
Hey @spwhitton,

Nice work!  See https://github.com/paperwm/PaperWM?tab=readme-ov-file#related--similar-projects

**Comment by spwhitton** [comment]
Many thanks, and glad to see the other links too.
-- 
Sean Whitton
