### ISSUE TITLE
Horizontal scroll support

### ISSUE THREAD

**Issue by irisdominguez** [paperwm/PaperWM#865]
**Is your feature request related to a problem? Please describe.**
My touchpad doesn't recognize well the three finger scroll gesture, and in any case I quite dislike that kind of gesture. Keyboard navigation is awesome, but sometimes I'm switching between mouse intensive applications.

**Describe the solution you'd like**
A switch to enable `super+scrolling` (horizontal mostly, but maybe even the regular vertical?) as a way of scrolling the full workspace, similar to the three finger swipe gesture.

**Describe alternatives you've considered**
I'm mostly using the keyboard scroll for now, but switching keyboard to mouse all the time can be a bit annoying.

**Additional context**
I sometimes launch the X11 session on my machine (to enable Rofi, mostly), and on that one the three finger swipes don't even work. I can imagine this could be nice for people using X11 sessions.

Also, on my system (is this all Gnomes? I'm not sure), I can enable one finger edge swiping, which has both vertical and horizontal scrolling. Using `super+horizontal scrolling` on this setup would be superb for me.

EXTRA: I just realized that the build is not the same for all versions of the shell. I'm on the 44 branch (I'll update soon, I hope), so there's a good chance that there are already alternatives on main. If that's the case, just close this ^_^U

**Comment by cpiber** [comment]
Was just looking for the same, seems to be duplicate of #331 and #208, doesn't seem like there's a solution atm

**Comment by irisdominguez** [comment]
Actually, the other dupe is #206 , now that you have pointed me in the right direction. I'll close this as a dupe, but yeah, hopefully we'll get this at some point :four_leaf_clover:

**Comment by irisdominguez** [comment]
Close as duplicate
