### ISSUE TITLE
Rounded lower corners for border, user.css

### ISSUE THREAD

**Issue by Plyply99** [paperwm/PaperWM#867]
Greetings,
I've been trying to get lower rounded corners for the border. 
![Screenshot from 2024-05-29 12-27-17](https://github.com/paperwm/PaperWM/assets/103620143/7acb49b0-28d3-4bb1-b204-9e436bf0f49f)

This is the modification I made to user.css but it doesn't apply the radius to lower corners:

.paperwm-selection {
    border: 12px rgba(248, 248, 242, 0.8);
    border-radius: 12px;
    background-color: rgba(0, 0, 0, 0);
}

**Comment by jtaala** [comment]
Hey @Plyply99,

This previously worked, but likely was impacted by #822.  Border color is honored but border-radius doesn't work.

In any case, I'll move border radius as a preference setting.

Thanks for reporting.
