### ISSUE TITLE
Maximized windows are broken in weird ways

### ISSUE THREAD

**Issue by valpackett** [paperwm/PaperWM#870]
**Describe the bug**

"internally" (?) maximized windows (i.e. not stretched with Super+F but rather actually maximized with headerbar double click etc.) seem quite broken

**To Reproduce**
1. Maximize various windows..?

**Expected behavior**

Well, not this:

**Screenshots**

For example when I maximize Firefox, it's a bit off-screen to the left and does not respond to cursor input anymore (keyboard yes)

![image](https://github.com/paperwm/PaperWM/assets/208340/994d28c7-4821-42e5-bebb-91c1c7c469d4)

Text editor in a nested shell being weirdly cropped:

![image](https://github.com/paperwm/PaperWM/assets/208340/3c0bffda-69c1-4346-807f-84254c88994b)

…but fully interactable and the weirdness goes away when dragging it and canceling.

upd: Opening two windows in the nested shell and maximizing the second one actually resulted in the same thing happening to the text editor as what happened to Firefox above.

**System information:**

```
Distribution: Chimera
GNOME Shell 46.2
Display server: Wayland
PaperWM branch/tag: develop
PaperWM commit: 53ddefb4d0b872abb217b96406e07ce1dd46e524
Enabled extensions:
- pip-on-top@rafostar.github.com
- compiz-windows-effect@hermes83.github.com
- do-not-disturb-while-screen-sharing-or-recording@marcinjahn.com
- burn-my-windows@schneegans.github.com
- just-perfection-desktop@just-perfection
- blur-my-shell@aunetx
- caffeine@patapon.info
- one-thing@github.com
- tailscale@joaophi.github.com
- AlphabeticalAppGrid@stuarthayhurst
- weatherornot@somepaulo.github.io
- panel-corners@aunetx
- paperwm@paperwm.github.com
- light-style@gnome-shell-extensions.gcampax.github.com
- system-monitor@gnome-shell-extensions.gcampax.github.com
- lgbutton@glerro.gnome.gitlab.io
```

**Additional context**

I'm going to send a PR with an option to turn maximizing into Super+F type stretching but that's just something I generally want, and only incidentally works as a *workaround*, full maximize should work still. Hm I wonder if doing layout on maximize could fix at least one of the things.

**Comment by jtaala** [comment]
Closing since #871 and #873 now merged and released.
