### ISSUE TITLE
Make a Kwin script for kde plasma

### ISSUE THREAD

**Issue by ghost** [paperwm/PaperWM#874]
I would like paperWM and also backported to older versions of plasma because how easy it is to develop kwin scripts and only break when like plasma 7 come out for example which is almost a decade to release.

**Comment by jtaala** [comment]
Hey @AnyCreatureMorph.  PaperWM isn't a script, and goes much deeper into Gnome internals than most (any) extension I know of.  In short, it relies on rewriting many gnome implementations and behaviours - and on doing things that aren't possible to change/do in kwin (e.g. see https://github.com/peterfajdiga/karousel/issues/3).

In any case, we won't be doing this, but would support other developers looking at what PaperWM does, and trying to do something similar in KDE.

Also, consider contributing and supporting [Karousel](https://github.com/peterfajdiga/karousel) which seeks to do something similar using kwin.
