### ISSUE TITLE
Blank Pop-ups

### ISSUE THREAD

**Issue by RobLW** [paperwm/PaperWM#875]
**Describe the bug**
In Firefox, I use an addon called Simple Tab Groups. I put the toolbar icon on the left side of my URL bar. 
When you click it, a pop up menu opens. If the menu opens within the window frame of Firefox, it works perfectly, if the pop up overlaps the window frame, so some of the popup window is outside of the firefox window, it can often show as blank. I'm guessing this isn't limited to just this addon and firefox.

Here is the odd bit, if you move your mouse over the extension icon, ready to click it, wait for the tooltip to pop up first, then click the extension icon, it all works perfect most of the time. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install STG addon ( https://addons.mozilla.org/en-Gb/firefox/addon/simple-tab-groups/ )
2. Click on firefox extensions and pin STG to your toolbar. 
3. Move the STG icon to the left of your toolbar
4. Create some new groups in the extension.
5. Ensure your firefox window size is 3/4 of your screen or less, so you can partially see the next tiled app.
6. Click the extension in firefox so the pop up opens. 

**Expected behavior**
For the pop up window from the extension to be rendered, whether inside the firefox window frame or partially outside.

**Screenshots**
![image](https://github.com/paperwm/PaperWM/assets/134645719/4f9504a3-c474-426a-8296-e1f343a92e0a)

**System information:**
Fedora = 40
```
Distribution: Fedora Linux
GNOME Shell 46.2
Display server: Wayland
PaperWM branch/tag: release
PaperWM commit: 43f03398d9c4963771cdb1266bf45f1deeb999ed
Enabled extensions:
- appindicatorsupport@rgcjonas.gmail.com
- paperwm@paperwm.github.com
```

**Additional context**
N/A

**Comment by jtaala** [comment]
Hey @RobLW,

This doesn't appear to be a PaperWM issue.  That is, it is reliably reproducible without PaperWM (disable/uninstall, logout/login).  E.g. see video below reproducing without PaperWM installed:

[Screencast from 2024-06-13 08-14-26.webm](https://github.com/paperwm/PaperWM/assets/30424662/38567a51-2ff5-4772-a27c-bc8515d856dc)

Closing this as an upstream (STG) issue.
