### ISSUE TITLE
Paperwm and ddterm crashes gnome shell

### ISSUE THREAD

**Issue by thenameisluk** [paperwm/PaperWM#880]
**Describe the bug**
when paperwm is enabled opening ddterm can crash gnome shell (that has not been the case before)

**To Reproduce**
1. install paperwm
2. install ddterm
3. try opening a terminal (on touch device)

**Expected behavior**
No crash

**Screenshots**
https://github.com/paperwm/PaperWM/assets/92756992/63acc6a1-2985-4158-820f-7c9234c77031

**System information:**
Distribution: Debian GNU/Linux
GNOME Shell: 46.2
Display server: Wayland
PaperWM version: 46.12.0
Enabled extensions:
- tophat@fflewddur.github.io
- ddterm@amezin.github.com
- paperwm@paperwm.github.com
- gsconnect@andyholmes.github.io
- caffeine@patapon.info
- gravatar@dsheeler.net
- weatheroclock@CleoMenezesJr.github.io

**Additional context**
might be the case that the black bar is also used to move windows on touch devices causes the issue #804

**Comment by jtaala** [comment]
Thanks for reporting @LukIsHere.  Will try to reproduce.  

I'll have a look at this one.  Can you install a previous version (e.g. 46.11.2) and see if your can reproduce?

**Comment by jtaala** [comment]
Just to help isolate the issue.

**Comment by thenameisluk** [comment]
where can i get that vers of shell from?
debian provides only [one version](https://packages.debian.org/pl/experimental/gnome-shell)
i don't know how to do version hopping

**Comment by jtaala** [comment]
> i don't know how to do version hopping

No probs - I can reproduce and have a fix ready.

For reference though, to change version you would install PaperWM by source:
https://github.com/paperwm/PaperWM?tab=readme-ov-file#install-via-source

and the checkout the version you want and run `.install.sh`, logout then login.

**Comment by jtaala** [comment]
Hey @LukIsHere, just pushed a fix.

Will need to wait until Gnome Extensions team (on extensions.gnome.org) approve it, but hopefully that should be today.

The fixed version is `v46.12.1`.  Once you get the updated version, let me know if you there's still an issue there.

**Comment by jtaala** [comment]
Will close this issue once v46.12.1 has been approved/released on extensions.gnome.org.

**Comment by jtaala** [comment]
Closed as fixed by #882.

**Comment by thenameisluk** [comment]
yep that fixed the issue thank u very much ❤️
