### ISSUE TITLE
dconf-editor segfault when run per readme

### ISSUE THREAD

**Issue by humanplayer2** [paperwm/PaperWM#887]
**Describe the bug**
Running, per the  readme,

    GSETTINGS_SCHEMA_DIR=$HOME/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/schemas dconf-editor /org/gnome/shell/extensions/paperwm/

returns

     segmentation fault (core dumped)  GSETTINGS_SCHEMA_DIR= dconf-editor /org/gnome/shell/extensions/paperwm/

**To Reproduce**
1. Open a terminal and run the command.
2. See error

**Expected behavior**
I expected `dconf-editor` to open and show me the available schemas and keys. 

**System information:**
Distribution: Fedora Linux 40 (Workstation Edition)
GNOME Shell: 46.2
Display server: Wayland
PaperWM version: 46.13.1
Enabled extensions:
- paperwm@paperwm.github.com

**Additional context**
Listing all keybindings, as I am interested in, works with

    gsettings --schemadir $HOME/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/schemas/ list-recursively org.gnome.shell.extensions.paperwm.keybindings

**Comment by jtaala** [comment]
Hey @humanplayer2,

So this is actually a bug in dconf rather than paperwm.  It has to do with dconf's schema parsing code.  In any case, there's a not-well-known workaround, try this:

```
GSETTINGS_SCHEMA_DIR=/null:/null:$HOME/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/schemas dconf-editor /org/gnome/shell/extensions/paperwm/
```

**Comment by jtaala** [comment]
Rather than wait until `dconf` fixes it, I might just update the readme to include the workaround.

**Comment by jtaala** [comment]
Closing as command has been updated in README.md.
