### ISSUE TITLE
Add switch-left-or-else-monitor and switch-right-or-else-monitor

### ISSUE THREAD

**Issue by humanplayer2** [paperwm/PaperWM#888]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I have to use a different shortcut to switch to a left/right monitor when I'm at my left/right-most windows.

**Describe the solution you'd like**
I would like to be able to change focus from left to right, and when reaching the left-most window on my right monitor, I would like to continue switching focus to the right-most window on my left monitor. And vice-versa for right to left.

So, like `switch-down-or-else-workspace`, but horizontally and with monitors instead of workspaces.

**Describe alternatives you've considered**
Using Forge, which has this behavior (no, not really: I come from Forge, and maybe that's why I miss this feature.

**Comment by jtaala** [comment]
Hey @humanplayer2,

This is already implemented - although the keybinds aren't assigned by default:

![image](https://github.com/paperwm/PaperWM/assets/30424662/9e6da0a7-1ac8-4ce7-87cd-6ba80804748d)

Set these to what you're preferred keybinds (e.g. you can replace the normal `switch to the right window` etc. keybinds).

**Comment by jtaala** [comment]
P.S. I have those set as my default switching keybinds.

Closing this issue as it's already implemented.  Let me know if you meant something else.

**Comment by humanplayer2** [comment]
I didn't, I just overlooked it. I've exported all the schemas to a script so I can set them using gsettings, and must there have overlooked it.

Thank you for your help!

**Comment by jtaala** [comment]
This was implemented in #850.

**Comment by humanplayer2** [comment]
Thanks, I found it by running setting a `Super + Alt + x` shortcut, and running `gsettings --schemadir $HOME/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/schemas/ list-recursively org.gnome.shell.extensions.paperwm.keybindings | grep Alt`.

`switch-global-left` and `switch-global-right`, here we go!
