### ISSUE TITLE
Hide this "XWayland recording gateway" window

### ISSUE THREAD

**Issue by megatux** [paperwm/PaperWM#889]
**Is your feature request related to a problem? Please describe.**

In my Nobara Gnome with PaperWM, there is an extra "window" for something called XWayland Video Recording gateway (translated, could be a bit diff. the name in English). Attached screenshot. I see the program name when using the alt-tab switcher.

**Describe the solution you'd like**

Ideally, this process/window should be invisible, omitted in alt-tab or some way to add in a hide-list.

**Additional context**
![Captura desde 2024-07-05 09-40-55](https://github.com/paperwm/PaperWM/assets/850020/25fe009f-c6be-4145-970c-f55cbd019ee7)

Thanks!

**Comment by jtaala** [comment]
Hmmm - haven't heard or seen that one before.  Unfortunately that screenshot isn't much help - I can't see the window (is it the whitespace in the middle?).

Generally for this type of thing we'd add it to PaperWM winprops and set it as a scratch window.  However you'd need to know the window class or title to have it detected:

https://github.com/paperwm/PaperWM?tab=readme-ov-file#setting-window-specific-properties

Are you able to create a short video showing the window (e.g. in atl-tab)?

**Comment by jtaala** [comment]
Do you think it's this?

https://www.phoronix.com/news/KDE-XWaylandVideoBridge

**Comment by jtaala** [comment]
Okay, yep, I think that was it.  Please add this to your `winprops` settings:

![image](https://github.com/paperwm/PaperWM/assets/30424662/ed0402bf-ed67-46f8-afc1-337c026b68a5)

Then you might need to logout / login again (or restart).  Basically, we need to kill `xwaylandvideobridge` and have it start again.

**Comment by jtaala** [comment]
Unless you really need `xwaylandvideobridge` I would suggest you uninstall it.  It still leaves a weird faint whiteline in the upper left corner of my monitor (even in vanilla gnome without PaperWM installed).

**Comment by jtaala** [comment]
> Unless you really need `xwaylandvideobridge` I would suggest you uninstall it. It still leaves a weird faint whiteline in the upper left corner of my monitor (even in vanilla gnome without PaperWM installed).

See this bug report (yes, it's `xwaylandvideobridge`): https://www.mail-archive.com/kde-bugs-dist@kde.org/msg856240.html

P.S. do you also have / use KDE?

**Comment by megatux** [comment]
Cool, I added the Winprop wm_class, will re-login later, after work, and recheck.
Yes, I also installed KDE desktop some days ago.


```
Distribution: Nobara Linux 39 (GNOME Edition)
GNOME Shell: 45.5
Display server: Wayland
PaperWM version: 46.13.1
Enabled extensions:
- clipboard-indicator@tudmotu.com
- paperwm@paperwm.github.com
- dash-to-dock@micxgx.gmail.com
- just-perfection-desktop@just-perfection
- user-theme@gnome-shell-extensions.gcampax.github.com
- window-list@gnome-shell-extensions.gcampax.github.com
```

Adding another shot, of the issue with the window-list switcher, just in case:

![Captura desde 2024-07-05 15-40-38](https://github.com/paperwm/PaperWM/assets/850020/ea3631aa-b7c6-4625-a18b-31f2e96b2dcd)

Thanks a lot for PaperWM, I really like it and wanted to try this concept since I saw that original concept some time ago. Also tried Niri compositor, it's nice but still immature.

**Comment by jtaala** [comment]
No probs.  So, AFAIK, this is a KDE application that causes issues in GNOME, and not just in PaperWM.  I don't think this is needed for GNOME (and especially GNOME wayland):
- https://www.mail-archive.com/kde-bugs-dist@kde.org/msg856240.html
- https://www.reddit.com/r/Fedora/comments/18ec7mm/recently_installed_kde_and_a_white_line_appeared/
- https://www.reddit.com/r/NobaraProject/comments/1bu0d9j/xwayland_video_bridge_issue/

In GNOME I would suggest closing/killing this process (or stopping it from starting).

Will close this issue now.

**Comment by megatux** [comment]
Adding the winprop worked perfectly. Thanks again.
