### ISSUE TITLE
Have a button to disable the current scroll behavior on the top panel 

### ISSUE THREAD

**Issue by CyberDruga** [paperwm/PaperWM#891]
**Is your feature request related to a problem? Please describe.**
I use PaperWM together with Dash to Panel, and in Dash to Panel I've set the scroll to change volume when scrolling in the pannel, but PaperWM now **also** changes windows left and right too, and I couldn't find a way to disable this feature.

**Describe the solution you'd like**
Have an option that allows me to disable it.

**Describe alternatives you've considered**
Having the Option keep it enabled or disable it is the best option IMO.

**Additional context**

I have disabled Dash to Panel to make sure it's a behavior from PaperWM, and I'm using version 46.13.1 .

It looks like this when I try to change my volume:

https://github.com/paperwm/PaperWM/assets/22626848/7a82bb70-bf39-419f-b752-468ac2cbe31f

**Comment by jtaala** [comment]
Fair enough - we can add an option to disable this new feature.

**Comment by jtaala** [comment]
Fixed by #892.

Will be available soon once extensions.gnome.org approves this version (version 46.13.2 has this new option to disable mouse-scrolling on topbar in PaperWM).
