### ISSUE TITLE
PaperWM cannot handle RDP desktops

### ISSUE THREAD

**Issue by stablestud** [paperwm/PaperWM#894]
**Describe the bug**
PaperWM is in a Error state when connecting remotely via RDP.
Looking at the user journal, I get the following JS Error:
```
gnome-shell[5779]: Added virtual monitor Meta-0
gnome-shell[5779]: JS ERROR: TypeError: (intermediate value).spaces is undefined
                   setupOverrides/<@file:///home/user/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/patches.js:445:13
                   _init/<@resource:///org/gnome/shell/ui/screenshot.js:1396:18
                   _monitorsChanged@resource:///org/gnome/shell/ui/layout.js:613:14
                   @resource:///org/gnome/shell/ui/init.js:21:20
```

Output of `gnome-extensions info paperwm@paperwm.github.com`
```
paperwm@paperwm.github.com
  Name: PaperWM
  Description: Tiling window manager with a twist
  Path: /home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com
  URL: https://github.com/paperwm/PaperWM
  Version: 46.13.2
  Enabled: Yes
  State: ERROR
```

**To Reproduce**
1. Enable Remote Desktop
   1. Open Gnome Settings
   2. Go to System
   3. Click on Remote Desktop
   4. Go to tab Remote Login
   5. Enable Remote Login
   6. Set Login details for RDP connection
2. Login via RDP
3. PaperWM not started

**Expected behavior**
PaperWM to be working with RDP

**System information:**
```
Distribution: Ubuntu (24.04)
GNOME Shell 46.0
Display server: Wayland
PaperWM branch/tag: release
PaperWM commit: 3a7c25f86ed5ad89a78ccfe7ad565537846fcf28
Enabled extensions:
- paperwm@paperwm.github.com
- ding@rastersoft.com
- tiling-assistant@ubuntu.com
- ubuntu-appindicators@ubuntu.com
- ubuntu-dock@ubuntu.com
```

**Additional context**
PaperWM is working fine without a remote desktop. However this is a VM and RDP is the only reasonable way of working with the desktop.

**Comment by jtaala** [comment]
hmm - so I use a vm often (actually develop PaperWM on virt-manager) - but don't use RDP.

I'll try reproduce this.  Interesting that the error is in the `ScreenshotUI`.

Thanks for reporting.

**Comment by jtaala** [comment]
Hey @stablestud, can you test a branch I've put up?

```
git fetch --all
git checkout fix-rdp-support
./install.sh
```

Then logout / login and try access via RDP again.  Let me know if it makes any difference (it might fix this - or hit a different exception - but this should fix the exception you outlined above).

Cheers.

**Comment by jtaala** [comment]
So, I can connect to a VM via RDP and PaperWM is working for me:

[Screencast from 2024-07-17 23-39-38.webm](https://github.com/user-attachments/assets/d2cf0f93-64d6-40bb-9760-d496265d6842)

I do note though that performance is very slow over RDP with my setup (and 3d acceleration doesn't appear to work) - at least compared to `virt-manager` or `virt-viewer`.

Let me know if those changes in that branch made any difference for you.

**Comment by stablestud** [comment]
Strange, I tried your branch and after `./install.sh` and    
`gnome-extensions enable paperwm@paperwm.github.com` it worked inside the RDP session.    
However when I logout and relogin I get the same error as before:

```
gnome-shell[33307]: Added virtual monitor Meta-0
gnome-shell[33307]: JS ERROR: TypeError: (intermediate value).spaces is undefined
                    setupOverrides/<@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/patches.js:445:13
                    _init/<@resource:///org/gnome/shell/ui/screenshot.js:1396:18
                    _monitorsChanged@resource:///org/gnome/shell/ui/layout.js:613:14
                    @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by stablestud** [comment]
Looking further into the log output this caught my eye:
```
gnome-shell[36305]: #PaperWM enabled
systemd[36067]: Starting dconf.service - User preferences database...
systemd[36067]: Started dconf.service - User preferences database.
gnome-shell[36305]: Extension paperwm@paperwm.github.com: TypeError: monitor is null
                    
                    Stack trace:
                      createBackground@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:1885:17
                      setMonitor@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:1957:18
                      Space@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:372:14
                      addSpace@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:3142:21
                      Spaces@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:2150:18
                      enable@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:150:14
                      enable/<@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:66:19
                      enable@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:64:22
                      _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:267:38
                      loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:479:32
                      async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:795:24
                      async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:801:48
                      _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:836:20
                      async*init@resource:///org/gnome/shell/ui/extensionSystem.js:77:14
                      _initializeUI@resource:///org/gnome/shell/ui/main.js:313:22
                      start@resource:///org/gnome/shell/ui/main.js:185:11
                      @resource:///org/gnome/shell/ui/init.js:12:47
                      @resource:///org/gnome/shell/ui/init.js:21:20
```

The above error message is happening before the RDP server is started:
```
gnome-remote-de[36696]: RDP server started
```

And only then the previous error message is displayed:
```
gnome-shell[33307]: Added virtual monitor Meta-0
gnome-shell[33307]: JS ERROR: TypeError: (intermediate value).spaces is undefined
                    setupOverrides/<@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/patches.js:445:13
                    _init/<@resource:///org/gnome/shell/ui/screenshot.js:1396:18
                    _monitorsChanged@resource:///org/gnome/shell/ui/layout.js:613:14
                    @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by stablestud** [comment]
Interesting is, when I login with PaperWM disabled, and enabling it afterwards when the default Gnome desktop has started, it works without problems.

Seems like it currently cannot be run on startup.
My guess is it expects a monitor to be available:
```
Extension paperwm@paperwm.github.com: TypeError: monitor is null
```
But hence the built-in Gnome RDP server has not started up yet, it fails.

**Comment by jtaala** [comment]
ah - I haven't tried logging out / logging in yet with rdp, but will try - and dig deeper tomorrow.

**Comment by jtaala** [comment]
So, I'm kind of stuck in trying to reproduce this.  Strangely, I can connect via rdp is I choose `Desktop Sharing` but not with `Remote Login` (and hence I can't actually "log out" to try reproduce this).

It's probably my vm setup (virt-manager, with SPICE video and full 3d acceleration in the vm).  I don't use RDP.

> Seems like it currently cannot be run on startup. My guess is it expects a monitor to be available:
> 
> ```
> Extension paperwm@paperwm.github.com: TypeError: monitor is null
> ```
> 
> But hence the built-in Gnome RDP server has not started up yet, it fails.

Yes, this would be it.  That error (by itself) doesn't help much as I can't see where this is occurring in the logs.

Anyways, will leave this open in case someone else uses RDP and wants to debug this.

**Comment by stablestud** [comment]
Thanks for looking into it. 😃👍

**Comment by jtaala** [comment]
> Looking further into the log output this caught my eye:
> 
> ```
> gnome-shell[36305]: #PaperWM enabled
> systemd[36067]: Starting dconf.service - User preferences database...
> systemd[36067]: Started dconf.service - User preferences database.
> gnome-shell[36305]: Extension paperwm@paperwm.github.com: TypeError: monitor is null
>                     
>                     Stack trace:
>                       createBackground@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:1885:17
>                       setMonitor@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:1957:18
>                       Space@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:372:14
>                       addSpace@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:3142:21
>                       Spaces@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:2150:18
>                       enable@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:150:14
>                       enable/<@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:66:19
>                       enable@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js:64:22
>                       _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:267:38
>                       loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:479:32
>                       async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:795:24
>                       async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:801:48
>                       _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:836:20
>                       async*init@resource:///org/gnome/shell/ui/extensionSystem.js:77:14
>                       _initializeUI@resource:///org/gnome/shell/ui/main.js:313:22
>                       start@resource:///org/gnome/shell/ui/main.js:185:11
>                       @resource:///org/gnome/shell/ui/init.js:12:47
>                       @resource:///org/gnome/shell/ui/init.js:21:20
> ```
> 
> The above error message is happening before the RDP server is started:
> 
> ```
> gnome-remote-de[36696]: RDP server started
> ```
> 
> And only then the previous error message is displayed:
> 
> ```
> gnome-shell[33307]: Added virtual monitor Meta-0
> gnome-shell[33307]: JS ERROR: TypeError: (intermediate value).spaces is undefined
>                     setupOverrides/<@file:///home/agottweis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/patches.js:445:13
>                     _init/<@resource:///org/gnome/shell/ui/screenshot.js:1396:18
>                     _monitorsChanged@resource:///org/gnome/shell/ui/layout.js:613:14
>                     @resource:///org/gnome/shell/ui/init.js:21:20
> ```

Actually, I didn't look at this stack trace properly, this is the type of info that's super helpful and makes sense. 

If you're able to test more on that branch, I'll make some more changes on that branch for you to test and feedback more log output.

**Comment by stablestud** [comment]
Yes sure! That would be awesome. I could report back on next Tuesday

**Comment by jtaala** [comment]
Just updated branch `fix-rdp-support`.  Basically added some `monitor` null/undefined checks.  Whenever you can, pull the latest on this branch and test if out.

I'm expect we should get past that error you showed in your logs - but we'll probably hit another one.

Thanks @stablestud!

**Comment by jtaala** [comment]
Oh, make sure when you pull the latest on that branch - you do a logout / login.

If you switched back to the normal install (e.g. from extensions.gome.org), you might need to do a:

```
git checkout fix-rdp-support
git pull
./install.sh
```

Thanks!

**Comment by stablestud** [comment]
@jtaala thats it!

It works now flawless!
Also checked the logs, but nothing.
Thank you :)

**Comment by jtaala** [comment]
> @jtaala thats it!
> 
> It works now flawless! Also checked the logs, but nothing. Thank you :)

Great news.  I'll do up a release for these changes tonight.

Cheers.

**Comment by jtaala** [comment]
Will reopen this until it's merged into release branch and the release is live.
