### ISSUE TITLE
Keyboard stops working if a window is closed while dragging

### ISSUE THREAD

**Issue by malcolmredheron** [paperwm/PaperWM#896]
**Describe the bug**
If you are dragging a window when it closes, things get into a very strange state:
- you can still use keyboard shortcuts to move focus between windows
- but no other keys work -- you can't type anywhere
- and clicking doesn't work anywhere either
- I have found no option but to force-restart

**To Reproduce**
1. Enable PaperWM
2. Open a terminal and run [sleep 5; exit]
3. Drag the terminal until it closes

This happened to me naturally because I'd popped out someone's shared screen into a new window. While I was dragging it around, they stopped sharing. Then I was unhappy for the rest of the meeting

**Expected behavior**
I'd expect to be back to normal after the window closes

**System information:**
Please provide system information:
- if you installed PaperWM via [extensions.gnome.org](https://extensions.gnome.org) please open PaperWM settings and select the `About` tab (last tab) and click the `Copy to Clipboard` button and paste the information below, or;
  - Distribution: NixOS 24.05
  - Gnome Shell: 46.2
  - Display server: Wayland
  - PaperWM version: 46.13.2
  - Enabled extensions:
    - Vitals
    - appindicatorsupport
    - bluetooth-quick-connect
    - just-perfection-desktop
    - paperwm
    - space-bar
    - switcher

**Comment by jtaala** [comment]
Nice find @malcolmredheron.  Thanks for reporting.

**Comment by jtaala** [comment]
> Then I was unhappy for the rest of the meeting

Ah yeah was probably awkward not being able to type etc. once that happened!

**Comment by jtaala** [comment]
Thanks @malcolmredheron,

Closing this one.  Fix is in `v46.13.3`.  I've submitted to gnome-extensions.org as well.

**Comment by malcolmredheron** [comment]
Wow! Thanks for fixing this so fast!

---

Sent with Superhuman ( https://superhuman.com/refer/cmsqjaxn ). Please favor brief email ( http://three.sentenc.es/ ) over chat, especially for tasks. For chat (+1-415-235-0687), WhatsApp is best. Never Signal unless there are legal issues.

**Comment by jtaala** [comment]
> Wow! Thanks for fixing this so fast!

Note, there was a regression in `v46.13.3` that was reported.  New version released (to address regression): `v46.13.4`.

Thanks!

Jay.
