### ISSUE TITLE
Scrolling when reordering windows

### ISSUE THREAD

**Issue by gro-david** [paperwm/PaperWM#910]
**Is your feature request related to a problem? Please describe.**
When I am trying to reorder my windows using a touchpad, I cannot scroll the view. This makes it so you have to either use the keyboard or go into the overview and swap the positions there. 

**Describe the solution you'd like**
When pulling down on the window (and with that moving it), you should still be able to scroll the view with three fingers (one will be clicking, since you are moving the window, and the other two could scroll the view).

**Describe alternatives you've considered**
The alternative could be the view automatically scrolling when you reach the edge of the screen when moving the window. Or a preview could appear at the edge of the screen, meaning that the window will automatically tile after the window that you are currently hovering.

**Comment by jtaala** [comment]
> The alternative could be the view automatically scrolling when you reach the edge of the screen when moving the window.

This here would seem more appropriate.  Also mentioned in #765.
