### ISSUE TITLE
Add animation for centering window horizontally on scratch layer

### ISSUE THREAD

**Issue by zhaob1n** [paperwm/PaperWM#911]
**Is your feature request related to a problem? Please describe.**
I generally like the animation all over paperwm. But there seems no animation for centering window horizontally on scratch layer.

**Describe the solution you'd like**
I'd love it if there are animations for that action.

**Comment by jtaala** [comment]
This would be a very low priority for me, but would accept a PR if you would like to work on this.

**Comment by jtaala** [comment]
Completed by #920.
