### ISSUE TITLE
Optional 'standard' workspace behaviour

### ISSUE THREAD

**Issue by gro-david** [paperwm/PaperWM#913]
**Is your feature request related to a problem? Please describe.**
I like to have my workspaces horizontally (like with most desktops and OSes traditionally). Because of that I deactivated the vertical shortcuts for the PaperWM workspace management (to switch workspaces on a trackpad I just swipe up with three fingers to get to the overview and then to the side to switch workspaces). My keyboard shortcuts too are setup this way (Ctrl+Super+Arrow). PaperWM overrides the standard behavior and separates monitors to different workspaces, which makes the usage frustrating to say the least. 

The current behavior also looks weird in the overview.

**Describe the solution you'd like**
An optional toggle to not override the standard behavior and use the default instead. This would mean that monitors are kept on the same workspace. 

**Describe alternatives you've considered**
I am not sure if there even are any.

**Comment by jtaala** [comment]
Separating the monitors to separate workspaces is central to PaperWM's design and operation ("per monitor workspaces).

I wouldn't be interested in implementing this or using this approach, but would accept a PR if someone would like to work on this one.

**Comment by gro-david** [comment]
I would be more than happy to develop it myself, have already forked the repo and am currently trying to wrap my head around the inner workings of both GNOME Extensions and PaperWM. Could you maybe help me out with where the logic for the workspace management even is? For now I have only found the logic for creating new empty workspaces if there aren't enough.

**Comment by jtaala** [comment]
It's a little involved to be honest.  In gnome (or Mutter), a workspace is just a collection (or logical grouping) of meta_windows.  In PaperWM we control that grouping very differently than standard Gnome.  `StackOverlay.js` is how we activate these "groups: (workspaces) by monitoring mouse position etc. when a the mouse goes out of a monitor's bounds.

 In any case, there's really no central place for workspace management - we just manage meta_windows (including setting their "workspace" ids).  In other words, there's really no place for "workspace management" - it's part of PaperWM tiling operations (so the philosophy and management of workspaces are at the meta_window level, which means it's part of many of PaperWM modules).

**Comment by gro-david** [comment]
So, to sum it up:
 - I need to create a setting either in General or in Advanced if the 'standard' workspace monitor behavior or the PaperWM per monitor workspaces mode should be active. 
 - At any place where the per monitor workspaces are enforced I need to check for the setting and only enforce it if the user wants it
 - If 'standard' mode is selected, just leave the default and do not do anything else. 
 - If per monitor workspaces are selected then leave the current behavior.

**Comment by jtaala** [comment]
The difficulty will be in that per monitor workspaces are "enforced" throughout the entire codebase (i.e. it was designed like that from the get go - if that wasn't part of the design PaperWM would have been written quite differently).

But yes, what you've written above is correct in principal.

**Comment by jtaala** [comment]
> The current behavior also looks weird in the overview.

Ah yes, this very related to per monitors workspaces (fighting against gnome's approach).  I have down to write our own `overview` (that works better with per monitor workspaces).  See some related issues  https://github.com/paperwm/PaperWM/issues/389#issuecomment-1911089672

**Comment by gro-david** [comment]
After reading into the source code for a bit (rlly not much, will try to find more time though) I think 
 - I might start from scratch with a smaller scope
 - I will look a bit more into it and try to change as little as possible to enable this functionality
 - Or I maybe just will let it be (unfortunately I have tons of other work to do)

**Comment by gro-david** [comment]
I have decided that it is not worth the effort (after trying to develop the most simple GNOME Extension for a day). I have settled on using PaperWM when on the move and only having one display, and using Forge when docked. For the switching between the two I have written the extension mentioned before. 

If there is any interest in that let me know, and I will publish it.

**Comment by jtaala** [comment]
If PaperWM is not quite what you're after, you should def give https://github.com/YaLTeR/niri a go (it's a scrolling tiling window manager that avoids some multi-monitor issues since it's not fighting against Gnome's (well really Mutter's) global window coord space and approach.

**Comment by gro-david** [comment]
I personally love having a full DE instead of just a WM (because I just spend far too much time configuring it when I should be doing other stuff instead), the only way I liked using a WM was with combining Plasma and I3 (back on X11). But I think I am quite happy with how I solved it. This makes me productive on the go when I love the scrolling aspect of PaperWM (because of the gestures), and I like the workspace management of Forge when docked on the desktop.
