### ISSUE TITLE
Default keybindings for tiling viewport drifting conflict with text highlighting

### ISSUE THREAD

**Issue by joeroe** [paperwm/PaperWM#919]
The default keybindings for "swiping" the viewport added in #917 are `ctrl`+`shift`+`left` and `ctrl`+`shift`+`right`. These are the same keybindings used for highlight forward or backward by word-by-word in many text editors (e.g. Firefox, LibreOffice, gedit).

Please consider a different default.

**Comment by Lythenas** [comment]
Good catch. I also quite often use `ctrl`+`shift`+`left/right`

@jtaala are there any keys left we could change the default to? Otherwise I think it is better to just remove the default. I can create a PR for this if we decide what to change it to.

**Comment by jtaala** [comment]
ha... yeah, didn't think of that one.

What about `shift`+`control`+`<` / `>`?

Otherwise, can just leave the default as blank/empty.

**Comment by KETHERCORTEX** [comment]
> What about `shift`+`control`+`<` / `>`?

@jtaala I personally prefer to keep window manager shortcuts separate from application ones by using `Super` (also known as "Windows key") in them. It prevents collisions with in-app shortcuts pretty well.

In my current configuration the combination is `Super + [ / ]`. It is another pair of brackets separate from "regular switching" brackets (`< / >`).

**Comment by jtaala** [comment]
> In my current configuration the combination is `Super + [ / ]`. It is another pair of brackets separate from "regular switching" brackets (`< / >`).

I'm happy with that.
