### ISSUE TITLE
Allow taken windows to be dropped in all positions

### ISSUE THREAD

**Issue by lambdaclan** [paperwm/PaperWM#928]
**Is your feature request related to a problem? Please describe.**

The take/drop window functionality is already a great way of managing multiple windows but can be further extended by allowing taken windows to be dropped under any of the available positions. The current implementation only supports [left/right/start/end positions](https://github.com/paperwm/PaperWM/issues/852#issuecomment-2282653959) so it would be great to also add the missing down and up positions.

![image](https://github.com/user-attachments/assets/6ecbf9f0-2ab9-4763-9702-327ad62c39fc)

Essentially since PaperWM already provides the ability to **position new windows** under all positions this request is to be able to also **position existing windows** (while in take/drop mode) since using the `Switch between positions for creating new windows` keybind can be used during take/drop modes. Possibly we will need to rename the keybind to all mention that it affects taken windows something along the lines of `Switch between positions for creating new windows or dropping existing windows`.

**Describe the solution you'd like**

I rarely create new windows because I normally pre-launch all my applications grouped by workspace, but I do a lot of shuffling around. Having more flexibility on where taken windows can be dropped will allow the **manual** creation of quick layouts.  I particularly mention manual because you will still have to take the windows and drop each one under the required position while switching the position while in drop mode.

I have another idea for **automatic** layouts, but I guess that would be more involved, so I will make a new issue for that.  To give a quick overview (but to also get an idea what the team thinks about this) basically we can have built-in layouts and potentially custom layouts that define how a series of existing windows should be well, laid out. Then while in take/drop mode a new apply layout keybind can be used to automatically drop multiple windows to satisfy the specified layout. I will be happy to discuss in more detail if the team/community thinks there is value to such a feature.

**Describe alternatives you've considered**
The only other alternative is to take the windows, rearrange them as desired, drop them and then use the provided keybinds to consume windows into rows/columns, but that is not as seamless as being able to do it while in drop mode.

**Additional context**
There is relevant discussion to this feature request in issue #852 

Thank you for all your work!

**Comment by jtaala** [comment]
Could you please test this one?

```
git clone https://github.com/paperwm/PaperWM.git
cd PaperWM
git checkout  improve-928-drop-windows-up-down
./install.sh
```
then logout/login.

**Comment by jtaala** [comment]
> I have another idea for **automatic** layouts, but I guess that would be more involved, so I will make a new issue for that. To give a quick overview (but to also get an idea what the team thinks about this) basically we can have built-in layouts and potentially custom layouts that define how a series of existing windows should be well, laid out. Then while in take/drop mode a new apply layout keybind can be used to automatically drop multiple windows to satisfy the specified layout. I will be happy to discuss in more detail if the team/community thinks there is value to such a feature.

Sounds interesting - although I wouldn't use this and my workflow is much simpler (and doesn't rely on automatic layouts etc.).  Others may be interested in this though, so I would accept/consider a PR if others would like to work on this.

Cheers.

**Comment by lambdaclan** [comment]
> Could you please test this one?
> 
> ```
> git clone https://github.com/paperwm/PaperWM.git
> cd PaperWM
> git checkout  improve-928-drop-windows-up-down
> ./install.sh
> ```
> 
> then logout/login.

Hello @jtaala thank you very much for putting up this together. After a quick test I can confirm that the requested feature is working as expected!

[paper-wm-extra-positions-drop-mode.webm](https://github.com/user-attachments/assets/0c5fbe38-3b5a-4d63-ac81-2ac48ecfa08c)

> Sounds interesting - although I wouldn't use this and my workflow is much simpler (and doesn't rely on automatic layouts etc.). Others may be interested in this though, so I would accept/consider a PR if others would like to work on this.

I will be willing to work on this myself, but the problem is I never dealt with Gnome extension development. I guess everyone needs to start from somewhere so I could give it a go. If you can provide me with any pointers such as relevant files, sections in the code etc it would be very helpful. 

Also is there a way of quickly testing changes? I saw your instructions above but does that mean that I need to uninstall, install (with new changes), logout and then log in each time I do a small change? I hope there is a better way of facilitating development 😅 I remember reading something about using GnomeOS in a VM and a way of restarting the shell in some fashion but not sure if that is the recommended way of doing things.

**Comment by jtaala** [comment]
> Also is there a way of quickly testing changes? I saw your instructions above but does that mean that I need to uninstall, install (with new changes), logout and then log in each time I do a small change? I hope there is a better way of facilitating development 😅 I remember reading something about using GnomeOS in a VM and a way of restarting the shell in some fashion but not sure if that is the recommended way of doing things.

Hey @lambdaclan,

Indeed, I use a similar approach.  Essentially I use `virt-manager` with some linux distro for development (currently using Fedora for dev, since it's pretty standard etc.).  I have my paperwm folder (on my host) mounted on the virtual machine.  So the process I use is develop (on my host), while running testing on my vm.  I have some little things which makes it easier (e.g. shortcut to kill gnome session on my vm, and no password so can easily login).

**Comment by lambdaclan** [comment]
> Indeed, I use a similar approach. Essentially I use virt-manager with some linux distro for development (currently using Fedora for dev, since it's pretty standard etc.). I have my paperwm folder (on my host) mounted on the virtual machine. So the process I use is develop (on my host), while running testing on my vm. I have some little things which makes it easier (e.g. shortcut to kill gnome session on my vm, and no password so can easily login).

Hello @jtaala 

Got it, thank you for taking the time to explain your setup. I will try to create a similar development environment and see how things go from there. I will start with a few easy tweaks to get a feel for extension development before trying to do anything with automatic layouts. Once (and if) I have something workable we can revisit this topic. I will make sure to open a new issue/discussion so that we can keep track of any progress.
