### ISSUE TITLE
add more settings [suggestion]

### ISSUE THREAD

**Issue by unknownuser88** [paperwm/PaperWM#95]
make it more customizable 

1. enable/disable minimap on switching between windows
2. enable/disable preview on mouse hover 
3. enable/disable workspace name on desktop
4. if it possible bind programm to position (for example always  run terminal on first position chrome on second etc)
5. import/export settings

**Comment by hedning** [comment]
> import/export settings

You can import/export using dconf. Eg. 
```
dconf dump /org/gnome/shell/extensions/paperwm/ | dconf load /org/gnome/shell/extensions/paperwm/
```

> if it possible bind programm to position (for example always run terminal on first position chrome on second etc)

Yes, this would be neat to have, though would require a fair bit of work. One possible implementation is something like this:

```javascript
defwinprop({
  wm_class: "tilix",
  position: 0,
  oneshot: true
})
defwinprop({
  wm_class: "Google-chrome",
  position: 1,
  oneshot: true
})
```

Getting this to work for 3+ windows and workspaces with existing windows isn't trivial though. Eg. if there's already a window on the workspace and we launch `tilix` and `chrome`. If the chrome window is created first we'll end up with this, which probably isn't what we want:
```
| tilix | | some existing window | | chrome |
```

> enable/disable preview on mouse hover

Disabling hover would be easy, but the underlying overlay also protects against a weird upstream bug: https://github.com/paperwm/PaperWM/issues/80 in X11, we should probably do without the actual overlay on wayland though.

> enable/disable workspace name on desktop

Shouldn't be too hard, and other people have expressed their want for this. I'll try to make it happen.

> enable/disable minimap on switching between windows

Would increasing the delay before the minimap pops up work?

**Comment by hedning** [comment]
It's now possible to disable workspace names like this:
```
dconf write /org/gnome/shell/extensions/paperwm/use-workspace-name false
```

**Comment by unknownuser88** [comment]
![image](https://user-images.githubusercontent.com/2427559/52997476-0cdbf500-343a-11e9-8fd4-ca2daaf501ae.png)
I mean workspace name on desktop wallpaper not on topbar (see screenshot)
now on master branch my topbar is no longer transparent

**Comment by hedning** [comment]
>  I mean workspace name on desktop wallpaper not on topbar (see screenshot)

Ah, the intention is that the name on the wallpaper should be aligned fully with the top bar name (ie. it shouldn't be visible when the workspace is active). So the fact it's not is certainly a bug.

I've tried a bunch of different non-latin characters (including lamda) and I'm unable to reproduce the issue. Do you get this with any title, or just the lamda? The gnome-shell version you're using might also be useful. 

>  now on master branch my topbar is no longer transparent

Hmm, that shouldn't happen and I'm unable to reproduce it here, any errors from `./debug` or `journalctl $(which gnome-shell)` (it that sounds like there's an error in `topbar.js` before the transparency hack is applied).

**Comment by unknownuser88** [comment]
journalctl screenshot
![image](https://user-images.githubusercontent.com/2427559/53016141-4aef0e00-3466-11e9-8097-c5c49925d3b7.png)

my os info
![image](https://user-images.githubusercontent.com/2427559/53016497-38c19f80-3467-11e9-98f7-94ca7e30f568.png)


same behavior with any workspace name 
![image](https://user-images.githubusercontent.com/2427559/53016317-c94bb000-3466-11e9-9379-a45a559cd5c7.png)

**Comment by hedning** [comment]
Does https://github.com/paperwm/PaperWM/commit/48adf04ae71c64479c2d64bbc82f5670cdf7a243 fix it?

**Comment by unknownuser88** [comment]
on first workspace  topbar is not transparent so I can't see it
but on second workspace it still there

![image](https://user-images.githubusercontent.com/2427559/53017644-e766df80-3469-11e9-8733-fc9f5109c838.png)

**Comment by hedning** [comment]
Huh, that's really weird. Does it persists through restarts too?

**Comment by unknownuser88** [comment]
after alt+f2 r topbar is transparent but after switch to second workspace it not transparent

**Comment by hedning** [comment]
Right, @olejorgenb is also on ubuntu on 2.28, I'll check in with him to see if we're able to reproduce and fix things.

**Comment by hedning** [comment]
No «luck» reproducing on ubuntu (gnome-shell 3.28.3).

I'm guessing one of these, or both, is the problem:
- Some top bar extension interacts in a bad way (eg. the one showing window icons)
- A recent commit introduced the workspace name misalignment. Do a `git bisect` (with restarts on each stop) to find any offending commit

**Comment by unknownuser88** [comment]
I have https://extensions.gnome.org/extension/1160/dash-to-panel/ extension enabled
after disable it topbar looks like this
![image](https://user-images.githubusercontent.com/2427559/53077204-efc32700-350a-11e9-9216-e616becd0a0e.png)

**Comment by hedning** [comment]
I'm, able to reproduce the transparency issue with dash-to-panel enabled. From what it's triggered when a workspace contains either a fullscreen or maximized window. Not sure if this is easy to fix, but might be doable.

To find the label misalignment problem (as it didn't seem to happen when you reported #94):
- `git checkout 48adf04ae71c64479c2d64bbc82f5670cdf7a243` (or another commit you know to be good)
- restart and see if the labels are properly aligned to verify the commit is good
- run `git bisect master 48adf04ae71c64479c2d64bbc82f5670cdf7a243`
  - restart, see if the labels are aligned
  - if things look good run `git bisect good` if they're bad `git bisect bad`
  - repeat until git tells you it found the first bad commit

I'm not sure if I can be any more helpful without being able to reproduce it myself.

**Comment by hedning** [comment]
Ah, if you've configured `LeftBox Font Size` then the labels might be misaligned.

Set it to `0` and restart to see if that's the problem.

**Comment by unknownuser88** [comment]
before dc97077 this commit label if fine but after d7336e9 this one label not aligned

**Comment by hedning** [comment]
5f20007ff25e29c30df21b6d6fe7d60d39ecf205 makes sure the font size matches correctly at least (might fix alignment too).

**Comment by unknownuser88** [comment]
alignment still not fixed 
Isn't it better just hide label at the bottom level ? too many factors can dis-align it custom font size, scale, extension etc.

**Comment by hedning** [comment]
OK, found the culprit, it was custom user-themes. c80a8fd7ebbfacef09e33b0d387ada76d9c9dde2 should fix the issue.

While hiding the label could've worked, the misalignment would still visible while animating, and getting the hide/show logic correct showed itself to be quite finicky.

**Comment by hedning** [comment]
I think this is done, I'll probably add another issue with plans to implement layout definitions.
