### ISSUE TITLE
Windows become detached when using a system open dialog.

### ISSUE THREAD

**Issue by luisbc92** [paperwm/PaperWM#954]
**Describe the bug**
After the upgrade to Gnome 47, managed windows get thrown in the scratch layer when a system open dialog is opened.

The binding to attach the window needs to be applied twice before the window will become tiled again.

It does not seem to happen on every application. Here it is demonstrated on VS Code.

**To Reproduce**
1. Open VS Code
2. Open a file or folder
3. Window will become detached.

**Expected behavior**
The window should not become detached.

**Screenshots**
[Screencast From 2024-09-30 18-26-47.webm](https://github.com/user-attachments/assets/b97fcd53-25cd-49f9-a6d4-120ce84f3b3b)

**System information:**
Please provide system information:
- Gnome 47
- EndeavourOS (Arch Linux)

**Comment by jtaala** [comment]
Thanks @luisbc92,

So, I can't reproduce this (I'm also on Gnome 47 and endeavour OS).  Let me know if I'm doing anything wrong there:

https://github.com/user-attachments/assets/bbb34dcd-4b19-4b13-9894-949aecac276e

Also, could you please paste the `About` tabs (from PaperWM's settings) contents:

![image](https://github.com/user-attachments/assets/fcf48e2b-d349-42b7-91b3-9f05e6eb9d22)

**Comment by luisbc92** [comment]
Looks like it was an issue with Electron applications. After the latest update, this issue went away.

Thank you for trying to reproduce!
