### ISSUE TITLE
Mixed-scale multi-monitor causes weird window behavior, flickering, unresponsiveness and overlapping. 

### ISSUE THREAD

**Issue by SimonBlancoE** [paperwm/PaperWM#955]
https://github.com/user-attachments/assets/02eff348-8932-46e7-a1dc-d92a4be6350c

**Describe the bug**
When opening windows, they seem push each other and sometimes overlap. Windows become unresponsive. It doesn't happen 100% of the time, but almost always with video players going fullscreen and terminals.

**To Reproduce**
This started happening since I added a 4K monitor to my laptop. I was using a FHD monitor before and the error didn't happen.  

**System information:**
Distribution: openSUSE Tumbleweed
GNOME Shell: 46.5
Display server: Wayland
PaperWM version: 47.0.0
Enabled extensions:
- just-perfection-desktop@just-perfection
- caffeine@patapon.info
- appindicatorsupport@rgcjonas.gmail.com
- burn-my-windows@schneegans.github.com
- drive-menu@gnome-shell-extensions.gcampax.github.com
- gsconnect@andyholmes.github.io
- clipboard-indicator@tudmotu.com
- status-area-horizontal-spacing@mathematical.coffee.gmail.com
- weekstartmodifier@saccuzm.gmail.com
- user-theme@gnome-shell-extensions.gcampax.github.com
- Vitals@CoreCoding.com
- IP-Finder@linxgem33.com
- runcat@kolesnikov.se
- AlphabeticalAppGrid@stuarthayhurst
- blur-my-shell@aunetx
- thinkpad-battery-threshold@marcosdalvarez.org
- Bluetooth-Battery-Meter@maniacx.github.com
- openbar@neuromorph
- mediacontrols@cliffniff.github.com
- unblank@sun.wxg@gmail.com
- launch-new-instance@gnome-shell-extensions.gcampax.github.com
- paperwm@paperwm.github.com

**Comment by jtaala** [comment]
Hey @SimonBlancoE,

Could you try enabling `scale-monitor-framebuffer`, logout/login and see if the situation is improved any?

See https://www.omglinux.com/how-to-enable-fractional-scaling-fedora/ for enabling in gnome.

**Comment by SimonBlancoE** [comment]
Activating fractional scaling seem to have solved all the issues. 

`gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`

Thank you so much for the help and for this great extension.
