### ISSUE TITLE
Cannot enable the "Show the notification list" hotkey

### ISSUE THREAD

**Issue by vivianlauerbsu** [paperwm/PaperWM#961]
**Describe the bug**
When I try to bind the "Show the notification list" hotkey, a message pops up saying
```
PaperWM: overriding 'toggle-message-tray' keybind
the Gnome Keybind will be restored when PaperWM is disabled
```
I understand that it might make sense for this to be disabled by default, but for the life of me I cannot figure out how to override paperWM and restore this keybind while still using PaperWM. It would be best if users could simply override keybinds disabled by paperWM. Otherwise, could someone let me know how to modify the source code to reassign this keybinding?

**To Reproduce**
1. Go to Settings > Keyboard > View and Customize Shortcuts > System
2. "Show the notification list" should say Disabled with a backspace icon next to it.
3. Attempt to set it to `Super + n` or another hotkey
4. See issue

**Expected behavior**
PaperWM should allow users to set keybindings that it overrides by default. Another option would be to re-expose this setting in the PaperWM keybind settings through the extensions app.

**System information:**
Please provide system information:

Distribution: EndeavourOS
GNOME Shell: 47.0
Display server: Wayland
PaperWM version: 47.1.0
Enabled extensions:
- paperwm@paperwm.github.com
- auto-move-windows@gnome-shell-extensions.gcampax.github.com

**Comment by Lythenas** [comment]
If I remember correctly this message appears if a keybinding in paperwm and one in gnome are the same. In that case we disable the keybinding in gnome, so the one paperwm works.

Can you try to check if the key combo you want to bind to "Show the notification list" is used in a paperwm keybinding?

**Comment by thestrike72** [comment]
I haven’t been able to check but I would guess that you are correct. What I want is to be able to assign a new keybinding to it that doesn’t conflict with PaperWM, but it’s locked in a disabled state.

**Comment by Lythenas** [comment]
So I just tried it and you can just assign a new keybinding without a problem. If it clashes with a paperwm keybinding it is immediately disabled and you get a notification. But if it does not clash you can assign whatever you want.

If you want to use a keybinding that is currently used in paperwm, you need to first remove the keybinding from paperwm and then you can assign it in the gnome settings.

**Comment by jtaala** [comment]
Hey @Evthestrike,

As @Lythenas mentioned, this is due to that keybind being assigned to `Centre windows horizontally (non-tiled window)` shortcut.  Basically, you can't have the same keybind assigned in Gnome and PaperWM - PaperWM disables gnome keybinds that clash.

Luckily, all keybinds can easily be changed/set/edited in PaperWM extension settings.  You can open extensions via the Gnome extensions app.  In settings you can then modify the `Super`+`V` shortcut (or disable it).  Once done, you'll be able to set that shortcut in Gnome.

![image](https://github.com/user-attachments/assets/01a6cbf0-7362-44ea-9583-541d5e17fe66)

**Comment by jtaala** [comment]
> What I want is to be able to assign a new keybinding to it that doesn’t conflict with PaperWM, but it’s locked in a disabled state.

??

[Screencast From 2024-10-26 20-31-58.webm](https://github.com/user-attachments/assets/ad7c5ba0-e8c4-43dd-b09c-93bfc1574e13)

**Comment by jtaala** [comment]
Closing this - let us know @Evthestrike if you're seeing a different issue or you can't replicate the video above.

**Comment by thestrike72** [comment]
Sorry for the delay in responding to this. I did not realize that there was another hotkey assigned to `<Super>n`, but when I disabled that hotkey, it fixed my problem. Thank you so much for helping me and for this great extension!
