### ISSUE TITLE
"Switch WS from all monitors" not working [Ubuntu 24.04.1]

### ISSUE THREAD

**Issue by outerlook** [paperwm/PaperWM#968]
**Describe the bug**
"Switch to workspace below/above (ws from all monitors)" seems not to work with Ubuntu 24.04 (Gnome 46.0).

**To Reproduce**
Override this option in PaperWM settings and try switching. Only one monitor is used.

**Expected behavior**
Switch to workspace below/above (ws from all monitors) should work.

**Screenshots**
![image](https://github.com/user-attachments/assets/bc2fa001-ef51-4d38-bc17-d128aa591e22)

[Recording of the issue](https://github.com/user-attachments/assets/f5dda859-efc1-4106-9795-d40f3836c46b)

**System information:**
- Distribution: Ubuntu 24.04.1 LTS
- OS Type: 64-bit
- PaperWM version 47.1.0
- GNOME Shell 46.0
- Display server: Wayland
- enabled extensions:
    paperwm@paperwm.github.com
    ubuntu-appindicators@ubuntu.com
    ubuntu-dock@ubuntu.com

**Additional context**
How can I help to debug this further?

**Comment by jtaala** [comment]
> Override this option in PaperWM settings and try switching. Only one monitor is used.

Hey @outerlook, you may be misunderstanding what this keybind does.

In PaperWM, workspaces can be "per monitor" (unlike gnome which has one workspace at a time across all monitors).

As such, in PaperWM, you can have (for example) workspace 1,2 assigned to Monitor 1; and workspace 3,4 assigned to Monitor 2.

By default, when you iterate workspaces on a monitor, it will iterate through workspaces _assigned_ to that monitor only.  The other keybind you mentioned _Switch to workspace below/above (ws from all monitors)_ will iterate through workspaces _assigned_ to other monitors as well.

In both cases, you're only iterating through them on the current monitor.

Note that it won't show workspaces currently on other monitors - if you're wanting to swap workspaces shown on other monitors, there are keybinds to `Swap workspace with monitor to the right`, etc.

Hope that makes sense.

You can see a little background info in the pull request here: https://github.com/paperwm/PaperWM/pull/645

**Comment by jtaala** [comment]
P.S. I couldn't tell from the video which how many monitors and workspaces you had, or if you're using dynamic/static workspaces etc.

**Comment by outerlook** [comment]
hey @jtaala thank you for clarifying. Yes, I misunderstood what the function did. 

I thought the difference was that the default switched the WS only in one monitor, while this option permitted switching the workspace in all monitors at once :pray: 

I'm using dynamic workspaces for now

Not sure if I should close the issue or leave it open if more people misunderstand the behavior

**Comment by jtaala** [comment]
Thanks @outerlook.  I'll close this.  Feel free to submit a PR though to improve the documentation around this (i.e. could add / clarify something about this in section https://github.com/paperwm/PaperWM?tab=readme-ov-file#the-workspace-stack--monitors).
