### ISSUE TITLE
ability to disable some features

### ISSUE THREAD

**Issue by unknownuser88** [paperwm/PaperWM#97]
is it possible disable some features ?
for example edge barrier which prevents my mouse move to second monitor for the first time (it is very annoying when working)
or edge overlays (preview) 
or hide minimap

**Comment by hedning** [comment]
In general we're not super excited about adding a bunch of preferences. It might quickly fix a problem for someone, but it's often better to find a general solution that solves the underlying issue for everyone. It also makes the code harder to maintain.

That being said:

>  for example edge barrier which prevents my mouse move to second monitor for the first time (it is very annoying when working)

I'll add an option for this, I can absolutely see it being annoying, and I can't come up with an alternative solution.

> edge overlays (preview)

The previews indicates that clicking will select another window. This isn't obvious when the window isn't visible (or just barely). Is there some specific example you have in mind where the previews doesn't work well or are annoying?

For instance adding a tiny delay is probably a good idea. That way moving the pointer across an overlay eg. to another monitor, or a dock to left won't trigger the preview.

We should probably also just show the previews when close to the monitor edge.

> hide minimap

Could you elaborate on when the minimap is bugging you? The purpose of the minimap is giving the user a better idea of where they are.

We could for instance increase the delay, that way quick switches won't trigger the minimap (would be good for the battery too if implemented correctly).

**Comment by unknownuser88** [comment]
> We could for instance increase the delay, that way quick switches won't trigger the minimap (would be good for the battery too if implemented correctly).

I think this is great idea to add delay to don't trigger minimap on quick switches 

> but it's often better to find a general solution that solves the underlying issue for everyone

it's not easy to find a general solution for everyone. I think easier make it more customizable and everyone can setup his workflow for example I use keyboard for switching windows so I don't need preview or barrier.Barrier prevents my mouse move to second monitor for the first time (to solve this I use old commit when barrier not implemented) I think the solution is just enable or disable barrier from settings

ps. sorry for my english

**Comment by hedning** [comment]
Pushed some changes to the  pressure-barrier branch.
- Set `pressure-barrier` to false to disable
- Previews now has a delay (it's pretty short, so so could possibly be larger) so going across shouldn't trigger the preview
- Minimaps now has a 200ms delay (without any animation), similar to the native gnome-shell popups.

**Comment by unknownuser88** [comment]
Thank you very much it looks great
