### ISSUE TITLE
Picture in picture doesnt work

### ISSUE THREAD

**Issue by GerardPolloRebozado** [paperwm/PaperWM#974]
**Describe the bug**
When im in the browser and activate picture in picture the window that has the picture in picture disappears it show when make click on Super key but if there is no way to see it even selecting doesnt make it appear

**To Reproduce**
1. Go to a media player site like youtube
2. Click on the music icon of your browser
4. And the nthe pip button to enable it

**Expected behavior**
Have a floatating window that reproduces the video

**System information:**
Please provide system information:
Distribution: Ubuntu 24.04.1 LTS (Noble Numbat)
GNOME Shell: 46.0
Display server: Xorg
PaperWM version: 47.1.0
Enabled extensions:
- paperwm@paperwm.github.com
- gsconnect@andyholmes.github.io
- color-picker@tuberry
- clipboard-history@alexsaveau.dev
- hibernate-status@dromi

**Comment by oktayacikalin** [comment]
Have you tried this?

![grafik](https://github.com/user-attachments/assets/45057419-3400-4b48-b282-5ab9afc253c1)

**Comment by GerardPolloRebozado** [comment]
Thanks that worked.
