### ISSUE TITLE
Add visual indicator that Scratch mode is on

### ISSUE THREAD

**Issue by goodwillcoding** [paperwm/PaperWM#99]
I experience some biugginess with some windows resizing or moving themselves. I try to put them in the scratch mode to avoid issues. However Currently it can get confusing if scratch is on. A visual indicator would be nice

**Comment by hedning** [comment]
Sounds like there might be two issues here:

1. The tiling doesn't handle windows that resize themselves (in particular if a window to the left of the active window is resized the active window will move), this is pretty much a bug on our end and should be fixed.
2. The scratch layer sometimes acts in a confusing way.

Could you elaborate on the floating window workflow that's confusing? That will make it easier for me to come up with a good solution. Is it for instance hard to see if a floating window have focus (gnome shell 3.32 improve that a lot, the contrast between active and inactive windows are much better)? Or is the problem actions which do different things if there's scratch windows that are open?

Generally the way the scratch and tiling integrates can be improved quite a bit, so I'm absolutely open to changing things here. For instance if there's open, but inactive, floating window `super-escape` should probably focus the window, not minimize it.

The way alt-tab works is also not always ideal. It currently works by prioritizing all scratch windows if a scratch window has focus and vice versa for tiling windows. We should really make it easier to switch between a open scratch window and the tiling.

As an aside, `super-shift-tab` has a hidden feature where it will go to the last used scratch window if started from the tiling, and go to the last used tiled window if started from a scratch window.

**Comment by goodwillcoding** [comment]
@hedning I've been playing around to reproduce this reliably so I can give steps to reproduce. The issue is happening semi-sporadically so it's been anoying. I am using 3.28 but will look and see how it behaves in 3.32.

That said in general I think any visual indicator of scratch mode windows might be nice. I am playing around with different border color for scratch window and trying to see if anyone in other tiling window communities have had coherent approach. Border color seems the easiest though. :)

**Comment by hedning** [comment]
> I am playing around with different border color for scratch window

I do think it's primarily the theme's responsibility to make it clear what window have focus. That said, Adwaita haven't been great at this in the past, though 3.32 improves the contrast a lot (I switched back to Adwaita dark this release, as I think it's fine now).

So while the focus highlight in the tiling makes it very clear what window have focus, it's main purpose is showing what window is selected when navigating, as we don't set focus until `super` is actually released (this makes it possible to alt-tab back after a navigating to a far off window).

I'm also not sure how it would look with extra borders for floating windows, but if you come up with a solution that looks good I'm open to it.

Note that we do make the tiling highlight more transparent when a scratch window have focus.

All in all I think there's a bunch of ways scratch windows could be improved, but I'm not entirely convinced borders is a great solution.

**Comment by olejorgenb** [comment]
> I experience some biugginess with some windows resizing or moving themselves

Which application(s)? Or just in general. It would be nice to collect applications that "misbehave" so we can include/document some workarounds.

**Comment by Pajn** [comment]
I also have a bit of a problem understanding the status of the scratch layer. Maybe the workspace name in the top bar should be appended or prepended with `Scratch - ` or something like that whenever the scratch layer is active? Just a small visual hint that could help remove the confusion.

**Comment by jtagcat** [comment]
Maybe just custom background for scratch?
